### ISSUE TITLE
Header is overlapping with the body content if the browser window is minimized.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [linnovate/mean#1000]
Header is overlapping with the body content if the browser window is minimized.
As Bootstrap is being used in this mean, the header should not be overlapped with the body content. 

 
![screenshot from 2015-01-04 15 08 05](https://cloud.githubusercontent.com/assets/9896335/5605484/1cb95770-9424-11e4-9fc7-0bc8b009ce96.png)

**Comment by sean-stanley** [comment]
Have a look at packages/system/public/views/header.html

You'll see that the responsive menu features of bootstrap are not by default written in. Edit this file to use Bootstrap's navbar classes and you'll be responsive in no time.

The reason they aren't by default written in I'm guessing is because they're not currently compatible with how the menu is laid out.

**Comment by liorkesos** [comment]
We should strive to a standard menu that will go responisve well.
Please issue a PR if you see an imporovment you can contribute here.
Lior

On Thu, Feb 12, 2015 at 8:26 AM, Sean Stanley <notifications@github.com>
wrote:

> Have a look at packages/system/public/views/header.html
>
> You'll see that the responsive menu features of bootstrap are not by
> default written in. Edit this file to use Bootstrap's navbar classes and
> you'll be responsive in no time.
>
> The reason they aren't by default written in I'm guessing is because
> they're not currently compatible with how the menu is laid out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1000#issuecomment-74023838>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by VikramTiwari** [comment]
Fixed.
