### ISSUE TITLE
mean install mean-admin package installation not completed.

### ISSUE THREAD

**Issue by vinaymavi** [linnovate/mean#1005]
I am try to install mean admin package with **mean-admin**  but installation not completed same window show till 30 minutes.
![mean-admin](https://cloud.githubusercontent.com/assets/1610828/5694646/b13fa350-9996-11e4-8199-bf4b0a97a737.png)

**Comment by Tyvain** [comment]
I had this problem quite often lately.
pressing 'enter' sometimes unblock it, or just ctrl-C, then relaunch.

And also, sometimes, installing mean-admin is just VERYYYYYY slow, so be patient.

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
