### ISSUE TITLE
Error: Cannot find module /bin/mean-postinstall

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1007]
Trying to install on linux, npm install throw this error:

```
[tyvain@alarm fast-annonces]$ npm install 
npm WARN package.json express@4.10.6 No README data
npm WARN package.json gridfs-stream@0.5.3 No README data
npm WARN package.json supertest@0.11.0 No README data
\
> mean@0.4.2 postinstall /projects/fast-annonces
> node node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall


module.js:340
    throw err;
          ^
Error: Cannot find module '/projects/fast-annonces/node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

npm ERR! Linux 3.14.27-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE
npm ERR! mean@0.4.2 postinstall: `node node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the mean@0.4.2 postinstall script 'node node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall'.
npm ERR! This is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /projects/fast-annonces/npm-debug.log
```

**Comment by webdesignberlin** [comment]
Same Problem here. On Windows 7 and in Ubuntu
```sh
mgerstmann@mgerstmann-VirtualBox:~/projects/blubb$ grunt
Running "hook" task
>> Starting hooked tasks.

Running "clean:0" (clean) task
>> 0 paths cleaned.

Running "jshint:all" (jshint) task
>> 42 files lint free.

Running "csslint:src" (csslint) task
>> 5 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "nodemon:dev" (nodemon) task
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858

module.js:340
    throw err;
          ^
Error: Cannot find module 'meanio'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/mgerstmann/projects/blubb/server.js:12:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by liorkesos** [comment]
Not finding meanio means npm install did not end correctly.
Please go in to the root directory - run npm install (as normal user) and paste the errors if you find some.
Lior

**Comment by morwalz** [comment]
Hi I am getting this same error while running npm install 
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
\
> mean@0.4.0 postinstall e:\node-examples\Oasis
> node node_modules/meanio/bin/mean-postinstall


module.js:340
    throw err;
          ^
Error: Cannot find module 'e:\node-examples\Oasis\node_modules\meanio\bin\mean-
ostinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! mean@0.4.0 postinstall: `node node_modules/meanio/bin/mean-postinstall

npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the mean@0.4.0 postinstall script.
npm ERR! This is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/meanio/bin/mean-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\node
s\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd e:\node-examples\Oasis
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     e:\node-examples\Oasis\npm-debug.log
npm ERR! not ok code 0

**Comment by mrapogee** [comment]
This is still an issue for me, but if I CD to node_modules/meanio/ and run npm install mean-cil it fixes it.

**Comment by Jeff-Lewis** [comment]
@mrapogee Install mean-cli globally. [See mean prerequisites.](https://github.com/linnovate/mean#install-the-mean-cli)

**Comment by Jeff-Lewis** [comment]
@mrapogee The postinstall script has moved across repos recently, from mean-cli to meanio, then to mean. See that latest version of mean's [postinstall.js](https://github.com/linnovate/mean/blob/master/tools/scripts/postinstall.js) script.

There are two ways to get around this. 
* Update your project to use the latest version of [mean](https://github.com/linnovate/mean), where your package.json should reference a postinstall.js script in your project.
``` json
"postinstall": "node tools/scripts/postinstall.js"
```

OR
* change your root package.json to reference use "meanio": "0.7.4", which is one of the last [versions of meanio](https://github.com/linnovate/meanio/commit/d1a160ce8cfe058c272aeb7b4d969a8ddd2b2876) to have the mean-cli dependency.
``` json
"meanio": "0.7.4",
```

@liorkesos We are big fans of mean and appreciate the aggregation and packaging architecture mean provides. It would be helpful for all and I assume reduce github issues, if breaking changes in meanio were handled better. By default, the mean repo depends on the latest version of meanio `"meanio": "linnovate/meanio"`, regardless of the version of the mean repo people are using. I can't think of any benefit to making mean, or other dependencies, refer to the latest version of meanio. 

Are you expecting people to add their own versions of dependencies since everything references `"latest"` in package.json? Or, is the assumption that people should stay up to date with the main mean repo by just `git pull upstream master`? 

Do you know if it's common for consumers of mean to be able to merge their project easily? 

At least for us, we find it very difficult and time consuming to upgrade mean because there is very little, if any, separation from 'our' code vs 'mean' code. As a project that was built using mean matures, more and more changes are made to the mean base code which makes it very difficult to upgrade.

Are there any plans to isolate and make the boundaries for the 'mean' code vs 'user' code? Any work in that direction would make mean much more usable from my teams perspective.

**Comment by liorkesos** [comment]
Hi Jeff,
Thanks for supporting the rest of the mean community and thanks for your
thoughtful comments.
Mean is like a 14 yr old kid restles, hyperactive and with pretty hectic
moodswings.
We defintly need to slow down and I've allready communicated that 0.5.x
will be the last version before the 1.0rc's
We have a few minor changes planned but 0.5 was pretty big.
In the meantime finding a version of meanio (the web kernel) and harcoding
the dependency is a good idea.
We moved to use npm shrinkwrap to reach the same outcome. have declarative
requirements in package.json while can control the versions you get when
tunning npm install.

Once we launch 1.0 we'll build more of an enterprise support development
rythm for the 1.0 branch (while we go nuts with angular2, es6 and various
goodies for the 2.x branch)
What are you guys building - you seemed well versed in the in and outs of
the project.
I'd also be happy to set up a hangout and share some of our directions in
regards of providing services to the mean community.
Have a MEANingful day :)
Lior


On Tue, May 26, 2015 at 10:43 PM, Jeff Lewis <notifications@github.com>
wrote:

> @mrapogee <https://github.com/mrapogee> The postinstall script has moved
> across repos recently, from mean-cli to meanio, then to mean. See that
> latest version of mean's postinstall.js
> <https://github.com/linnovate/mean/blob/master/tools/scripts/postinstall.js>
> script.
>
> There are two ways to get around this.
>
>    - Update your project to use the latest version of mean
>    <https://github.com/linnovate/mean>, where your package.json should
>    reference a postinstall.js script in your project.
>
> "postinstall": "node tools/scripts/postinstall.js"
>
> OR
>
>    - change your root package.json to reference use "meanio": "0.7.4",
>    which is one of the last versions of meanio
>    <https://github.com/linnovate/meanio/commit/d1a160ce8cfe058c272aeb7b4d969a8ddd2b2876>
>    to have the mean-cli dependency.
>
> "meanio": "0.7.4",
>
> @liorkesos <https://github.com/liorkesos> We are big fans of mean and
> appreciate the aggregation and packaging architecture mean provides. It
> would be helpful for all and I assume reduce github issues, if breaking
> changes in meanio were handled better. By default, the mean repo depends on
> the latest version of meanio "meanio": "linnovate/meanio", regardless of
> the version of the mean repo people are using. I can't think of any benefit
> to making mean, or other dependencies, refer to the latest version of
> meanio.
>
> Are you expecting people to add their own versions of dependencies since
> everything references "latest" in package.json? Or, is the assumption
> that people should stay up to date with the main mean repo by just git
> pull upstream master?
>
> Do you know if it's common for consumers of mean to be able to merge their
> project easily?
>
> At least for us, we find it very difficult and time consuming to upgrade
> mean because there is very little, if any, separation from 'our' code vs
> 'mean' code. As a project that was built using mean matures, more and more
> changes are made to the mean base code which makes it very difficult to
> upgrade.
>
> Are there any plans to isolate and make the boundaries for the 'mean' code
> vs 'user' code? Any work in that direction would make mean much more usable
> from my teams perspective.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1007#issuecomment-105644867>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by VikramTiwari** [comment]
I think we need to get rid of postinstall altogether. I will see what I can do.
