### ISSUE TITLE
Hiding security sensitive fields in user model

### ISSUE THREAD

**Issue by pratik60** [linnovate/mean#1011]
Specifically referring to this code in user.js :-)

```
  /**
   * Hide security sensitive fields
   * 
   * @returns {*|Array|Binary|Object}
   */
  toJSON: function() {
    var obj = this.toObject();
    delete obj.hashed_password;
    delete obj.salt;
    return obj;
  }

```

Isn't this the better way? http://stackoverflow.com/questions/12096262/how-to-protect-the-password-field-in-mongoose-mongodb-so-it-wont-return-in-a-qu?rq=1

You can change the default behavior at the schema definition level using the select attribute of the field:

```password: { type: String, select: false }```
Then you can pull it in as needed in find and populate calls via field selection as '+password'.

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
