### ISSUE TITLE
Documentation: How to update the meanio project.

### ISSUE THREAD

**Issue by ramandv** [linnovate/mean#1012]
I have created a project with meanio just 2 weeks ago. But now, meanio core package is updated and there are other changes in mean also. 

What is the best way to update the project to the latest version?  I could not find the documentation related to that.

**Comment by liorkesos** [comment]
If you run "git remote -v" you'll see a remote called upstream.
To update to the latest updates run
*git pull upstream master*
Good luck!
Lior

On Thu, Jan 15, 2015 at 10:03 AM, ramandv <notifications@github.com> wrote:

> I have created a project with meanio just 2 weeks ago. But now, meanio
> core package is updated and there are other changes in mean also.
>
> What is the best way to update the project to the latest version? I could
> not find the documentation related to that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1012>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by ramandv** [comment]
Thanks Lior. Just for reference , it is good to do "npm install" after that.

```
git pull upstream master && npm install
```

**Comment by liorkesos** [comment]
yup

On Thu, Jan 15, 2015 at 11:06 AM, ramandv <notifications@github.com> wrote:

> Thanks Lior. Just for reference , it is good to do "npm install" after
> that.
>
> git pull upstream master && npm install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1012#issuecomment-70057444>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by fyockm** [comment]
fixed by #1014
