### ISSUE TITLE
Edit an article that I don't own

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1016]
Here is my use case:

A user can tag articles as 'favorite'.

Instead of recording this in the user object with a 'favoriteId' array I would rather prefere store it in 'article' object with a 'favoriteUser' array.

The reason is that it's a lot more simple when I delete an article, it just disapear from the list. And also I prefere modifying articla package than user.

Is this a good idea or not ??

if yes, isn't it dangerous to modify an article that I don't own ?? How to do this ??

**Comment by andrija-hers** [comment]
Just a proposal:
"User" is one type of data.
"Article" is another type of data.
"FavoriteArticle" may be a new type of data - a one-to-one relationship User<->Article showing what User favorited which Article.

It is a (more or less) standard procedure in DB design; a clear way to scale systems.

**Comment by liorkesos** [comment]
You can name the functionality -
The "flag" package
;)

**Comment by andrija-hers** [comment]
"FavoriteArticle" should go to a favorite_article package. There are details that make it User and Article specific, so it is not a good choice to name it "flag".

In app.js of that package the developer needs to put users and articles as additional dependencies when registering. There is also a "catch" that asks for more work here - but that's the fun: users package need to emit a "removed" event, and the favorite_article package needs to subscribe for that event. Once the event is emitted, favorite_article package gets the articleId of the article removed, and removes the favs for the removed article (if any).

At this point it is clear that the users package need to emit a "removed" event as well (of course, mean.io at this moment has no way to remove a User, but anyhow...).

**Comment by VikramTiwari** [comment]
I think this hints towards writing a new articles package which could have two schemas, one for the article and another for association with users, mainly favs. If anyone would like to work on it, please go nuts!

Closing this issue, but re-open if you need more clarity/direction.
