### ISSUE TITLE
Adding role not working

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1017]
My app is running, I try to add an admin:

``` 
mean user xxx@gmail.com --addRole admin;
  Adding role `admin` to user `xxx@gmail.com`
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by BrockMcKean** [comment]
Try installing bson? Looks like it's missing.

**Comment by Tyvain** [comment]
How to install bson? Isn't it supposed to be installed automaticaly?
My app is working well, so I though I have it...

**Comment by fyockm** [comment]
@Tyvain it should be installed automatically, but apparently there was a problem.
In this case, `bson` package must installed for `mean-cli`, not the `mean` app. I recommend uninstalling and re-installing `mean-cli` as:
```
$ npm uninstall -g mean-cli
# note: you may have meanio installed globally, if so please uninstall it instead
$ npm install -g mean-cli
# try the command again
$ mean user xxx@gmail.com -a admin
```

**Comment by Tyvain** [comment]
Ok thank you, I will try that (not now because I fear to break my production server).

I manage to bypass the problem (maybe it can help someone even if it's not a good way to do it):
Changed my working 'development version' to target my prod DB, then add the user with mean user -a.
