### ISSUE TITLE
Web signup on https://git.mean.io/ does not work.

### ISSUE THREAD

**Issue by ramandv** [linnovate/mean#1018]
Finally, Managed to register with mean command, but web signup does not work though. When signup button got clicked, web server is still serving the signin page.

BTW Why cant the mean packages be hosted at Github and only the URL of repositories are part of  meanio packages repo? What is the rational behind that?

**Comment by liorkesos** [comment]
Did we do the changes to avoid spam?

**Comment by BrockMcKean** [comment]
Yes, I would like to understand the rationale behind the mean.io package repository.

**Comment by liorkesos** [comment]
1. The alternative was to host the packages in npm - the downsides of that where that we had a namespace clash making us call everything mean-this or mean-that.
2. We also wanted to create a silo which is less noisy and more relevant then npm.
3. We wanted to createw a notion of an app store - a group of open and commercial packages that a community member might be monazite (and we can take a cut and make it the project sustainable).

**Comment by ramandv** [comment]
Understand your point.

How about this approach
1. For open source mean packages, Repository can be anywhere, which is publicly accessible. (eg, github repo)
2. Instead of publishing to npm repo, publish it to mean packages repo. [mean packages repo will contain only the reference to the mean package git repository.]
3. In case of commercial packages, git repo can be hosted at mean.io

**Comment by BrockMcKean** [comment]
That's basically already how it works. You can specify at `mean install` a
repo to pull it from I'm pretty sure.

Brock McKean
Web: http://brockmckean.com
Email: brock@brockmckean.com

**Comment by ramandv** [comment]
As per my understanding from the code,

"mean publish"  does the following 
  - create a new repo at git.mean.io 
  - and push the code to meanio repository using new meanio remote.
 
So there is no way of publishing only the reference to a github repo as a meanio package.

@BrockMcKean "mean install" does not allow you to install from a repo
```
$mean install https://github.com/pratik60/mean-ga
Package not found.
```

```
$ mean help install

  Usage: mean-install [options]

  Installs a MEAN module

  Options:

    -h, --help  output usage information
    -g, --git  clone using git:// instead of https://
```

**Comment by pratik60** [comment]
@ramandv - Your understanding is correct. Mean does not provide installation for any package outside git.mean.io.

Previously all the packages used to be hosted on github, now they have all be been shipped to git.mean.io. "mean install mean-ga" or "mean install ga" will work for sure.

To install a package from the repo on github, you will have to send a pr to linnovate/mean-cli where the basic logic would be first look for a package in git.mean.io, and if it doesn't exist it can look in github as well. Or use pass that as an option. 

Mean install any way requires a bit of work - needs to support commit id, branch, and tag. If someone has time, this would be a really good candidate for a PR request.

**Comment by liorkesos** [comment]
We have a flag we've prepared to do non git.mean.io installation which was
requested by @almogbaku
I'll send details shortly

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
