### ISSUE TITLE
Custom menus

### ISSUE THREAD

**Issue by zwhitchcox** [linnovate/mean#1021]
Is there any way to make a custom menu?

I would like to remove the top menu, and just use a sidebar. Also, I would like a sidebar on the left, just like the mean admin menu sidebar. Is this achievable?

**Comment by liorkesos** [comment]
If you check here -
http://learn.mean.io/#m-e-a-n-stack-packages-menu-system
You'll see an assignment of  menu: "main"
towards the end...
you can assign a different menu called sidebar and move the menu
registrations to there.
best regards
Lior

On Tue, Jan 20, 2015 at 4:07 PM, zwhitchcox <notifications@github.com>
wrote:

> Is there any way to make a custom menu?
>
> I would like to remove the top menu, and just use a sidebar. Also, I would
> like a sidebar on the left, just like the mean admin menu sidebar. Is this
> achievable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1021>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos
