### ISSUE TITLE
Production vesion: Leverage Browser Caching

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1025]
As advice by google, this should be donne:
https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

How can I add this to my project to improve the speed of my app ?

**Comment by zwhitchcox** [comment]
I don't think you would really want to do this. Angular aggregates and minifies the code, meaning, if you want to change any part of your code, your going to have to change the whole file.

The js file (which is really the only one you would want to cache) is so small that it won't make a big difference anyway. It is only loaded one time, when the user first opens your site, and if the user has the javascript cached, and you've made a change, he's not going to get good results.

The whole aggregated script is about 355KB out of the box, less than that if the client is using a browser with gzip.

If you're worried about SEO, I would install [mean-seo](https://www.npmjs.com/package/mean-seo), as that is the only way you're going to get ranked with Google.

**Comment by zwhitchcox** [comment]
Also, if seo is your goal,you need to install mean-seo.

It is not currently included (although it should be soon), but without it, your site probably wont' show up on google [see here](https://developers.google.com/webmasters/ajax-crawling/docs/specification)

Feel free to use [my fork](https://github.com/zwhitchcox/mean), which is the pull request to add these features.

**Comment by zwhitchcox** [comment]
So, scratch that, you can actually use browser level caching on the bower_components. You just replace the code
```JS
  // Enable compression on bower_components
  app.use('/bower_components', express.static(config.root + '/bower_components'));
```
with
```JS
  // Enable compression on bower_components
  app.use('/bower_components', express.static(config.root + '/bower_components', {maxAge:86400000}));
```
and that will cache all bower components for one day

**Comment by VikramTiwari** [comment]
Fixed.
