### ISSUE TITLE
Sharing Mongoose Schema with Angular - Thoughts on Updating Nested Values in a Record

### ISSUE THREAD

**Issue by hydrotik** [linnovate/mean#1026]
Is there a way/methodology for passing/enforcing the schema definitions on the client side? I am looking at the best way to update portions of a record. Looking at the simple article example, it just updates the entire record and doesn't leverage any of the query functions of Mongoose (for example $elemMatch in an array and updating only that array element).

As Mean is essentially a micro service architecture with the client side accessing the server as an API, it would make sense to me to pass only changed values to the API and have the changes handled on the sever side along with the querying. Versus manipulating the record on the client side and passing the entire record to the server side for updating. However, leveraging the ability to process the data to the client side frees up backend resources.

It would be interested to hear any thoughts on this as well as any plans to integrate any existing tools to mirror the Schema definitions on the client side to the font end side of things. It would be great to get the Schema from the backend through the JSON response or have access to it as persistent object in Angular.

**Comment by hydrotik** [comment]
I'm going to explore using https://github.com/bevry/query-engine

**Comment by hydrotik** [comment]
This looks promising https://github.com/Irrelon/ForerunnerDB

**Comment by VikramTiwari** [comment]
You can easily achieve this by writing your own routes which will access your own controllers and there you can do all sorts of queries with Mongoose.
