### ISSUE TITLE
Article WYSWIG editor

### ISSUE THREAD

**Issue by BrockMcKean** [linnovate/mean#1031]
What is currently there for the articles package is very basic, but works. However, the designers and less technical users would be far more impressed with it if it had a WYSYWIG editor. This is something common that is expected of any kind of blogging or cms-like software. I am not familiar with the _best_ choice for this, but [textAngular](http://textangular.com/) and [ngQuill](https://github.com/KillerCodeMonkey/ngQuill ) seem to stand out in an initial search/scan through Google and http://ngmodules.org

**Comment by enkodellc** [comment]
I use TextAngular and have contributed a bit to it.  It has a lot of features but it does have some special conditions you need to be aware of so read the docs.

**Comment by BrockMcKean** [comment]
@enkodellc Okay, good to know. Looking at texAngular it seems a little more robust in feature, but ngQuill seems like it's based on a more stable project.

**Comment by pratik60** [comment]
You could use tinymce as well.... Of course, that's the age old editor.

For modern wysiwyg you could go for quill, or even better the editor that
medium uses.

**Comment by BrockMcKean** [comment]
Well, maybe which editor is active should be configurable.. which would be very cool. :) Or, maybe we should decide on one to implement first. Maybe people could vote for which one they think should be used?

*[tinyMCE](http://www.tinymce.com/tryit/basic.php)
*[textAngular](http://textangular.com/) 
*[ngQuill](https://github.com/KillerCodeMonkey/ngQuill)
*[medium-editor](http://daviferreira.github.io/medium-editor/)

My thoughts are, medium-editor is nice, but I think it's a little too abstract initially for completely non-technical users, but it might be a cool thing to add if we really changed the way editable font looks in the article package. It's also missing easy access to things like uploading, color selection, and many other simple things you would expect for an "article" editor, so I'm not sure that's a great selection for this in that capacity either.

TextAngular is missing a few complex luxury things like, uploading a photo and specifying the upload to be an image to insert all at once by selecting the image from your file system.

ngQuill and tinyMCE seem to have all the functionality that you could want in an article editor, but I'm not sure how it would fit into the mean.io project. 

Maybe we can vote? I'm thinking ngQuill is a good balance between modern and stable.

**Comment by liorkesos** [comment]
We have implemented an editor using medium editor.
Very basic an initial functionality is in the the "editable" package.

**Comment by BrockMcKean** [comment]
I installed the wixmedia and editable packages and it does look nice. I remember seeing a wixmedia presentation somewhere on youtube you guys did, but I still think that it's all a far cry from being integrated to the articles package and being on par with some of these other tools and expectations non-technical users have of tools for their blog.

**Comment by liorkesos** [comment]
Let's discuss in next meeting.

**Comment by BrockMcKean** [comment]
Sounds good. I will shut my door at work and talk this time if I don't have another meeting or anything.

**Comment by VikramTiwari** [comment]
Awesome idea. I personally like [medium-editor](https://github.com/yabwe/medium-editor)

Also, I think we should create a separate `meanio-articles` package and take all these ideas there to be implemented.
