### ISSUE TITLE
Question about Certificate Authority (HTTPS)

### ISSUE THREAD

**Issue by coolsebz** [linnovate/mean#1034]
hey guys, just saw this piece of code in ```meanio/lib/boostrap.js``` and i was wondering if we could load the CA certificate with it too 
```
    var httpsOptions = {
      key: fs.readFileSync(config.https.ssl.key),
      cert: fs.readFileSync(config.https.ssl.cert)
    };

```

Personally, i received from godaddy both the ssl certificate as well as the CA certificate, and after looking around i saw that most people who enable https in their node apps use this CA file too (usually passing in as an option as the ```ca``` parameter in the https options object. 

If you guys give it a go, i can add this really quick and i'm gonna make a pull request with it :D (gonna be the first time i can actually contribute to this awesome tool)

Cheers!
(sorry if should be posted in the meanio repo's issues, just let me know if that's the case and i'll move it asap)

**Comment by coolsebz** [comment]
Also, at this point, there is no way to automatically redirect over to https if it's available, and in my opinion this is something that should be available as a feature

**Comment by VikramTiwari** [comment]
Few pointers:
- Always use a reverse proxy on production servers
- Use your reverse proxy with HTTPs cert form LetsEncrypt (https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04)
- You can find redirection instruction in the DO link.
