### ISSUE TITLE
has no method 'apply'

### ISSUE THREAD

**Issue by escurzo** [linnovate/mean#1036]
When I try to start my new/clean roject:

$ grunt
Running "hook" task
>> Starting hooked tasks.

Running "clean:0" (clean) task
>> 0 paths cleaned.

Running "jshint:all" (jshint) task
>> 47 files lint free.

Running "csslint:src" (csslint) task
>> 5 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Running "nodemon:dev" (nodemon) task
Waiting...
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
Mean app started on port 3000 (development) cluster.worker.id: 0

<pat_project>/node_modules/meanio/node_modules/q/q.js:128
                    throw e;
                          ^
TypeError: Object #<Object> has no method 'apply'
    at <pat_project>/node_modules/meanio/lib/module.js:131:22
    at <pat_project>/node_modules/meanio/lib/util.js:21:7
    at Array.forEach (native)
    at walk (<pat_project>/node_modules/meanio/lib/util.js:16:25)
    at <pat_project>/node_modules/meanio/lib/util.js:23:7
    at Array.forEach (native)
    at Object.walk (<pat_project>/node_modules/meanio/lib/util.js:16:25)
    at Module.routes (<pat_project>/node_modules/meanio/lib/module.js:130:10)
    at Object.func (<pat_project>/packages/articles/app.js:17:12)
    at Meanio.get (<pat_project>/node_modules/dependable/index.js:127:31)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dalefrancis88** [comment]
I started getting this today too out of the blue after not touching my project for a few days

**Comment by zwhitchcox** [comment]
I just did a fresh install, and it worked for me. Maybe try
```
sudo npm update -g mean-cli
```
?

**Comment by dalefrancis88** [comment]
I should of come back sooner, i figured mine out, it's unrelated to your resolution. I tried to create a package from scratch and forgot the file in the routes directory..fail

**Comment by VikramTiwari** [comment]
Fixed.
