### ISSUE TITLE
npm install errors failing to initialise new meanio server

### ISSUE THREAD

**Issue by laurencefass** [linnovate/mean#1042]
immediately after running "mean init" npm install is failing. the error is at the end of this text but ive included the entire install record... i havent included the npm debug log because it is huge. any help greatly appreciated.

please note on other installations npm install has passed and grunt has failed due to absence of express-session in mongodb. i dont know if these problems are related.

root@host101:/home/nodejs.server.com/meanioserver# ls
bower.json  Gruntfile.js   LICENSE    node_modules  packages  README.md  tools
config	    karma.conf.js  mean.json  package.json  Procfile  server.js

root@host101:/home/nodejs.server.com/meanioserver# npm install

npm WARN engine meanio@0.7.1: wanted: {"node":"0.10.x","npm":"1.4.x"} (current: {"node":"0.10.36","npm":"2.4.1"})

> meanio@0.7.1 preinstall /home/nodejs.server.com/meanioserver/node_modules/meanio
> node ./scripts/preinstall

npm WARN engine mean-cli@0.9.19: wanted: {"node":"0.10.x","npm":"2.1.x"} (current: {"node":"0.10.36","npm":"2.4.1"})

> mean-health@0.1.7 postinstall /home/nodejs.server.com/meanioserver/node_modules/meanio/node_modules/mean-health
> node ./postinstall.js

 
> mean-cli@0.9.19 preinstall /home/nodejs.server.com/meanioserver/node_modules/meanio/node_modules/mean-cli
> node ./scripts/preinstall

\
> meanio@0.7.1 postinstall /home/nodejs.server.com/meanioserver/node_modules/meanio
> cd ./lib/core_modules/server && npm install && cd ../../..

npm WARN package.json server@ No description
npm WARN package.json server@ No repository field.
npm WARN package.json server@ No README data
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! path /root/.npm/express/4.11.1/package
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/root/.npm/express/4.11.1/package'
npm ERR!  { [Error: EACCES, mkdir '/root/.npm/express/4.11.1/package']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/root/.npm/express/4.11.1/package',
npm ERR!   parent: 'server' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodejs.server.com/meanioserver/node_modules/meanio/lib/core_modules/server/npm-debug.log
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! meanio@0.7.1 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the meanio@0.7.1 postinstall script 'cd ./lib/core_modules/server && npm install && cd ../../..'.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodejs.server.com/meanioserver/npm-debug.log

**Comment by laurencefass** [comment]
update: ive checked the root/.npm folder and there is a mix of user ownership on the packages in there. npm installed as root. should all packages in there be root owned for npm install to work?

**Comment by laurencefass** [comment]
is there an easier more reliable way to install meanio than through the mean init/npm install route?

**Comment by liorkesos** [comment]
You install linnovate/mean which depends on the linnovate/meanio npm.
Those two together + the mean-cli are "meanio"

**Comment by laurencefass** [comment]
thanks for advising. im still not entirely clear why the  following commands are not just working as presented. do i have to install some additional npm package? i have all the necessary prerquisites in place and other node projects working as expected.

from mean.io docs:

install the MEAN CLI

$ npm install -g mean-cli (pass)
$ mean init <myApp> (pass)
$ cd <myApp> (pass)
£ npm install (fail) 

is there a step missing? do i need to install linnovate/npm into <myApp>?

**Comment by laurencefass** [comment]
looking here: 

https://github.com/linnovate?query=mean

is the mean init command failing?

**Comment by laurencefass** [comment]
please is there anyone can assist possibly someone who has contributed to development? i need to get this working urgently. thanks.

**Comment by laurencefass** [comment]
is it possible if someone in support could at least give me an indication of the correct versions of node and npm to use. i saw a long list of warnings flashed up showing incompatbilities. please note this is related to my previous post were there were genuine formatting errors in the package.json file invalidating it. any help fixing this issue asap will be genuinely appreciated.

**Comment by liorkesos** [comment]
Hi Laurence,
Sorry, We're working on a larger issue right now with installation.
Sorry youre having a bumpy and unpleasent experience :)
best regards
Lior



On Sun, Feb 1, 2015 at 9:13 PM, laurence fass <notifications@github.com>
wrote:

> is it possible if someone in support could at least give me an indication
> of the correct versions of node and npm to use. i saw a long list of
> warnings flashed up showing incompatbilities. please note this is related
> to my previous post were there were genuine formatting errors in the
> package.json file invalidating it. any help fixing this issue asap will be
> genuinely appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1042#issuecomment-72379004>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by laurencefass** [comment]
if i can be of any assistance, offer any additional info on my own build, or run any further tests my end please let me know and i will be happy to help. thanks, L.

**Comment by caomca** [comment]
Hi I was having a similar issue. I update my development environment to the latest version of node, grunt. Then I ran sudo npm cache clean. Check if this helps.

**Comment by laurencefass** [comment]
upgraded grunt and bower clean all caches now im seeing problems with mongodb referencing  express-session package which appears to be missing. i tried a man ual install has made no difference. really need to get this working soon. please note i have had no problems with npm or node in any other projects... i have raised this new issue in #1046

**Comment by aaronroberson** [comment]
What do you get when you run `mean status`

I was having the same problems as you and I got the error `Invalid MEAN app or not in app root`

The following comment resolve the issue for me:

https://github.com/linnovate/mean/issues/486#issuecomment-43281139

**Comment by liorkesos** [comment]
When you run mean status - are you in the mean app root?

**Comment by aaronroberson** [comment]
Yes I'm in the mean app root.

When I do a `npm ls` I get the following:

`npm ERR! missing: meanio@git+https://github.com/linnovate/meanio, required by mean@0.4.4`

If I do a ls on the directory I get the following:
<pre>
LICENSE		README.md	config		gulpfile.js	mean.json	package.json	server.js
Procfile	bower.json	gulp		karma.conf.js	node_modules	packages	tools
</pre>

Here is the output from running `sudo npm install`
<pre>
npm WARN package.json karma-chrome-launcher@0.1.7 No README data
npm WARN package.json karma-coffee-preprocessor@0.2.1 No README data
npm WARN package.json karma-coverage@0.2.7 No README data
npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
npm WARN engine meanio@0.7.1: wanted: {"node":"0.10.x","npm":"1.4.x"} (current: {"node":"0.12.0","npm":"2.5.1"})

> meanio@0.7.1 preinstall /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio
> node ./scripts/preinstall

npm WARN engine mean-cli@0.9.21: wanted: {"node":"0.10.x","npm":"2.1.x"} (current: {"node":"0.12.0","npm":"2.5.1"})

> mean-health@0.1.7 postinstall /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/node_modules/mean-health
> node ./postinstall.js

\
> mean-cli@0.9.21 preinstall /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/node_modules/mean-cli
> node ./scripts/preinstall

\
> meanio@0.7.1 postinstall /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio
> cd ./lib/core_modules/server && npm install && cd ../../..

npm WARN package.json server@ No description
npm WARN package.json server@ No repository field.
npm WARN package.json server@ No README data
npm WARN locking Error: EACCES, open '/Users/aaronroberson/.npm/_locks/connect-mongo-36ff0dc186831e3c.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aaronroberson/.npm/_locks/connect-mongo-36ff0dc186831e3c.lock failed { [Error: EACCES, open '/Users/aaronroberson/.npm/_locks/connect-mongo-36ff0dc186831e3c.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aaronroberson/.npm/_locks/connect-mongo-36ff0dc186831e3c.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/node_modules/connect-mongo, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/aaronroberson/.npm/_locks/express-session-c7976e0716c4dd36.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aaronroberson/.npm/_locks/express-session-c7976e0716c4dd36.lock failed { [Error: EACCES, open '/Users/aaronroberson/.npm/_locks/express-session-c7976e0716c4dd36.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aaronroberson/.npm/_locks/express-session-c7976e0716c4dd36.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/node_modules/express-session, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/aaronroberson/.npm/_locks/passport-3e4c96366ffa3a98.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aaronroberson/.npm/_locks/passport-3e4c96366ffa3a98.lock failed { [Error: EACCES, open '/Users/aaronroberson/.npm/_locks/passport-3e4c96366ffa3a98.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aaronroberson/.npm/_locks/passport-3e4c96366ffa3a98.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/node_modules/passport, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/aaronroberson/.npm/_locks/cookie-parser-88849829ca2e7988.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aaronroberson/.npm/_locks/cookie-parser-88849829ca2e7988.lock failed { [Error: EACCES, open '/Users/aaronroberson/.npm/_locks/cookie-parser-88849829ca2e7988.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aaronroberson/.npm/_locks/cookie-parser-88849829ca2e7988.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/node_modules/cookie-parser, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/aaronroberson/.npm/_locks/method-override-6b6fc8af4307655a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aaronroberson/.npm/_locks/method-override-6b6fc8af4307655a.lock failed { [Error: EACCES, open '/Users/aaronroberson/.npm/_locks/method-override-6b6fc8af4307655a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aaronroberson/.npm/_locks/method-override-6b6fc8af4307655a.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/node_modules/method-override, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/aaronroberson/.npm/_locks/gridfs-stream-1911cb763414116e.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aaronroberson/.npm/_locks/gridfs-stream-1911cb763414116e.lock failed { [Error: EACCES, open '/Users/aaronroberson/.npm/_locks/gridfs-stream-1911cb763414116e.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aaronroberson/.npm/_locks/gridfs-stream-1911cb763414116e.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/node_modules/gridfs-stream, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/aaronroberson/.npm/_locks/express-920746d8e33fcc3d.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aaronroberson/.npm/_locks/express-920746d8e33fcc3d.lock failed { [Error: EACCES, open '/Users/aaronroberson/.npm/_locks/express-920746d8e33fcc3d.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aaronroberson/.npm/_locks/express-920746d8e33fcc3d.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/node_modules/express, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/aaronroberson/.npm/_locks/express-validator-5e5fef7d82a29c00.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aaronroberson/.npm/_locks/express-validator-5e5fef7d82a29c00.lock failed { [Error: EACCES, open '/Users/aaronroberson/.npm/_locks/express-validator-5e5fef7d82a29c00.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aaronroberson/.npm/_locks/express-validator-5e5fef7d82a29c00.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/node_modules/express-validator, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/node_modules/meanio/lib/core_modules/server/npm-debug.log
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! meanio@0.7.1 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanio@0.7.1 postinstall script 'cd ./lib/core_modules/server && npm install && cd ../../..'.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaronroberson/Sites/sandbox/mean.io/GameSportsNetwork/npm-debug.log
</pre>

**Comment by aaronroberson** [comment]
npm 2.5.1
    mongo 2.6.4
    gulp cli 3.8.11
    gulp local 3.8.11
    grunt-cli 0.1.13

Running `mean init` without sudo doesn't appear to change anything, still getting errors.

**Comment by liorkesos** [comment]
what user are you running this as?
please run
```
whoami
pwd
```

**Comment by aaronroberson** [comment]
whoami - aaronroberson
pwd - /Users/aaronroberson/Sites/sandbox/mean.io/GSNPortal (after switching from GameSportsNetwork init to new init named GSNPortal)

**Comment by aaronroberson** [comment]
Problem solved by following instructions from @liorkesos to run the following commands:

    cd ~/.npm
    sudo chown -R aaronroberson *
    cd ~/Sites/sandbox
    mean init mymeanapp

Thanks @liorkesos you rock my friend!

**Comment by lambertb** [comment]
Solved it as well! Thanks @aaronroberson and @liorkesos

**Comment by pragya-olx** [comment]
nvm use 6.9.4
