### ISSUE TITLE
Error: ENOENT, no such file

### ISSUE THREAD

**Issue by robin521111** [linnovate/mean#1049]
i installed my mean successful but when i tried to running my first page with 'node server', got below error. 

Error: ENOENT, no such file or directory 'C:\CodeForFun\test\pullet\bower_compon
ents\jquery\dist\jquery.min.map'

i am sure that i don't have above folder in my project, and i am tried reinstall bower with npm install -g bower but still meet this error.

even i create it manually, still got error. can anybody tell me how can i solve it?

**Comment by liorkesos** [comment]
Run bower install.

**Comment by davecyen** [comment]
I get this same error on occasion when I try deploying to Heroku. I don't get this issue when running the project locally. I've tried npm cache clean, bower cache clean, npm install, and bower install -- but nothing seems to consistently solve this problem. Sometimes a combination of these commands work, sometimes they don't. Anyone have other ideas?

**Comment by davecyen** [comment]
Perhaps this pull request is related? https://github.com/linnovate/mean/pull/243

**Comment by mwizzle** [comment]
+1

**Comment by sevenfrost** [comment]
bower install

**Comment by VikramTiwari** [comment]
Fixed.
