### ISSUE TITLE
chain of related issues

### ISSUE THREAD

**Issue by metasean** [linnovate/mean#1052]
1. Mean-Admin Package entry points to wrong repo:
    - http://mean.io/#!/packages/538180d8a331eb26d1e97d39 points to https://github.com/linnovate/mean-admin, but the readme for https://github.com/linnovate/mean-admin states:  

        > This package is now obsolete. The new package which is actively being developed is at https://git.mean.io/linnovate/mean-admin.
    - Please redirect http://mean.io/#!/packages/538180d8a331eb26d1e97d39 so it points directly to https://git.mean.io/linnovate/mean-admin.

2. https://git.mean.io/linnovate/mean-admin/blob/master/README.md has the following problems:
   - Continues to point to the obsolute GitHub account:
      > Note: the mean-admin pubilshed on npm does not work with meanio. The line above will pull the module directly from GitHub.  
      - Is it actually pulling from the obsolete GitHub repo (see above)?
      - If it is, please point to the actively maintained git.mean.io repo.
      - When true, please update the README verbiage to indicate it is pulling from the git.mean.io repo.

  - Instructs users to add an entry to non-existent file in the depths of a non-existent directory:
    > Make sure server/config/env/production.js is updated with ...  

     - I just installed the Mean.IO CLI npm package this afternoon and made my very first mean.io application.  There is no `server` directory, yet alone a `server/config/env/production.js`.
     - Please provide more current information on when to add the `mean user <email> -a admin --env production` entry, or clearly state that the user needs to create a new `server/config/env/production.js`.

3. The git.mean.io sign up process is broken:
   - I tried to report the previous issues through the git.mean.io repo.  To do so I need to create an account.  When I click the "Sign In" button I'm taken to https://git.mean.io/users/sign_in?redirect_to_referer=yes which has a very unhelpful "Don't have an account? Sign up" option.  When I click the "Sign up" link I'm taken to https://git.mean.io/users/sign_up which is *EXACTLY* like the Sign in page and *provides no way to actually create a new account*.
   - Please either make it possible to sign up for a new account or remove the Sign up section of the Sign in page and leave an obvious message that you aren't accepting new sign ups.

**Comment by VikramTiwari** [comment]
Since `mean.io` based package support is being deprecated parts of this issue makes sense more than normal. Rest assured this is being worked upon.
