### ISSUE TITLE
non-reusable schemes "Schema hasn't been registered" mena#0.4.3 

### ISSUE THREAD

**Issue by jcsena** [linnovate/mean#1055]
Hi! My questions is that the new version can not reuse schemes other packages , if the previous 0.4.2 version can do this .
Try using another controller package to not recreate the model , but just repeats the error.

**Comment by andrija-hers** [comment]
You can, actually, but now packages are just integrated tighter. I need to ask you for details of the particular use case that fails - from what package do you need to use module/scheme from what package?
I'm asking because I need to point you to the particular Module registration function - where you will need to add the dependency to the package you need the module/scheme from.

**Comment by jcsena** [comment]
ok , I have a package called "posting " and have another called "categories" .
ok , in " categories " in my model moogose add a scheme called "Posting" and that it can not be reused in "posting " because it does not recognize

/categories/server/model

var PostingSchema = new Schema({
  created: {
    type: Date, 
    default: Date.now
  },
  title: {
    type: String, 
    required: true,
    trim: true
  },
  images: Array,
  categorie: String,
  subcategorie: String,
  locale:Array,
  price :Object,
  description: String, 
  name:String,
  email:String,
  phone:String,
  aggregates:Object
});
mongoose.model('Posting', PostingSchema);

now, in the controller of "posting" I want to reuse the model "Posting"
/posting/server/controller


var mongoose = require('mongoose'),
    Posting = mongoose.model('Posting');


exports.findPosting = function(req, res) {
  var postingId = req.params.postingId;
  var query = Posting.findOne({
      _id: postingId
    });

  query.exec(function(err, posting) {
    if (err) {
      res.render('error', {
        status: 500
      });
    } else {
      res.json(posting);
    }
  });
};

Schema hasn't been registered for model "Posting".

Now this if I can do in version 0.4.2 and it works

Thx

**Comment by andrija-hers** [comment]
In file
packages/posting/app.js
you have the standard function
Posting.register(function(app, auth, database){...

(I believe I got the word "Posting" right).

after the "database" parameter, add the "categories" parameter. Your package "posting" depends on "categories", right? That's what Dependency Injection is all about... So finally your registration function should look like

Posting.register(function(app, auth, database, categories){...

**Comment by jcsena** [comment]
this is true but that version 0.4.2 is not necessary ?

**Comment by andrija-hers** [comment]
Version 0.4.2. has serious performance problems (if you didn't experience them, you were just lucky :) ), so 0.4.3 should be considered as an obligatory security/performance patch for 0.4.2

**Comment by jcsena** [comment]
Thanks , really was silly of mine hand, but equally are giving support is magnificent.

**Comment by andrija-hers** [comment]
Until the 0.4.3 version, DI was not given the role it deserved. Because of that, versions up to 0.4.2 worked on hacks. 0.4.2 revealed the problem, and finally 0.4.3 works as expected.
However, the importance of the parameters in the register function for Modules is not emphasized enough. I'm glad I could help, and ask you to spread the DI word whenever possible :)

**Comment by jcsena** [comment]
Hi Again ,
ok , the jshint the error , that is, do not show me the error is released but really there because when you record another package

NamePackage.register (function ( app , auth , database , Other ) {

This removes all the routes the packet trasncurrente

as finding I can not reuse another model would have to copy the same , in another package and that would not be very well : \

 you should replicate the bug creating a model in a package and then try to use it in another package , and each with their routes , the error will be displayed

**Comment by jcsena** [comment]
ok , I simply recreate the error code .
Then , create two packages "ad" and "categorie" with simple model , simple route , and simple controller I describe below:

********************************************************************************************
****ad package *****
********************************************************************************************
```javascript
//model "ad"
'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

 var AdSchema = new Schema({
  title         : String
});
mongoose.model('Ad', AdSchema);
```
********************************************************************************************
```javascript
//route "ad"
'use strict';
 var index = require('../controllers/ads');
   module.exports = function(Ads, app, auth, database) {
     app.route('/ads/all').get(index.findAds);
};
```
********************************************************************************************
```javascript
//controller "ad"
'use strict';
var mongoose = require('mongoose'),
      Ad              = mongoose.model('Ad');

exports.findAds = function(req, res) {

  Ad.find().exec(function(err,data){
   if(err) return res.status(500).json({
        error: 'err'
      });
    res.json(data);
  });
};
```
********************************************************************************************
****categorie package *****
********************************************************************************************
```javascript
//model "categorie"
'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

 var CategorieSchema = new Schema({
  title         : String
});

mongoose.model('Categorie', CategorieSchema);
```
********************************************************************************************
```javascript
//route "categorie"
'use strict';
var index = require('../controllers/categories');

module.exports = function(Categories, app, auth, database) {

  app.route('/categories/all')
  .get(index.findCategories);
};
```
********************************************************************************************
```javascript
//controller "categorie"
'use strict';

var mongoose = require('mongoose'),
  Categorie = mongoose.model('Categorie');

exports.findCategories = function(req, res) {

  Categorie.find().exec(function(err,data){
   if(err) return res.status(500).json({
        error: 'Cannot delete the article'
      });
    res.json(data);
  });
};
```
![screen shot 2015-02-11 at 7 48 11 am](https://cloud.githubusercontent.com/assets/4293508/6147294/c16df7aa-b1c3-11e4-9380-5ee7fe33a9ad.png)

********************************************************************************************
and successfully Read

in this process we are well ! , 
but when I try to use the model of another package I get the first error !

```javascript
'use strict';
/**
 * Module dependencies.
 */
var mongoose  = require('mongoose'),
    Ad        = mongoose.model('Ad'),
    Categorie = mongoose.model('Categorie');
/**
 * Create an categorie
 */
exports.findAds = function(req, res) {

  Ad.find().exec(function(err,data){
   if(err) return res.status(500).json({
        error: 'Cannot delete the article'
      });
    res.json(data);
  });
};
exports.findCategoriesFromAd = function(req, res) {
  Categorie.find().exec(function(err,data){
   if(err) return res.status(500).json({
        error: 'err'
      });
    res.json(data);
  });
};
```

![screen shot 2015-02-11 at 8 11 51 am](https://cloud.githubusercontent.com/assets/4293508/6147465/dbab1510-b1c5-11e4-910e-07eb734f0751.png)

### Schema hasn't been registered for model "Categorie".

well, now you tell me that you register the package.
and error in routes

**Comment by lvarayut** [comment]
I'm using the `0.5.0` version and still facing the same issue.
