### ISSUE TITLE
After logging in value of Global is not updated

### ISSUE THREAD

**Issue by nabello** [linnovate/mean#1056]
Ok I'm actively developing a module that uses the user roles (authenticated and admin). The issue here is that I go to /login, login with my credentials (authenticated user not admin) and I'm successfully redirected to / but if I inspect the value of Global, witch should contain something looking like this 

e.g. Object {user: Object, authenticated: 1, isAdmin: false} 

instead looks like this 
e.g. Object {user: Object, authenticated: false, isAdmin: false, registerForm: false}).

If I happen to refresh the page the value of Global updates correctly. Any fixes/suggestions would be welcome !

Best,
Nicola

**Comment by pratik60** [comment]
your answer is in system/server/controllers/index.js where there is a
res.render .....

The problem is on subsequent traversal within the mean app, this res.render
is not called despite the chat in the user object. What you need to do is
on the angular end, make sure that you do a window.location.reload() after
login, so that it refreshes this state. There may actually be a better
solution so I will stay tuned to this thread.

**Comment by jcsena** [comment]
In system/public/global.js change variable
```javascript
  _this._data.authenticated = window.user.roles.length;
```

**Comment by nabello** [comment]
Thx pratik60 for now I've solved this problem by adding window.location.reload(); to line 57 of /packages/users/public/controllers/meanUser.js but there definitely must be a more elegant solution to this. I'll stay tuned to this thread as well.

**Comment by timelf123** [comment]
Still having this issue - where did you guys call window.location.reload()?

`console.log(Global)`

`Object {user: "", authenticated: false, isAdmin: false}`

The values in `packages/core/system/server/views/index.html` are not set:
```
  <script type="text/javascript">
    window.user = {{user|json|safe}};
    window.modules = null;
  </script>
```

**Comment by VikramTiwari** [comment]
Seems like this is still an issue. Sigh!

**Comment by timelf123** [comment]
@VikramTiwari this should be solved with https://github.com/linnovate/meanio-system/pull/1 

The Global service is called every time `$rootScope 'loggedin'` is called
