### ISSUE TITLE
Failed at the meanio@0.7.1 postinstall script 'cd ./lib/core_modules/server && npm install && cd ../../..'.

### ISSUE THREAD

**Issue by alexryall** [linnovate/mean#1061]
OS: Ubuntu Server 14.10

After trying:
     mean init myApp
     cd myApp
     npm install myApp

Error (same for my own user and root):
     npm ERR! Linux 3.16.0-23-generic
     npm ERR! argv "node" "/usr/local/bin/npm" "install"
     npm ERR! node v0.10.25
     npm ERR! npm  v2.5.1
     npm ERR! path /root/.npm/express-session/1.10.2/package
     npm ERR! code EACCES
     npm ERR! errno 3

     npm ERR! Error: EACCES, mkdir '/root/.npm/express-session/1.10.2/package'
     npm ERR!  { [Error: EACCES, mkdir '/root/.npm/express-session/1.10.2/package']
     npm ERR!   errno: 3,
     npm ERR!   code: 'EACCES',
     npm ERR!   path: '/root/.npm/express-session/1.10.2/package',
     npm ERR!   parent: 'server' }
     npm ERR!
     npm ERR! Please try running this command again as root/Administrator.

     npm ERR! Please include the following file with any support request:
     npm ERR!     /home/alex/myApp/node_modules/meanio/lib/core_modules/server/npm-debug.log
     npm ERR! Linux 3.16.0-23-generic
     npm ERR! argv "node" "/usr/local/bin/npm" "install"
     npm ERR! node v0.10.25
     npm ERR! npm  v2.5.1
     npm ERR! code ELIFECYCLE

     npm ERR! meanio@0.7.1 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
     npm ERR! Exit status 3
     npm ERR!
     npm ERR! Failed at the meanio@0.7.1 postinstall script 'cd ./lib/core_modules/server && npm install && cd ../../..'.
     npm ERR! This is most likely a problem with the meanio package,
     npm ERR! not with npm itself.
     npm ERR! Tell the author that this fails on your system:
     npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
     npm ERR! You can get their info via:
     npm ERR!     npm owner ls meanio
     npm ERR! There is likely additional logging output above.

     npm ERR! Please include the following file with any support request:
     npm ERR!     /home/alex/myApp/npm-debug.log

**Comment by kaizokuace** [comment]
I'm confirming this issue as well: 
```
> meanio@0.7.1 postinstall /Users/hasenahmad/Development/986Studios/HerokuApps/nineeightsix/node_modules/meanio
> cd ./lib/core_modules/server && npm install && cd ../../..

npm WARN package.json server@ No description
npm WARN package.json server@ No repository field.
npm WARN package.json server@ No README data
npm http GET https://registry.npmjs.org/connect-mongo
npm http GET https://registry.npmjs.org/express-validator
npm http GET https://registry.npmjs.org/gridfs-stream
npm http GET https://registry.npmjs.org/cookie-parser
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express-session
npm http GET https://registry.npmjs.org/passport
npm http GET https://registry.npmjs.org/method-override
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/express-session
npm ERR! Error: EACCES, mkdir '/Users/hasenahmad/tmp/npm-56938-aESWU5qE'
npm ERR!  { [Error: EACCES, mkdir '/Users/hasenahmad/tmp/npm-56938-aESWU5qE']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/hasenahmad/tmp/npm-56938-aESWU5qE',
npm ERR!   parent: 'server' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/Users/hasenahmad/.nvm/v0.10.25/bin/npm" "install"
npm ERR! cwd /Users/hasenahmad/Development/986Studios/HerokuApps/nineeightsix/node_modules/meanio/lib/core_modules/server
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.7
npm ERR! path /Users/hasenahmad/tmp/npm-56938-aESWU5qE
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/Users/hasenahmad/tmp/npm-56938-aESWU5qE'
npm http 304 https://registry.npmjs.org/passport
npm http 304 https://registry.npmjs.org/gridfs-stream
npm http 304 https://registry.npmjs.org/cookie-parser
npm http 304 https://registry.npmjs.org/express-validator
npm http 304 https://registry.npmjs.org/connect-mongo
npm http 304 https://registry.npmjs.org/method-override
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/hasenahmad/Development/986Studios/HerokuApps/nineeightsix/node_modules/meanio/lib/core_modules/server/npm-debug.log
npm ERR! not ok code 0
npm ERR! meanio@0.7.1 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the meanio@0.7.1 postinstall script.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/Users/hasenahmad/.nvm/v0.10.25/bin/npm" "install"
npm ERR! cwd /Users/hasenahmad/Development/986Studios/HerokuApps/nineeightsix
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.7
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/hasenahmad/Development/986Studios/HerokuApps/nineeightsix/npm-debug.log
npm ERR! not ok code 0
```

also after running gulp:

```
[17:40:02] Using gulpfile ~/Development/986Studios/HerokuApps/nineeightsix/gulpfile.js
[17:40:02] Starting 'clean'...
[17:40:02] Starting 'jshint'...
[17:40:02] Starting 'less'...
[17:40:02] Starting 'csslint'...
[17:40:02] Starting 'env:develop'...
[17:40:02] Finished 'env:develop' after 59 μs
[17:40:02] Starting 'develop'...
[17:40:02] Finished 'develop' after 38 ms
[17:40:02] Starting 'watch'...
[17:40:04] Finished 'watch' after 1.47 s
[17:40:04] Live reload server listening on: 35729
[17:40:04] Finished 'clean' after 1.71 s
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node --debug server.js`
debugger listening on port 5858

module.js:340
    throw err;
          ^
Error: Cannot find module 'meanio'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/hasenahmad/Development/986Studios/HerokuApps/nineeightsix/server.js:12:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[gulp] [nodemon] app crashed - waiting for file changes before starting...
[17:40:06] csslint: 5 files lint free
[17:40:06] Finished 'csslint' after 3.66 s
[17:40:06] Finished 'less' after 3.86 s
[17:40:06] jshint: 44 files lint free
[17:40:06] Finished 'jshint' after 4.31 s
[17:40:06] Starting 'default'...
[17:40:06] Finished 'default' after 4.74 μs
```

**Comment by liorkesos** [comment]
This is a permissions problem.
Start again and make sure all of your ~/.npm directory subdirs are all with your permissions and not with root

**Comment by ravimathur23** [comment]
Thanks for your response @liorkesos. 
I followed the meanio documentation for installation but somehow the '~/.npm/_locks' owner and group is coming as root. Once I changed that to my permissions, the 'npm install' works fine for me. 

drwxr-xr-x   2 root     root     45056 Feb 14 14:50 _locks
chown and chgrp recursilvely for _locks.
drwxr-xr-x   2 ramathur ramathur 57344 Feb 14 15:25 _locks

**Comment by kaizokuace** [comment]
Yea this worked for me as well. I ran 
```
sudo chown -R `whoami` ~/.npm 
```

**Comment by alexryall** [comment]
Thanks that worked

**Comment by mcarlucci** [comment]
Thanks Kaizokuace, sudo chown -R `whoami` ~/.npm worked for me

**Comment by Carlos487** [comment]
I was having the same issue on Mac OS X Yosemite, but not on windows, as @kaizokuace said, after running
```
sudo chown -R `whoami` ~/.npm 
```
the command npm install worked correctly

**Comment by SixCopters** [comment]
Had the same issue.  Might be worth clarifying in the instructions when to run sudo, and when not to, and why

**Comment by CoericK** [comment]
When should i use:
```
chown -R `whoami` ~/.npm 
```
I've been trying to run Mean.io on OS X 10.10 and im unable to start an app: mean init app, its so frustrating that this bug is out there and cant do nothing.

**Comment by VikramTiwari** [comment]
Re-open if still an issue.
