### ISSUE TITLE
layout override issues

### ISSUE THREAD

**Issue by tmpg** [linnovate/mean#1063]
I have been trying to override the header by introducing: app.set('views', __dirname + '/server/views'); to my app.js in my new custom package. It did not override it until i added MYPACKAGE.register(function(system, app, auth, database), BUT that caused some routing issue because the global variable no longer works for example the header now displays {{global.user.name}} in the header instead of the username.... anyone have any suggestions?

**Comment by camhart** [comment]
This isn't a solution, but a workaround I figured out.  'app.set' will accept lists of paths.  It looks at the first element for the given view and then goes on to the next.  To fix it I made the app.set within my system package/app.js file an array with the first element pointing towards my views within my package, and the second element being the default value it had.  It ended up looking something like below.

app.set('views', [__dirname + '/../custom/my-app-name/public/views', __dirname + '/server/views']);

**Comment by tmpg** [comment]
Thank you for responding!

I will check this solution out and get back to you.

Best Regards,
Tim

**Comment by ballenjr** [comment]
Is there another way to do this without changing the core package? I am trying to override from my custom package but injecting System as a dependency no longer works to ensure load order. As per the docs: http://learn.mean.io/#mean-stack-packages-overriding-the-default-layouts

**Comment by ballenjr** [comment]
In fact it just injects undefined.

**Comment by VikramTiwari** [comment]
This works fine last I checked. Please reopen issue if required.
