### ISSUE TITLE
Mean init creates projects as submodules with local git upstream set making it difficult to use

### ISSUE THREAD

**Issue by nickjuntilla** [linnovate/mean#1067]
I've been trying for 2 hours to use this mean init project in my main git-hub project, but for some reason the init adds .git files by default. This creates an automatic sub-module within a project, which then becomes cached somewhere globally so even removing the .git files doesn't matter. In order to do anything in the project we need to modify folders in it. Maybe there is a use case for keeping it linked back to the main project, but the we need to be told how that can possibly work. As it is I can't get past init and run. I want to start changing and adding files and have my own repot, but it just shows up as a a grayed out submodule folder in in my repo in github. What can we do please?

**Comment by VikramTiwari** [comment]
Fixed.
