### ISSUE TITLE
How to authenticate 

### ISSUE THREAD

**Issue by xkeshav** [linnovate/mean#1068]
I am working on MEAN stack and created a project on my localhost

now I want to host it online, so this GitLab comes with such facility.I have selected private type repository.

I have added SSH key to my local desktop /Home folder ( with other name as I already have id_ras.pub for other github project )

now it gives authentication failure whenever i enter the password.
I have checked the password . I think I am doing some silly mistake. Kindly guide me.
adding screen shot for the final error 
![firefox_screenshot_2015-02-23t06-44-43 666z](https://cloud.githubusercontent.com/assets/415219/6323773/ee689760-bb55-11e4-980d-ecfbd2aafa6e.png)
![screenshot from 2015-02-23 12 19 22](https://cloud.githubusercontent.com/assets/415219/6323796/5eec7f9c-bb56-11e4-902e-a3a069992760.png)

**Comment by xkeshav** [comment]
What so far i come to know that there is already a .git folder which have different .git project

So created a new directory and init geo  but this it gives authentication error again:

          git push -u origin master
         git@git.mean.io's password: 
                Permission denied, please try again.
         git@git.mean.io's password: 
         Permission denied, please try again.
         git@git.mean.io's password: 
            Permission denied (publickey,password).
            fatal: Could not read from remote repository.

          Please make sure you have the correct access rights
          and the repository exists.

**Comment by codydaig** [comment]
Your trying to push to the main mean repo hosted on github by linnovate. 

You need to run this command in your console:
git remote add gilt git@git.mean.io:xkeshav/geoFM.git

Then instead of running "git push -u origin master" you need to run:
git push -u gitlab master

**Comment by codydaig** [comment]
Ah, your second attempt and error logs show that you have not established your public key on the git.mean.io GitLab server yet.

**Comment by xkeshav** [comment]
codyaig :  I have tried to run below command 
git remote add gilt git@git.mean.io:xkeshav/geoFM.git

it return repository already exist That's why I tried the other approach.

btw is it **gilt**  or **git** ?

**Comment by xkeshav** [comment]
for second attempt : How to establish public key on git.mean.io 

what I have read the [instructions given here](https://git.mean.io/help/ssh/ssh.md)
but there is one changes I have done while generating SSH.  there is already *id_rsa.pub* and other files in the **.ssh* folder for other projects running with different credentials and I afraid to change it or overwritten so I have generate `ssh` file with new name and it saved on /home with `new` & `new.pub`  

now will you guide where is the mistake?

I also have doubt on the documentation 

> Copy-paste the key to the 'My SSH Keys' section under the 'SSH' tab in your user profile. Please copy the complete key starting with ssh- and ending with your username **and host.**

so do I need to add host manual or just copy the code of geo.pub and add into 
https://git.mean.io/profile/keys SSH keys section

**Comment by xkeshav** [comment]
:~/geoFM$:  git remote add gilt git@git.mean.io:xkeshav/geoFM.git
    :~/heoFM$: git push -u gitlab master

BUT gives error :(

> fatal: 'gitlab' does not appear to be a git repository
> fatal: Could not read from remote repository.

> Please make sure you have the correct access rights and the repository exists.

**Comment by codydaig** [comment]
Type: gilt should be gitlab.

**Comment by VikramTiwari** [comment]
Fixed.
