### ISSUE TITLE
git mean io password?

### ISSUE THREAD

**Issue by xkeshav** [linnovate/mean#1069]
what I have done so far 

    mkdir prof
    cd prof
    git init
    touch README
    git add README
    git commit -m 'first commit'
    git remote add origin git@git.mean.io:xkeshav/whatever.git
  
- generate SSH key  
- add *SSH key* into SSH Keys section on [git mean](https://git.mean.io/profile/account)
- `git push -u origin master`

> Agent admitted failure to sign using the key.
> git@git.mean.io's password: 

I don't understand which password it is asking for? 

I have passed my github account password , my  gitlab password , my ststemn password even the secret key but it gives error continuously

 **Permission denied, please try again.**

Please light on my missing points.

**Comment by liorkesos** [comment]
Try to run mean register
