### ISSUE TITLE
no server and public (client) file structure on new install.

### ISSUE THREAD

**Issue by laurencefass** [linnovate/mean#1073]
I have finally got my first meanio stack to run (running bower install which is not mentioned in the guide). 

There appears to be a problem with the default file structure. I was expecting this: http://learn.mean.io/#m-e-a-n-stack-packages-files-structure (and other pages on the web).

The project created by npm install has not provided a file structure for server and public folder trees. Is that intentional i.e. are you being less opinionated with the latest version - or has something gone wrong with the installation?

thanks

laurence

**Comment by laurencefass** [comment]
node.js does seem to be responding with default home page content though i cant find the routing for this. It would much easier if i had an editable landing page in my own project to start from. 

where does the home page content come from if i dont have server and public folders in my project?

**Comment by VikramTiwari** [comment]
@laurencefass Please read our wiki for more questions or ask on the gitter chatroom. (https://gitter.im/linnovate/mean)
