### ISSUE TITLE
Grunt issue after updating to latest mean

### ISSUE THREAD

**Issue by ramandv** [linnovate/mean#1074]
I have updated my mean app to the latest 
```
$ git pull upstream master
$ npm install
```
After that not able to run grunt, the issue is because of this commit 5fbe7358fabc794e6699e83cee0eec8a90cff94a

Currently, I manually add those deleted lines to my package.json

**Comment by liorkesos** [comment]
We're moving to gulp alltogether and working on it in the 2gulp branch.
Maintanence of two task runners isn't working out.
Closing issue
