### ISSUE TITLE
issue on $ cd <myApp> && npm install

### ISSUE THREAD

**Issue by Artofacks1** [linnovate/mean#1075]
cd ../../..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanio@0.7.1 postinstall script 'cd ./lib/core_modules/server && npm install && cd ../../..'.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.

Any help is appreciated, I've installed and used before but looks like the latest build has errors.

**Comment by martinuho** [comment]
I have this problem as well- will be emailing them shortly.

**Comment by liorkesos** [comment]
That's a very old meanio.
Make sure you upgrade to 0.8.2/3

**Comment by martinuho** [comment]
http://stackoverflow.com/questions/8191459/how-to-update-node-js

I wiped my whole Node JS and installed the latest stable version. 
Worked for me.

**Comment by VikramTiwari** [comment]
Fixed.
