### ISSUE TITLE
MissingSchemaError: Schema hasn't been registered

### ISSUE THREAD

**Issue by elvisvoer** [linnovate/mean#1080]
Hey guys,

I have just stumbled upon a very strange issue. I have a custom package that has a model defined, just as the articles module, that I am using in the users module. Everything was working fine until I created a new custom package and I started receiving the error message:

MissingSchemaError: Schema hasn't been registered...

Is this because lazy-dependable somehow does not load the dependencies at the right moment? Perhaps it is using a async load?

Elvis

**Comment by jasonok6** [comment]
I am having what I believe is the same issue.  I have two packages one package named "gme" and this package contains a vanilla model called "states".   

**/packages/custom/gme/server/models/states.js:**  
```
var mongoose = require('mongoose');
var schema = mongoose.Schema({
    id: String,
    country_id: String,
    name: String,
    abbreviation: String
}, {collection: 'states'});
mongoose.model('states', schema);
```  

I then have a second package called "gov" which instantiates  the states model from gme on line 2 of the controller like so:

**/packages/custom/gov/server/controllers/states.js:**  
 ```
'use strict';
var mongoose = require('mongoose'),
     state = mongoose.model('states'); //this errors out randomly

...
exports.doSomeSuch = function(req, res) {
    //defining the state model here, where it will be used, fixes the bug
    //var state = mongoose.model('states');
}
...
```

If I startup my mean.io app using grunt or even "node server.js" it runs 2 out of 3 times with no issue.  However 1 out of 3 times I will get the following error on line 2 of /gov/server/controllers/states.js:
```
MissingSchemaError: Schema hasn't been registered for model "states".
```
It seems to me like there is a race issue when attempting to instantiate a model within a custom package that was defined in a different custom package.  

This is an easy bug to fix by moving the instantiation of the model to the specific function in which the model will be used.

**Comment by elvisvoer** [comment]
Hey,

Thanks for the reply. I am not sure I was using the same model in both packages. I can't remember exactly what caused the error as I have been focusing on other parts of the application but I will try reproduce the bug and see how it goes.

Cheers,
Elvis

**Comment by VikramTiwari** [comment]
Fixed.

**Comment by ScottFred** [comment]
@jasonok6 Did you ever get a response to your question about a possible race-condition when loading Mongoose Models?  We are seeing the same thing you reported seeing and as our app gets larger, the failed race condition occurs more frequently (which is not surprising).

**Comment by ScottFred** [comment]
@VikramTiwari  Can you tell me what version of MEAN.io this fix was made it, or better yeet, what lines were affected - maybe a Git commit that I can reference?  We forked MEAN.io and we may need to reproduce the fix that you checked in.  Thanks!

**Comment by VikramTiwari** [comment]
@ScottFred You might wanna use the solution suggested by @jasonok6. Not sure if this was fixed any other way.

**Comment by ScottFred** [comment]
@VikramTiwari  Yeah, I saw that, just a lot of places in our code where we do that, so I was hoping for a more global solution.  Do you happen to know what causes this race condition?

**Comment by VikramTiwari** [comment]
Not sure but could be the meanio module which acts as aggregator for all of
the packages.
