### ISSUE TITLE
Low hanging fruit - /articles 303 -> /articles/

### ISSUE THREAD

**Issue by MichaelJCole** [linnovate/mean#1082]
Hey, I noticed this in my server log every time I clicked the "Articles" menu link.
```
GET /loggedin 304 1.060 ms - -
GET /articles 303 1.610 ms - -
GET /articles/ 304 3.155 ms - -
```
We could change the articles example module to make just one or two requests

**Comment by VikramTiwari** [comment]
No longer relevant, but will look for similar issues in latest versions.
