### ISSUE TITLE
Does not startup on node v0.12.0

### ISSUE THREAD

**Issue by fir3pho3nixx** [linnovate/mean#1089]
Hi

This might not in fact be a problem in your code but perhaps something to do with mongoose? Also not entirely sure if anyone is actually supporting latest version of node so you are welcome to tell me: "No, too hard, too many dependencies" :)

Some output: 

$ grunt
Running "hook" task
>> Starting hooked tasks.

Running "clean:0" (clean) task
>> 0 paths cleaned.

Running "jshint:all" (jshint) task
>> 42 files lint free.

Running "csslint:src" (csslint) task
>> 5 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Running "nodemon:dev" (nodemon) task
Waiting...
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
Debugger listening on port 5858
/usr/local/src/nodejs/playo-mean/packages/contrib/mean-admin/public/assets/css/themes.css not found
/usr/local/src/nodejs/playo-mean/packages/contrib/mean-admin/public/assets/js/users.js not found
/usr/local/src/nodejs/playo-mean/packages/contrib/mean-admin/public/assets/js/themes.js not found
/usr/local/src/nodejs/playo-mean/packages/contrib/mean-admin/public/assets/js/modules.js not found
/usr/local/src/nodejs/playo-mean/packages/contrib/mean-admin/public/assets/js/ng-clip.js not found
/usr/local/src/nodejs/playo-mean/packages/contrib/mean-admin/public/assets/js/settings.js not found
Mean app started on port 3000 (development) cluster.worker.id: 0
/usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:107:17)
    at null.<anonymous> (/usr/local/src/nodejs/playo-mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
[nodemon] app crashed - waiting for file changes before starting...
^C

Execution Time (2015-03-11 18:30:11 UTC)

Execution Time (2015-03-11 18:29:59 UTC)

Execution Time (2015-03-11 18:30:11 UTC)
concurrent:tasks  37m 57.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 38m 9.1s

watch            37m 46.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 37m 57.3s

nodemon:dev      37m 46.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 37m 57.3s

**Comment by andrija-hers** [comment]
http://hueniverse.com/2015/03/02/the-node-version-dilemma/

**Comment by liorkesos** [comment]
I've worked with iojs with recent mean...
Lior

On Wed, Mar 11, 2015 at 10:51 PM, Andrija Petrovic <notifications@github.com
> wrote:

> http://hueniverse.com/2015/03/02/the-node-version-dilemma/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1089#issuecomment-78368610>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by fir3pho3nixx** [comment]
Ok, I always had this sense naturally(because of somewhat spooky errors that cropped up switching to v0.11 or v0.12 using NVM) but never found any good reading on it. 

Kind of begs the question, who is holding us up here in the now though. Mongoose right? Perhaps this could all run on node v0.12 if we got mongoose to support it. I reckon it is holding heaps of people up because it stores data. 

Not the first time I have run into this issue and it is mostly centered around these guys.

Not upgrading will kill node.

**Comment by fir3pho3nixx** [comment]
Ok, I always had this sense naturally(because of somewhat spooky errors that cropped up switching to v0.11 or v0.12 using NVM) but never found any good reading on it. 

Kind of begs the question, who is holding us up here in the now though. Mongoose right? Perhaps this could all run on node v0.12 if we got mongoose to support it. I reckon it is holding heaps of people up because it stores data. 

Not the first time I have run into this issue and it is mostly centered around these guys.

Not upgrading will kill node.

**Comment by fir3pho3nixx** [comment]
@Lior - Are you sure you are running v0.12? Also what environment? I am using a mac(yosemite) with node installed via hombrew.

**Comment by liorkesos** [comment]
also with yosemite - node throgh nvm

$ node --version

v0.12.0

$ nvm ls

    iojs-v1.3.0

        v0.12.0

->       system

stable -> 0.12 (-> v0.12.0) (default)

On Wed, Mar 11, 2015 at 11:50 PM, Gav <notifications@github.com> wrote:

> @Lior <https://github.com/Lior> - Are you sure you are running v0.12?
> Also what environment? I am using a mac(yosemite) with node installed via
> hombrew.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1089#issuecomment-78380121>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by fir3pho3nixx** [comment]
Right, so had some updates that I needed to apply, rebooted tried again and still same error. Might be a difference between io.js and the version on home brew. Home brew uses Joyent's version.

http://brewformulas.org/Node

Going to re-raise this with mongoose after a little more investigation.
