### ISSUE TITLE
Gulp running new project failed

### ISSUE THREAD

**Issue by zhanghan177** [linnovate/mean#1091]
My environment: node: 0.10.37, npm: 1.4.28

After creating a new project with `mean init <name>`, and `npm install`,

I start mongod and ran `Gulp`.

Then I got this error log:

```
[03:10:11] Using gulpfile ~/Desktop/MoneyPitcher/gulpfile.js
[03:10:11] Starting 'clean'...
[03:10:11] Starting 'jshint'...
[03:10:11] Starting 'less'...
[03:10:11] Starting 'csslint'...
[03:10:11] Starting 'env:develop'...
[03:10:11] Finished 'env:develop' after 81 μs
[03:10:11] Starting 'develop'...
[03:10:12] Finished 'develop' after 85 ms
[03:10:12] Starting 'watch'...
[03:10:17] Finished 'watch' after 5.45 s
[03:10:17] Live reload server listening on: 35729
[03:10:17] Finished 'clean' after 6 s
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node --debug server.js`
debugger listening on port 5858
[gulp] [nodemon] watching 31,452 files - this might cause high cpu usage. To reduce use "--watch".
Mean app started on port 3000 (development) cluster.worker.id: 0

/Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/Users/zhanghan/Desktop/MoneyPitcher/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
[gulp] [nodemon] app crashed - waiting for file changes before starting...
[03:10:24] csslint: 5 files lint free
[03:10:24] Finished 'csslint' after 13 s
[03:10:26] Finished 'less' after 15 s
[03:10:27] jshint: 43 files lint free
[03:10:27] Finished 'jshint' after 16 s
[03:10:27] Starting 'default'...
[03:10:27] Finished 'default' after 8.22 μs
```

What's more, I can not get it running when I init a new project with Grunt. It will give me another error message, saying missing some package.

**Comment by zhanghan177** [comment]
In Grunt it says I am missing package 'minimatch'

**Comment by SibuStephen** [comment]
Hi i'm getting the same error message, can you please tell me the how did you solve that  scenario ?

**Comment by liorkesos** [comment]
What operating are you guys running on?
I saw a similar issue recently on windows...
Lior

On Thu, Mar 12, 2015 at 3:23 PM, Sibu Stephen <notifications@github.com>
wrote:

> Hi i'm getting the same error message, can you please tell me the how did
> you solve that scenario ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1091#issuecomment-78478018>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by SibuStephen** [comment]
Me ubuntu 14.04

**Comment by liorkesos** [comment]
Please paste value of
node version : node --version
npm version: npm --version
mongo version
mean stuff  versions : run mean status in the application root
Lior

On Thu, Mar 12, 2015 at 3:32 PM, Sibu Stephen <notifications@github.com>
wrote:

> Me ubuntu 14.04
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1091#issuecomment-78479390>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by SibuStephen** [comment]
npm - 2.7.0
node -v0.10.36
mongo -MongoDB shell version: 3.0.0

**Comment by liorkesos** [comment]
Can you try with mongo 2.6?
Lior

On Thu, Mar 12, 2015 at 3:38 PM, Sibu Stephen <notifications@github.com>
wrote:

> npm - 2.7.0
> node -v0.10.36
> mongo -MongoDB shell version: 3.0.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1091#issuecomment-78480485>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by SibuStephen** [comment]
will try doing that..

**Comment by SibuStephen** [comment]
Actually this is the error log which i got right now , and will it do good if i  use mongo 2.6 ?
####################
/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)

**Comment by liorkesos** [comment]
Please try.
I just looked at the failure on thw windows box and it was related to mongo
3 as well


On Thu, Mar 12, 2015 at 3:59 PM, Sibu Stephen <notifications@github.com>
wrote:

> Actually this is the error log which i got right now , and will it do good
> if i use mongo 2.6 ?
> ####################
>
> /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
> throw message;
>
> ^
> TypeError: Cannot read property 'length' of undefined
> at processResults
> (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
> at
> /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
> at
> /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
> at
> /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
> at Server.Base._callHandler
> (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
> at
> /home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
> at MongoReply.parseBody
> (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
> at null.
> (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
> at emit (events.js:95:17)
> at null.
> (/home/spare2/n/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1091#issuecomment-78484084>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by SibuStephen** [comment]
Hey i installed Mongo 2.6 too , but i guess it's not able to connect it's saying that "Failed to connect to 127.0.0.1:27017, reason: errno:111 Connection refused"
,in addition  the mongo DB is not working in it's 2.6 version.

**Comment by liorkesos** [comment]
The node error is because its looking for a db connection.
Try to get 2.x working and see if the error persists
Lior

**Comment by zhanghan177** [comment]
After downgrading MondoDB from 3.0 to 2.6.8, problem solved.

**Comment by SibuStephen** [comment]
Yes did it ,  thank's alot fr ur help.

**Comment by liorkesos** [comment]
Maybe it is a mongoose version?
Can you upgrade back  to 3 and change mongoose latest in package.json?
Lior

**Comment by zhanghan177** [comment]
Previously in package.json, it is `mongoose: 3.8.21`

And after test, `MongoDB 3.0.0` + `mongoose: 3.8.24` works fine.
