### ISSUE TITLE
Mean.IO does not work on Redhat 6.5 VM

### ISSUE THREAD

**Issue by johnking** [linnovate/mean#1095]
Hi, 

I am developing an application based on MEAN.IO, it works fine on my local Windows 7 machine, so I want to publish the app.

I have a remote Redhat 6.5 virtual machine (VM) server which can be used to host my application for public access. After uploading and run the app with grunt, it stops with an error: 

______________________________________________
$ grunt

Running "hook" task
>> Starting hooked tasks.

Running "clean:0" (clean) task
>> 0 paths cleaned.

Running "jshint:all" (jshint) task
>> 42 files lint free.

Running "csslint:src" (csslint) task
>> 5 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Waiting...

Running "nodemon:dev" (nodemon) task

[nodemon] v1.2.1

[nodemon] to restart at any time, enter `rs`

[nodemon] watching: *.*

[nodemon] starting `node --debug server.js`

debugger listening on port 5858

events.js:72

        throw er; // Unhandled 'error' event

              ^

Error: getaddrinfo ENOTFOUND

    at errnoException (dns.js:37:11)

    at Object.onanswer [as oncomplete] (dns.js:124:16)

[nodemon] app crashed - waiting for file changes before starting...
______________________________________________________________________
______________________________________________________________________

I also tried to clone the code into the server directly from https://github.com/linnovate/mean.git, without ANY changes and run the app, but I got the same error as above.

I tried run node server.js instead of grunt, I got similar errors as below: 

_________________________________________________________________________
_________________________________________________________________________

[jking@server eclipse_test]$ node server.js

for real!

forking  0

forking  1

forking  2

forking  3

events.js:72

        throw er; // Unhandled 'error' event

              ^
Error: getaddrinfo ENOTFOUND

    at errnoException (dns.js:37:11)

    at Object.onanswer [as oncomplete] (dns.js:124:16)

Worker 3 died :(

events.js:72

        throw er; // Unhandled 'error' event

              ^

Error: getaddrinfo ENOTFOUND

    at errnoException (dns.js:37:11)

    at Object.onanswer [as oncomplete] (dns.js:124:16)

Worker 2 died :(

__________________________________________________________
----------------------------------------------------------

**I don't know if it is due to the virtual machine or the mean.io stack.**

Can someone give me any clue or answer to resolve it? 

thanks

-John

**Comment by liorkesos** [comment]
The DNS.js an IP related errors might be related to how localhost is
configured.
1. Ping localhost and see its OK
2. Make sure mongo is listening and bound to the localhost interface.
3. Attache the output of
Netstat -ntlp (as root)
Lior

**Comment by johnking** [comment]
Hi Lior, 

Thanks for replying.

I have done the steps as you asked, please take a look. 

-  1. Ping  Ok
```
[jking@server eclipse_test]$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.056 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.054 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.043 ms
```
- 2. mongo setting is O.K

```
# mongod.conf

#where to log
logpath=/var/log/mongodb/mongod.log

logappend=true

# fork and run in background
fork=true

#port=27017

dbpath=/var/lib/mongo

# location of pidfile
pidfilepath=/var/run/mongodb/mongod.pid

# Listen to local interface only. Comment out to listen on all interfaces.
bind_ip=127.0.0.1

```

- 3. Netstat -ntlp
```
[root@server ~]# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN      1512/rpcbind
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      1787/sshd
tcp        0      0 127.0.0.1:631               0.0.0.0:*                   LISTEN      1672/cupsd
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      1863/master
tcp        0      0 0.0.0.0:60611               0.0.0.0:*                   LISTEN      1530/rpc.statd
tcp        0      0 127.0.0.1:27017             0.0.0.0:*                   LISTEN      1906/mongod
tcp        0      0 :::111                      :::*                        LISTEN      1512/rpcbind
tcp        0      0 :::22                       :::*                        LISTEN      1787/sshd
tcp        0      0 ::1:631                     :::*                        LISTEN      1672/cupsd
tcp        0      0 ::1:25                      :::*                        LISTEN      1863/master
tcp        0      0 :::49672                    :::*                        LISTEN      1530/rpc.statd
```
- By the way, I can set up a simple nodejs web server on this VM.

**Comment by lirantal** [comment]
@johnking please show the output of your /etc/resolv.conf

**Comment by johnking** [comment]
Hi Liran,

the content of /etc/resolv.conf is:

--------------------------------------
# Generated by NetworkManager

nameserver 65.97.224.190
nameserver 172.30.5.112

---------------------------------------

thanks

-John

On Tue, Mar 17, 2015 at 4:57 AM, Liran Tal <notifications@github.com> wrote:

> @johnking <https://github.com/johnking> please show the output of your
> /etc/resolv.conf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1095#issuecomment-82211800>.
>



-- 
-John

**Comment by johnking** [comment]
@lirantal 

the content of /etc/host.conf is: 

```
multi on

```
___________
the content of /etc/hosts.allow is: 

```
#
# hosts.allow   This file contains access rules which are used to
#               allow or deny connections to network services that
#               either use the tcp_wrappers library or that have been
#               started through a tcp_wrappers-enabled xinetd.
#
#               See 'man 5 hosts_options' and 'man 5 hosts_access'
#               for information on rule syntax.
#               See 'man tcpd' for information on tcp_wrappers
#
~
~
```
____________________
the content of /etc/hosts.deny is: 

```
#
# hosts.deny    This file contains access rules which are used to
#               deny connections to network services that either use
#               the tcp_wrappers library or that have been
#               started through a tcp_wrappers-enabled xinetd.
#
#               The rules in this file can also be set up in
#               /etc/hosts.allow with a 'deny' option instead.
#
#               See 'man 5 hosts_options' and 'man 5 hosts_access'
#               for information on rule syntax.
#               See 'man tcpd' for information on tcp_wrappers
#
~
~

```

thanks for your help.

-John

**Comment by johnking** [comment]
@lirantal 

the content of etc/hosts is: 

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

thanks for your help. 

-John

**Comment by lirantal** [comment]
@johnking can you show us your relevant config file with regards to the hosts/ips set in it? maybe its configured badly?

**Comment by johnking** [comment]
@lirantal 

Hi Liran, 

What did you mean by 'config file with regards to the hosts/ips set in it?', did you mean the configuration files of Mean.IO? or other Redhat VM configurations? 

- If you were asking for Mean.IO, __I did not modify any mean.io files__. After cloning the project, I just  run `grunt` or `node server.js` commands and found the issues. 

- If you were asking for other VM configurations, may you please give me a list of configurations you would like to have a look? . 

Again, thanks for your help. _I am stuck with the issue now._ 

Best

-John

**Comment by lirantal** [comment]
yeah I was referring to MEAN.io configuration files, but may seem irrelevant if you didn't change any of them.

**Comment by lirantal** [comment]
Can you try changing some VM network configurations? meaning if you have it now running on NAT, then change it to HOST, or BRIDGE modes.
If none of those options work, try to set google's nameservers for /etc/resolv.conf and try then.

**Comment by johnking** [comment]
@lirantal 

I just changed /etc/resolv.conf by using google's name servers.

```
[root@server etc]# more resolv.conf
# Generated by NetworkManager

# nameserver 65.97.224.190
# nameserver 172.30.5.112
nameserver 8.8.8.8
nameserver 8.8.4.4
```

Unfortunately, I got the same issue.

Best

-John

**Comment by johnking** [comment]
@liorkesos and @lirantal 

By playing the different name servers as showed in my previous comments (above), I noticed one  difference between different name servers.

For default name server, the exception happened just after message `debugger listening on port 5858`:
__________________
```
[nodemon] starting `node --debug server.js`
debugger listening on port 5858

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
[nodemon] app crashed - waiting for file changes before starting...

```
________________
but for google name server, the exception happened after message `Mean app started on port 3000 (development) cluster.worker.id: 0`:

```
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
Mean app started on port 3000 (development) cluster.worker.id: 0

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
[nodemon] app crashed - waiting for file changes before starting...

```

Does it provide you any clues?

thanks

-John

**Comment by lirantal** [comment]
@johnking try the following: https://help.ubuntu.com/12.04/serverguide/network-configuration.html

**Comment by VikramTiwari** [comment]
@johnking Is this still an issue for you? If yes, please reopen.

**Comment by johnking** [comment]
I am using meteor instead now 

Thanks anyway. 

-John

**Comment by abhilashsajeev** [comment]
So is there any solution available for this?
