### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before - Windows 8.1

### ISSUE THREAD

**Issue by Kernzy** [linnovate/mean#1097]
trying to install on windows 8.1
Ive got as far as starting Mongo then running Grunt from the app folder but get the following error..

"[nodemon] app crashed - waiting for file changes before"

![image](https://cloud.githubusercontent.com/assets/11395797/6652873/4dd3bb42-ca76-11e4-9464-bf24a95342ad.png)

**Comment by liorkesos** [comment]
Please install the latest version of mean.
The error you see is related to a muanatxh between the latest mongo-3.x and
an older version of mongoose.
Run mean init again please.
Lior

**Comment by Kernzy** [comment]
Thanks Lior, thats working now
