### ISSUE TITLE
angular-bootstrap 0.11.0 typeahead issue, upgrade to 0.12.1

### ISSUE THREAD

**Issue by elvisvoer** [linnovate/mean#1100]
I found that "angular-bootstrap": "0.11.0" has some issues with typeahead directive. If anyone experience the same issues just upgrade to 0.12.1. 

Elvis

**Comment by liorkesos** [comment]
I'll set the default to 0.12.1
Thanks for the update
Lior

**Comment by VikramTiwari** [comment]
Fixed.
