### ISSUE TITLE
[Feature] remote after installation should be none

### ISSUE THREAD

**Issue by VikramTiwari** [linnovate/mean#1102]
When i install a new app using `mean init` the project folder is created. This project folder has remote already attached to it. 

```
git remote -v

origin	https://github.com/linnovate/mean.git (fetch)
origin	https://github.com/linnovate/mean.git (push)
```

Rather than doing this, i guess having no remote would be better.

**Comment by liorkesos** [comment]
Typically an additional remote was associated with it called upstream.
The idea is to use the remote to get updates from the server.
Lior

**Comment by VikramTiwari** [comment]
Not an issue. `upstream` is there to provide updates from core package.
