### ISSUE TITLE
Link directly to mean repository in the packages section instead of the obsolete github accounts

### ISSUE THREAD

**Issue by hydrotik** [linnovate/mean#1106]
Currently if you go to:
http://mean.io/#!/packages/538180d8a331eb26d1e97d39
And then want to go to the repo you click on the
![git-banner](https://cloud.githubusercontent.com/assets/157727/6677595/db0d2402-cc07-11e4-9b88-c66a6851dea8.jpg)
it takes you to the git repo which then has a message for https://github.com/linnovate/mean-admin which then tells you to go to https://git.mean.io/linnovate/mean-admin

**Comment by liorkesos** [comment]
Thanks. this whole area will change soon.
Till then I'll review and change.
Lior

**Comment by hydrotik** [comment]
great thanks. I'm sure there are more important things to address, but it's happened to me more than once:)

**Comment by liorkesos** [comment]
Done.
