### ISSUE TITLE
How to upgrade from a very old version to latest mean io

### ISSUE THREAD

**Issue by anoopsinghbayes** [linnovate/mean#1111]
Hi ,
I have been working on a project for a while now but i found out the we are still working on a very old version of mea io i.e version 0.1.2 any suggestion/steps to upgrade to the latest version .

**Comment by liorkesos** [comment]
There is no upgrade path from mean-0.1.x to 0.4.
There where major changes in mean's infrastructure, code and even
philosophy mainly during the end of 0.2.x and 0.3.x
My suggestion is (time permissing).
Start with a fresh copy of 0.4.4 and start moving the existing code in to
packages based on the application functionality.
It might take you a few days to get the idea and complete the refactor but
I have no "magic solutions"
If you do choose to the upgrade I think it would be a fascinating blog post
to read and I'd be glad to cross post it in blog.mean.io
Lior

On Thu, Mar 19, 2015 at 8:33 AM, Anoopsingh Bayes <notifications@github.com>
wrote:

> Hi ,
> I have been working on a project for a while now but i found out the we
> are still working on a very old version of mea io i.e version 0.1.2 any
> suggestion/steps to upgrade to the latest version .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1111>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by anoopsinghbayes** [comment]
hey thanks @liorkesos ,
just a small question here do I have create separate mean packages for every functionality for e.g orders,invoices etc .

**Comment by liorkesos** [comment]
Well it makes sense, especially if you keep the packages generic and may
consider contributing them back (nudge nudge, wink wink).
To much packegination could be uncomfortable so you could also have a
"billing" package containign both models/controllers/services/views etc..
It's more a matter of style and comfort then a solid best principle
Lior

On Thu, Mar 19, 2015 at 9:08 AM, Anoopsingh Bayes <notifications@github.com>
wrote:

> hey thanks @liorkesos <https://github.com/liorkesos> ,
> just a small question here do I have create separate mean packages for
> every functionality for e.g orders,invoices etc .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1111#issuecomment-83374809>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos
