### ISSUE TITLE
Gulp not watching

### ISSUE THREAD

**Issue by shiftie** [linnovate/mean#1112]
Hi!
Just got the latest version, gulp doesn't seem to watch .less changes when I run:
gulp

Also seems that the "watch" task isn't called at all.

edit.:
after checking the changes to gulp files I've seen some odd things:

**in gulpfile.js:**
gulp.paths is defined but it's values doesn't seem relevent in other scripts, I think it should be assigned with the paths found in /gulp/server.js:
```javascript
gulp.paths = {
    js: ['*.js', 'test/**/*.js', '!test/coverage/**', '!bower_components/**', 'packages/**/*.js', '!packages/**/node_modules/**', '!packages/contrib/**/*.js', '!packages/contrib/**/node_modules/**'],
    html: ['packages/**/public/**/views/**', 'packages/**/server/views/**'],
    css: ['!bower_components/**', 'packages/**/public/**/css/*.css', '!packages/contrib/**/public/**/css/*.css'],
    less: ['**/public/**/css/*.less']
  };
```

**in /gulp/devel.js:**
```javascript
var through = require('through');
var gutil = require('gulp-util');
```
are missing.

defaultTasks should be ['env:develop', 'jshint', 'csslint','watch'] & used in "develop" task (clean is already ran from gulpfile.js):
```javascript
var defaultTasks = ['env:develop', 'jshint', 'csslint','watch'];
```
"less" task is also missing:
```javascript
gulp.task('less', function() {
  return gulp.src(paths.less)
    .pipe(plugins.less())
    .pipe(gulp.dest(function (vinylFile) {
      return vinylFile.cwd;
    }));
});
```
Maybe I missed something, especially about the paths from gulpfile.js.
Thx in advance..

**Comment by liorkesos** [comment]
Hi I just pushed something that might fix it - please see if it helps...

**Comment by shiftie** [comment]
works, thx!
