### ISSUE TITLE
Where can I find documentation for the Access package?

### ISSUE THREAD

**Issue by dandv** [linnovate/mean#1114]
New to MEAN, please forgive the noob question. I'm trying to learn more about the capabilities of the [Access package](http://learn.mean.io/#mean-stack-packages-core-packages) to control authentication. The documentation seems to have only one line about this package and no links to more information. Same problem with the Users package.

In [this repo's packages directory](https://github.com/linnovate/mean/tree/master/packages) I see a `users` directory, but not an `access` one. Is the Access package not implemented yet?

**Comment by liorkesos** [comment]
access and users where merged to one package.
Most of the access related stuff is based on passport - refer to their docs (depnding whivh passport strategy you want to configure) for more docs.
Lior
