### ISSUE TITLE
would you guys work with docker in the future? 

### ISSUE THREAD

**Issue by ssmlee04** [linnovate/mean#1115]
as title.  I see mean.js is working in this direction and wondering if you guys would do the same thing?  Thanks.

**Comment by enkodellc** [comment]
My code buddy showed me Vagrant running a docker container yesterday. I am still learning but it seems pretty awesome.

**Comment by liorkesos** [comment]
We have a dockerfile for mean .we can add it to the repo.
Lior

**Comment by VikramTiwari** [comment]
:+1:  for docker!

**Comment by liorkesos** [comment]
Will ask @brownman or @shai-weinstein to add the most recent Dockerfile to the repo
