### ISSUE TITLE
"mean init" and "fatal: Unable to find remote helper for 'httpsl'"

### ISSUE THREAD

**Issue by sergeifedorenko** [linnovate/mean#1126]
Run command:
-----------

mean init example_project

? What would you name your mean app? example_project
Cloning branch: master into destination folder: example_project
git clone  --depth 1  -bmaster httpsl://github.com/linnovate/mean.git "example_project"
Cloning into 'example_project'...
fatal: Unable to find remote helper for 'httpsl'

/usr/local/lib/node_modules/mean-cli/lib/install.js:80
      throw output;
            ^
Cloning into 'example_project'...
fatal: Unable to find remote helper for 'httpsl'
-----------
my configuration:
mac - 10.10
node - v0.12.0
git - 1.9.5 (Apple Git-50.3)
npm - 2.5.1

**Comment by liorkesos** [comment]
Hi Sergei,
Thanks for reporting this .
This is due to a bug i introduced about 2 hrs ago.
I fixed and pushed it in version 0.9.26
Please reinstall and verify it works now.
thanks
Lior

On Sun, Mar 29, 2015 at 2:10 PM, Sergei Fedorenko <notifications@github.com>
wrote:

> Run command:
>
> mean init example_project
>
> ? What would you name your mean app? example_project
> Cloning branch: master into destination folder: example_project
> git clone --depth 1 -bmaster httpsl://github.com/linnovate/mean.git
> "example_project"
> Cloning into 'example_project'...
> fatal: Unable to find remote helper for 'httpsl'
>
> /usr/local/lib/node_modules/mean-cli/lib/install.js:80
> throw output;
> ^
> Cloning into 'example_project'...
> fatal: Unable to find remote helper for 'httpsl'
>
> my configuration:
> mac - 10.10
> node - v0.12.0
> git - 1.9.5 (Apple Git-50.3)
> npm - 2.5.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1126>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by sergeifedorenko** [comment]
!!!! Yes !!!!
Thank you for instance support ))!

**Comment by liorkesos** [comment]
My pleasure.
Have fun with mean!

**Comment by sergeifedorenko** [comment]
mean init wordshome.com
? What would you name your mean app? wordshome.com
Cloning branch: master into destination folder: wordshome.com
git clone  --depth 1  -bmaster https://github.com/linnovate/mean.git "wordshome.com"
Cloning into 'wordshome.com'...
/Users/sf/.npm/_locks
There are 2 files in your ~/.npm owned by root
Please change the permissions by running - chown -R `whoami` ~/.npm 

/usr/local/lib/node_modules/mean-cli/lib/utils.js:67
      throw('ROOT PERMISSIONS IN NPM');
      ^
ROOT PERMISSIONS IN NPM

**Comment by sergeifedorenko** [comment]
I was trying to run command 
- chown -R `whoami` ~/.npm 
but problem all the same exist ((

**Comment by liorkesos** [comment]
It's chown -R `whoami` ~/.npm


On Sun, Mar 29, 2015 at 2:42 PM, Sergei Fedorenko <notifications@github.com>
wrote:

> I was trying to run command
>
>    - chown -R whoami ~/.npm but problem all the same exist ((
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1126#issuecomment-87400226>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by sergeifedorenko** [comment]
All working excellent !!! My big thank for you!! ))
Folder /Users/sf/.npm/_locks I can remove only direct from finder
