### ISSUE TITLE
high cpu usage with gulp

### ISSUE THREAD

**Issue by emps** [linnovate/mean#1128]
![cpu](https://cloud.githubusercontent.com/assets/2281169/6888250/ac035ae0-d680-11e4-9e33-10487178809c.jpg)

just by runing gulp

os: win7 64
node 0.12.1
node 0.10.33 (laptop)
node-debug gives cpu 99% on function (program)

**Comment by bluepuma77** [comment]
I receive a gulp message when starting, do you get the same?
```
[gulp] [nodemon] watching 26,417 files - this might cause high cpu usage. To reduce use "--watch".
```

**Comment by emps** [comment]
still jumping cpu a bit less but still 10 - 50%

**Comment by VikramTiwari** [comment]
This is cause gulp is processing the files at that time. This has been significantly reduced in the newer versions by not tracking a lot of files.

If you think that this is still an issue, please reopen.
