### ISSUE TITLE
Making MEANIO PhoneGap-friendly

### ISSUE THREAD

**Issue by claustres** [linnovate/mean#1130]
I started integrating a MEANIO app into a PhoneGap Android app (http://docs.phonegap.com/en/4.0.0/). I would like to share my return on experience because making MEANIO more PhoneGap friendly will be probably a good way to increase its popularity. Here is my feedback:
* Conforming to the PhoneGap file structure is just a matter of copying all files in the public folder of each MEAN package into a folder named 'package' under the root 'www' PhoneGap folder > I did it manually first for testing purpose, then using gulp to create an automated task
* As the front and the back-end are not located on the same host you need to prefix all the requests to the back-end services with the base URL of your server, I did that easily using a $httpProvider interceptor for the Angular part, however I had to modify the MEANIO source code for the initial call to _getModules which uses jQuery.

My **system\services\interceptor.js** to get the idea
```javascript
...
function($q, $location) {
      var baseUrl = 'http://ec2-52-16-10-154.eu-west-1.compute.amazonaws.com:3000'
      return {
            // optional method
        'request': function(config) {
            console.log('Requested URL : ' + config.url);
            // Add base URL for server requests (not view resources)
            var isView = ( config.url.indexOf('.html') > 0 );
            var isAsset = ( ( config.url.indexOf('.png') > 0 ) || ( config.url.indexOf('.jpg') > 0 ) || ( config.url.indexOf('.svg') > 0 ) ||
                            ( config.url.indexOf('.woff') > 0 ) || ( config.url.indexOf('.ttf') > 0 ) );
            var startsWithSlash = (config.url.indexOf('/') === 0);

            if ( !isView && !isAsset ) {
              config.url = baseUrl + (startsWithSlash ? '' : '/') + config.url;
            } else {
              // Internal URL are given relative to localhost like this : '/system/views/html'.
              // With phone gap this does not work properly because it gets transformed into file://URL,
              // so we need to remove the starting '/'
              if ( startsWithSlash ) {
                config.url = config.url.slice(1, config.url.length);
              }
            }
            console.log('Final URL : ' + config.url);
            return config;
          },
...
```
I would suggest to add a configuration constant in the 'mean-factory-interceptor' in order to make the base URL configurable. Don't know how to manage this right as well in **bower_components/web-bootstrap/index.js**
```javascript
...
jQuery.ajax(baseUrl + '/_getModules', {
  dataType: 'json',
  async:false,
  success: processModules
});
...
```

* We need a static index.html (i.e. not templated with swig). First I simply merged the original index.html/default.html/head.html/foot.html files into a single one. The tricky point here has been to create a gulp task doing a similar job than the aggregation task of MEANIO on the server side. For this I used two gulp plugins : https://www.npmjs.com/package/gulp-inject for package' internal js/css files automated injection and https://www.npmjs.com/package/gulp-replace for exernal js/css files manual injection based on the content of *assets.json*.

In the original **system/server/views/index.html** there is also a code used to restore the user from the current session (if any) to the window object (the user is catched back in **system/public/services/global.js**) :
```javascript
...
  <section data-ui-view ></section>
  <script type="text/javascript">
    window.user = {{user|json|safe}};
    window.modules = null;
  </script>
...
```
Without server-side templating we need to retrieve the user via an ajax request, similarly to (and just before retrieving) the available modules in **bower_components/web-bootstrap/index.js** :
```javascript
...
function getUser(user) {
  if ( user ) {
    window.user = user;
  }
  window.modules = null;
}

jQuery.ajax(baseUrl + '/users/me', {
  dataType: 'json',
  async:false,
  success: getUser
});
...
```

With all of this *I can build an almost complete Android app based on MEANIO*. However, some small problems remain :
* the interceptor does not work for images or so referenced directly in html/css, I will need to create a lower-level interceptor, probably using jQuery (https://api.jquery.com/category/ajax/global-ajax-event-handlers/), to catch all asset requests (any example is welcome !)
* some routes do not seem to work fine such as /logout, I have to investegate...

Don't know how I can make this (still) work (in progress) more available to the community but any suggestion is welcome. For now I store all the required modified files in a **phonegap** folder at the root level and all the gulp tasks in gulp/utils.js (a dedicated file would be better IMHO).

![screenshot_2015-04-03-19-10-58](https://cloud.githubusercontent.com/assets/2647117/7011723/d35b13c2-dcab-11e4-9c40-66a2d8fd9d0f.png)

**Comment by liorkesos** [comment]
Sounds cool,
We use mean.io with ionic as a wrapper to phonegap/cordova.
I'd love to brainstorm on how to make the integration "tighter"
Feel free to jump by in to gitter.im/linnovate/mean to chat...

**Comment by claustres** [comment]
OK thanks, I will as soon as possible, so you already succeded in getting MEANIO running under PhoneGap ?

**Comment by claustres** [comment]
I updated my first post because thanks to a colleague I realized I misunderstood the fact that the MEANIO index.html includes client-side AngularJS templating **as well as** server-side SWIG templating...

**Comment by VikramTiwari** [comment]
Things have changed a lot since then. Please reopen if you are still facing the issue.
