### ISSUE TITLE
Gulp dev server stops on bad syntax

### ISSUE THREAD

**Issue by jamesla** [linnovate/mean#1131]
How can I stop the gulp dev server from stopping when there is bad syntax - it's really slowing me down.

Workflow:
Write some code
run gulp
Test it in browser works ok.
Change some code
Test in browser and 404
check terminal and gulp has an unhanded syntax error and has stopped

Repeat.

I assume it's not supposed to work like this? Anyone know what I can do, is there an ignore syntax changes switch or something?

**Comment by liorkesos** [comment]
This is related to gulp running jshint (to support the development phase)
You can run mean also by running node server.js bypassing all of the Dev
related tasks.
Another option is to comment out the jahont task in gulp/development...

**Comment by jamesla** [comment]
ok thanks commenting out jshint did the trick :-)
