### ISSUE TITLE
What is the correct way to add js libraries to mean.io applications?

### ISSUE THREAD

**Issue by jamesla** [linnovate/mean#1132]
I am trying to add underscore to my mean.io application. I'm not sure where to link the js library to the page as it doesn't have a main html page like the Angular generator does.

I manually added it via the config/assets.json file and it works however the dev server keeps crashing saying _ is undefined (even though the web app uses the _ function ok and returns the data just before the dev server stops).

I asume I must be doing this wrong.

What is the correct way to add custom js libraries to a mean.io project?

**Comment by liorkesos** [comment]
Read about aggregation in learn.mean.io
