### ISSUE TITLE
Should I wrap all the front-end code inside IIFE?

### ISSUE THREAD

**Issue by lvarayut** [linnovate/mean#1134]
Normally, I wrap all the front-end code, `AngularJs`,  inside IIFE. I just started to use `meanio` for a while  and found that all code in `public` folder didn't be wrapped inside IIFE. So, my question is that should I manually wrap it myself or does `meanio` already have any mechanism to automatically do so?

**Comment by VikramTiwari** [comment]
@lvarayut A pull request will be very helpful for this.

**Comment by lvarayut** [comment]
@VikramTiwari Thanks for your response. Do you want me to wrap all the client code inside IIFE?

**Comment by VikramTiwari** [comment]
@lvarayut The reason there's been not much push on this is that we are awaiting for Angular 2.0 to be finalised and implement that in the MEAN stack. That will mean that we won't require to modify a lot of performance based tweaks that we should be doing in order to better the stack.

I would rather recommend you to identify the changes that we will need to do in order to be compatible for Angular 2.0 thus helping us in that process.

**Comment by rjVapes** [comment]
@lvarayut In regards to your 3 bullet points, you're right.  Moving forward this should happen, and as time is available we'll likely move towards this.  I think in the immediate future, the templates will be updated so 'mean package' will follow these guidelines, also others present as best practices by John Papa.

Moving through and applying this to the core code base will take a bit more doing, or someone being very helpful.  If this is something you're interested in, feel free to take a stab at it using https://github.com/johnpapa/angular-styleguide as reference.

There are certain things that would be breaking changes, so we'd rather not tread there immediately (things like changing the casing of core services that users may inject).

**Comment by lvarayut** [comment]
@VikramTiwari Shouldn't be in another branch? IMHO, even though, the Angular 2.0 released, we need to still support for Angular 1.x as well. For example, we could have options to choose either 1.x or 2.x when generating the "mean" project.

@rjVapes Alright. Thanks for your response. I will help improving this project in my spare time, might start with changing AnguarJs code based on the John Papa style guide.

**Comment by VikramTiwari** [comment]
@lvarayut Rejoice! This is present in latest versions.
