### ISSUE TITLE
Mocha tests not running

### ISSUE THREAD

**Issue by fflajom** [linnovate/mean#1135]
Hi, 

Running the app using gulp test, i noticed that the mocha tests are not being run. 

part of the output is :
10:12:54] Finished 'loadTestSchema' after 487 ms
[10:12:54] Starting 'mochaTest'...

  0 passing (0ms)

[10:12:54] Finished 'mochaTest' after 48 ms

**Comment by CjS77** [comment]
I've just figured out how to fix this:

http://stackoverflow.com/questions/29444270/mean-io-unit-tests-dont-run

Also, glad I'm not the only one who experienced this :)

**Comment by vmartis** [comment]
+1

**Comment by VikramTiwari** [comment]
Fixed.
