### ISSUE TITLE
how can i access development.js or config file content in controller

### ISSUE THREAD

**Issue by deepaksisodiya** [linnovate/mean#1137]
i want to do set config for my application. so want to access config in controller.

like this
http://www.ng-newsletter.com/advent2013/#!/day/5

**Comment by max-mog** [comment]
You can add this to your controller
``` config = require('meanio').loadConfig(); ```

Does this help?

**Comment by VikramTiwari** [comment]
Fixed. Ask questions in out gitter chatroom. (https://gitter.im/linnovate/mean)
