### ISSUE TITLE
mean init fails

### ISSUE THREAD

**Issue by velkymx** [linnovate/mean#1138]
I've checked that rx is installed, and that it is at the latest version. Nodejs is 0.12.2, mean show version 0.9.28 on OSX Yosemite

/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: undefined is not a function
    at Object.exports.checkNpmPermission (/usr/local/lib/node_modules/mean-cli/lib/utils.js:70:3)
    at Array.checkPermissions (/usr/local/lib/node_modules/mean-cli/lib/install.js:36:11)
    at handleItem (/usr/local/lib/node_modules/mean-cli/node_modules/async-series/index.js:14:13)
    at series (/usr/local/lib/node_modules/mean-cli/node_modules/async-series/index.js:30:3)
    at Object.exports.init (/usr/local/lib/node_modules/mean-cli/lib/install.js:14:3)
    at exports.init (/usr/local/lib/node_modules/mean-cli/lib/cli.js:836:11)
    at PromptUI.completed (/usr/local/lib/node_modules/mean-cli/lib/wizard.js:43:5)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1977:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)

**Comment by ruizhit** [comment]
same problem here
:pensive:

**Comment by aqvari** [comment]
I'm hitting this also and I've tried to open up permissions on ./npm as well as /usr/local/lib/node_modules
Is the init command going to output to the debug log for mean/npm? I'd gladly provide that if it's generated.

**Comment by dossantospat** [comment]
Same here

**Comment by muaaz-vf** [comment]
Same issue occur on the ubuntu 14.04 LTS as well. 

mean init yourNewApp    

? What would you name your mean app? yourNewApp

/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: undefined is not a function
    at Object.exports.checkNpmPermission (/usr/local/lib/node_modules/mean-cli/lib/utils.js:70:3)
    at Array.checkPermissions [as 0] (/usr/local/lib/node_modules/mean-cli/lib/install.js:36:11)
    at handleItem (/usr/local/lib/node_modules/mean-cli/node_modules/async-series/index.js:14:13)
    at series (/usr/local/lib/node_modules/mean-cli/node_modules/async-series/index.js:30:3)
    at Object.exports.init (/usr/local/lib/node_modules/mean-cli/lib/install.js:14:3)
    at exports.init (/usr/local/lib/node_modules/mean-cli/lib/cli.js:836:11)
    at PromptUI.completed (/usr/local/lib/node_modules/mean-cli/lib/wizard.js:43:5)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1977:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)

**Comment by aakos** [comment]
Same here

**Comment by Jmdavison** [comment]
same here ! ubuntu 14.04 LTS

**Comment by edisontkp** [comment]
i tried it in debian, ubuntu and mac osx and have the same problem...

**Comment by blyssy** [comment]
I just did a mean init testApp, cd testApp, npm install, bower install, gulp and all went fine. npm version 2.7.4, bower version 1.4.1, latest mean version, and I'm running RHEL6 and latest Mac OSx.  None of the commands required super user permissions and npm didn't complain about EACCESS stuff.  I would check your permissions.

**Comment by edisontkp** [comment]
blyssy can you share your installation step with me? thanks

**Comment by velkymx** [comment]
@edisontkp I installed the latest Node.js with the 64bit installer for mac. Then using the npm I installed the mean-cli. Then I went to the init. When it failed I used the npm to install rxjs and it still failed. On ubuntu 14.04 I had to make the node.js then followed the mean-cli route again. Same result.

**Comment by blyssy** [comment]
The first one helped me with installing on my Mac.
https://gist.github.com/isaacs/579814

As for my linux box, I install all binaries in /usr/local/bin.  That includes bower, npm, mongo and mean stuff.  Before I install in that directory I made sure to do a chown so that my regular user account can run binaries from that directory.

For the two guys who have posted their errors, I would say there is an issue with permissions on the /usr/local/lib directory.  If I do an ls -la /usr/local/, my bin, lib, and share directories are owned by my user account.

**Comment by velkymx** [comment]
@blyssy I show:

drwxr-xr-x   7 24561  wheel  238 Apr 12 11:05 node_modules

**Comment by blyssy** [comment]
the parent directory is what's important.  check /usr/local/

**Comment by velkymx** [comment]
@blyssy 

drwxrwxr-x  111 root     admin   3774 Apr 12 11:05 bin
drwxrwxr-x    5 root     admin    170 Apr 12 09:38 lib

**Comment by blyssy** [comment]
su to root and do a chown -R wheel bin and chown -R wheel lib

**Comment by blyssy** [comment]
and for the share directory

**Comment by velkymx** [comment]
@blyssy ok I chown'd those three directories to my user name, it still throws the same error (OSX Yosemite)

**Comment by velkymx** [comment]
at line 579 of rx.js is: 

  function thrower(e) {
    throw e;
  }

**Comment by blyssy** [comment]
I would suggest reinstalling npm.  If you had to sudo to install npm then that means npm is owned by root.  you could also go to the npm binary and chown that.  Either way would work.  Your user account has to be the owner of npm, bower, mean, and mongo

**Comment by blyssy** [comment]
I run both RHEL6 and Mac OSx.  installing npm, bower, mean, and mongo has to be done in such a way you do not need super user access at all.  The programs should be owned by your user account, the bin directory they reside in should be owned by your user account, and the directories they use/install in need to be owned by your user account.

**Comment by velkymx** [comment]
OK I got it to work. Here's what I did. 

#1 Removed Node.js entirely

go to /usr/local/lib and delete any node and node_modules
go to /usr/local/include and delete any node and node_modules directory
go to /usr/local/bin and delete any node executable

sudo rm /usr/local/bin/npm
sudo rm /usr/local/share/man/man1/node.1
sudo rm /usr/local/lib/dtrace/node.d
sudo rm -rf ~/.npm
sudo rm -rf ~/.node-gyp
sudo rm /opt/local/bin/node
sudo rm /opt/local/include/node
sudo rm -rf /opt/local/lib/node_modules

Then I reinstalled node.js from the installer on their web site.

#2 installed the CLI

sudo npm install -g mean-cli 

#3 change permissions on the ndm

chown -R `USERNAMEHERE` ~/.npm 

#4 setup to create my project in my docs directory cd ~/Documents/projects/

#5 init worked!

mean init yourNewApp

**Comment by blyssy** [comment]
awesome!  Thank you for the detailed steps of what you did.

**Comment by liorkesos** [comment]
Not sure it's related.
version 0.9.29 that was released 4 hrs ago by Orit fixed that problem.
https://github.com/linnovate/mean-cli/commit/b6352ab8151f0b162c8265ee131f80543e400a41
My bad - apologies...

**Comment by aqvari** [comment]
The error I was getting on Windows 7:
TestUser@TestMachine /c/users/TestUser/Sandbox
$ mean init TestApp1
? What would you name your mean app? TestApp1
On windows platform - Please check permissions independently
All permissions should be run with the local users permissions
Cloning branch: master into destination folder: TestApp1
git clone  --depth 1  -bmaster https://github.com/linnovate/mean.git "TestApp1"
find: C:\Users\TestUser/.npm: No such file or directory
There are 2 files in your ~/.npm owned by root
Please change the permissions by running - chown -R `whoami` ~/.npm

c:\Users\TestUser\AppData\Roaming\npm\node_modules\mean-cli\lib\utils.js:67
      throw('ROOT PERMISSIONS IN NPM');
      ^
ROOT PERMISSIONS IN NPM


I don't think it was related to the above issue, but it turns out the Mean.io documentation may need to be updated to specify that the Git tools should be run from a Windows command prompt (with Git tools available on PATH.) Once I reinstalled Git for Windows and node.js I was able to get it to work.

**Comment by liorkesos** [comment]
Thanks for the comment,
We'll change the docs (which are actually the README file).
If you can submit a pullrequest with window specific tips that would be
awesome
Lior

On Mon, Apr 13, 2015 at 9:54 PM, aqvari <notifications@github.com> wrote:

> The error I was getting on Windows 7:
> TestUser@TestMachine /c/users/TestUser/Sandbox
> $ mean init TestApp1
> ? What would you name your mean app? TestApp1
> On windows platform - Please check permissions independently
> All permissions should be run with the local users permissions
> Cloning branch: master into destination folder: TestApp1
> git clone --depth 1 -bmaster https://github.com/linnovate/mean.git
> "TestApp1"
> find: C:\Users\TestUser/.npm: No such file or directory
> There are 2 files in your ~/.npm owned by root
> Please change the permissions by running - chown -R whoami ~/.npm
>
> c:\Users\TestUser\AppData\Roaming\npm\node_modules\mean-cli\lib\utils.js:67
> throw('ROOT PERMISSIONS IN NPM');
> ^
> ROOT PERMISSIONS IN NPM
>
> I don't think it was related to the above issue, but it turns out the
> Mean.io documentation may need to be updated to specify that the Git tools
> should be run from a Windows command prompt (with Git tools available on
> PATH.) Once I reinstalled Git for Windows and node.js I was able to get it
> to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1138#issuecomment-92459434>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by dartinez** [comment]
https://github.com/linnovate/mean/pull/1140

**Comment by torresrodrigoe** [comment]
is an old thread but I just found myself on the same issue and this is what I did to move on:

create a development user 

adduser devuser                    /* go through adding user steps and then get in
su devuser
mkdir ~/.npm                          /* this folder would be missing on your dev user
mean init myApp

**Comment by liorkesos** [comment]
Why are you manually making .npm? You just need to be sure that the home is
writeable because then it creates the .npm direc tty ory independentlt.
You mentioned all kinds of commands in "adduser".
The question is if you did a
Chown devusee.devusee /home/devuser

Lior

**Comment by noahfreedman** [comment]
I found that the error is that the app is looking for my global .npm folder in ~/.npm, while on my OS X installation it is located in /usr/local/lib/.npm. I made sure that I had correct user and group permissions on this directory, and then created a symlink, which solved the problem:
ln -s /usr/local/lib/.npm ~/.npm

To find where your global .npm file is, do a root search:
sudo find / -name ".npm"
