### ISSUE TITLE
update mongoose version to 4.0.1

### ISSUE THREAD

**Issue by andrewandrew** [linnovate/mean#1141]
package.json contains pretty old version of mongoose 3.8.4, while mongoose has already stable 4.0.1 according to https://gitter.im/Automattic/mongoose
4.0.1 some nice features, so it would be great to update to the latest one.
Tried upgrading to 4.0.1 in a clean mean stack install, but this brings errors: "possible EventEmitter memory leak detected. 11 reconnect listeners added."
What could be the reason? Is it mean and mongoose incompatibility or a mongoose 4.0.1 bug?

**Comment by deepakbhattarai** [comment]
same here

**Comment by VikramTiwari** [comment]
Fixed. Using latest now.
