### ISSUE TITLE
Node 0.12.2 MongoDB 3.0.1 node-gyp 1.0.3 failed installation of mean.io

### ISSUE THREAD

**Issue by jamesvanleuven** [linnovate/mean#1143]
so....
clearly mean.io isn't up to date with the lastest builds of all the prerequisites...

- OS: Windows 7 SP1 x64
- Microsoft Visual Studio 2010 Express (0.10)
- Microsoft Visual Studio Express 2012 (0.11)
- Microsoft Visual Studio for Desktop 2012 (0.11)
- Microsoft Visual Studio 2013 (0.12)

- Python 2.7.9 [MSC v.1500 64 bit (AMD64)] on win32

- MongoDB shell version: 3.0.1
- node-gyp@1.0.3
- node@0.12.2 | win32 | x64

- AngularJS v1.3.15
- Express v4.12.3

Beyond the error of "was expecting node 0.08" on every line of the install

    e:>www> npm install -g mean-cli

was nothing but a scrolling screen of red compile errors

What is the timeline on mean.io being ready for the new functionality of my build specs listed above?

I haven't installed socket.io yet, but I'm sure it'll be without issues... 

I am not going to downgrade my entire environment just to test this framework. so I need a timeline guestimation when this will be up to date... 

:)

**Comment by liorkesos** [comment]
The timeline should be immidiate.
We did some "defensive versioning" when cutting edge stuff kept breaking on production.
since that we understand we should utilize npm shrinkwrap instead of hardcoding versions (untill this type of breakage happens).
If you can help inthe process - you can notch all dependencies to latest and test.
I will do so today and merge your PR (or get to it independently) if it works for either of us.

**Comment by jamesvanleuven** [comment]
Yes Please. Totally include me. That's kind of sexy.  Just an FYI. Getting gyp-node to work took me about 3 days. There are interesting glitches with the MSVS versions and their new installs. They seem to be gutting their previous versions ripping out the tools, forcing people to use 2012 or higher for any builds or compiling, or of course, buy the full versions. Cuz clearly we're all going to just run out and do that (as if).  I also had to modify the binding.gyp file to the following as a default 'add to' any node.js flavour of build I want to test.  Here it is if you're interested:

    {
        "targets": [
            {
            "target_name": "binding",
            "sources": [ "build/binding.vcxproj" ]
            }
        ]
    }

obviously all the prerequisites need be installed from the node-gyp repository readme

**Comment by VikramTiwari** [comment]
@jamesvanleuven Is this still an issue for you? If so, please reopen.
