### ISSUE TITLE
Aggregation parameter ignored!

### ISSUE THREAD

**Issue by shiftie** [linnovate/mean#1144]
Hey,

I ran into some troubles in production mode with my assets. I have angular dependencies that I inject with:
```javascript
RatesAdmin.aggregateAsset('js', '../lib/angular-ui-ace/ui-ace.js', {aggregate: false});
```
But since the angular module loads more js scripts i had "not found" errors in production environment like: 
*Cannot find http://localhost:300/additionnal-script-loaded-by-the-angular-module.js*

When I checked the scripts, my angular module is aggregated in aggregated.js although I asked it not to be aggregated.

It seems that aggregation.js forces this option to be the one defined in the environment config:
```javascript
Meanio.prototype.Module.prototype.aggregateAsset = function(type, asset, options) {
    options = options || {};
    options.aggregate = Meanio.Singleton.config.clean.aggregate;
    options.debug = Meanio.Singleton.config.clean.debug;
```
Which means that we can't  override the global configuration value, so basicly we have a choice bewteen 0 aggregation( dev mode ) OR 100% aggregation (which causes troubles).

**Comment by liorkesos** [comment]
aggregate:false is not a paramter for the aggrgateAsset per aggregation but instead it's a generic paramter referenced in the env configuration files like here ...
https://github.com/linnovate/mean/blob/master/config/env/development.js#L10
