### ISSUE TITLE
Small documentation rendering problem

### ISSUE THREAD

**Issue by dartinez** [linnovate/mean#1146]
Seems there is a small rendering problem in Chrome 42 on Windows 7 with this markup. Oddly enough it cannot be reproduced when I fork and try to edit.

![image](https://cloud.githubusercontent.com/assets/8079732/7211178/0c20f508-e51e-11e4-8518-ea3ed09e212c.png)

![image](https://cloud.githubusercontent.com/assets/8079732/7211180/1299194c-e51e-11e4-9e80-7384c8cf9531.png)

Someone with better HTML troubleshooting skills should probably investigate :)

**Comment by VikramTiwari** [comment]
@dartinez Where is the issue? Can you pin point it?
