### ISSUE TITLE
Could you provide a way to access mongoStore instance?

### ISSUE THREAD

**Issue by dttungsyn** [linnovate/mean#1147]
I use socket io and got the **sessionID** from cookie when a connection arrive. I would like to get the **session data** corresponding  to the **sessionID** via **mongoStore** ( the instance was used by MEAN to config session ).
All I need now is to access the right **mongoStore** instance.
How could I easily do that ?
I use MEAN 0.7.1

**Comment by dttungsyn** [comment]
By the way, I tried to export the mongoStore instance by adding app.set('mongoStore ', mongoStore ) in ExpressEngine class. But the *sessionID* get from cookie didn't work with mongoStore.get(sessionID, function(){...}) because this *sessionID* is differrent from the session id in db sessions collection.

Some body please help !??

**Comment by VikramTiwari** [comment]
Have you resolved this issue. If so, please comment here so that it could be useful for others as well. Thanks!
