### ISSUE TITLE
nodemon ignore wrong path usage

### ISSUE THREAD

**Issue by Hendrik** [linnovate/mean#1148]
The ignore option in in gulp/development.js isn't working for me on latest OSX & Ubuntu releases.

The original version is:
```javascript
gulp.task('devServe', ['env:development'], function () {
  plugins.nodemon({
    script: 'server.js',
    ext: 'html js',
    env: { 'NODE_ENV': 'development' } ,
    ignore: ['./node_modules/**'],
    nodeArgs: ['--debug']
  });
});
```

but I had to change the ignore path to the following for it to stop parsing the node_modules files.

```javascript
gulp.task('devServe', ['env:development'], function () {
  plugins.nodemon({
    script: 'server.js',
    ext: 'html js',
    env: { 'NODE_ENV': 'development' } ,
    ignore: ['node_modules/'],
    nodeArgs: ['--debug']
  });
});
```

Before changing it, gulp would start watching 27.000+ files:
```
[gulp] [nodemon] watching 27,363 files - this might cause high cpu usage. To reduce use "--watch".
```

That message disappeared after adjusting the folder name in the ignore option.

There are reported issues with folder names in nodemon's ignore option, where some users had to remove the ./ for it to work and others had to add it. It may be OS and/or nodemon version dependent, but for the current mean.io 0.4.4 release I had to make above changes for nodemon to stop watching the node_modules directory under OSX and Ubuntu.

**Comment by liorkesos** [comment]
This looks awesome,
Couldn't figure out why we where watching so much files with the ignore on.
If it helps me up I'll merge it in!

**Comment by liorkesos** [comment]
works! Commiting
