### ISSUE TITLE
SEO google mean.io support with angular ui-route index page?

### ISSUE THREAD

**Issue by jcsena** [linnovate/mean#1149]
SEO google mean.io support with angular ui-route index page?

**Comment by timelf123** [comment]
I see mean-seo is commented out in the express config in https://github.com/linnovate/mean/commit/c19c0f8dd4e0a49f7d3f8bbb4d5f82d488bb02e3 

Was the package removed because it was not working?

**Comment by VikramTiwari** [comment]
This is still commented out. Not sure what the issue is. Will look into it.

**Comment by timelf123** [comment]
The technique of prerendering content is no longer needed for the major search engines AFAIK
