### ISSUE TITLE
Overriding "/" angularjs route with custom package issue

### ISSUE THREAD

**Issue by alexryall** [linnovate/mean#1150]
I have managed to override the "/" angular route from the system package in my own custom package however it works inconsistently. Sometimes when the server starts up it will work fine 100% of the time but if I restart the server it might work 0% of the time. When it isn't working there is a JS error saying:

Argument 'HomeCtrl' is not

At the top of my custom package's routes I have:

     angular.module('mean.custom-package', ['mean.system']).config(['$stateProvider',

At the bottom of the custom package's routes I have:

     .config(['$viewPathProvider', function($viewPathProvider) {
         $viewPathProvider.override('system/views/index.html', 'streamers/views/index.html');
     }]);

and inside the new index.html file it starts with

     <div data-ng-controller="HomeCtrl">

I believe this is an issue with the framework since this is the documented way on overriding views and like I said sometimes it works.

**Comment by alexryall** [comment]
In the error console of the browser it says

     Error: [ng:areq] http://errors.angularjs.org/1.3.2/ng/areq?p0=HomeCtrl&p1=not%20aNaNunction%2C%20got%20undefined
    at Error (native)

**Comment by sharphill** [comment]
http://stackoverflow.com/a/30077148/4870635

Don't know why, but removing the ['mean.system'] worked for me. Something as below,

angular.module('mean.mysystem')
  .config(['$viewPathProvider',
   function($viewPathProvider) {
    $viewPathProvider.override('system/views/index.html', 'mysystem/views/index.html');
   }
]);

**Comment by VikramTiwari** [comment]
Current versions provide this as part of scaffolding. Please reopen if you still face the issue.
