### ISSUE TITLE
mean init <new-project> failing

### ISSUE THREAD

**Issue by akofoed** [linnovate/mean#1151]
When executing mean init <new-project>, it skips the password prompt and then fails.

```
$ mean init meantest
? What would you name your mean app? meantest
? The Mean project is currently in developer preview. To help improve the -
  quality of this product, we collect anonymized data on how the mean-cli is used -
  You may choose to opt out of this collection now (by choosing 'N' at the below prompt)
  or at any time in the future by running the following command:

  mean disable user-reporting

  Do you want to help us improve the mean network (Y/n)?  Y
? Please provide your email so we can create your first admin user: foo@bar.com
? Please provide your username so we can create your first admin user: foo
Cloning branch: master into destination folder: meantest
git clone  --depth 1  -bmaster https://github.com/linnovate/mean.git "meantest"
Cloning into 'meantest'...


##############################################################
#
#   !!! MONGOOSE WARNING !!!
#
#   This is an UNSTABLE release of Mongoose.
#   Unstable releases are available for preview/testing only.
#   DO NOT run this in production.
#
##############################################################

    DB connection successful!

Please provide password so we can create your first admin user
prompt: password:  /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:107:17)
    at null.<anonymous> (/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
```

**Comment by oritpersik** [comment]
Which version of mongoose do you have?

**Comment by akofoed** [comment]
$ npm view mongoose version
4.0.2

**Comment by Tobyee** [comment]
I got the same issue.

![default](https://cloud.githubusercontent.com/assets/1400574/7375131/2896e5e6-ee09-11e4-8b75-cfa50a160654.jpg)

![qq 20150429004628](https://cloud.githubusercontent.com/assets/1400574/7375142/3d5d4330-ee09-11e4-9ee9-638d36256582.png)

node -v
v0.10.33
npm -v
2.8.4

**Comment by liorkesos** [comment]
what operating system/ version?
we checked it on ubuntu and osx
Lior

On Tue, Apr 28, 2015 at 7:47 PM, Tobyee <notifications@github.com> wrote:

> I got the same issue.
>
> [image: default]
> <https://cloud.githubusercontent.com/assets/1400574/7375131/2896e5e6-ee09-11e4-8b75-cfa50a160654.jpg>
>
> [image: qq 20150429004628]
> <https://cloud.githubusercontent.com/assets/1400574/7375142/3d5d4330-ee09-11e4-9ee9-638d36256582.png>
>
> node -v
> v0.10.33
> npm -v
> 2.8.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1151#issuecomment-97134498>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by Tobyee** [comment]
windows 8.1 x64

**Comment by akofoed** [comment]
I am OSX

**Comment by ur92** [comment]
Same problem...
Win 7 x64
Mongoose 4.0.2

**Comment by liorkesos** [comment]
Can any of you try to downgrade to mongoose 3.x ?
And check whats up?
I'm using 3.8.24
Lior

On Tue, Apr 28, 2015 at 10:52 PM, Evgeni Dikerman <notifications@github.com>
wrote:

> Same problem...
> Win 7 x64
> Mongoose 4.0.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1151#issuecomment-97185976>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by liorkesos** [comment]
on osx

On Tue, Apr 28, 2015 at 10:59 PM, Lior Kesos <lior@linnovate.net> wrote:

> Can any of you try to downgrade to mongoose 3.x ?
> And check whats up?
> I'm using 3.8.24
> Lior
>
> On Tue, Apr 28, 2015 at 10:52 PM, Evgeni Dikerman <
> notifications@github.com> wrote:
>
>> Same problem...
>> Win 7 x64
>> Mongoose 4.0.2
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/linnovate/mean/issues/1151#issuecomment-97185976>.
>>
>
>
>
> --
>
> Lior Kesos - http://www.linnovate.net
> Linnovate - Community Infrastructure Care
> mail: lior@linnovate.net
> office: +972 722500881
> cell: +972 524305252
> skype: liorkesos
>
>


-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by akofoed** [comment]
Just tried on Cloud9 using npm install mean-cli still with mongoose 4.0.2 and here it works fine.

**Comment by oritpersik** [comment]
i need you to check the version in /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/package.json

**Comment by ur92** [comment]
"name": "mongoose",
  "description": "Mongoose MongoDB ODM",
  "version": "3.9.7",


*Evgeni Diker**man    |            CEO*

ur92.ed@gmail.com | 055-6677469

2015-04-29 9:02 GMT+03:00 Orit Persik <notifications@github.com>:

**Comment by akofoed** [comment]
I think the problem is that it skips the password prompt and therefore dies with "Cannot read property 'length' of undefined" - because the password var is undefined (because there is no password in it).

**Comment by liorkesos** [comment]
Thanks
Well check it out...
Lior

**Comment by mjesuele** [comment]
Any word on this? I'm experiencing the same problem on Yosemite with Mongoose 4.0.2.

**Comment by SzybkiSasza** [comment]
The same for me. Mongoose version 4.0.2, Windows 8.1x64. It seems, as @akofoed mentioned that mean skips prompt input and then gets empty (undefined) value.

**Comment by p2pmining** [comment]
Same here:

Ubuntu 14.04
Mongoose 3.9.7

**Comment by ivanlemeshev** [comment]
Same problem:
OS X Yosemite 10.10.3
node 0.12.2
mongoose 4.0.2
npm 2.7.4
mongodb 3.0.2

**Comment by oritpersik** [comment]
I found it here: https://github.com/Automattic/mongoose/wiki/3.7-(unstable)-Release-Notes :
      ** X.OddNumber.X is an unstable release
       X.EvenNumber.X is a stable release
       For example: 3.7.0, 3.7.1 and 4.11.398 are unstable, whereas 3.8.0, 3.8.1, and 3.20.1 are stable.**

Can you check the mongoose version in your global mean-cli?
(/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/package.json)

@akofoed  it's not a problem of the password....

**Comment by ivanlemeshev** [comment]
@oritpersik it's unstable 3.9.7 
```
$ cat /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/package.json
{
  "name": "mongoose",
  "description": "Mongoose MongoDB ODM",
  "version": "3.9.7",
  "author": {
    "name": "Guillermo Rauch",
    "email": "guillermo@learnboost.com"
  },
...
```

**Comment by oritpersik** [comment]
can you install mean-cli again?
sudo npm uninstall -g mean-cli
sudo npm install -g mean-cli

mongoose version is updated...

**Comment by ivanlemeshev** [comment]
@oritpersik it's work! Thanks!

**Comment by VikramTiwari** [comment]
Fixed.
