### ISSUE TITLE
Referrer url after login or signup

### ISSUE THREAD

**Issue by max-mog** [linnovate/mean#1152]
To pass a 'referrer' url to BOTH login and signup so that after a successful login or signup instead of going to the root, the referrer url (in either http or https) will be used to get redirected.

ie.
- User is at /somecustom/path/somepage
- User tries to access   /someCustomAuthRequiredUrl    so this   '/someCustomAuthRequiredUrl' will be set as the 'referrer'.
- User gets redirected to signup or login
- After a successful signup or login user gets redirected to the 'referrer'  (/someCustomAuthRequiredUrl)

Thank you.

**Comment by max-mog** [comment]
any help?
Thanks

**Comment by liorkesos** [comment]
I see the value in this support, I think this should make it's way as a configuration option for the user package, not sure a monolothic approach or routing to the refferer is the right approach.
We're working on settings per pakage in 0.5 and this can be incorperated as a user setting

**Comment by max-mog** [comment]
@liorkesos Awesome.

**Comment by oritpersik** [comment]
for now, only routes that have the resolve function "checkLogin" (see an example in articles/public/routes/articles.js), will be redirected after register/login.
