### ISSUE TITLE
connect-mongo.js error Error('Required MongoStore option `db` missing or is not a string.')

### ISSUE THREAD

**Issue by ajbraus** [linnovate/mean#1153]
I am just running this cold from the instructions on Mac. Mongodb is installed and running.

**Comment by ajbraus** [comment]
Fixed:

added 

    mongoose       = require('mongoose');
    ... 
    // Express/Mongo session storage
    app.use(session({
        secret: config.sessionSecret,
        store: new MongoStore({
            mongooseConnection: mongoose.connection, // NEW CODE
            db: db.connection.db,
            collection: config.sessionCollection
        })
    }));

**Comment by staminna** [comment]
I have a mean.js fork with this issue, though the error is gone, is goes on for as long as until timeout. Any idea? My guess is that I need to initialize mongoose.connection, but I also passed db.connection.db and config.sessionCollection with no luck. Thanks
