### ISSUE TITLE
the tutorial and github code are different

### ISSUE THREAD

**Issue by mlotfi2005** [linnovate/mean#1157]
Hi,

I found this tutorial 
http://www.sitepoint.com/introduction-mean-stack/

but it looks like you are updating the github code and not the tutorial, for example 
there is no public forlder
there is no Grantfille.

Thanks, your help is appreciated.

**Comment by max-mog** [comment]
That tutorial was probably done by someone outside the team of contributors and it was made last year. Things are constantly improving and updating tutorials are the responsibility of their authors so I suggest getting in touch with the author of that tutorial rather than posting here.

**Comment by liorkesos** [comment]
As @max-mog mentioned - We control the code and cant update any obsolete tutorial.
Closing
