### ISSUE TITLE
 Cannot find module 'bower'

### ISSUE THREAD

**Issue by Bl4ckM** [linnovate/mean#1160]
I installed bower and gulp globally, as its necessary. Mean init is successfull, after cd <project> && npm install this error occured. I'm on Windows 8.1 x86_64, clean install of nodejs, mongo, mean, vs2012, python 2.7.x and as i said gulp and bower globally installed. Any Ideas?:
mongodb verion: 2.6
nodejs: 0.12.2
bower: 1.4.1
npm: 2.7.4
mean-cli: 10.5

```javascript
 validation.vcxproj -> G:\Users\user\simple\node_modules\karma\node_modul
  es\socket.io\node_modules\socket.io-client\node_modules\ws\build\Release\\val
  idation.node

> mean@0.4.6 postinstall G:\Users\user\simple
> node tools/scripts/postinstall.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'bower'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (G:\Users\user\simple\tools\scripts\postinstall.j
s:172:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! mean@0.4.6 postinstall: `node tools/scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean@0.4.6 postinstall script 'node tools/scripts/postins
tall.js'.
npm ERR! This is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\Users\user\simple\npm-debug.log```

**Comment by UnknownBird** [comment]
Solved Issue through installing bower locally in project dir... fix this please.

**Comment by Tushararvind** [comment]
I have tried the same installing in the local directory,but now it is giving EACCES error for npm install,and if used with sudo doesn't work.Is there any other solution as its installation is on priority.

**Comment by DeptiWaghmare** [comment]
I have tried the same installing in the local directory of my application of mean,worked first time but now it's throwing "EACCESS" for npm install,Is there any workaround for this?

**Comment by liorkesos** [comment]
Are you running as root? We built failsafes against that.

**Comment by DeptiWaghmare** [comment]
No,I am using another user, which is giving this error
"npm WARN locking errno: -13,
npm WARN locking code: 'EACCES',"

**Comment by UnknownBird** [comment]
did you chown/chmod the files to your user?

**Comment by DeptiWaghmare** [comment]
Yes,I have tried that also and also with sudo but it then gives cannot run in wd.

**Comment by VikramTiwari** [comment]
@DeptiWaghmare Is this issue fixed for you? If not, please reopen.
