### ISSUE TITLE
Network registration failed 

### ISSUE THREAD

**Issue by shubhangi-tandon** [linnovate/mean#1162]
![image](https://cloud.githubusercontent.com/assets/3772512/7550268/8ba1f136-f678-11e4-97cb-60f1f91fea61.png)

I'm completely new to MEAN. I tried installing today using the instructions on my windows 8.1 machine. It seems to be working ok till the part where i need to register, where I get a registration error and it fails . 

How can I fix this ?

**Comment by wangzhizhen** [comment]
I have the same issue now.....

**Comment by VikramTiwari** [comment]
@shubhangi-tandon @wangzhizhen Were you able to go through? Reopen with more details if it still persists.
