### ISSUE TITLE
login by email ONLY

### ISSUE THREAD

**Issue by limulidae** [linnovate/mean#1164]
the default login is by username,
how can I config it to email login ONLY in a elegant way?

**Comment by VikramTiwari** [comment]
Good Question. I personally think that username based login is not a great approach. Currently, you can use email/username both for logging in. I will try and update docs with how to use ONLY email.

**Comment by timelf123** [comment]
Quick and dirty fix in the meanio-users model
```
username: {
    type: String,
    unique: true,
    required: false,
    get: escapeProperty
  },
...
/**
 * Pre-save hook
 */
UserSchema.pre('save', function(next) {
  var self = this;
  if (this.isNew && this.provider === 'local' && this.password && !this.password.length) {
    return next(new Error('Invalid password'));
  }
  // generate username from email
  if (!self.username) {
    self.username = this.email.split('@')[0];
  }
  next();
});

```

**Comment by timelf123** [comment]
Unfortunately most users don't remember which username goes to which site. If no one disagrees in the next few days I'll submit a PR making email the default login field
