### ISSUE TITLE
EventEmitter in mean.io

### ISSUE THREAD

**Issue by Exiliot** [linnovate/mean#1165]
How can I use EventEmitter mechanisms in custom packages?
Earlier I used to use such code and it worked well for me:
```
var EventEmitter = require('meanio').events;
EventEmitter.emit('newevent');
```
After install new verison of mean.io EventEmitter is undefined:
![image](https://cloud.githubusercontent.com/assets/4901187/7606394/13a4df54-f961-11e4-8551-9070e4679afb.png)

**Comment by VikramTiwari** [comment]
@Exiliot You can ask these questions in the gitter chatroom at https://gitter.im/linnovate/mean
