### ISSUE TITLE
Error: Error setting TTL index on collection : sessions

### ISSUE THREAD

**Issue by DonKarlione** [linnovate/mean#1167]
I have just installed the mean.io stack and getting "Error: Error setting TTL index on collection : sessions" when I run gulp or nodemon server.js.

What am I doing wrong? how can I fix this??

Regards,
Don

**Comment by claustres** [comment]
Usually this message indicates that the mongodb authentication is not right (bad user/password).

Have a look at your env files in the config folder and check your db settings.

**Comment by VikramTiwari** [comment]
Not an issue with MEAN. Please check your configs. Reopen if issue persists.
