### ISSUE TITLE
Error: request entity too large for body-parser

### ISSUE THREAD

**Issue by shailendramonu** [linnovate/mean#1169]
I just found this issue when trying to set the limit for json and urlencoded for body-parser. I tried to add in express.js config but it was not worked. I debug more into body-parser and see the options are setting twice i.e. first time 100kb and then my custom limit but when it process to raw-body it will only take 100kb i.e. default option. 
Then i have found that in ExpressEngine.js (node_modules/meanio/lib/core_modules/server/ExpressEngine.js), it is declared as default  (Line 47 - 50) and it is overriding all the time and not set the custom configuration from express.js.
I commented out here and then set the configurations in express.js and it start working fine.

**Comment by lvarayut** [comment]
I have the exact same issue. Don't know how to override the default one in `ExpressEngine.js`. :disappointed:

**Comment by shailendramonu** [comment]
@lvarayut  Use the same fix as I mentioned above. I am also waiting for fix.
@liorkesos  @VikramTiwari  Can you please look into this issue. This seems a defect in the meanio node modules.

**Comment by iolufemi** [comment]
@liorkesos Kindly merge my pull request, It fixes this issue.

**Comment by iolufemi** [comment]
My pull request has been merged. I think this issue can be closed now.

**Comment by sunil-ideas2it** [comment]
Still ExpressEngine.js (node_modules/meanio/lib/core_modules/server/ExpressEngine.js),  is overriding all the time and not able to  set the custom configuration from express.js.. It is taking configuration from ExpreessEngine.js only.
