### ISSUE TITLE
Menu ordering across multiple packages

### ISSUE THREAD

**Issue by hydrotik** [linnovate/mean#1170]
Not finding any info on this and I think it should also be added to the docs if it exists. My next step is to dig into the source. Some sort of weighting/indexing logic would be great. Maybe even some sorting as well? In the meantime I just want to change the order my package menu items are loading into the header:) Cheers!

**Comment by hydrotik** [comment]
Even better to create a default package that can manage the menu through the admin and DB!

**Comment by liorkesos** [comment]
Totally agree - "menu" is planned to ship in 5.1

**Comment by VikramTiwari** [comment]
There's not been much work on menu package. But I will dig around and update this will anything I can find on that.
