### ISSUE TITLE
Mean still dependen of assets/lib

### ISSUE THREAD

**Issue by yuniers** [linnovate/mean#1171]
Recently I updated to MeanIO 8.0 and Mean 0.5 and app still depend form some [files deleted on](https://github.com/linnovate/mean/commit/244d63b5196b869d70547a1df66717126531365a):
If you want I can provide the error log file.

```code
/home/sosa/Dev/Prueba/packages/core/users/public/assets/lib/angular-jwt/dist/angular-jwt.min.js
/home/sosa/Dev/Prueba/packages/core/admin/public/assets/lib/ng-clip/src/ngClip.js
/home/sosa/Dev/Prueba/packages/core/admin/public/assets/lib/zeroclipboard/dist/ZeroClipboard.js
```

After access to app, an error is triggered:
```code
Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=mean&p1=%5B%24injector%3Amodulerr%5D
```code

Other thing: when I start previous version of my app with Mongosse 3.8 it show a warning that it is a test purpose only version and now not.

**Comment by liorkesos** [comment]
Regarding the warning thats a mongoose thing.
Latest mean and meanio mean that you can use mongoose-4.x
The files you mentioned are part of the admin and core package.
Aren't they in place?

**Comment by mwaqze** [comment]
I am having the same problem!!! Please help me with this.

**Comment by liorkesos** [comment]
This error patten  typically is relatd to an angular error.
Try to roll back your code and find the root cause.
Lior

On Sun, May 31, 2015 at 10:09 PM, mwaqze <notifications@github.com> wrote:

> I am having the same problem!!! Please help me with this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1171#issuecomment-107235429>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by yuniers** [comment]
@mwaqze you must go to each public folder of users and admin package and do
```
bower install
```
After it, all angular dependence will be installed.

**Comment by may215** [comment]
Hi,
Just manually create the folder: 
/packages/core/users/public/assets/lib/angular-jwt
/packages/core/admin/public/assets/lib/ng-clip
/packages/core/admin/public/assets/lib/zeroclipboard

And copy the packages from the bower_components folder to the specific created folder.

**Comment by nikitabanthiya** [comment]
/home/nikita/Meantry/packages/core/users/public/assets/lib/angular-jwt/dist/angular-jwt.min.js not found
/home/nikita/Meantry/packages/core/admin/public/assets/lib/ng-clip/src/ngClip.js not found
/home/nikita/Meantry/packages/core/admin/public/assets/lib/zeroclipboard/dist/ZeroClipboard.js not found
/home/nikita/Meantry/packages/custom/i18n/public/assets/lib/i18next/i18next.js not found
/home/nikita/Meantry/packages/custom/i18n/public/assets/lib/ng-i18next/dist/ng-i18next.js not found

**Comment by nikitabanthiya** [comment]
how to fixed it???

**Comment by VikramTiwari** [comment]
@nikitabanthiya in your project folder run `npm postinstall`

**Comment by nikitabanthiya** [comment]
@VikramTiwari  u mean npm install? i did that still getting error

**Comment by VikramTiwari** [comment]
@nikitabanthiya No, I specifically mean `npm postinstall`.

This this should totally work, but if not then you will need to do following:
- `cd` to `core/users` and run `npm install`
- `cd` to `code/admin` and run `npm install`
- `cd` to `custom/i18n` and run `npm install`

**Comment by nikitabanthiya** [comment]
@VikramTiwari  great its works (y)..

**Comment by supernova23** [comment]
thinks @VikramTiwari
