### ISSUE TITLE
Support for custom error handling?

### ISSUE THREAD

**Issue by gregcarlin** [linnovate/mean#1172]
Does mean allow this? Mean currently only logs error stacks and we want to see the full object.

**Comment by liorkesos** [comment]
Can you elaborate a bit furthur? ideas of what to catch and to log? 
We're very interested to capture as much as possible...

**Comment by gregthegeek** [comment]
Well currently mean seems to handle errors by just logging their stacks:

    console.error(err.stack);

There also seems to be no way to write custom error handlers. I want to see the full error:

    console.error(err);

We are using mongoose validations. When a validation fails, there is a lot of helpful information put into the error object that is not in the stack, including the data that caused the validation to fail. Additionally, we'd like to use our own loggers that record information to files as well as outputting them to stderr.

**Comment by liorkesos** [comment]
Well defintly look in to this. We're building something that will index
these errors to an external service so I want as much data as possible.
Lior

**Comment by VikramTiwari** [comment]
This is definitely that I would like to work on.

Just as a suggestion, you might wanna look into sentry for exception and error handling. (https://sentry.io/welcome/)

**Comment by timelf123** [comment]
I'll try to publish our error logging package later this week as an example. We process the error through stacktrace-js then log to an `errors` collection with the users IP, and a stringified error trace.

Some improvements I've been meaning to add - log user agent, better sourcemap support, frontend views
