### ISSUE TITLE
Zombie server

### ISSUE THREAD

**Issue by shturm** [linnovate/mean#1174]
The HTTP server doesn't always shutdown correctly. I hit CTRL+C two times but then notice in the browser that the page is still responsive. I ran `pidof node` and saw 2 processes. I had to kill them and restart the server.

**Comment by liorkesos** [comment]
hmm any way to recreate this?
you run ctrl-c on the server?

**Comment by shturm** [comment]
Yep. When it happened I was trying to run `gulp` on two mean applications at the same time. Ofcourse, the 2nd failed to start, but it may have something in common

**Comment by liorkesos** [comment]
hmm - not sure if we can cover this situation...
