### ISSUE TITLE
creating custom package 

### ISSUE THREAD

**Issue by vjkumarsw** [linnovate/mean#1176]
I  created a Mean quickstart application in Openshift and cloned it successfully in my development machine and run  locally with my local  node server and mongodb.
I added a custom package test1 using the command
mean package test1 
in my root directory.
When I ran my server and tried 
http://localhost:8080/test1/example 
or 
http://localhost:8080/test1
I get the error given at the end.
Should I do something more to register the package?
Is my url wrong?
Please help.
I use windows laptop and adobe brackets, git bash for development.

Error: [ng:areq] Argument 'HeaderController' is not a function, got undefined
http://errors.angularjs.org/1.2.25/ng/areq?p0=HeaderController&p1=not%20aNaNunction%2C%20got%20undefined
    at http://localhost:8080/bower_components/angular/angular.js:78:12
    at assertArg (http://localhost:8080/bower_components/angular/angular.js:1509:11)
    at assertArgFn (http://localhost:8080/bower_components/angular/angular.js:1519:3)
    at http://localhost:8080/bower_components/angular/angular.js:7278:9
    at http://localhost:8080/bower_components/angular/angular.js:6670:34
    at forEach (http://localhost:8080/bower_components/angular/angular.js:332:20)
    at nodeLinkFn (http://localhost:8080/bower_components/angular/angular.js:6657:11)
    at compositeLinkFn (http://localhost:8080/bower_components/angular/angular.js:6105:13)
    at publicLinkFn (http://localhost:8080/bower_components/angular/angular.js:6001:30)
    at link (http://localhost:8080/bower_components/angular/angular.js:19933:38)
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by vjkumarsw** [comment]
I might have found the problem.
I created the package test1 by using the command 
mean package test1 
Then I moved the test1 folder up one level  from the custom folder to packages folder.
I started the server.
Browsed to localhost:8080, logged in.
test1 example page link showed up in the menu bar and I was ale to navigate to  test1 example.
If I want to leave the test1 folder in the custom folder, what changes should I make to have it working?

**Comment by liorkesos** [comment]
What version of mean are you using on openshift?

**Comment by vjkumarsw** [comment]
I created the application on openshift using MEAN Quickstart 
following instruction given in this
https://openshift.redhat.com/app/console/application_type/quickstart!63
then did a git clone for my development.
I ran a mean status to get the version numbers
and the output is given below:


$ mean status

    MEAN Status
    -----------

    MEAN VERSION: 0.4.0

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
    DB connection successful!

    MongoDB URI: mongodb://localhost/undefined

    checking meanio and global mean-cli versions
    mean-cli at latest version: 0.10.9
    meanio at latest version: 0.5.17

**Comment by liorkesos** [comment]
This is a very old version of mean. We need to update it so you'll get
0.5.0

**Comment by vjkumarsw** [comment]
I tried npm update, npm mean update and had no effect.
What will be the best way to update mean?
Thanks

**Comment by VikramTiwari** [comment]
@vjkumarsw Is this fixed for you. If not, please reopen.
