### ISSUE TITLE
ngAnimate in MEAN. How to use?

### ISSUE THREAD

**Issue by atum201** [linnovate/mean#1178]
i just want use ngAnimate in MEAN, i also add library and declare angular dependencies in system package.
SystemPackage.angularDependencies(['ui.router', 'mean-factory-interceptor','ngAnimate']);

but it not working. Help me use it, please!

**Comment by atum201** [comment]
My problem is version angular. i use version 1.3.2 error with angular animate.

**Comment by KartheekJavvaji** [comment]
how did the problem resolve?
