### ISSUE TITLE
custom package example view server links with auth fail (JWT)

### ISSUE THREAD

**Issue by oliviermills** [linnovate/mean#1183]
When creating a custom package  `mean package mypackage`  the sample view that comes out the box, has links to illustrate server-side with auth and with admin permissions. `http://localhost:3000/api/mypackge/example/auth` . These fail now with the use of JWT as the links are just hrefs with no JWT payload/interceptor.
**Suggest:  using an ajax call with JWT to illustrate how that server call should work.**

**Comment by VikramTiwari** [comment]
@oliviermills Fixed in latest versions. If this is still an issue for you, please reopen.
