### ISSUE TITLE
[Error: /var/www/html/github/startapp/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release/bson.node: undefined symbol: node_module_register]

### ISSUE THREAD

**Issue by gauravbansal74** [linnovate/mean#1185]
Please help me to resolve this Error. I have tried 5-6 times.It's giving me same issue everytime.

Thanks
Gaurav Kumar

**Comment by claustres** [comment]
I had a similar issue and jumped to node v0.12 seems to make it worked. You can also try 'npm update mongoose'.

This might help : https://github.com/Automattic/mongoose/issues/2718#issuecomment-103860265 and https://github.com/Automattic/mongoose/issues/2285.

**Comment by VikramTiwari** [comment]
Fixed in latest versions. If this is still an issue for you, please reopen.
