### ISSUE TITLE
 Cannot read property 'publish' of undefined  MeanUser.events.publish 

### ISSUE THREAD

**Issue by jcsena** [linnovate/mean#1186]
Cannot read property 'publish' of undefined  MEAN@0.5.2

``` JavaScript
  MeanUser.events.publish('logout', {
          description: req.user.name + ' logout.'            
});
```

**Comment by liorkesos** [comment]
Are you sure your using the latest version of mean?
Please send the output of mean status

**Comment by jcsena** [comment]
You're right, I don't was using the latest version of meanio.. i 'm sorry... Lior excellent job thanks MEAN 0.5.x is perfect

**Comment by claustres** [comment]
I have this issue as well using mean.io master branch when clicking on logout in the menu, mean status output : 

```

    MEAN Status
    -----------

    MEAN VERSION: 0.5.0

    DB connection successful!

    MongoDB URI: mongodb://arts2-dev:arts2-dev@localhost:27017/arts2-dev

    checking meanio and global mean-cli versions
    mean-cli at latest version: 0.10.8
    meanio at latest version: 0.8.2
```

**Comment by jcsena** [comment]
Really.. the version latest for meanio is  
 ```
 "name": "meanio",
  "version": "0.8.5"
```

**Comment by claustres** [comment]
OK, things are going really fast with mean.io !

npm install again did the job, issue still closed.

Thanks.
