### ISSUE TITLE
req.user.save ( .... not working

### ISSUE THREAD

**Issue by emps** [linnovate/mean#1189]
var user = req.user;

user.name = 'x';

user.save(function... // undefine isnot func..

not working any more at this version, seems like req.user isnt moongose model object, take look on it, its very importent be able update user from the req, instead of loading it from the db again to update something

example:
            User.findOne({
                _id: req.user._id
            }, function(err, user) {
                console.log('req.user');
                console.log(req.user.hasOwnProperty('save'));  //ret false
                console.log('user');
                console.log(user.hasOwnProperty('save'));  //ret true
            });

**Comment by VikramTiwari** [comment]
Guess this is not an issue anymore. If otherwise, please reopen.
