### ISSUE TITLE
Submenus and menu module

### ISSUE THREAD

**Issue by hydrotik** [linnovate/mean#1195]
Sorry to open up YET another ticket about sub menus but this seems like an easy win to get integrated into master with a number of existing pull requests and a ton of already open tickets. This should hint as to the need. In addition, installing mean-menu doesn't work as well which seems like a useful default module.

https://github.com/linnovate/mean-menu/issues/1

Not always, but occasionally for every problem mean.io helps solve, I find 2 more that get in the way of my ability to quickly implement my work. What's frustrating is that these are just matters if merging. Sorry for the rant, but I come from a place of wanting to see mean.io thrive and I find myself contemplating alternatives.

On that note I am looking forward to the next version and hoping that this is the reason some of these things haven't been integrated :)

In the meantime I have looked at the drop down branch and if someone could point me to where the logic is to structure the data that is passed to the header template, I would be eternally grateful. Cheers.

**Comment by hydrotik** [comment]
https://github.com/linnovate/mean/issues/1199

**Comment by huachangzha** [comment]
any solution or manual?

**Comment by rjVapes** [comment]
The core menu functionality supports sub menus, but the referenced issue isn't attempting to implement them properly.  The general idea is that a submenu has a name, and then links under it.  So if you want a high level dropdown on the 'main' menu for 'MyPackage' to have 3 links, you'd do something like:

```
MyPackage.menus.add({
  title: 'title1',
  link: 'link1',
  roles: ['anonymous'],
  menu: 'main/MyPackage'
});  
MyPackage.menus.add({
  title: 'title2',
  link: 'link2',
  roles: ['anonymous'],
  menu: 'main/MyPackage'
});  
MyPackage.menus.add({
  title: 'title3',
  link: 'link3',
  roles: ['anonymous'],
  menu: 'main/MyPackage'
});  
```

The default core/system header controller doesn't handle this to defaultly create dropdown menus or anything so you'd have to handle it in your controller (in its current state it'll actually throw errors).  I'll try to look into fixing up a few things with menus to make it more seemless, but this should get you on the right track.

The big take away here is that to create a submenu, you just use a '/' to nest in the 'menu' option, and don't attempt to populate the array yourself, as it's an array of MenuItems (a proper class) not an arbitrary object with some strings in it.

**Comment by VikramTiwari** [comment]
Menus man! They are everywhere. 🎯
