### ISSUE TITLE
req.user problem

### ISSUE THREAD

**Issue by emps** [linnovate/mean#1202]
after logging in req.user not get changed even if user.name (or any other prop in user) in db changes , only after logout and than relogin req.user get new properties from the db and again stays same for all the session

**Comment by emps** [comment]
u can see this problem visually when u change user name than just refresh, u see the user stays with the old name..

**Comment by emps** [comment]
as i see the user in the req is the user in localstorage at JWT, even if i run second project of mean i get same user in diffrent db... and JWT implementation must be fixed

**Comment by emps** [comment]
its even secure hole cause if i come with admin role in the jwt i can see mean-admin and get all users

**Comment by emps** [comment]
the problem comes from express-jwt that is at \node_modules\meanio\node_modules\express-jwt\lib\index.js
line 108:
      jwt.verify(token, secret, options, function(err, decoded) {
        if (err && credentialsRequired) return next(new UnauthorizedError('invalid_token', err));

        req[_requestProperty] = decoded;
        next();
      });

while req[_requestProperty] is req.user that is taken from the token and not from the db after refreshing.. so req.user stays same from the login moment while db user get changes (exmpl: changing user name , or any property)

**Comment by liorkesos** [comment]
Thanks for digging in.
If you can submit a PR with a fix - I'll definitely test and merge it.
Lior

On Sat, Jun 6, 2015 at 12:56 PM, Karol <notifications@github.com> wrote:

> the problem comes from express-jwt that is at
> \node_modules\meanio\node_modules\express-jwt\lib\index.js
> line 108:
> jwt.verify(token, secret, options, function(err, decoded) {
> if (err && credentialsRequired) return next(new
> UnauthorizedError('invalid_token', err));
>
>     req[_requestProperty] = decoded;
>     next();
>   });
>
> while req[_requestProperty] is req.user that is taken from the token and
> not from the db after refreshing.. so req.user stays same from the login
> moment while db user get changes (exmpl: changing user name , or any
> property)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1202#issuecomment-109561503>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by emps** [comment]
k take a look..

**Comment by VikramTiwari** [comment]
@emps This is fixed, right? Please reopen if still persists.
