### ISSUE TITLE
can't install mean-cli, no npm-debug.log written

### ISSUE THREAD

**Issue by jeffsp** [linnovate/mean#1205]
I have followed the steps in the README, but **Install the mean-cli** step fails.

     jsp@gorilla ~/projects/mean % sudo npm install -g mean-cli
     -
    > mean-cli@0.10.12 preinstall /usr/local/lib/node_modules/mean-cli
    > node ./scripts/preinstall

    npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be
    propagated
 
    > mean-health@0.1.7 postinstall /usr/local/lib/node_modules/mean-cli/node_modules/mean-health
    > node ./postinstall.js

    > kerberos@0.0.12 install /usr/local/lib/node_modules/mean-
    cli/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-
    core/node_modules/kerberos
    > (node-gyp rebuild 2> builderror.log) || (exit 0)
    make: Entering directory `/usr/local/lib/node_modules/mean- 
    cli/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-
    core/node_modules/kerberos/build'
    CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    make: Leaving directory `/usr/local/lib/node_modules/mean-
    cli/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-
    core/node_modules/kerberos/build'

    jsp@gorilla ~/projects/mean % ls npm-debug.log
    ls: cannot access npm-debug.log: No such file or directory

**Comment by luckiss** [comment]
me too.

**Comment by jeffsp** [comment]
Also: I am installing on Ubuntu 14.04.  I am running node 0.12.4 and npm 2.11.1.

**Comment by traskcs99** [comment]
I had the same issue, the mean file is located here:  ./node_modules/mean-cli/bin/mean

**Comment by jeffsp** [comment]
I fixed this, but forgot to cross-reference from npm issues.  See the fix [here](https://github.com/npm/npm/issues/8471).
