### ISSUE TITLE
Article file in the wrong location

### ISSUE THREAD

**Issue by vtdave** [linnovate/mean#1206]
@mqli - The file
https://github.com/linnovate/mean/blob/master/packages/articles/public/routes/articles.js

is in the wrong location, it should be under:
/packages/core/articles/...

it was merged in earlier this week.

**Comment by vtdave** [comment]
@liorkesos you may want to look at this too, i think it came in the same PR as:
https://github.com/linnovate/mean/issues/1208

Thanks.

**Comment by liorkesos** [comment]
I tthink this has been address in commit -https://github.com/linnovate/mean/commit/e4a5b50f3c436884ab05ddea176901513da03ffb
Please see if it solves the issue.

**Comment by vtdave** [comment]
Yep, looks to be fixed, thanks.
