### ISSUE TITLE
Error when I check the mean status

### ISSUE THREAD

**Issue by intrepido** [linnovate/mean#1212]
When I check the status in the command line (mean status), I get the following error.

MEAN Status
    -----------

    MEAN VERSION: 0.5.0

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
    DB connection successful!

    MongoDB URI: mongodb://localhost/mean-dev

    checking meanio and global mean-cli versions
    mean-cli at latest version: 0.10.12
    meanio at latest version: 0.8.74

**Comment by liorkesos** [comment]
This is not a mean specific issue...
Reffer to this - it might help -
http://stackoverflow.com/questions/21656420/failed-to-load-c-bson-extension
