### ISSUE TITLE
I would like to include font awesome without modifying the font-awesome.css

### ISSUE THREAD

**Issue by ctesene** [linnovate/mean#1214]
Font Awesome uses relative paths inside of their CSS files which work fine in development mode, but in production mode, and once the css is aggregated, those relative paths no longer resolve to working paths.

I am getting a 404 error for the `/fonts/font-awesome.woff` file. To get this to work, I had to modify the `font-awesome.css` file to point to the custom package location `/customtheme/assets/fonts/font-awesome.woff`

I spoke with @BrockMcKean and he suggested opening an issue.

It doesn't feel right to have to modify the font-awesome.css file, any suggestions?

**Comment by VikramTiwari** [comment]
You can overcome this by adding fontawesome file urls in the https://github.com/linnovate/mean/blob/master/packages/core/system/server/views/includes/head.html file.

**Comment by timelf123** [comment]
How exactly can you add those urls to the `head.html` file without causing the 404s?

**Comment by timelf123** [comment]
I solved this like so:

1. copied the fontawesome scss folder into my css folder
2. copied fonts to `/yourthemepackage/assets/fonts/`
2. set `$fa-font-path:        "/yourthemepackage/assets/fonts/" !default;` in `_variables.scss`
4. `YourThemePackage.aggregateAsset('css', 'fontawesome/font-awesome.css');`

**Comment by VikramTiwari** [comment]
Awesome! Thanks @timelf123 for updating the solution.

@ctesene Please reopen if still unresolved.
