### ISSUE TITLE
Glyphicons cannot be found on gulp/node production

### ISSUE THREAD

**Issue by shailendramonu** [linnovate/mean#1218]
Mean 0.4.4 - I see that these bootstrap fonts are calling from bootstrap.css and expects fonts folder to be on root on production build but it will not be able to find. I have checked the gulp task not able to see anything for adding fonts folder resources. I am using these fonts for my project and running fine on development but when tried for production it stops working as I got 404 error for bootstrap fonts call. Please help....

**Comment by liorkesos** [comment]
We don't actively support 0.4.4
I need to check this in the last version.

On Tue, Jun 16, 2015 at 2:20 PM, shailendramonu <notifications@github.com>
wrote:

> Mean 0.4.4 - I see that these bootstrap fonts are calling from
> bootstrap.css and expects fonts folder to be on root on production build
> but it will not be able to find. I have checked the gulp task not able to
> see anything for adding fonts folder resources. I am using these fonts for
> my project and running fine on development but when tried for production it
> stops working as I got 404 error for bootstrap fonts call. Please help....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1218>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by shailendramonu** [comment]
Thanks for a quick reply... I am also fine if any fix is provided in the current version... Thanks again...
