### ISSUE TITLE
starting server is extremely slow when connected to the internet

### ISSUE THREAD

**Issue by ssmlee04** [linnovate/mean#1221]
When I try to do `node server` with no internet it takes like 10 seconds to start a server. But when I am connected to the internet sometimes it takes 1 minute to start a server.  I wonder what might be the problem? 

My meanio package version is 0.7.1

**Comment by gauravscorpsgit** [comment]
You might want to see the network calls while app loads, one of the reason for the delay is all the bower dependencies gets loaded whether its required or not by the current view. I am myself facing the same issue when I try to run my app hosted at Amazon EC2 server.

**Comment by claustres** [comment]
This has nothing to do with bower dependencies loading because this is not done by the web server it is done by your browser.

**Comment by ssmlee04** [comment]
I ultimately figured out the problem. The problem is with DNS and mongoose.  if you change the host from localhost to 127.0.0.1 the problem disappears. just in case anyone who's still reading this.
