### ISSUE TITLE
Fresh install... angular errors out of box

### ISSUE THREAD

**Issue by gathem** [linnovate/mean#1223]
I did a couple of mean.io projects in the past and really liked it. Previously I had torn out angular in favor of Jade/other JS framework. I've been using angular a lot lately so for this new project I decided to go with out of the box mean.io

I have yet to change any code, and the only thing I have done so far is install missing deps via npm/bower/mean install

Mean starts up just fine, and runs without errors. Angular... not so much
Failed to instantiate module mean.mean-admin due to:
Error: State 'users'' is already defined

**Comment by gathem** [comment]
note: mean uninstall mean-admin does seem to fix the issue. Would be nice to have mean-admin though : /

**Comment by rjVapes** [comment]
I haven't run into this when I installed very recently.  The only place in my repo that I see the 'users' state being defined is in admin.  Could you search your project and see if you can find where the duplicate might be?

https://github.com/linnovate/mean/search?utf8=%E2%9C%93&q=%22.state%28%27users%27%22&type=Code

**Comment by VikramTiwari** [comment]
Please reopen if still an issue.
