### ISSUE TITLE
Unable to display image for package when overriding views

### ISSUE THREAD

**Issue by mr-e-** [linnovate/mean#1225]
I used this code in the documentation to override my package as the default:

angular.module('mean.mycustompackage', ['mean.system'])
.config(['$viewPathProvider', function($viewPathProvider) {
  $viewPathProvider.override('system/views/index.html', 'mycustompackage/views/myhomepage.html');
}]);

When the page displays it tries to load the image from the url: http://localhost:3000/assets/img/logo.png  instead of looking in the correct packages assets folder. How do I override the default page?

**Comment by claustres** [comment]
Take care that MEAN.IO is a [SPA](https://en.wikipedia.org/wiki/Single-page_application) so there an index page on the 'server' side providing static parts such as the logo, the menu bar, etc. and an index page on the 'client' side which is the content of the index page. I think you have overriden the second one but not the first one. In this case you will need to use this in your custom module app.js:
```
// Override default views path to serve our index
app.set('views', __dirname + '/server/views');
```
Then create the appropriate index.html in custompackage/server/views (you can have a look to the default page from MEAN.IO and reuse).

**Comment by VikramTiwari** [comment]
@mr-e- If this is still an issue, please reopen.
