### ISSUE TITLE
Isn't passport supposed to be integrated in mean.io? I don't I see any of them available on the sign up page?

### ISSUE THREAD

**Issue by mr-e-** [linnovate/mean#1226]

**Comment by liorkesos** [comment]
You need to configure them in the confog and then whatever app you
configured will "magocally" appear

**Comment by mr-e-** [comment]
Is there any documentation for this?

**Comment by liorkesos** [comment]
Maybe a blog post way back.
If you could document and submit a pull request it would be great
contribution to the project
Liir

**Comment by VikramTiwari** [comment]
Please re-open if still an issue.
