### ISSUE TITLE
Load view specific bower dependencies

### ISSUE THREAD

**Issue by gauravscorpsgit** [linnovate/mean#1227]
Currently package dependent bower dependencies are loaded, there are performance issues with respect to page speed where redundant or non-required dependencies are loaded every time. In brief we should have a way to load bower dependencies required by the current view only not all.

**Comment by claustres** [comment]
Could you detail more your though ? Indeed MEAN.IO is basically a [SPA](https://en.wikipedia.org/wiki/Single-page_application), so dependencies are only loaded once and content updated dynamically. IMHO users are more tolerant to wait once a couple of seconds on first load then have a smoother navigation instead of waiting more on each page change...

**Comment by gauravscorpsgit** [comment]
The issue is when the app is not single page one, whenever other page loads all the bower dependencies are loaded. Logically and simply this should not happen and only required bower dependencies should be requested.

**Comment by claustres** [comment]
A MEAN.IO app is ALWAYS a single page app, I think you do not really understand what does mean a SPA or I completly miss your point...

**Comment by gauravscorpsgit** [comment]
I do understand SPA and already released the first version of our app using MEAN.IO and its live, there are some pages which needs to be explicitly opened in new tab when user clicks on the link <a target="_blank" data-ng-href="/#!/abc">New Page</a>, as said all the content is loaded again which is taking time. FYI we do respect client requirements and try to find solutions instead overriding them and its nice to raise issue in endeavor of improvements. It would be appreciable if solutions should be brainstormed.

**Comment by claustres** [comment]
In think that browsers are specifically designed to try to prevent a page in one tab from attacking a page open in another tab (assuming they are from two different domains). The specific security mechanism is known as the same-origin policy. So opening a new tab leads to an isolated sandboxed environment just like connecting from another browser. However everything gets cached by your browser so it will not load your scripts again and again, I think that what takes time is initializing the new context and run the scripts.
