### ISSUE TITLE
Error when pushing to Heroku: Error: ENOENT, open '.bower-cache/e9f8053314f992cbc734f1d338e7339c-1.3.2.lock'

### ISSUE THREAD

**Issue by RhysJevons** [linnovate/mean#1228]
I keep seeing Error: ENOENT, open '.bower-cache/e9f8053314f992cbc734f1d338e7339c-1.3.2.lock' when pushing to Heroku. Everything completes but then I when I try to run my app the Heroku logs show:

Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'

I've tried everything suggested npm cache clean, bower cache clean, npm install, bower install etc the only issue I can find is in the git logs below when pushing to Heroku:

remote:        > mean-health@0.1.7 postinstall /tmp/build_b50ea7b8307710370a76f233491733a7/packages/contrib/mean-admin/node_modules/mean-health
remote:        > node ./postinstall.js
remote:        
remote:        Error: ENOENT, open '.bower-cache/e9f8053314f992cbc734f1d338e7339c-1.3.2.lock'
remote:        request@2.58.0 node_modules/request
remote:        ├── caseless@0.10.0

Can anyone please throw some light on this for me? I've been trying to deploy for over a week now.

**Comment by VikramTiwari** [comment]
@RhysJevons If this is still an issue for you, please reopen.
