### ISSUE TITLE
Error: dependency 'access' was not registered

### ISSUE THREAD

**Issue by deepaksisodiya** [linnovate/mean#1229]
Error: dependency 'access' was not registered

**Comment by claustres** [comment]
Please if you want some help provide as much as information you can:

 - context (during installation, when executing, etc.)
 - version used
- complete log/error messages
- ...

This might help : http://stackoverflow.com/help/how-to-ask

**Comment by VikramTiwari** [comment]
@deepaksisodiya If this is still an issue for you, please reopen.
