### ISSUE TITLE
OS X Chrome - Login and Join are showing the default landing page

### ISSUE THREAD

**Issue by jcaldwell** [linnovate/mean#1240]
Newly initialized mean app with commit 7c1e1cbc0b12ef0405ba26560bdffc456b00527c

On OS X Chrome the login and join buttons are showing the default landing page instead of the respective sections for login and join.

**Comment by Jbartsch** [comment]
Same here. No issues with FF 38.0.5 and safari 8.0.6

**Comment by VikramTiwari** [comment]
@jcaldwell If this is still an issue for you, please reopen.
