### ISSUE TITLE
OS X Installation Error

### ISSUE THREAD

**Issue by Kemaletdin** [linnovate/mean#1242]
Hi,

I have been trying to install MEAN on my iMac and I keep getting this error permission error.
i did "npm install -g mean-cli"
I tried both with and without "sudo"

I have following working:
OSX 10.9.5
node 0.10.35
npm 2.11.3
brew 0.9.5
bower 1.4.1
gulp CLI 3.9.0
git 1.9.5 (Apple Git-50.3)
mongoDB 3.0.4

Any ideas why ?

thanks
Kemal

==========================================================================
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:838
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:838:23)
    at startup (node.js:58:13)
    at node.js:929:3
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "mean-cli"
npm ERR! node v0.10.35
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
==========================================================================

**Comment by VikramTiwari** [comment]
Please update your Node version to 0.12 as most of the dependent packages have closed the support for older packages. Reopen if it still persists.
