### ISSUE TITLE
Cannot find module error when starting server.js

### ISSUE THREAD

**Issue by tjsingh** [linnovate/mean#1243]
I followed the instructions as per documentation on the site.

But I keep getting constant error when trying to start server.js via the terminal on MAC OS X.

module.js:338
    throw err;
          ^
Error: Cannot find module 'caseless'
    at Function.Module._resolveFilename (module.js:336:15)

I keep updating these using npm install <npm module> manually but keep getting more modules not found.

I had a quick scan of the code and found that mean-seo requires in the caseless if that helps

Not sure what i have done differently?

Thanks

**Comment by VikramTiwari** [comment]
@tjsingh NPM package installation for you did not completed successfully. Can you give it a retry and reopen if this is still an issue for you.
