### ISSUE TITLE
Mean-Admin $injector:modulerr when try open website

### ISSUE THREAD

**Issue by michalmw** [linnovate/mean#1247]
Hi, 
when i install mean-admin and try start node server.js i have white page and in consoe log 
```
'Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=mean&p1=Error%3A%20…Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3A19%3A219)'
```

but normal mean working without this package.

Someone can help?

**Comment by felixSchl** [comment]
Why is this closed? What did you have to do to get it working? I am greeted exactly with the same message after installing mean-admin using `mean install mean-admin`.
