### ISSUE TITLE
File upload : multiple files and more than 10 kb size not uploading

### ISSUE THREAD

**Issue by pankaj884** [linnovate/mean#1248]
I did try multiple methods from angular front-end and I also try uploading from simple html form. Data is sending perfectly from front-end. If I upload a small file (< 10kb) it's work fine, but multiple files and big files are not uploading. I am implementing the uploading code in user package. And here is the function:

exports.upload = function (req, res, next) {

    console.log('userjs-upload');

    var form = new formidable.IncomingForm();
    form.keepExtensions = true;
    form.parse(req, function (err, fields, files) {

        if(err){
                   return res.json(500, err);
        }
        console.log('----------------------fields---------------------------');
        console.log(files);
        var tempFilePath = "" + files.file['path'],
            userFileName = files.file['name'],
            bucketName = 'xxxxx',
            key = req.user._id + '/' + Math.random().toString(36).slice(2),
            contentType = files.file['type'];

        fs.readFile(tempFilePath, function (err, file_buffer) {

            console.log(err);

            var params = {
                Bucket: bucketName,
                Key: 'xxxx' + '/' + key + userFileName,
                Body: file_buffer,
                ACL: 'public-read',
                ContentType: contentType
            };

            s3.putObject(params, function (err, response) {
                if (err) {
                    console.log("Error uploading data: ", err);
                } else {
                    res.json({
                        'src': 'http://s3.amazonaws.com/' + bucketName + '/' + 'seller' + '/' + key + userFileName,
                        "name": userFileName,
                        "status": true
                    });
                    fs.unlink(tempFilePath, function (err, result) {
                        console.log('final file deletion here goes')
                    });
                }
            });
        });
    });
};

**Comment by VikramTiwari** [comment]
@pankaj884 You will need to use `multipart` based uploader. Take a look at https://git.mean.io/orit/upload for some inspiration.
