### ISSUE TITLE
When installing, user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.37"

### ISSUE THREAD

**Issue by DIMPLY** [linnovate/mean#1251]
> bson-ext@0.1.10 install /usr/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
    > (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)

    gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.37"
    gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/.node-gyp"
    make: Entering directory `/usr/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build'
    make: *** No rule to make target `../.node-gyp/0.10.37/common.gypi', needed by `Makefile'.  Stop.
    make: Leaving directory `/usr/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by liorkesos** [comment]
Your not supposed to install with the root user -  I don't understand why it's not able to create the file...

**Comment by VikramTiwari** [comment]
Please check permissions for your `~/.npm` dir. It should have admin access to your user. Reopen if this is still an issue.
