### ISSUE TITLE
hide the menus for admin user (MEAN VERSION: 0.4.3)

### ISSUE THREAD

**Issue by leonzmq520** [linnovate/mean#1252]
Hi, modifing the user roles like "user" ,"doc-owner" and "admin".
I want to hide the menus for "admin" user, 
in the  questionnaires/app.js
 ```javascript
Questionnaires.menus.add({
        title: 'Questionnaires',
        link: 'all questionnaires',
        roles: ['user'],
        menu: 'main'
    });
    Questionnaires.menus.add({
        title: 'Create New Questionnaire',
        link: 'create questionnaire',
        roles: ['doc-owner'],
        menu: 'main'
    });
```
But it doesn't work , anyone could help?

**Comment by igorgarofano** [comment]
Hi, you can try to load a new "view", where you separate user and admin view. Let me know.

**Comment by igorg1312** [comment]
Questionnaires.menus.add({
        title: 'Questionnaires',
        link: 'all questionnaires',
        roles: admin,
        menu: 'admin-menu'
    });
Questionnaires.menus.add({
        title: 'Questionnaires',
        link: 'all questionnaires',
        roles: ['user'],
        menu: 'main'
    });
    Questionnaires.menus.add({
        title: 'Create New Questionnaire',
        link: 'create questionnaire',
        roles: ['doc-owner'],
        menu: 'main'
    });

**Comment by leonzmq520** [comment]
@igorg1312  it is a real good idea to resolve it , but i want to hide both of the 'Questionnaires' and 'CreateNewQuestionnaire' views just for Admin user. The 'Questionnaires' view only could be accessed by User and the 'CreateNewQuestionnaire' view could be accessed by Doc-owner.

**Comment by leonzmq520** [comment]
It has been done ! 
The solution that i found is to add this code in packages/system/server/routes/menus.js
`
 if (menu === 'main' && roles.indexOf('admin') !== -1) {
               roles.splice(roles.indexOf('admin'), 1);
}
`
Because I used MEAN 0.4.3 like MEAN STATUS shows:

MEAN Status
    -----------

MEAN VERSION: 0.4.3
