### ISSUE TITLE
Auth Failing for Custom Packages

### ISSUE THREAD

**Issue by vincentlawlor** [linnovate/mean#1256]
Hi guys,

After creating a completely new application without any modification.

When I open the i18n example page and click on either of the links:
2. Server route that requires authentication
3. Server route that requires admin user

The result is:
User is not authorized

This also happens for any package that is created and not core.

Any ideas?

**Comment by igorg1312** [comment]
Hey, do you checked same User Grant on MongoDB,
Check this, otherwise test to link page package on core version, and past log here.

**Comment by vincentlawlor** [comment]
Don't know what you mean. "do you checked same User Grant on MongoDB,"

I have only one user - it works on the core packages without any problems.
For the same user logged in when I go to a custom package none of the authentication works.

When I check for a res.user server side it shows as undefined.

Vinny.

**Comment by igorg1312** [comment]
Ok, very good, you checked all server side is on public fold, or if you
change the directory for this package check this var
app.use(express.static(__dirname
+ '/public'));
do you checked var methodOverride = require('method-override'
All this setting is on server.js.. Update please.
);

2015-07-09 17:37 GMT+02:00 vincentlawlor <notifications@github.com>:

> Don't know what you mean. "do you checked same User Grant on MongoDB,"
>
> I have only one user - it works on the core packages without any problems.
> For the same user logged in when I go to a custom package none of the
> authentication works.
>
> When I check for a res.user server side it shows as undefined.
>
> Vinny.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1256#issuecomment-120036951>.
>



-- 

*Igor Garofano*

**Comment by CoericK** [comment]
Hello, im just having the same issues, but i noticed that the authentication is working when you make ajax request using $http(), even if your route has auth.requiresAdmin /api/products, it will work but if you go to the browser and type /api/products it tells you "User is not authorized" @igorg1312 what do you mean by var methodOverride... im checking my server.js file and its not there

**Comment by CoericK** [comment]
@vincentlawlor did you solve your problem? if so please can you share how can i fix that?

**Comment by CoericK** [comment]
@liorkesos maybe you can give us a hand here?

**Comment by vincentlawlor** [comment]
@CoericK 
Erick no haven't managed to figure this out yet some help from Lior (@liorkesos) would really help here.
Vinny.

**Comment by liorkesos** [comment]
I;m on vacation will be able to look at this next week

On Thu, Jul 9, 2015 at 3:25 PM, vincentlawlor <notifications@github.com>
wrote:

> @CoericK <https://github.com/CoericK>
> Erick no haven't managed to figure this out yet some help from Lior (
> @liorkesos <https://github.com/liorkesos>) would really help here.
> Vinny.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1256#issuecomment-120148373>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by vincentlawlor** [comment]
Thanks Lior.

**Comment by vincentlawlor** [comment]
@liorkesos - Hey Lior will you have a chance to have a look at this problem this week?

**Comment by vincentlawlor** [comment]
@CoericK,  @liorkesos - did you manage to make any progress on this?
I am completely at a loss as to why this is happening.

**Comment by vincentlawlor** [comment]
Ok so I have had to resort to turning off auth completely on custom packages for now until this is resolved.

**Comment by vincentlawlor** [comment]
@liorkesos - any update on this problem?

**Comment by ducminhquan** [comment]
@liorkesos - any fix for this problem?

**Comment by persandstrom** [comment]
I'm having the same problem. Has anyone succeeded to solve this?

**Comment by cdubois** [comment]
I too am having this same issue.  Is there a quick fix?  The custom package example template does seem to be missing something.

**Comment by cdubois** [comment]
I keep tracing this back up the chain.  For these get requests, the user object does not exist as part of req, and that is why auth.requiresLogin and then req.isAuthenticated returns false.  @liorkesos, hopefully this is a quick one for you.

**Comment by vincentlawlor** [comment]
Yea traced this back to the same place but still no solution.

**Comment by flythebluesky** [comment]
This is happening because the user id isn't stored in a session, so the user can't be retrieved and put  into req.user for authentication processing. It doesn't affect the /api routes because JWT takes care of those. 

Here's a workaround for https://github.com/linnovate/meanio/blob/master/lib/core_modules/server/ExpressEngine.js

I'm not sure what appropriate session settings would be, but this gets it working.

```javascript
var session = require('express-session'),

...

  this.app.use(session({
	  resave: false,
	  saveUninitialized: true,
	  secret: 'a very big secret'
  }));
  this.app.use(passport.initialize());
  this.app.use(passport.session());
  this.mean.register('passport',passport);
```

**Comment by mirul16** [comment]
try to edit document on monggo, you can edit with robomongo : 
"roles" : [ 
   "authenticated",
   "admin",
],
