### ISSUE TITLE
Tests fail for core package user

### ISSUE THREAD

**Issue by kvan1** [linnovate/mean#1257]
The circles branch package for ACL has added a default role (sic) 'annonymous'.
Test 
    `it('should check that roles are assigned and created properly',  `
now fails at 
`expect(_user.roles.length).to.equal(1);`

This has a cascade effect on 6 other tests as the uncaught error precludes the 
`_user.remove`
in the first mentioned test

**Comment by VikramTiwari** [comment]
@kvan1 If this is still an issue for you, please reopen.
