### ISSUE TITLE
Cannot download MEAN

### ISSUE THREAD

**Issue by GijsGoudzwaard** [linnovate/mean#1258]
When I write "npm install -g mean-cli" into my command prompt, it always gets stuck. This is what happens:
C:\Users\<my name>>npm install -g mean-cli
-
> mean-cli@0.10.14 preinstall C:\Users\<my name>\AppData\Roaming\npm\node_modules\mea
n-cli
> node ./scripts/preinstall

npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile
would not be propagated
|

> mean-health@0.1.7 postinstall C:\Users\<my name>\AppData\Roaming\npm\node_modules\m
ean-cli\node_modules\mean-health
> node ./postinstall.js

And it just stays stuck here.

Edit:
When I run it again it does the following:
C:\Users\<my name>>npm install -g mean-cli
-
> mean-cli@0.10.14 preinstall C:\Users\<my name>\AppData\Roaming\npm\node_modules\mea
n-cli
> node ./scripts/preinstall

npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile
would not be propagated
/

> mean-health@0.1.7 postinstall C:\Users\<my name>\AppData\Roaming\npm\node_modules\m
ean-cli\node_modules\mean-health
> node ./postinstall.js

|
> kerberos@0.0.12 install C:\Users\<my name>\AppData\Roaming\npm\node_modules\mean-cl
i\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modu
les\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\<my name>\AppData\Roaming\npm\node_modules\mean-cli\node_modules\mongoose\no
de_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos>if not define
d npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-g
yp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebu
ild )
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled packa
ge wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled pac
kage wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled pa
ckage wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled pac
kage wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled packag
e wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled p
ackage wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled pac
kage wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package
 wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled pac
kage wasn't found in unpacked tree
|

And now it stays stuck here.

**Comment by VikramTiwari** [comment]
@GijsGoudzwaard If this is still an issue for you, please reopen.
