### ISSUE TITLE
/packages/custom/i18n/public/assets/lib/i18next/i18next.js not found

### ISSUE THREAD

**Issue by cssgdhd** [linnovate/mean#1266]
After initializing my mean-app,I run `gulp`,then I got an error like below
`/packages/custom/i18n/public/assets/lib/i18next/i18next.js not found`
`/packages/custom/i18n/public/assets/lib/ng-i18next/dist/ng-i18next.js not found`
However,I can't find these two js files on the repository nether.
And my mean's version is 0.10.14.
Some one help me,plz.

**Comment by oritpersik** [comment]
@cssgdhd run `mean postinstall` in your app root folder.

**Comment by cssgdhd** [comment]
I resolve this problem by doing `npm install`. THX @oritpersik all the same!
