### ISSUE TITLE
When overriding mean.system to add your own route for the default route, state gets broken and only works with hash. HTML5 mode doesnt work.

### ISSUE THREAD

**Issue by peb7268** [linnovate/mean#1271]
//Override the home routes
//Setting up route
angular.module('mean.system').config(['$meanStateProvider', '$urlRouterProvider', function($meanStateProvider, $urlRouterProvider){
    $meanStateProvider.state('index', {
        url: '/',
        templateUrl: 'myProject/views/index.html'
      });
    }
]).config(['$locationProvider',
  function($locationProvider) {
    $locationProvider.html5Mode({
      enabled: true,
      requireBase: false
    });
  }
]);

**Comment by VikramTiwari** [comment]
@peb7268 If this is still an issue for you, please reopen.
