### ISSUE TITLE
Angular module error on stock generated project

### ISSUE THREAD

**Issue by h3xc0ntr0l** [linnovate/mean#1274]
I couldn't find anything about this on the web, so I figured it might be an unknown issue (or, I wasn't typing the right words).

I used the mean-cli to create a new project. Got everything in working order. when I used gulp to run the dev server and went to http://localhost:3000/, I got this error:

Failed to instantiate module mean due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=m...)
    at Error (native)
    at http://localhost:3000/bower_components/angular/angular.min.js:6:416
    at http://localhost:3000/bower_components/angular/angular.min.js:38:154
    at m (http://localhost:3000/bower_components/angular/angular.min.js:7:322)
    at g (http://localhost:3000/bower_components/angular/angular.min.js:37:229)
    at http://localhost:3000/bower_components/angular/angular.min.js:37:398
    at m (http://localhost:3000/bower_components/angular/angular.min.js:7:322)
    at g (http://localhost:3000/bower_components/angular/angular.min.js:37:229)
    at eb (http://localhost:3000/bower_components/angular/angular.min.js:40:503)
    at Ac.d (http://localhost:3000/bower_components/angular/angular.min.js:19:339
I have never had this issue before. The ONLY difference between generating this project and the others that I have done is that I (unfortunately) am using a Windows 8 machine right now. However, I have all the necessary prerequisite compilers and packages installed, my PATH (as far as I know) isn't causing any trouble, MongoDB works fine, and so does many other projects (not utilizing Mean.io, but using the MEAN stack) I tested on this machine when I got this error. Any ideas?

**Comment by wixmove** [comment]
Sorry my English is not perfect,
Issue:
Install manually in folder 

dowload https://github.com/asafdav/ng-clip
                https://github.com/zeroclipboard/zeroclipboard
                https://github.com/auth0/angular-jwt

/packages/core/admin/public/assets/ --> Create folder lib and dowload & install ng-clip and zeroclipboard

/packages/core/users/public/assets/ --> Create folder lib and dowload & install angular-jwt

**Comment by VikramTiwari** [comment]
@wixmove's solution works. You can also use bower install in ```/packages/core/admin/``` and ```/packages/core/admin``` folders and ti should work fine.

Though my question to others and @liorkesos is that why we don't have these in the main bower file?
