### ISSUE TITLE
Session timeout not letting the application logout

### ISSUE THREAD

**Issue by shailendramonu** [linnovate/mean#1289]
I have tried to set the sessionCollection, sessionCookie and sessionName in all.js config. 
-------------------- all.js ----------------------------------
  sessionCollection: 'sessions',
  sessionCookie: {
    path: '/',
    httpOnly: true,
    secure: false,
    maxAge: 60000 //90*60*1000 ms
  },
  sessionName: 'connect.sid'

------------------------------------------------------

And, Using Express/Mongo session storage in config

-----------------------express.js-----------------------------------
app.use(session({
    secret: config.sessionSecret,
    resave: false,
    saveUninitialized: true,
    unset: 'destroy',
    store: new mongoStore({
      db: db.connection.db,
      collection: config.sessionCollection
    }),
    cookie: config.sessionCookie,
    name: config.sessionName
  }));

----------------------------------------------------------

I can see the sessions is creating/updating and clearing as per the maxAge set in db and browser but it will not let the application logout/signout after the session expires.

Please look into this as this is very critical. Let me know if I need to implement in another way.

Using Latest mean version
------------------------------------

**Comment by liorkesos** [comment]
Latest mean uses jwt and does not use the session collection in my
opinion...
Lior

**Comment by shailendramonu** [comment]
Yes but the same problem with JWT. No configurable expirations and I don't see it actually expired after certain time. Any idea, How can I implement session logout functionality with JWT?

**Comment by shailendramonu** [comment]
I think current JWT implementation is only to use to sending the payload inside token. No functionality for token expire and verification to send unauthorized response. It would be nice if we will use the same for session timeouts. Thanks...

**Comment by claustres** [comment]
The verific

**Comment by shailendramonu** [comment]
@claustres Exactly what it should be but here we have 2 issues.
1. No configurable expiration time, currently hardcoded to some 5 days something.
2. It won't check for expiration anymore. Still able to call /api/xxxx successfully with same expiry token or new token.

**Comment by claustres** [comment]
Not 5 days but 5 hours. I agree it will be great to make it configurable.

For expiration check it seems it is built-in jwt verification as long you generate a token with this option. It seems to work for me in a web app, but i will check as soon as possible.

**Comment by shailendramonu** [comment]
@claustres Yes, you are right it is 5 hours. 
In the ExpressEngine.js (mean node modules), when protecting the api routes, "credentialsRequired: false" is configured as false. And I think thats why it is not validating but if you remove or change to true (which is default) it start validating everything even static routes like css, js, jpg, html etc. I think there is something missing here for proper authentication cycle.

------------
// We are going to protect /api routes with JWT
  this.app.use('/api', expressJwt({
    secret: config.secret,
    credentialsRequired: false
  }), function(req, res, next) {
      if (req.user) req.user = JSON.parse(decodeURI(req.user));
      next();
  });
------------

Anyway, I was looking this for session timeout so that I can let user to be logout and redirect user to login page but even after timeout I am able to access the restrict api without any problem. I have also changed things to configurable (Expiretime).

**Comment by claustres** [comment]
Indeed you are right, looking at the code of express-jwt I can see that with the `credentialsRequired` option no error is thrown when verification has failed. Can someone from MEANIO tell us if there was any particular reason to activate this option, otherwise it is probably a bug...

**Comment by VikramTiwari** [comment]
As I know this is not a bug in the project as of now. You can reopen this in the `mean-cli` or related project.
