### ISSUE TITLE
Ensure new mean asset aggregation can support a CDN

### ISSUE THREAD

**Issue by dazwin** [linnovate/mean#1293]
In order to support a CDN, the following two things must happen:

- There needs to be some ability to specify a base URL prefix to any static resource assets, such that an element in a development environment might look like this:
```html
    <link rel="stylesheet" href="/theme/assets/css/theme.css">
```

but in a production environment, it would look like this:
```html
    <link rel="stylesheet" href="http://mycdn.com/theme/assets/css/theme.css">
```

Secondly, each time there is a new version of a resource (or aggregate resource), the URL must uniquely identify it's content. This is to avoid CDN resource TTLs resulting a an old version of the resource being delivered to the browser for some time after an upgrade.

_If_ there are only a few resources to deal with, then this could be handled entirely by DevOps, such that the above resource might then become: 
```html
    <link rel="stylesheet" href="http://mycdn.com/[some-unique-tag-eg-a-guid]/theme/assets/css/theme.css">
```

However, with multiple files, this quickly becomes sub-optimal as a new product release would automatically invalidate all static resources, even if they did not actually change (as is often the case for imported libraries). So, a better solution is to append a hash to the end of each resource....
```html
    <link rel="stylesheet" href="http://mycdn.com/theme/assets/css/theme.css@[md5-hash]">
```

This ensures changes to assets result in a change to the URL (effectively invalidating the old version), but resources that did not actually change would get the same hash value (and thus the benefit of probably already being cached).

**Comment by BrockMcKean** [comment]
I do not know enough about CDN's, but after clearing up some confusion about why and how we would implement this, I do think this could be done internally and would be a good idea, I am just not sure when would be the best time to address this. Perhaps with package configuration.

**Comment by liorkesos** [comment]
CDN integration is a must as we scale this to be a serious solution that has the ability to scale...
What we would need is either to have a convention of linking to appRoot + '/themes/theme/assets/css/theme.css' and then having a cdn integration package overide the appRoot variable - another (wierd) alternative would be to use an 'mref' directive instead of href that would do it for us.
