### ISSUE TITLE
favicon is not coming

### ISSUE THREAD

**Issue by shailendramonu** [linnovate/mean#1294]
I just find out that in config/express.js. inside app.use(modRewrite()[...])), forgot to mention ".ico" extension and it cause to not loading favicon on the page. Please fix this. Thanks...

app.use(modRewrite([

    '!^/api/.*|\\_getModules|\\.html|\\.js|\\.css|\\.ico|\\.swf|\\.jp(e?)g|\\.png|\\.gif|\\.svg|\\.eot|\\.ttf|\\.woff|\\.pdf$ / [L]'

  ]));

**Comment by shailendramonu** [comment]
Thanks Vikram...

**Comment by VikramTiwari** [comment]
Thanks for spotting this. @shailendramonu :+1: Always ready to fix things. :)
