### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by zwhitchcox** [linnovate/mean#1296]
Are there any plans for implementing MySQL? If not, how would we want to go about this?

**Comment by liorkesos** [comment]
We where toying with the ability to create a db abstraction and then support multiple databases.
Most interesting project inthis area is waterline by the sails.js team

**Comment by jcsena** [comment]
@zwhitchcox  https://github.com/jcsena/mean-relational support (mysql and etc.. using sequelize ORM)
