### ISSUE TITLE
Why the mean.system module must be created manually?

### ISSUE THREAD

**Issue by lvarayut** [linnovate/mean#1300]
I read in the document. It's written that: `Every package registration automatically creates a corresponding angular module of the form mean.[package-name]`. 

So, the `mean.system` module should have been created automatically. However, I saw that in the `system/public`, there is a system.js file used to create the mean.system module as following:

``` javascript
// system/public/system.js
angular.module('mean.system', ['ui.router', 'mean-factory-interceptor'])
  .run(['$rootScope', function($rootScope) {
    $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
      var toPath = toState.url;
      toPath = toPath.replace(new RegExp('/', 'g'), '');
      toPath = toPath.replace(new RegExp(':', 'g'), '-');
      $rootScope.state = toPath;
      if ($rootScope.state === '') {
        $rootScope.state = 'firstPage';
      }
    });
  }]);
```

The problem is angular dependencies are defined twice, in the `system.js` and `app.js`:

``` javascript
// system/app.js
SystemPackage.angularDependencies(['ui.router', 'mean-factory-interceptor']);
```

My questions are as following:
- Why the `mean.system` must be created manually, any reason behind the scene?
- If I wanted to add more angular dependencies, where should I add them?

**Comment by claustres** [comment]
I guess this is a bug, dependencies should not be given in *system/public/system.js*. Thus, the intention was probably not to create the module but simply add a custom *run()* function. I open a pull on this : https://github.com/linnovate/mean/pull/1318.

Your angular dependencies have to be given like in *system/app.js*.
