### ISSUE TITLE
Header vars are showing not loggedIn after a reload

### ISSUE THREAD

**Issue by pasupulaphani** [linnovate/mean#1304]
1. LogIn -> successlogin
2. Reload the page
3. Observe the nav bar you will see login and singup buttons.
4. Inspect header vars {{hdrctr.hdrvars}} gives u
```
       {"authenticated":false,"user":{},"isAdmin":false}
```
Apparently MeanUser object shows not authenticated.

**Comment by rjVapes** [comment]
What login strategy are you using, and can you replicate it in a fresh install via `mean init`?

**Comment by pasupulaphani** [comment]
passport auth strategy: local

Yes u should be able to replicate with fresh install via "mean init"

**Comment by rjVapes** [comment]
A fresh install works fine for me.  Make sure you're up to date, and have npm installed again once updating to ensure the proper version of mean.io lib.  If the problem still persists, observe your localStorage in your browser as you login in.  Once logged in you should have an entry with a key of 'JWT'.  This is what identifies you as logged in on the front-end, if that value is being destroyed somehow you would be logged out.

**Comment by pasupulaphani** [comment]
I installed using Yoeman. I will update my app tonight and update the ticket as well.

Thank you for your help.

**Comment by rjVapes** [comment]
I was unaware there was a Yeoman generator for mean.io.  Can you link me the one you used?  That could be a source of issues.

**Comment by pasupulaphani** [comment]
Sorry it was not with yoeman.

I used "mean init".

Anyhow I added some mean modules like uploader and video then I started to see the issue. The cookie is fine and I can still identify login session in my custom project. But the header is not fine.

To save you time please use this repo. It is just a mean project with above modules.(no business login)
https://bitbucket.org/ppasupula/realexperts/src

**Comment by rjVapes** [comment]
Your core files don't match up to current mean.io core files, specifically user.  It looks like you have a pre-0.5.0 (JWT) core/users folder.
https://bitbucket.org/ppasupula/realexperts/src/32c5c512553ee5ef7f93d78db096cda85e9cffea/packages/core/users/app.js?at=master
vs.
https://github.com/linnovate/mean/blob/master/packages/core/users/app.js

I couldn't even successfully run your repo via `clone` + `npm install` due to dependency issues.

**Comment by VikramTiwari** [comment]
@pasupulaphani Please update to latest version of MEAN. If the issue still persists, reopen the issue.
