### ISSUE TITLE
Unable to perform controller initialization after redirect from OAuth callback

### ISSUE THREAD

**Issue by dazwin** [linnovate/mean#1311]
This is somewhat involved... steps to reproduce:

- Ensure Twitter OAuth is configured and working (other passport-based authentication will probably have the same behavior)

- Implement a typical angular controller/view/route using the following code to ensure that the controller is initialized properly when the user is logged in:
```
angular.module('mycontroller').controller('MyController', ['$rootScope', 'MeanUser',
    function($rootScope, MeanUser) {
...
        function init() {
            console.log("Initializing...");
        }

        if (MeanUser.loggedin)
            init();
        else
            $rootScope.$on('loggedin', init);
...
};
```

- Use the cookie redirect feature (found in https://github.com/linnovate/mean/blob/master/packages/core/users/public/services/meanUser.js#L66) to route the user to another page after they have authenticated. For example, this could be done by adding a redirect cookie to the authCallback handler (https://github.com/linnovate/mean/blob/master/packages/core/users/server/controllers/users.js#L43) as follows:
```
        res.cookie('redirect', '/myview');
        res.redirect('/');
```

Actual results
- The new init() function is never called. This is because a) MeanUser.logged in is false when the controller is instantiated and b) the 'loggedin' event is emitted before the new controller has been instantiated
- Refreshing the browser page and any other type of $stateProvider navigation calls init() as expected

Expected
- Either the view/controller is instantiated before 'loggedin' event is emitted, or...
- MeanUserKlass does not lose its loggedin status when the view/controller is instantiated

This means there is no apparent way to perform page initialization after the first callback from an OAuth login.

**Comment by dazwin** [comment]
I've confirmed that I get the same MeanUser when the $location.path() happens as when I'm in my new controller, so it appears that MeanUserKlass.loggedin is explicitly getting reset to false somewhere along the process flow.

**Comment by dazwin** [comment]
- The /api/auth/twitter/callback endpoint sets the 'token' cookie
- When MeanUserKlass is constructed, it makes an XHR call to /api/users/me. When this XHR call is made, there is no user object yet.
- The tokenWatch code detects the change in the 'token' cookie as a result of the /callback XHR
- tokenWatch results in a first call to onIdentity and sets up the MeanUserKlass object correctly
- There is now a second call to onIdentity as a result of the /api/users/me getting a response
- Because Express returns a 304 from /api/users/me, the second call to onIdentity gets a null 'response' parameter
- MeanUserKlass.logged in is now set to false
- Initialization continues as per above with incorrect an MeanUserKlass.loggedin value (as well as an empty .user and false .isAdmin)

**Comment by adskjohn** [comment]
https://github.com/linnovate/mean/pull/1275/files  Looks through the meanUser service in this PR.  Ignore all the environment changes, and the landing page customization and try applying the service and controller changes.  It fixes some race conditions and double loading and stuff like that and should ensure a callback doesn't wipe out your user.

**Comment by adskjohn** [comment]
@dazwin The meanUser.js updates have been merged into master.  See what issues remain, tokenwatch no longer exists, and conditions that caused the logged in state to be wiped out have been sorted out (at least some have been, if your testing finds more I'll look into it).

**Comment by dazwin** [comment]
Upgraded mean/meanio and reversed my earlier workaround. Only $rootScope.$on('loggedin', init) is needed now and is fired after the Twitter OAuth callback - it all looks good.

Thanks @adskjohn.
