### ISSUE TITLE
packages/core/users/public/assets/lib/angular-jwt/dist/angular-jwt.min.js not found

### ISSUE THREAD

**Issue by tianyusasori** [linnovate/mean#1313]
Sorry for my poor English

After I run the command 'node server'
some information is printed on the console like this

/packages/core/admin/public/assets/lib/zeroclipboard/dist/ZeroClipboard.js not found
/packages/core/users/public/assets/lib/angular-jwt/dist/angular-jwt.min.js not found
/packages/custom/i18n/public/assets/lib/i18next/i18next.js not found
/packages/core/admin/public/assets/lib/ng-clip/src/ngClip.js not found
/packages/custom/i18n/public/assets/lib/ng-i18next/dist/ng-i18next.js not found

if i visit the url localhost:3000
the server will crash 

I don't know how to fix it .
Thank you

**Comment by VikramTiwari** [comment]
Hey @tianyusasori, easy fix is that you will need to go into ```users``` ```admin``` and ``` i18n``` folders and run ```bower install```

I will check why they were not installed by themselves.

**Comment by tianyusasori** [comment]
@VikramTiwari  
Thanks .
I follow your advice and fix it .but I got a new problem.

when i use broswer visit localhost:3000
I got this in console

Mean app started on port 3000 (development) cluster.worker.id: 0
GET / 200 - - 116.583 ms
GET /i18n/assets/css/i18n.css?v=6c3b7954dae82c325834f065a8b4c5b0 200 48 - 37.716 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '****/bower_components/bootstrap/dist/css/bootstrap.css'

in my workplace .i didn't find the folder named bower_components.
So how to fix this?

Thanks again

**Comment by VikramTiwari** [comment]
Just a sanity check: Have you run ```bower install``` in root folder of your app?

**Comment by tianyusasori** [comment]
@VikramTiwari 

I have fixed it. Thanks

**Comment by piannaf** [comment]
> easy fix is that you will need to go into users admin and i18n folders and run bower install
> 
> I will check why they were not installed by themselves.

@VikramTiwari I had the same problem. It was solved by going into the subfolders and running bower install. 

This is a recently installed mean-cli (npm list is showing mean-cli@0.10.17).

I also did "bower cache clean" and "bower install" at the top level before needing to go into the subfolders.

Not sure if there is a bug or if the docs need to be updated.

**Comment by VikramTiwari** [comment]
@piannaf When you init a MEAN app, and do NPM install, bower dependencies are supposed to be installed by `npm postinstall` script. In itself, it should run without any hiccups. The reason at times it breaks could be cause of some issue prior to execution of the script at `tools/scripts/postinstall.js`.

Since those issues are mostly network based, i.e. timeout while fetching the dependencies, and they can occur randomly, there is currently no fix for that.

We are looking for possibly removing bower as package manager and using just NPM for all dependencies, but those changes are still in discussions. Expect some solution soon. :)

**Comment by piannaf** [comment]
@VikramTiwari Thanks for the info. I have had networking hiccups lately so that must be the issue. Just using npm would definitely simplify things. Cheers!
