### ISSUE TITLE
which MEAN version is the most adapted to my needs

### ISSUE THREAD

**Issue by sarahl123** [linnovate/mean#1315]
Hi

We have used MEAN to create a catalog website and we were really happy and satisfied by MEAN which perfectly matched our needs. Thank you!
We need to create a new website and wondered if we could use the old MEAN version(i don't know which version number it is but it was 2 years ago) or if we should use the new one (which seems must heavier, looking more like a CMS, might be too big for our needs).
In a few words our website needs 
- login + user info
- display content with angularjs
- all data coming from api

Please advise
Regards
Sarah

**Comment by shailendramonu** [comment]
@sarahl123 There is no support for old versions below 0.5.x. You can still
use any version as per your need. Newer version have much stability and
configurable options.

On Thursday, 20 August 2015, sarahl123 <notifications@github.com> wrote:

> Hi
>
> We have used MEAN to create a catalog website and we were really happy and
> satisfied by MEAN which perfectly matched our needs. Thank you!
> We need to create a new website and wondered if we could use the old MEAN
> version(i don't know which version number it is but it was 2 years ago) or
> if we should use the new one (which seems must heavier, looking more like a
> CMS, might be too big for our needs).
> In a few words our website needs
>
>    - login + user info
>    - display content with angularjs
>    - all data coming from api
>
> Please advise
> Regards
> Sarah
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1315>.
>


-- 
Thanks & Regards,
Shailendra Singh

**Comment by VikramTiwari** [comment]
@sarahl123 Please ask generic and use case based questions in the gitter channel (https://gitter.im/linnovate/mean). Thanks!
