### ISSUE TITLE
Mean admin installation breaks all

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1317]
On linux:

1/ installed last mean version -> everything is ok.
2/ installed "mean install mean-admin" -> white page with error: 

```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.4/$injector/modulerr?p0=mean&p1=Error%3A%20…angular%2Fangular.min.js%3Fv%3Dfeeb76d0de3487eb412c1928625e8fca%3A19%3A381)
```

3/ uninstall admin -> works again...

How come?

**Comment by arnason** [comment]
Confirm same issue on OS X.

**Comment by HintikkaKimmo** [comment]
Same here. I did not even realize this was an angular error log just seem to be pulling some local asset forever. After uninstalling the package everything works again.

**Comment by VikramTiwari** [comment]
Ah! Seems like you guys are overwriting the core admin package when you are installing `mean-admin` package. `mean-admin` is now in the core packages and comes with scaffolded app. If you want to use functionality for package, you can use it by creating an admin user and logging with it in the scaffolded app itself.
