### ISSUE TITLE
How to override 'home' state from system package in custom package

### ISSUE THREAD

**Issue by ghost** [linnovate/mean#1320]
$viewPathProvider allows us to override the views but I searched through the documentation and even the issues, but couldn't find a way to override the 'state'.

My scenario is such that I want my view to be seen only when the user has 'logged in', I can use this resolve function - 
resolve: {
          loggedin: function(MeanUser) {
            return MeanUser.checkLoggedin();
          }
        }
to my state, which also gets invoked on default route - '/'. 

Now two solutions can work in my scenario:
1. If I can override the entire state itself 
2. If I can reorder the packages so that my custom package's routes runs before system's, in that case my custom package's route will execute first and thus it will run the resolve function and I will go home happy :)

Thanks in anticipation.

**Comment by claustres** [comment]
I used to manage this by making the home page display different information depending on the authentication state, something like this :
```html
...
<p class="alert alert-info" data-ng-hide="hdrctr.hdrvars.authenticated">
First, you have to <a href="/#!/auth/login">login</a> or <a href="/#!/auth/register">register</a>.
</p>

<p class="alert alert-info" data-ng-show="hdrctr.hdrvars.authenticated">
As you are already logged in, you have experienced user authentication.
</p>
...
```
