### ISSUE TITLE
Angular Module Dependency issue problem

### ISSUE THREAD

**Issue by hbzhang** [linnovate/mean#1337]
I have developed several packages using Mean for my project. I want to move it to the current mean release. 

However I found out that Mean team has changed how angular Module dependency works. In the before, under package public folder, there is a JS file with same name as the customized package. I just put all my dependency there, and it works. However, for the current mean release, under public folder of the package, that js file is gone. Where I should put the angular dependencies? I really like that js file, it is very handy!

For example, I have something like this in the before:

'use strict';

angular.module('mean.product', [
    'angular.filter',
    'angular-loading-bar',
    'angularFileUpload',
    'angularModalService',
    'ngSanitize',
    'ngAnimate',
    'ngClipboard',
    'toaster',
    'ui.bootstrap',
    'ui.router',
    'ui.calendar',
    'ui.grid',
    'slidepanelcontent',
    'focusOn',
    'gridster',
    'pageslide-directive',
    'fundoo.services',
    'builder',
    'builder.components',
    'event',
    'registration',
    'eventformbuilderhelper',
    'wizard',
    'textAngular',
    'restangular'
]);

**Comment by claustres** [comment]
This is not the way to manage module dependencies with MEAN.IO, either in previous releases : https://github.com/linnovate/mean#angular-modules-and-dependencies

**Comment by hbzhang** [comment]
I understand this is not the official way doing dependency management. However it works for previous release. For the current release, I just tested it. The dependency management seems not working well, 

I included several modules in global bowercomponents, and the dependency management is not able to inject some of those angular modules.  For previous mean release, the same modules in the  global bowercomponents can be easily injected into mean using both official way and the way I just presented.

**Comment by claustres** [comment]
The problem is that you will have a double declaration of your 'mean.product', one by MEAN.IO and one by you. Anyway, if some dependencies were not injected this is not normal, check that you have included the right files on your page : external angular modules + their own dependencies. Check as well you have declare the angular dependencies in your `app.js`.

**Comment by hbzhang** [comment]
I have tested it more carefully for the current release. For example, for theme module, this will not pass

Theme.angularDependencies([
    'mean.users',
    'mean.system'
    ]);

This however pass

  Theme.angularDependencies([
    'mean.system'
    ]);

This simple example did not inject customized angular module. It just injects the mean internal module and it can not pass the test.  Except I am doing something wrong here, so my initial conclusion is that the current release of Mean has some problem of this.

**Comment by hbzhang** [comment]
I need to test more for the current release, it seems there are a lot of changes compared to the previous release....

**Comment by VikramTiwari** [comment]
@hbzhang If this is still an issue for you, please reopen.
