### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by hbzhang** [linnovate/mean#1339]
MEAN has thrown this error. Any idea?

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by hbzhang** [comment]
This error is appeared during startup phase of mean. This is whole trace.

--------
Running "clean:0" (clean) task

Running "jshint:all" (jshint) task
>> 61 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "nodemon:dev" (nodemon) task
[nodemon] v1.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
Debugger listening on port 5858
js-bson: Failed to load c++ bson extension, using pure JS version
Mean app started on port 3000 (development)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
[nodemon] app crashed - waiting for file changes before starting...
Running "watch" task
Waiting...

**Comment by claustres** [comment]
Your network config might be invalid because it seems it cannot simply reach the host. Did you change any of the mean.io config files ? Otherwise ping localhost and see if it's OK then make sure mongo is listening and bound to the localhost interface.

**Comment by hbzhang** [comment]
Thanks for the reply, localhost is pingable.  I can double check other files. But I did not change much configurations.

**Comment by adskjohn** [comment]
Are there any potential network/policy limitation on the network/domain you're running from?

**Comment by VikramTiwari** [comment]
@hbzhang If this is still an issue for you, please reopen.
