### ISSUE TITLE
Time line for support of Node's latest version(s)

### ISSUE THREAD

**Issue by xiaoyang2022** [linnovate/mean#1345]
node4.0 ,will be support？how times?

**Comment by VikramTiwari** [comment]
@xiaoyang2022 Questions like this should be asked in gitter chatroom. Please join us there. https://gitter.im/linnovate/mean

**Comment by timelf123** [comment]
Node 4.X and 5.X should be supported. You may have to install some peerDependencies as a result of npm no longer resolving them, but we can work through those as they come up

**Comment by liorkesos** [comment]
+1
Hope to work on it soonish...

On Fri, Jan 15, 2016 at 6:14 AM, Tim Elfelt <notifications@github.com>
wrote:

> Node 4.X and 5.X should be supported. You may have to install some
> peerDependencies as a result of npm no longer resolving them, but we can
> work through those as they come up
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1345#issuecomment-171867900>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by VikramTiwari** [comment]
Wait! Our travis build file includes build mechanisms for 4.x (stable) and 5.x (latest) branches. It builds and test cases do pass all the time. Doesn't this means that we are already working fine on newer node versions?

Travis file: https://github.com/linnovate/mean/blob/master/.travis.yml

**Comment by clowenhg** [comment]
It's a good sign, however, the tests are not that extensive.
Given the concepts we've discussed for getting Mean to 1.0, I've held off working on tests until that starts to settle more.

That being said, we've been using Node 4.2.x LTS with the bundled npm (2.3.x) I think, for several weeks now without much issue. And I've been working in meanio and mean with Node 5 and npm 3 as well.

**Comment by liorkesos** [comment]
I've been worm ng with node 4 with several client applications.
We might want to clean up some warnings where some packages require
"engine" 0.10 or 0.12
Lior
