### ISSUE TITLE
What is the use of these two modules？circles and swagger

### ISSUE THREAD

**Issue by xiaoyang2022** [linnovate/mean#1346]
What is the use of these two modules？circles and swagger

 i loss!

**Comment by liorkesos** [comment]
*swagger* is swagger.io support - api documentation
*circles* is infrastructured for user permissions and acl (hopefully we can
send some examples soon)
Lior

On Wed, Sep 16, 2015 at 12:50 PM, 密西西比河 <notifications@github.com> wrote:

> What is the use of these two modules？circles and swagger
>
> i loss!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1346>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by ADSKLowenthal** [comment]
@xiaoyang2022 I'd recommend joining us in Gitter: https://gitter.im/linnovate/mean for any questions you may have. It's better setup than github issues for answering questions like these.

**Comment by xiaoyang2022** [comment]
how to use this package?if you giving some teaching,i hopeful!

**Comment by xiaoyang2022** [comment]
Roles ，What is dry？circles？What is the difference?

**Comment by AngryDonny** [comment]
Is there any documents for circles and swagger now? I m stuck on it.

**Comment by timelf123** [comment]
https://github.com/linnovate/mean/wiki/Circles for circles is the best I've found.

The best documentation for Swagger is in the [package itself](https://github.com/linnovate/mean/tree/master/packages/core/swagger)

## Basic Swagger process:
- create a docs directory like so


docs/
> [models.js](https://github.com/linnovate/mean/blob/master/packages/core/articles/docs/models.js)
>  [services.js](https://github.com/linnovate/mean/blob/master/packages/core/articles/docs/services.js)


- inject swagger and add your doc folder

```
Articles.register(function(app, auth, database, circles, swagger) {
...
  // Only use swagger.add if /docs and the corresponding files exists
  swagger.add(__dirname);
```
