### ISSUE TITLE
CSS and JS is not getting aggregated in production env

### ISSUE THREAD

**Issue by gauravscorpsgit** [linnovate/mean#1350]
I have worked on webapp throughout on development mode and it works perfectly, while deploying in production environment I am facing this issue where aggregated.css and js is missing in the modules folder.

Kindly assist as I have no clue how to debug this issue.

**Comment by claustres** [comment]
I think these files are generated on the server side and should not be on the disk, but you can see them in the browser debugger. You should only have something in `bower_components\build` on the disk, which is all your dependencies from the `assets.json` file but minified.

Please provide more information (error messages, logs, etc.).

**Comment by VikramTiwari** [comment]
Closing since this is not an issue in the latest build. Reopen with more details (error messages/logs) on your end @gauravscorpsgit. Thanks.
