### ISSUE TITLE
Custom package - ng:areq

### ISSUE THREAD

**Issue by marianiku** [linnovate/mean#1351]
Hi, 

Just started looking around Mean.io, so far enjoying it a great deal. Attempting to test a simple app listing the contents of a mongodb collection on a web page, I initiated an app with 'mean init', created a custom package with 'mean package ...', then basically copied the files of the example package 'articles', editing the model schema attributes and renaming things according to my needs. Whereas the articles package works without issue, I am getting the angular side error of ng:areq, controller is not a function when accessing the list page or attempting to add new content via the form I create. Should a custom package created with such a method of copying and editing work 'out of the box', or is something extra (such as db connection definitions in the model) needed on the custom package side?

**Comment by VikramTiwari** [comment]
@marianiku Need more details.
