### ISSUE TITLE
OSX npm install failed

### ISSUE THREAD

**Issue by fox91** [linnovate/mean#1353]
I'm newbie with mean stack.
I'm using OSX 10.10.
I used this commands:
```bash
brew install git node mongodb

npm install -g gulp
npm install -g grunt-cli
npm install -g bower

npm install -g mean-cli

cd /tmp
mean init yourNewApp
cd yourNewApp && npm install
```
`npm install` ends with this error message:
```
npm WARN EPACKAGEJSON mean@0.5.5 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/yourNewApp/npm-debug.log
```
How can I fix this error?

**Comment by pyrextor** [comment]
Have you downloaded Xcode and accepted the license? This may be the reason

**Comment by fox91** [comment]
@pyrextor yes, I'm not newbie with OSX ;)
Now I'm using OSX 10.11.1, just I find some time I try with this version.

**Comment by nathanielltaylor** [comment]
I'm having this same issue right now, were you able to find a solution?

**Comment by VikramTiwari** [comment]
@fox91 did you tried running `npm install` again. Also this might be totally due to latest version of Node.

**Comment by fox91** [comment]
@VikramTiwari I've uninstalled and cleaned npm and bower.
I've also updated OSX and Xcode.
Now everything works properly, but I can not say what that was causing problems.

**Comment by VikramTiwari** [comment]
At times there is in-complete cache data which have caused similar problems on my end as well. Best practice I follow is to clean your cache after each installation so that next installation is always clean.
