### ISSUE TITLE
install mean-cli failed (warning with json-file-plus and ENOENT)

### ISSUE THREAD

**Issue by RichardWuTry** [linnovate/mean#1355]
I'm newbie with mean stack.
I'm using OSX 10.10.5
node version: v4.0.0
npm version: 3.3.5

I entered command "sudo npm install -g mean-cli", and got following results. 

npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be propagated
npm WARN lifecycle mean-cli@0.10.14~preinstall: cannot run in wd %s %s (wd=%s) mean-cli@0.10.14 node ./scripts/preinstall /usr/local/lib/node_modules/.staging/mean-cli-2db3416b5b1ebe281952b19cb09e6e2f
npm WARN install:lru-cache ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/bower-registry-client/node_modules/lru-cache' -> '/usr/local/lib/node_modules/mean-cli/node_modules/bower-registry-client/node_modules/lru-cache'
npm WARN install:mkdirp ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/bower-registry-client/node_modules/mkdirp' -> '/usr/local/lib/node_modules/mean-cli/node_modules/bower-registry-client/node_modules/mkdirp'
npm WARN install:rimraf ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/bower-registry-client/node_modules/rimraf' -> '/usr/local/lib/node_modules/mean-cli/node_modules/bower-registry-client/node_modules/rimraf'
npm WARN install:object-assign ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/configstore/node_modules/object-assign' -> '/usr/local/lib/node_modules/mean-cli/node_modules/got/node_modules/object-assign'
npm WARN install:async ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/async' -> '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/async'
npm WARN install:chalk ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/chalk' -> '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/chalk'
npm WARN install:graceful-fs ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/graceful-fs' -> '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/graceful-fs'
npm WARN install:lodash ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/lodash' -> '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/lodash'
npm WARN install:mute-stream ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/mute-stream' -> '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/mute-stream'
npm WARN install:object-assign ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/object-assign' -> '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/object-assign'
npm WARN install:xdg-basedir ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/xdg-basedir' -> '/usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/xdg-basedir'
npm WARN install:graceful-fs ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/mean-cli/node_modules/tar-pack/node_modules/fstream/node_modules/graceful-fs' -> '/usr/local/lib/node_modules/mean-cli/node_modules/tar-pack/node_modules/fstream/node_modules/graceful-fs'
lru-cache@2.3.1 node_modules/mean-cli/node_modules/bower-registry-client/node_modules/lru-cache -> node_modules/mean-cli/node_modules/bower-registry-client/node_modules/lru-cache
mkdirp@0.3.5 node_modules/mean-cli/node_modules/bower-registry-client/node_modules/mkdirp -> node_modules/mean-cli/node_modules/bower-registry-client/node_modules/mkdirp
rimraf@2.2.8 node_modules/mean-cli/node_modules/bower-registry-client/node_modules/rimraf -> node_modules/mean-cli/node_modules/bower-registry-client/node_modules/rimraf
osenv@0.1.3 node_modules/mean-cli/node_modules/insight/node_modules/osenv -> node_modules/mean-cli/node_modules/configstore/node_modules/osenv
form-data@0.2.0 node_modules/mean-cli/node_modules/bower/node_modules/request/node_modules/form-data -> node_modules/mean-cli/node_modules/form-data
request@2.51.0 node_modules/mean-cli/node_modules/bower/node_modules/bower-registry-client/node_modules/request -> node_modules/mean-cli/node_modules/bower-registry-client/node_modules/request
bower-registry-client@0.3.0 node_modules/mean-cli/node_modules/bower/node_modules/bower-registry-client -> node_modules/mean-cli/node_modules/bower-registry-client
object-assign@3.0.0 node_modules/mean-cli/node_modules/insight/node_modules/configstore/node_modules/object-assign -> node_modules/mean-cli/node_modules/got/node_modules/object-assign
async@1.4.2 node_modules/mean-cli/node_modules/insight/node_modules/async -> node_modules/mean-cli/node_modules/insight/node_modules/async
chalk@1.1.1 node_modules/mean-cli/node_modules/insight/node_modules/chalk -> node_modules/mean-cli/node_modules/insight/node_modules/chalk
graceful-fs@4.1.2 node_modules/mean-cli/node_modules/insight/node_modules/graceful-fs -> node_modules/mean-cli/node_modules/insight/node_modules/graceful-fs
lodash@3.10.1 node_modules/mean-cli/node_modules/insight/node_modules/lodash -> node_modules/mean-cli/node_modules/insight/node_modules/lodash
mute-stream@0.0.5 node_modules/mean-cli/node_modules/insight/node_modules/mute-stream -> node_modules/mean-cli/node_modules/insight/node_modules/mute-stream
object-assign@4.0.1 node_modules/mean-cli/node_modules/insight/node_modules/object-assign -> node_modules/mean-cli/node_modules/insight/node_modules/object-assign
readline2@1.0.1 node_modules/mean-cli/node_modules/insight/node_modules/readline2 -> node_modules/mean-cli/node_modules/insight/node_modules/readline2
inquirer@0.10.1 node_modules/mean-cli/node_modules/insight/node_modules/inquirer -> node_modules/mean-cli/node_modules/insight/node_modules/inquirer
xdg-basedir@2.0.0 node_modules/mean-cli/node_modules/insight/node_modules/xdg-basedir -> node_modules/mean-cli/node_modules/insight/node_modules/xdg-basedir
graceful-fs@3.0.8 node_modules/mean-cli/node_modules/tar-pack/node_modules/fstream/node_modules/graceful-fs -> node_modules/mean-cli/node_modules/tar-pack/node_modules/fstream/node_modules/graceful-fs
write-file-atomic@1.1.3 node_modules/mean-cli/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/write-file-atomic -> node_modules/mean-cli/node_modules/write-file-atomic
configstore@1.2.1 node_modules/mean-cli/node_modules/bower/node_modules/insight/node_modules/configstore -> node_modules/mean-cli/node_modules/insight/node_modules/configstore
insight@0.7.0 node_modules/mean-cli/node_modules/bower/node_modules/insight -> node_modules/mean-cli/node_modules/insight
- /usr/local/lib/node_modules/mean-cli/node_modules/tar-pack/node_modules/fstream node_modules/mean-cli/node_modules/tar-pack/node_modules/fstream
- /usr/local/lib/node_modules/mean-cli/node_modules/write-file-atomic node_modules/mean-cli/node_modules/write-file-atomic
- /usr/local/lib/node_modules/mean-cli/node_modules/insight/node_modules/configstore node_modules/mean-cli/node_modules/insight/node_modules/configstore
/usr/local/lib
└── (empty)

npm ERR! code 1

**Comment by Lewiscowles1986** [comment]
I think this is linked to https://github.com/linnovate/mean/issues/1341
