### ISSUE TITLE
This webpage is not available,  ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by alexliubj** [linnovate/mean#1357]
Npm install without errors, it works well on my Mac but after deployed to Ubuntu it doesn't work and showing the error in chrome : 

This webpage is not available

ERR_CONNECTION_REFUSED

Any help?

**Comment by claustres** [comment]
Please provide more information (your config, error messages, complete logs, ...).

**Comment by alexliubj** [comment]
resolved by set node add from local host to 0.0.0.0 with port.
