### ISSUE TITLE
Can't find variable angular

### ISSUE THREAD

**Issue by davidcm86** [linnovate/mean#1359]
Hello,

When I run npm test, i recivied a error

PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /var/www/salarios/packages/core/system/public/system.js:3

Does anybody know something about this?

**Comment by VikramTiwari** [comment]
Seems like PhantomJS installation on your machine failed. Can you re-install and run the tests again. Haven't seen this as an issue since long time. Also provide details regarding your machine and node, npm and mean versions. Thanks.
