### ISSUE TITLE
User is not authorized

### ISSUE THREAD

**Issue by anu-priya** [linnovate/mean#1365]
I am new to MEAN  and I am trying to create Article using API but I am getting "User is not authorized". 
Kindly provide a sample json format for Article creation.
Thanks In Advance.

**Comment by xiaoyang2022** [comment]
this problem i have,too

**Comment by claustres** [comment]
How do you do that, through a front-end service ? Using HTTP requests ? In this last case you need to understand how JWT works. I wrote an article about doing that with the POSTMAN extension of Chrome : https://github.com/claustres/meanio-tutorial-2 (unfortunately it's in French but give it a try with Google Translate).

**Comment by anu-priya** [comment]
Thanks Claustres, Your Article helped me to fix this issue.

I passed Authorization in Header with Basic Header.
