### ISSUE TITLE
"mean init" not working (gives error connecting to database) (OSX)

### ISSUE THREAD

**Issue by MrFlash67** [linnovate/mean#1370]
I'm trying to run mean init on OSX 10.11.1 but, after I've run the admin user help thing, it gives me a Mongo error:
```Error Connecting to database: { [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONNREFUSED' }```
I've got all the components installed. I've got a full log on Pastbin http://pastebin.com/rvp8P8Bb

Am I doing something wrong or is it MEAN?

**Comment by AraanBranco** [comment]
You mongod is runnig?

**Comment by shailendramonu** [comment]
Start your mongo server before init

Thanks
Shailendra

**Comment by MrFlash67** [comment]
Yeah, that was the problem.
Thanks!
