### ISSUE TITLE
Latest Angular Bootstrap UI deprecated names

### ISSUE THREAD

**Issue by ADSKLowenthal** [linnovate/mean#1373]
`angular-bootstrap-ui` has added the `uib-` prefix requirement.

Mean's bower.json will load the latest, which should still work, but it will produce warnings about the deprecation.

Not sure when the naming will be removed.  And worried that updating Mean core code right now may break projects that rely on it, but aren't updating/updated to the latest.

At the very least `packages\core\system\public\views\header.html` is using the `dropdown` directive.

**Comment by JrPribs** [comment]
@VikramTiwari It looks like there is some other directives being used that need to be updated. Looks like just the tooltip directives. Ill have another PR in shortly
