### ISSUE TITLE
req.acl.query not always available

### ISSUE THREAD

**Issue by tcg123** [linnovate/mean#1381]
My problem is this,I create a package named "databases",when I use the order of "node server" to start my App,it runs ok,when I use "gulp" for my application,It will have an error 500:GET http://localhost:3000/api/databases 500 (Internal Server Error),
detail:
   TypeError: Cannot read property 'query' of undefined
    at module.exports.Databases.all

**Comment by claustres** [comment]
It seems to be an internal error in your code (Databases module), you are trying to access the query property of probably the request that is undefined, please try to debug to see what's happening, IMHO it is not related to MEAN.io.

**Comment by VikramTiwari** [comment]
@tcg123 Use [articles package](https://github.com/linnovate/mean/tree/master/packages/core/articles) as reference for debugging into your package.

**Comment by luckylucky** [comment]
I have same trouble. Here is my screenshot http://prntscr.com/9uwt1s
Article package work correctly, but my packages not always work. Some times work, some times not work. In my code I made some magic and I don't find.
I just copy Articles packages code and rename variables.

Where I should looking for resovle this trouble?

**Comment by luckylucky** [comment]
Create! I am resolve this trouble. 

If you copy code from Artcils and you get this error, it means you don't do this in angular controller 

    Circles.mine(function(acl) {
        $scope.availableCircles = acl.allowed;
        $scope.allDescendants = acl.descendants;
    });

**Comment by luckylucky** [comment]
I got this error again. I do not know why. Most likely due to the fact that I've added a new role

**Comment by luckylucky** [comment]
Who can explain why? :)

**Comment by timelf123** [comment]
I have this issue too where sometimes req.query.acl is not available
