### ISSUE TITLE
getting issues in production mode with latest version

### ISSUE THREAD

**Issue by sd031** [linnovate/mean#1400]
In development application running properly , but in production mode application not loading javascript's properly and page not loading. Can anyone help out  , what can I do to make it work ?

**Comment by VikramTiwari** [comment]
@sd031 Can you provide more details?

  1. OS name and version
  2. NodeJS and NPM version : Output of `node -v` and `npm -v`
  3. MEAN Status : Output of `mean status` in project directory
  4. Trace Log : The error that got printed on the console

**Comment by VikramTiwari** [comment]
If you are still facing this, please reopen the issue.
