### ISSUE TITLE
SASS support with gulp-sass

### ISSUE THREAD

**Issue by timelf123** [linnovate/mean#1410]
With `gulp-sass` no ruby is needed - `gulp-sass -> node-sass> libsass`

This package https://github.com/AlmogBaku/mean-compass from 2014 uses the old Grunt build setup and `grunt-hook`. As far as I know there isn't an alternative plugin to hook gulp tasks (not saying it's not possible to create one) so the alternative is adding a gulp task directly to `Gulpfile.js`

**Comment by stonelasley** [comment]
This should be able to be closed now. I should have added this in my commit message. 

https://github.com/linnovate/mean/pull/1436

**Comment by timelf123** [comment]
Thanks @stonelasley
