### ISSUE TITLE
npm install fails on CentOS7 with Node v4.2.2

### ISSUE THREAD

**Issue by blyssy** [linnovate/mean#1417]
Installed CentOS7 and installed node v4.2.2 from source.  Pulled the latest version of mean.  Ran npm install and it is failing at circles.  Looks like its looking at the wrong directory (packages/contrib).

Installing module: circles:
git clone --branch master https://git.mean.io/ellman/circles.git packages/contrib/circles
Installing module: circles:
shell.js: internal error
Error: ENOENT: no such file or directory, lstat 'packages/contrib/circles/.git/config.lock'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at rmdirSyncRecursive (/home/blyssy/PTS055/node_modules/shelljs/src/rm.js:20:23)
    at rmdirSyncRecursive (/home/blyssy/PTS055/node_modules/shelljs/src/rm.js:23:7)
    at /home/blyssy/PTS055/node_modules/shelljs/src/rm.js:159:7
    at Array.forEach (native)
    at Object._rm (/home/blyssy/PTS055/node_modules/shelljs/src/rm.js:123:9)
    at Object.rm (/home/blyssy/PTS055/node_modules/shelljs/src/common.js:186:23)
    at /home/blyssy/PTS055/tools/scripts/postinstall.js:53:15
    at Request._callback (/home/blyssy/PTS055/tools/scripts/postinstall.js:18:28)

npm ERR! Linux 3.10.0-229.20.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! mean@0.5.5 postinstall: `node tools/scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean@0.5.5 postinstall script 'node tools/scripts/postinstall.js'.
npm ERR! This is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/blyssy/PTS055/npm-debug.log
[blyssy@localhost PTS055]$ Username for 'https://git.mean.io': https
bash: https: command not found...

**Comment by rjVapes** [comment]
@blyssy I think this is resolved by https://github.com/linnovate/mean/pull/1418
