### ISSUE TITLE
 [nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by Mkveera1993** [linnovate/mean#1422]
![node](https://cloud.githubusercontent.com/assets/16030209/11841185/92e4ec76-a421-11e5-96ad-46a653a1330c.JPG)
   when i try to run my project using GULP   ,
the above error is appered ....
What to do ?

**Comment by claustres** [comment]
It seems that you did not setup your routes correctly, please check the articles module as an exemple.
