### ISSUE TITLE
mean.io’s configurations

### ISSUE THREAD

**Issue by VikramTiwari** [linnovate/mean#1423]
`A query i got in mail`
I’m new to mean.io and I have a question for the mean.io’s configurations.
 
I have changed the app.name to “Hey” in the `config/env/development.js`. And when view the home page in the browser, the title of the page shows as “Hey – Hey”. I found that there is a line `<title> {{appName}} - {{title}} </title>` in the `packages\core\system\server\views\includes\head.html`, so I think `{{title}}` has been assigned the same value of `{{appName}}`.
 
I have tried to find how I can set `{{appName}}` and `{{title}}`, but there is no code assigning the values to them directly. So, my questions:

1. Where do these two values come from? Angular model values or Swig arguments?
2. How can I change the values of them? Especially for `{{title}}`.
3. Can I add custom variables like these two? If yes, how?

**Comment by sawino** [comment]
Thanks for posting this issue for me, Vikram.

I have found the answer by myself. Here is the answer. Basically, this is an express.js rule that I didn't know.

1. Express.js uses res.locals in the route to pass the values to a render engine, which is Swig in mean.io case. http://stackoverflow.com/questions/24072333/difference-between-assigning-to-res-and-res-locals-in-node-js-express 
2. Mean.io package calls app.use(helpers(config.app.name)); in config/express.js. And the function helpers is a middleware which assigns res.locals.title with the argument config.app.name,. This function is defined in YourAppRoot\node_modules\view-helpers\index.js.
3. When rendering the pages, the core package system uses the "title" value in the server/views/include/head.html.

**Comment by VikramTiwari** [comment]
@sawino Nice! :)
