### ISSUE TITLE
Google Auth Call back generates error - The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by mmumshad** [linnovate/mean#1424]
When logging in using the Google Auth provider, and the user is redirected to the landing page, the below decode error is generated. On refreshing the page it goes away:

```
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Error (native)
    at b64_to_utf8 (http://localhost:3000/users/services/meanUser.js?v=5556b11e12abb8f9000722c0a1e74d23:18:47)
    at MeanUserKlass.onIdentity (http://localhost:3000/users/services/meanUser.js?v=5556b11e12abb8f9000722c0a1e74d23:72:33)
```

**Comment by mmumshad** [comment]
I did some more troubleshooting and it looks like the jwt.sign call places an underscore in the encoded token instead of a forward slash:
How it is:
```
... 1TS9waG90by5qcGc_c3o9NTAlMjIsJT ...
```

How it should have been:
```
... 1TS9waG90by5qcGc\c3o9NTAlMjIsJT ...
```

Any ideas?

**Comment by anandi2i** [comment]
Iam also facing the same issue with Google Oauth...Any help ?

**Comment by mmumshad** [comment]
There is a section of commented code in core/users/public/services/meanUser.js. I had to uncomment the function and call it :+1: 
function url_base64_decode(str) {
      var output = str.replace('-', '+').replace('_', '/');
      switch (output.length % 4) {
      case 0:
      break;
      case 2:
      output += '==';
      break;
      case 3:
      output += '=';
      break;
      default:
      throw 'Illegal base64url string!';
      }
      //return window.atob(output); //polifyll https://github.com/davidchambers/Base64.js
      return output
    }


MeanUserKlass.prototype.onIdentity = function(response) {
...
        try{
            encodedUser = decodeURI(b64_to_utf8(url_base64_decode(response.token.split('.')[1])));
            //encodedUser = decodeURI(b64_to_utf8(response.token.split('.')[1]));
            user = JSON.parse(encodedUser);
        }catch(e){
            console.log("Error decoding User URI");
        }
      }
....
}

**Comment by arung-ideas2it** [comment]
@mmumshad Thanks a lot....It's working fine...Is this merged with MEAN latest  ?

**Comment by timelf123** [comment]
Do the other providers still work with this change? Seems it was introduced with https://github.com/linnovate/mean/commit/d0ad83925a6b810bd9022f0ad3b143fa77a71b5c
