### ISSUE TITLE
What does the admin user mean in MEAN full stack ?

### ISSUE THREAD

**Issue by Erichain** [linnovate/mean#1425]
when I use `mean init`, then it will show this:

`Before you install the dependencies and fire up the server we can help you with setting up your first admin user.`

so, what does the admin user mean? what can I do with it?

and there are an output shows `Register to the mean network`

then, what is the `mean network`?

**Comment by VikramTiwari** [comment]
@Erichain I hope you have tested assigning a user as `admin` and see what are the changes you see in view. Here's a quick read for those who have stumbled across this:

`admin` user has capability for following:
- Modules list: List all the available modules and ability to enable/disable them on the fly
- Bootswatch themes support:  Change themes based upon boostwatch templates
- App Settings: Change various variables which are part of the app
- User Management: Manage users and their permissions

So when you register a user as admin, you get the ability to view options for these when you log in with that user. You should be able to a light blue left bar.

In short admin user can change the view and behaviour of MEAN app from just the admin console.

==

`Register to MEAN network` is for those who want to contribute in MEAN by building custom packages. Linnovate provides the git hosting for those projects and you can put up your projects there for others to use. The registration is CLI based signup to git and MEAN app hosted on mean network.

MEAN network in itself is a place where you can connect your test and production apps to monitor logs etc. I do not have enough understanding about what are the features that they can offer, but I am expecting monitoring, easy error diagnostics etc.

==
If you have any follow up questions, feel free to ask. And give it all a try. If there's a login, there's always a logout. :)

**Comment by Erichain** [comment]
@VikramTiwari  Thanks for your answer, thanks very much! I think I have understood the meaning of that.  :)
