### ISSUE TITLE
'MEAN-ADMIN' package - exeption

### ISSUE THREAD

**Issue by amirmog** [linnovate/mean#1426]
There seems to be some angular injection issues with  the MEAN-ADMIN package.
installed the 'MEAN-ADMIN' package, and re-run the app

Getting this exception:
```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=mean&p1=Error%3A%20…angular%2Fangular.min.js%3Fv%3D90fb950dbc3e9296755d9cc23a211744%3A19%3A463)
```

Any ideas?

Thanks.

**Comment by liorkesos** [comment]
mean-admin is depracted, the admin package is part of core these days
Lior

On Sat, Dec 19, 2015 at 9:15 PM, Amir Mog <notifications@github.com> wrote:

> There seems to be some angular injection issues with the MEAN-ADMIN
> package.
> installed the 'MEAN-ADMIN' package, and re-run the app
>
> Getting this exception:
>
> Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=mean&p1=Error%3A%20…angular%2Fangular.min.js%3Fv%3D90fb950dbc3e9296755d9cc23a211744%3A19%3A463)
>
> Any ideas?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1426>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by amirmog** [comment]
ok great. thanks.
And an off topic question, where should issues with the 'Stripe' package be posted?

Cheers

**Comment by VikramTiwari** [comment]
@amirmog Stripe package is delivered from here: https://git.mean.io/ellman/stripe

**Comment by estock** [comment]
so what is the correct way to fix this error?
