### ISSUE TITLE
Unified dependency management

### ISSUE THREAD

**Issue by claustres** [linnovate/mean#1429]
Detailed here : https://github.com/linnovate/mean/wiki/RC1.0-Core-Packages#unified-dependency-management.

Related to : https://github.com/linnovate/mean/issues/1130.

**Comment by timelf123** [comment]
Nice work on fleshing this out. This will be a great addition to mean.io!

**Comment by timelf123** [comment]
As a stopgap until we have bundling with browserify/webpack (2.0), using gulp inject like you mention in [the wiki](https://github.com/linnovate/mean/wiki/RC1.0-Core-Packages#unified-dependency-management) would be awesome. With several custom packages, the aggregate assets files can be pretty big.

Here is an untested example/psuedocode of how to split into bundles per page, and inject with gulp inject:

packages/custom/mymodule/assets.json
```
{
  "mymodule": {
    "pages": [  // html files to run gulp inject on. globbing patterns supported here
          "packages/custom/mymodule/server/views/includes/head.html"
        ],
    "css": {
      "bower_components/build/mymodule/css/mymodule.min.css": [
        "bower_components/library/lib.css",
        ...
      ]
    },
    "js": {
      "bower_components/build/mymodule/js/mymodule.min.js": [
        "bower_components/lib/lib.js",
        ...
      ]
    },
    "angularDependencies": ["mean.mymodule", "lib", ...]
  }
}
```

packages/custom/mymodule/server/views/includes/head.html
```
<head>
  <base href="/">
  <meta>....

  <!-- {{locals.config.cssFramework}} -->
  <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.css">
  
  <!-- mymodule:css -->
  <!-- bower_components/build/mymodule/css/mymodule.min.css will be injected here -->
  <!-- endinject -->

  <!-- mymodule:js -->
  <!-- bower_components/build/mymodule/js/mymodule.min.js will be injected here -->
  <!-- endinject -->

</head>

```

gulp task, where config.bundles = assets.json
```
var inject = require('gulp-inject');
var each = require('async-each-series');

gulp.task('inject', function(done) {
    each(config.bundles, function(el, next) {
        gulp.src(el.pages)
        .pipe(inject(gulp.src(el.css.concat(el.js), {read: false}), {
            name: el.name,
            ignorePath: 'public' // example
        }))
        .pipe(gulp.dest('public'))
        // reload browser in dev
        .on('finish', next);
    }, done());
});
```

I have not seen any RC1.0 branch -- @claustres is the code in your wiki post just an example?

**Comment by claustres** [comment]
Yes the code in the wiki is given as a template but extracted from a working environment (I mean tested). I am afraid I do not have enough time to make a clean pull request for this, I use a fork of MEAN.io on some of my projects but there are specific parts that would require some work to "extract".

However I would be please to help answering questions or giving code snippets. For instance I have a **phonegap.js** file including all tasks required to generate a phonegap app based on a MEAN.io app. It is base on a custom **index.js** to tackle the issues related in https://github.com/linnovate/mean/issues/1130 and a custom **index.html** as you proposed:
```html
<head>
  ...
 
  <!-- inject:external css -->
  {external-css}
  <!-- endinject -->

  <!-- inject:external js -->
  {external-js}
  <!-- endinject -->

  <!-- inject:css -->
  <!-- endinject -->

  <!-- inject:js -->
  <!-- endinject -->

    <script src="cordova.js"></script>
</head>
...
```

**Comment by rjVapes** [comment]
I think currently the goal for assets is to shift over to using npm3/webpack (no bower).  It's a bit of a change from how we're doing things but important enough to come in for 1.0.  2.0 is likely more a Angular 2.0, Typescript, ES6 etc kind of thing.  The aggregation framework in the mean.io lib isn't well done and would just be better being removed and the effort outsourced to npm3/webpack.

It should solve the same issues this approach is solving as well.  Unfortunately I haven't had a deep dive into webpack to really assess the effort required to shift over, but any strategy that still involves a call to the existing `aggregateAssets` is going to be inherently flawed.  This is certainly a better approach than what we currently have though, but if we're going to change the strategy twice it would be great if someone could just put that effort towards npm3/webpack instead, so we don't have to change a very core concept multiple times, update docs etc.

**Comment by liorkesos** [comment]
I totally agree with this direction
The reason aggrgeation is part of the meanio core was so we could deal with
aggregating packages css/js on the fly (as they are added)
Modern systems like webpack or invocation of gulp or grunt tasks through js
could get triggered upon package addition and rebuild the aggregated css/js.
Webpack asoption is also part of larger theme we should follow which is
"reduce custom magic" -
One of the key strengthes in mean was providing best of breed components
and an efficient integration between them.
Introducing webpack reduces aggregation quirks and lets us integrate a well
known and proven component to replace it.
Lior

On Mon, Jan 4, 2016 at 8:55 PM, John Webb <notifications@github.com> wrote:

> I think currently the goal for assets is to shift over to using
> npm3/webpack (no bower). It's a bit of a change from how we're doing things
> but important enough to come in for 1.0. 2.0 is likely more a Angular 2.0,
> Typescript, ES6 etc kind of thing. The aggregation framework in the
> mean.io lib isn't well done and would just be better being removed and
> the effort outsourced to npm3/webpack.
>
> It should solve the same issues this approach is solving as well.
> Unfortunately I haven't had a deep dive into webpack to really assess the
> effort required to shift over, but any strategy that still involves a call
> to the existing aggregateAssets is going to be inherently flawed. This is
> certainly a better approach than what we currently have though, but if
> we're going to change the strategy twice it would be great if someone could
> just put that effort towards npm3/webpack instead, so we don't have to
> change a very core concept multiple times, update docs etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1429#issuecomment-168768361>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos
