### ISSUE TITLE
User can delete content without having permissions

### ISSUE THREAD

**Issue by amirmog** [linnovate/mean#1430]
In the 'Articles' example package:

An authenticated user with 'can create content' role (authenticated;can create content;) added from the /admin/user screen, can create content which is an expected behaviour. The user can not edit content which is also an expected behaviour but then can delete content even though 'can delete content' has not been added to the roles.

Any ideas ?
Thanks.

**Comment by VikramTiwari** [comment]
@amirmog It seems like in `server/routes.js` for `articles` we were not checking for the permission. 
@liorkesos any reason for this? @rjVapes 

This is now fixed. You can either update using upstream or update your code as in this pull request. https://github.com/linnovate/mean/pull/1431

**Comment by amirmog** [comment]
Works great now. Thanks
