### ISSUE TITLE
Struggling to import AngularUI Grid

### ISSUE THREAD

**Issue by daniel-elsner** [linnovate/mean#1432]
I performed a bower install of angular-ui-grid on the root of my project. It was installed and the files are at `../bower_components/angular-ui-grid`.

I reference both `ui-grid.min.js` and `ui.grid.min.css` in my `../config/assets.json` folder.

Then I go to the package where I want to use the grid and in `../package/app.js` I try:

`myPackage.angularDependencies(['ui-grid']);`

and 

`myPackage.angularDependencies(['ngGrid']);`

but an error is always thrown before page load stating a module injection error. Even if I just try to import 'ui-grid' in my controller and skip over the `app.js` I get the same error.

What is the current supported way of doing this? I saw another similar issue back from 2014 that was closed, but I cannot solve my problem the way he/she did.

Thank you!

**Comment by VikramTiwari** [comment]
Hey @daniel-elsner a few follow up questions.
- In your network tab in chrome inspect tools, can you see the `ui-grid.min.js` and `ui-grid.min.css` being pulled through?
- If so then following the steps to create a basic grid [here](http://ui-grid.info/docs/#/tutorial/101_intro), should work fine. Make sure to check following:
 - CSS property should be added

**Comment by claustres** [comment]
Just to be sure, file in **assets.json** are relative to root dir so you should have something like *bower_components/angular-ui-grid/whatever.css* and *bower_components/angular-ui-grid/whatever.js* inside.

**Comment by claustres** [comment]
You should also carefully read the docs and the demo files, it looks like the main module is called 'ui.grid' (http://ui-grid.info/docs/#/tutorial/101_intro) and you need to add more depending on the features you want like 'ui.grid.autoResize' (http://ui-grid.info/docs/#/tutorial/213_auto_resizing).
