### ISSUE TITLE
Does it supports Middleware ?

### ISSUE THREAD

**Issue by mansa-dev** [linnovate/mean#1442]
I want to apply a simple `basic-auth` before the `mean.serve()`. Just like the `htaccess` protection. But I dont know if `mean.serve()` supports the middleware.

```
// Authentication module.
var auth = require('http-auth');
var basic = auth.basic({
    realm: "Node JS Realm",
    file: __dirname + "/users.htpasswd" // gevorg:gpass, Sarah:testpass ...
});

```

How to pass this middleware to this function

```
  mean.serve({ workerid: workerId /* more options placeholder*/ }, function (app, config) {
        var port = config.https && config.https.port ? config.https.port : config.http.port;
        console.log('Mean app started on port ' + port + ' (' + process.env.NODE_ENV + ') cluster.worker.id:', workerId);
    });

```

**Comment by rjVapes** [comment]
Yes and no.

You can use middleware, you'd use the express integration for it, as outline in the readme for that module.  The no part is that mean.io uses Bearer token auth, and you can only use one auth method so you can't combine the two.  If you want to use basic auth, you'd need to integration with express as mention and then probably write all packages from scratch to support your alternate authentication.
