### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by Alishankhan** [linnovate/mean#1443]
I have follow mean.io getting started page and setup all the packages and git.
After I hit npm install, installation starts and   it stops at  "updating bower dependencies" after waiting couple of minutes hit ctrl+c and end the process. Manually run bower install.

running gulp or node server. Mean page show blank page

**Comment by VikramTiwari** [comment]
@Alishankhan Try doing a fresh install of node modules and bower components. If this does not solve it, run `npm postinstall`
