### ISSUE TITLE
Could mean.io use different file name to distinguish controller, router and model?

### ISSUE THREAD

**Issue by AngryDonny** [linnovate/mean#1447]
For example:

articles
|-server
|      |-controllers
|      |      |-server.controllers.articles.js
|      |-models
|      |      |-server.models.article.js
|      |-routes
|             |-server.routes.articles.js
|-public (same as server)

I switch files that dizzied me.

**Comment by rjVapes** [comment]
You can setup your packages however you want.  It doesn't look for certain filenames.  If this is a request to change what is defaultly generated by `mean package <pkgName>` then you could create an issue for it over in linnovate/mean-cli
