### ISSUE TITLE
tar.unpack issue during npm install

### ISSUE THREAD

**Issue by dineshsprabu** [linnovate/mean#1448]
Hi ~,

I'm facing the below error during my 'npm install' step, after creating mean project using 'mean init <appname>'. Can you please help me fixing it?

Note: I'm using OSX Yosemite 10.10.4 (14E46)

********************************************************
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/mongodb/-/mongodb-2.1.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/mongodb/-/mongodb-2.1.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/cliff/-/cliff-0.1.10.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/cliff/-/cliff-0.1.10.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.11.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/bson/-/bson-0.4.19.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/bson/-/bson-0.4.19.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/hawk/-/hawk-3.1.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/semver/-/semver-4.3.6.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/semver/-/semver-4.3.6.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/handlebars/-/handlebars-2.0.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/handlebars/-/handlebars-2.0.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-16903-873e1c69/registry.npmjs.org/npm/-/npm-2.13.5.tgz
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v3.5.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v3.5.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v3.5.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v3.5.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
*************************************************************

Thanks,
Dinesh.

**Comment by dineshsprabu** [comment]
For your information, I have tried using all the below,
sudo npm install
npm cache clean
npm update -g npm

**Comment by VikramTiwari** [comment]
@dineshsprabu You should read the error you are getting. This is neither an issue with NPM or MEAN. Its a network issue. Maybe you are behind a firewall, or your network is losing connection.
```
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'
```
