### ISSUE TITLE
App can't load ...c9users.io:35729/livereload.js file

### ISSUE THREAD

**Issue by luckylucky** [linnovate/mean#1449]
My app can't load ...c9users.io:35729/livereload.js file. After compilation in index file included this JS file,but in my server side I can't find this file.

Because of this, my web app load so longer.
How can I resolve this problem ?
I am using ubuntu OS on cloud9.

On of the result Google search
https://github.com/linnovate/mean/issues/448
I had the same problem where it would take a minute or so to load. I'm still running on the development environment. The console showed a timeout when trying to access livereload.js on port 35729. I solved it by adding port 35729 (set Source to My IP) to my Security Group -> Inbound ports in EC2. Now it runs very fast.

I have same trouble, but how to open port in Ubuntu, I don't understant.

**Comment by luckylucky** [comment]
in shell i wrote this command: $ sudo netstat -lnp
and get this result (http://prntscr.com/9phyux screenshot)
sbeatport:~/workspace $ sudo netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::5858                 :::*                    LISTEN      -               
tcp6       0      0 :::8080                 :::*                    LISTEN      -               
tcp6       0      0 :::35729                :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      1/micro-inetd   
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     682675545 -                   /home/ubuntu/.c9/2380465/collab.sock
unix  2      [ ACC ]     STREAM     LISTENING     648900399 -                   /tmp/tmux-1000/cloud91.8
unix  2      [ ACC ]     STREAM     LISTENING     648988145 -                   /tmp/mongodb-27017.sock
unix  2      [ ACC ]     STREAM     LISTENING     682675544 -                   /home/ubuntu/.c9/bridge.socket

**Comment by timelf123** [comment]
To get this working in c9 you will have to proxy with Apache and do some other stuff. Details here: http://stackoverflow.com/a/27461258/411284

**Comment by luckylucky** [comment]
Thanks for your advice. 

Cloud9 hosted workspaces now allow workspaces to listen on multiple ports. The following ports are supported (along with the urls they can be accessed from):

8080 -> https://<workspacename>-<username>.c9users.io
8081 -> https://<workspacename>-<username>.c9users.io:8081
8082 -> https://<workspacename>-<username>.c9users.io:8082
This allows things like running multiple applications on a workspace and LiveReload.

https://docs.c9.io/docs/multiple-ports

I am using MEAN.io and I just change the port in foot.html file (see here http://prntscr.com/9qcvrr) 

Rightnow my App Loads quickly, but still not find livereloadfile in root directory, so that, I go to MEAN.io support.
