### ISSUE TITLE
cannot continue...  nam install looping over... !

### ISSUE THREAD

**Issue by erwin16** [linnovate/mean#1450]
I tried to run pm install but , it's never passing over the netwo  , fetching over and over .. I had to terminate it with ctrl-C  

ves@MacMini: tuts1  (master *)$ npm install
npm ERR! tar.unpack unzip error /var/folders/kc/k_tvbzbd7js1svtf5rz7gdfh0000gn/T/npm-68263-7c4c46d7/registry.npmjs.org/gridfs-stream/-/gridfs-stream-1.1.1.tgz
cloneCurrentTree -> netwo | |##############------------------------------------------------------------------|
^C

**Comment by timelf123** [comment]
What version of node and npm are you running?
