### ISSUE TITLE
req.acl.query not work for others models

### ISSUE THREAD

**Issue by yuniers** [linnovate/mean#1454]
I trying update my app to latest version and I cloned Articles package.
All going good before get all documents of my model and found that <code>req.acl.query</code> only work with models of MEAN.
For example, when I use: ```var query = req.acl.query('Event');``` not work and back to old method of ```Event.find({}).sort('-created').populate('user', 'name username email')```

Somebody knows why happened that? Or can explain the purpose of ```req.acl.query```

**Comment by timelf123** [comment]
`req.acl.query('Article')` looks at the 'Article' model, and pulls any articles which have a permission in the permissions array that match the user's roles

You'll need to add this to your model
```
  permissions: {
    type: Array
  },
```

**Comment by yuniers** [comment]
Thank you @timelf123 . Now work perfect
