### ISSUE TITLE
Socket.io don't work in production mode

### ISSUE THREAD

**Issue by bertho-zero** [linnovate/mean#1471]
Hi,

Socket.io don't work in production mode because of clusters fork break it, you can implement sticky-session in your core_modules/server.

Thanks for your good job ;)

**Comment by timelf123** [comment]
So replace clusters with https://www.npmjs.com/package/socketio-sticky-session ?

**Comment by bertho-zero** [comment]
Thanks for your answer.

I would like to know how to get http server's variable in `server.js` and implement this in mean.io ?

**Comment by timelf123** [comment]
Hi @bertho-zero - which variables do you need to access?

**Comment by bertho-zero** [comment]
The return of createServer function, but i do not want edit the core of mean.io

**Comment by bertho-zero** [comment]
I've replace (in `/node_modules/meanio/lib/core_modules/server/ExpressEngine.js` l.126) :
```javascript
  var httpServer = http.createServer(app);
      meanioinstance.register('http', httpServer);
      httpServer.listen(config.http ? config.http.port : config.port);
```

by :
```javascript
  if (!cluster.isMaster) {
    sticky({proxy: false}, function() {
      var httpServer = http.createServer(app);
      meanioinstance.register('http', httpServer);
      httpServer.listen(config.http ? config.http.port : config.port);
      return httpServer;
    }).listen(config.http ? config.http.port : config.port, function () {
      console.log('Slave: server started on 3000 port');
    });
  } else {
    var httpServer = http.createServer(app);
    meanioinstance.register('http', httpServer);
    httpServer.listen(config.http ? config.http.port : config.port);
  }
```

It's work, i have 8 slaves but i have the message below in my navigator:
> WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket&sid=iiKJ7D2v7akTPp-cAAAA' failed: Connection closed before receiving a handshake response

**Comment by timelf123** [comment]
You can submit a pull request to https://github.com/linnovate/meanio

**Comment by bertho-zero** [comment]
I looked but I have not been able to integrate myself.

**Comment by bertho-zero** [comment]
https://github.com/linnovate/mean/pull/1472
https://github.com/linnovate/meanio/pull/93
