### ISSUE TITLE
How does the bootstrap.css be repleaced by the theme.css stored in mongodb?

### ISSUE THREAD

**Issue by povergoing** [linnovate/mean#1474]
I just could not understand how the bootstrap.css be replaced by the file in mongodb, after changing the theme, and saving a theme.css into db.
Guys, how does it work? :)

**Comment by timelf123** [comment]
I had similar questions about how the `fs.file` filestore works. It seems  `packages/core/admin/server/controllers/themes.js` is responsible for setting this file. I'm not using the admin package but I think it had an interface where you could set your theme.

**Comment by povergoing** [comment]
Hi @timelf123, sorry about I didn't make the question clear. What I mean is, after the theme.css (from bootswatch) saved into db, how does it be read out from db and replace the default bootstrap.css.
I am still quite confused.
