### ISSUE TITLE
Random aggregated files pending

### ISSUE THREAD

**Issue by bertho-zero** [linnovate/mean#1482]
Hi,

On almost every page load I have a file that aggregateg remains pending

![Image of problem](http://j15.imgup.net/Screenshotf6c6.png)

**Comment by timelf123** [comment]
Did you ever find fix for this?

**Comment by bertho-zero** [comment]
No, I looked a long time but I have found nothing, it's a shame I had to turn to other solutions

**Comment by liorkesos** [comment]
the new webpack dupport obsoletes aggregation.
next project stop by and reasess... :)
