### ISSUE TITLE
Configuration root changed to some old location

### ISSUE THREAD

**Issue by AnotherCodeArtist** [linnovate/mean#1483]
Hi!
I was suffering from some really weird problem for quite some while. Once I started with a project within my Dropbox folder. Then  checked it into github, deleted the dropbox folder and checked it out into some other folder. It works nice on machines where I never had used the project from the old dropbox location but on the machines I initially worked with the old location I got the following error:

Error: ENOENT: no such file or directory, open '/OldDropboxProjectFolder/bower_components/jquery/dist/jquery.min.map'

I searched the entire project as well as my global npm installation for any file containing a reference to this old folder, however, without any success. I also tried to hunt down the problem, but also with limited success.

With some "console.log-debugging" I at least found out where the problem occurs, but with no good explanation why:

``` javascript
function findModules(meanioinstance,defer,app) {

 var disabled = _.toArray(meanioinstance.config.clean.disabledModules);
  console.log(JSON.stringify(meanioinstance.config.clean.root))
  console.log("============= findModules ====================")
  Q.all([
    search(_modules, disabled, 'packages'),
    search(_modules, disabled, 'packages/core'),
    search(_modules, disabled, 'packages/custom'),
    search(_modules, disabled, 'packages/contrib')
  ]).done( function() {console.log(JSON.stringify(meanioinstance.config.clean.root)); findModulesDone.call(null, meanioinstance, app, defer);}, findModulesError.bind(null, defer));
}
```

The effect was, that the config.root was fine when entering findModules (first console.log), but referred to the wrong location once all promises completed and the done-handler was called. So there must me some weird side effect, modifying the meanioinstance object in the meantime.  

I eventually could get my project up and running by doing the following nasty thing:

``` javascript
function findModules(meanioinstance,defer,app) {
  var disabled = _.toArray(meanioinstance.config.clean.disabledModules);
  var instance = _.cloneDeep(meanioinstance.config)
  console.log(JSON.stringify(meanioinstance.config.clean.root))
  console.log(JSON.stringify(_modules))
  console.log("============= findModules ====================")
  Q.all([
    search(_modules, disabled, 'packages'),
    search(_modules, disabled, 'packages/core'),
    search(_modules, disabled, 'packages/custom'),
    search(_modules, disabled, 'packages/contrib')
  ]).done( function() {meanioinstance.config =instance; console.log(JSON.stringify(meanioinstance.config.clean.root)); findModulesDone.call(null, meanioinstance, app, defer);}, findModulesError.bind(null, defer));
}
```

So I make a copy of the config property and re-assign it once done() is called.
But it's completely unclear what causes the problem in the first place and where the old project location comes from. Is there any location, where you are saving a cache with project information?

**Comment by AnotherCodeArtist** [comment]
Did some more debugging and figured out that loading the wrong configuration was triggered by a mongoose post-hook (using kareem). Without digging any deeper it seems that mongoose somehow saves configuration information and associates it to the database name. 
After I renamed the dev-db from its default name (mean-dev) to something else, the problem was solved.

**Comment by timelf123** [comment]
Excellent use of console.log! Glad you got your problem sorted out
