### ISSUE TITLE
angularjs + Error: [$injector:unpr] Unknown provider

### ISSUE THREAD

**Issue by rajinikumar** [linnovate/mean#1485]
I am new in angularjs.
I try to download the csv file. So i tried to use angular sanitize and ng-csv files.

Index.html

` 

    <!DOCTYPE html>
        <html lang="en">
    <head>

        <script src="vendor/theme_files/js/jquery.min.js"></script>
    </head>
    <body ng-app="myApp" class="nav-md">

        <div class="container body" ui-view></div>

        <script src="vendor/angular/angular.js"></script>
        <script src="vendor/angular-resource/angular-resource.js"></script>
        <script src="vendor/angular-ui-router/release/angular-ui-router.js"></script>
        <script src="js/services/lb-services.js"></script>
        <script src="vendor/angular-sanitize/angular-sanitize.js"></script>
        <script src="vendor/ng-csv/ng-csv.min.js"></script>

        <script src="js/app.js"></script>
        <script src="js/controllers/offerLetterCtl.js"></script>
        <script src="js/services/offerLetter.js"></script>

    </body>
</html>`

app.js

    angular.module('myApp', ['lbServices', 'ui.router']).config(['$stateProvider', '$urlRouterProvider',
    function($stateProvider, $urlRouterProvider) {
    $stateProvider.state('login', {
        url : '/login',
        templateUrl : 'views/login.html',
        controller : 'loginController'
    }).state('addOfferletter', {
        url : '/create_offerletter',
        templateUrl : 'views/create_offer_letter.html',
        controller : 'offerLetterController'
    });
    $urlRouterProvider.otherwise('login');

    }]);`

offerLetterCtl.js (controller folder)

`    
    
    angular.module('myApp').controller('offerLetterController', ['$scope', '$location', 'offerLetterService',
    ,function($scope, $location, offerLetterService) { 
        //mycode

    }]);`

offerLetter.js(Service folder)

`   
    
    angular.module('myApp').factory('offerLetterService', ['$q', '$timeout', '$http',
    function($q, $timeout, $http,OfferLetter) {

        //mycode

    }]);`

create_offer_letter.html

`    
     
    <button type="button" ng-csv="getArray()" csv-header="['Field A', 'Field B', 'Field C']" filename="test.csv">
        Export
    </button>`

I followed this link for csv download.  [https://github.com/asafdav/ng-csv](url)

If i include this lines in controller

`    
    
    ['ngSanitize', 'ngCsv']

     angular.module('myApp').controller('offerLetterController', ['$scope', '$location', 'offerLetterService',"ngSanitize", "ngCsv"
    ,function($scope, $location, offerLetterService, ngSanitize, ngCsv) {

        $scope.filename = "test";  
    }]);`

Error Details:

`    Error: [$injector:unpr] Unknown provider: ngSanitizeProvider <- ngSanitize <- offerLetterController
http://errors.angularjs.org/1.3.20/$injector/unpr?p0=ngSanitizeProvider%20%3C-%20ngSanitize%20%3C-"<div class="container body ng-scope" ui-view="">"fferLetterController
`

**Comment by liorkesos** [comment]
Fixed in f87b8f3a98082a041e0f24f80fd267e59dd35f44
