### ISSUE TITLE
Timeline to Angular 2?

### ISSUE THREAD

**Issue by hbzhang** [linnovate/mean#1488]
Just wonder timeline to Angular 2?  I have been using mean framework for a while. I like it. But just want to know the timeline to angular 2. So I can be prepared for upgrading my websites....

**Comment by mbvb1223** [comment]
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by liorkesos** [comment]
I don;t believe it will be a clean upgrade and I assume it will take at least 6-8 monthes untill we have a version with angular2 support
