### ISSUE TITLE
Console Uncaught Error: [$injector:modulerr]

### ISSUE THREAD

**Issue by deividaspetraitis** [linnovate/mean#1492]
I have following this doc: http://learn.mean.io/

Unfortunately with no success, in console i see following:

`Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=mean&p1=Error%3A%20…angular%2Fangular.min.js%3Fv%3D8c9ac3aa67fee6aa599b4624398feba7%3A20%3A449)(anonymous function) @ angular.js:38(anonymous function) @ angular.js:4526n @ angular.js:321g @ angular.js:4487fb @ angular.js:4409Ac.c @ angular.js:1691Ac @ angular.js:1712(anonymous function) @ index.js?v=2738ecbd5273ee77f02ee08d77eaa20e:9i @ jquery.min.js?v=6fc159d00dc3cea4153c038739683f93:2j.fireWith @ jquery.min.js?v=6fc159d00dc3cea4153c038739683f93:2n.extend.ready @ jquery.min.js?v=6fc159d00dc3cea4153c038739683f93:2J @ jquery.min.js?v=6fc159d00dc3cea4153c038739683f93:2`

_OS name and version_ (running on vagrant):

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

_NodeJS and NPM version : Output of node -v and npm -v_:

```
node: v5.6.0
npm: 3.7.2
```
_MEAN Status : Output of mean status in project directory_:

```
    MEAN Status
    -----------

    MEAN VERSION: 0.5.5

    DB connection successful!

    MongoDB URI: mongodb://localhost/mean-dev

    checking meanio and global mean-cli versions
    mean-cli at latest version: 0.11.1
    meanio at latest version: 0.8.83
```

**Comment by deividaspetraitis** [comment]
I've figured out the problem. It was about not installed bower dependencies. by running _bower install_ in _project rool_ and followed packages fixed issue:

```
root/packages/custom/i18n$ bower install
root/packages/core/users$ bower install
root/packages/core/admin$ bower install
```

**Comment by FrankOrtmann** [comment]
I have the same problem on OS X 10.11.

mean-cli 0.11.1
meanio 0.8.83
npm 2.14.20
bower 1.7.7
nodejs 4.3.1

I have tried to run bower install in each package, but that did not help.

Any other ideas how to solve this?
