### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by hemanthsunny** [linnovate/mean#1498]
I want to start my web app page, but I'm facing this error. So, how can I fix this issue?
![image](https://cloud.githubusercontent.com/assets/16863363/13279049/d062d38c-dafa-11e5-97b1-610e4acf7259.png)

**Comment by timelf123** [comment]
`npm install`
`gulp`

**Comment by hemanthsunny** [comment]
Nope! I'm getting this error
![npm install_error](https://cloud.githubusercontent.com/assets/16863363/13344705/7ab10866-dc7e-11e5-8cbc-db452824b83e.png)
`

**Comment by timelf123** [comment]
This is not a mean.io application (we do not have an app.js file in root) and thus this issue should be closed.

Your second screenshot shows that you are no in the right directory. Try `cd vehico-api-busines` before the other commands

**Comment by hemanthsunny** [comment]
1. Before Installing 
![1](https://cloud.githubusercontent.com/assets/16863363/13371774/531e3bee-dd54-11e5-927d-f75adf9e74f4.png)
2. After Installing npm & opening the app.js file. Still, it is not.
![2](https://cloud.githubusercontent.com/assets/16863363/13371775/531f8846-dd54-11e5-8283-b1a136384cf1.png)

**Comment by praWINK** [comment]
@hemanthsunny i am also having this same issue could you solved that..
I am also new to this concepts...
