### ISSUE TITLE
TAG:0.5.x Package not found.

### ISSUE THREAD

**Issue by sjpartri** [linnovate/mean#1501]
Whenever I download a package. I get returned TAG:0.5.x
Package not found.

For example, "mean install upload"

Returns:

TAG:0.5.x
Package not found.

**Comment by xquarel** [comment]
I am having the same issue. Can someone help?

**Comment by ADSKLowenthal** [comment]
I posted this in the mean-cli repository, as I suspect it's more relevant to the command line tool.
