### ISSUE TITLE
Mean dependency injector issue in mean.io application.

### ISSUE THREAD

**Issue by jahanzaib-kk** [linnovate/mean#1502]
I  am facing this issue "Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=mean&p1=Error%3A%20…angular%2Fangular.min.js%3Fv%3D8c9ac3aa67fee6aa599b4624398feba7%3A20%3A449)" can any one tell becuase i have the same code running on development server but faing this  issue when deploy the application on prod server

**Comment by tkarls** [comment]
Looks like the same problem I am facing right now.

My "old" copy on my dev server worked but not when I deployed. I suspected that some dependency has been updated that breaks things and yes, running npm install again on my dev server breaks that one too.

I have no idea where to even begin looking for the error.
@jahanzaib-kk did you find any solution?

**Comment by tkarls** [comment]
Turned out my problem was #1486
