### ISSUE TITLE
Prerequisite not installed: git

### ISSUE THREAD

**Issue by anta40** [linnovate/mean#1512]
My laptop is runing 32-bit Windows 10. Just got Node v5.8 installed:

> C:\Users\CSL-NB-064\Codes\JS>node -v
> v5.8.0

Then I installed mean

> npm install -g mean-cli

And creating my first project

> C:\Users\CSL-NB-064\Codes\JS>mean init
> ? What would you name your mean app? (mean) blahblah
> ? What would you name your mean app? blahblah
> ? The Mean project is currently in developer preview. To help improve the -
>   quality of this product, we collect anonymized data on how the mean-cli is used -
>   You may choose to opt out of this collection now (by choosing 'N' at the below prompt)
>   or at any time in the future by running the following command:
> 
>   mean disable user-reporting
> 
>   Do you want to help us improve the mean network (Y/n)?  n
> On windows platform - Please check permissions independently
> All permissions should be run with the local users permissions
> Prerequisite not installed: git

I already have git installed in %PATH% (C:\Program Files\Git\bin). Is this a problem?

**Comment by bhargavgunreddy** [comment]
Please try
1) Adding Git to class path
2) clear npm cache
This worked out for me
