### ISSUE TITLE
[nodemon] app crashed

### ISSUE THREAD

**Issue by iamShantanu101** [linnovate/mean#1520]
App is getting crashed when visiting http://localhost:3000

**Comment by liorkesos** [comment]
Please send the error report

On Tue, Apr 5, 2016 at 10:34 PM, Shantanu Deshpande <
notifications@github.com> wrote:

> App is getting crashed when visiting http://localhost:3000
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1520>
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos
