### ISSUE TITLE
Blank page when run: http://localhost:3000

### ISSUE THREAD

**Issue by tuanflour** [linnovate/mean#1526]
Console show errors like:

[$injector:nomod] http://errors.angularjs.org/1.5.3/$injector/nomod?p0=mean.admin

**Comment by madnotdead** [comment]
Have you made any changes to the starter app? It seems to be a client side error, check if both packages, bower and node, are correctly installed.

**Comment by tuanflour** [comment]
I installed these at all before create the app.

**Comment by saeed68gm** [comment]
One issue that I faces, is that mean postinstall fails to run (i.e. bower fails to install the dependencies for the packages). Your error looks like it failed to install the dependencies for the admin package. Can you run the app locally?

**Comment by gigenthomas** [comment]
Here's one of the errors I get with the admin package : 
WARNING in ./~/meanio-users/public/services/meanUser.js
Module parse failed: /node_modules/meanio-users/public/services/meanUser.js Unexpected token (4:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (4:2)

**Comment by timelf123** [comment]
I missed a comma in my PR. Fixed with https://github.com/linnovate/meanio-users/commit/55d693cd41de8a0c5d72c533aa604f11d5b8a055 @gigenthomas 

I've updated the meanStarter mean.json so the deps point at linnovate now, so you will want to pull these changes and `npm install` again

**Comment by shahfaisal91** [comment]
I guess you have crated a new package or installed a crontrib packages.
You have to pass anguler dependencies while with new created public(client)  controllers like below:

var myApp = angular.module('myApp', [])

I was facing same issued and it solved.
you can also refer https://docs.angularjs.org/error/$injector/nomod?p0=mean.admin

**Comment by timelf123** [comment]
I don't think this is the right solution. AFAIK, meanio creates the module definitions and injects things as defined in app.js i.e. `Yourpackage.angularDependencies(['mean.users', 'ngClipboard']);`

**Comment by ziaullahkhan** [comment]
If you see in the console you will see something like that. 

> Uncaught ReferenceError: angular is not defined

Stop the running process and run the following command from root.

bower install --allow-root 

Then run grunt
