### ISSUE TITLE
Can't get the mean app to start

### ISSUE THREAD

**Issue by deecm22** [linnovate/mean#1528]
I have followed the simple instructions in the README.md but I can't get the app to run.

I keep getting the following error: Packages with unresolved dependencies: meanStarter.
I even went as far as to go into the meanio folder under node_modules and ran npm install to ensure that I had all the mean related dependencies.

What are these dependencies and where do I get them? 

Below is the console output.  It just hangs at the end and when I go to localhost:3000 I get a black page saying I can't connect to the server.

```
Packages with unresolved dependencies: meanStarter
[02:38:45] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kazajhodo** [comment]
This means that the meanStarter module has dependencies that are not included in your install. Which means more than likely that they weren't installed, which means those dependencies are not included in their respective bower.json file.

If you navigate into meanStarter, packages/custom/meanStarter, if there is a 'bower.json' file in there, you can type 'bower install' and hit enter. That should install those dependencies.

Though I'm having similar issues even getting the default module to fire, so its likely something else.

**Comment by timelf123** [comment]
`Packages with unresolved dependencies` means you are missing packages defined in mean.json of meanStarter

Try to `npm install`
