### ISSUE TITLE
Missing module dependency in mean.users

### ISSUE THREAD

**Issue by dazwin** [linnovate/mean#1535]
The mean.users module depends on $meanStateProvider, which is implemented by mean.system. However, in v0.5.5 (the current release per https://mean.io), this dependency is missing (https://github.com/linnovate/mean/blob/0.5.5/packages/core/users/app.js#L42).

This results in non-deterministive behavior - if angular compiles mean.system first, we're Ok. Otherwise, we get an angular exception similar to...

```
Failed to instantiate module mean due to:
[$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=m...
https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:6:417
https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:40:136
q@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:7:359
g@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:39:223
https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:39:392
q@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:7:359
g@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:39:223
bb@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:43:247
c@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:21:21
yc@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:21:333
https://##############.cloudfront.net/bower_components/web-bootstrap/index@c538dae53ee5da4250487a5d7291a58e.js:9:20
i@https://##############.cloudfront.net/bower_components/jquery/dist/jquery.min@33cabfa15c1060aaa3d207c653afb1ee.js:2:27156
fireWith@https://##############.cloudfront.net/bower_components/jquery/dist/jquery.min@33cabfa15c1060aaa3d207c653afb1ee.js:2:27915
ready@https://##############.cloudfront.net/bower_components/jquery/dist/jquery.min@33cabfa15c1060aaa3d207c653afb1ee.js:2:29718
J@https://##############.cloudfront.net/bower_components/jquery/dist/jquery.min@33cabfa15c1060aaa3d207c653afb1ee.js:2:29897
```

It looks like the dependency on $meanStateProvider has now been removed entirely, however, as mentioned, this is still an issue in the current release.

**Comment by liorkesos** [comment]
The current version is 0.6
Can you make sure you're working on the most recent version and that you
can recreate using the meanio-users npm which is the recent mean.users
Lior

On Thu, Apr 21, 2016 at 7:47 AM, Darren Warner <notifications@github.com>
wrote:

> The mean.users module depends on $meanStateProvider, which is implemented
> by mean.system. However, in v0.5.5 (the current release per
> https://mean.io), this dependency is missing (
> https://github.com/linnovate/mean/blob/0.5.5/packages/core/users/app.js#L42
> ).
>
> This results in non-deterministive behavior - if angular compiles
> mean.system first, we're Ok. Otherwise, we get an angular exception similar
> to...
>
> Failed to instantiate module mean due to:
> [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=m...
> https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:6:417
> https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:40:136q@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:7:359g@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:39:223
> https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:39:392q@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:7:359g@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:39:223bb@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:43:247c@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:21:21yc@https://##############.cloudfront.net/bower_components/angular/angular.min@5e2d2057d96976d43c756dcc1efaa1dc.js:21:333
> https://##############.cloudfront.net/bower_components/web-bootstrap/index@c538dae53ee5da4250487a5d7291a58e.js:9:20i@https://##############.cloudfront.net/bower_components/jquery/dist/jquery.min@33cabfa15c1060aaa3d207c653afb1ee.js:2:27156fireWith@https://##############.cloudfront.net/bower_components/jquery/dist/jquery.min@33cabfa15c1060aaa3d207c653afb1ee.js:2:27915ready@https://##############.cloudfront.net/bower_components/jquery/dist/jquery.min@33cabfa15c1060aaa3d207c653afb1ee.js:2:29718J@https://##############.cloudfront.net/bower_components/jquery/dist/jquery.min@33cabfa15c1060aaa3d207c653afb1ee.js:2:29897
>
> It looks like the dependency on $meanStateProvider has now been removed
> entirely, however, as mentioned, this is still an issue in the current
> release.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1535>
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by dazwin** [comment]
Hey Lior, this is not what http://mean.io says. I was going to create a PR, but it seems like it's not worthwhile doing so then?
