### ISSUE TITLE
TypeError: Circles.aggregateAsset is not a function - Mean.io Fresh Install

### ISSUE THREAD

**Issue by Manish2005** [linnovate/mean#1537]
I need an urgent workaround for this. I've tried like 3-4 times to do fresh install.. everytime I got this error. There were some missing dependencies as well like mongoose and async

**Comment by gigenthomas** [comment]
+1

**Comment by Manish2005** [comment]
Just to clear, I did not get the error while installing. I am getting the error when I run the gulp command.
Am I the only one who is facing this issue? Did anyone else try fresh install for latest version?

Please let me know.

**Comment by gigenthomas** [comment]
I have the same exact issue

**Comment by gigenthomas** [comment]
There is an outstanding PR in meanio-circles. This should resolve your issue.

https://github.com/linnovate/meanio-circles/pull/1

**Comment by markSbrandt** [comment]
similar issue with https://github.com/linnovate/meanio-admin/pull/1

**Comment by Manish2005** [comment]
Yes, these 2 PR solved the issue, there is similar.

Thanks.

**Comment by timelf123** [comment]
https://github.com/linnovate/meanio-circles/pull/1 and https://github.com/linnovate/meanio-admin/pull/1 have been merged but not tagged/released on npm yet. should be able to get the latest changes by changing the meanStarter `package.json` to look at master for each package
```
  "dependencies": {
    "meanio-system": "git://github.com/linnovate/meanio-system.git#master",
    "meanio-users": "git://github.com/linnovate/meanio-users.git#master",
    "meanio-circles": "git://github.com/linnovate/meanio-circles.git#master",
    "meanio-admin": "git://github.com/linnovate/meanio-admin.git#master"
  },
```

**Comment by gigenthomas** [comment]
Can confirm that this has been resolved
