### ISSUE TITLE
MEAN.io application not starting "/bundle/app.js 404"

### ISSUE THREAD

**Issue by shenopkss** [linnovate/mean#1541]
When  I run the following commands:

> $ npm install -g mean-cli
> $ mean init <myApp>
> $ cd <myApp> && npm install
> $ node server

Console log：

> for real!
> forking  0
> forking  1
> forking  2
> forking  3
> Mean app started on port 3000 (undefined) cluster.worker.id: 2
> Mean app started on port 3000 (undefined) cluster.worker.id: 1
> Mean app started on port 3000 (undefined) cluster.worker.id: 3
> Mean app started on port 3000 (undefined) cluster.worker.id: 4

Then, open a browser and go to: http://localhost:3000/，but browser content is blank!

Console log：

> GET / 200 - - 37.773 ms
> GET /bundle/app.js 404 - - 8.016 ms`

node version

> v4.4.3

mean version

> 0.11.1

**Comment by martyychang** [comment]
I'm experiencing the same issue.
```bash
$ node -v
v5.6.0
$ npm -v
3.6.0
$ mean -v
0.11.1
```

**Comment by gromatl** [comment]
Hello,
I've just got this problem today, after launching `gulp` all the less, sass.. files should compile.
Launch back node after that, and everything should work fine !

**Comment by igorg1312** [comment]
Happy man!! I'm working on they will be ok, next i Have to crypt sending
get data
Il 10 Mag 2016 23:10, "Luidgi Gromat" <notifications@github.com> ha scritto:
