### ISSUE TITLE
Gulp running new project failed  "node_modules/q/q.js:155        throw e;"

### ISSUE THREAD

**Issue by leonzmq520** [linnovate/mean#1542]
My environment: 
node: v5.4.0
npm: 3.8.8

After creating a new project with mean init <name>, and npm install,

I start mongod and ran Gulp.

Then I got this error log:
```bash
[02:16:48] Using gulpfile ~/Documents/zl-webMEAN/gulpfile.js
[02:16:48] Starting 'clean'...
[02:16:48] Finished 'clean' after 7.78 ms
[02:16:48] Starting 'default'...
[02:16:48] Starting 'webpack:build-dev'...
[02:16:48] Starting 'clean'...
[02:16:48] Starting 'less'...
[02:16:48] Starting 'sass'...
[02:16:48] Starting 'csslint'...
[02:16:49] Starting 'env:development'...
[02:16:49] Finished 'env:development' after 16 μs
[02:16:49] Starting 'devServe'...
[02:16:49] Finished 'devServe' after 45 ms
[02:16:49] Starting 'watch'...
[02:16:49] Finished 'watch' after 519 ms
[02:16:49] Finished 'clean' after 842 ms
[02:16:49] [nodemon] 1.9.1
[02:16:49] [nodemon] to restart at any time, enter `rs`
[02:16:49] [nodemon] watching: *.*
[02:16:49] [nodemon] starting `node --debug server.js`
Debugger listening on port 5858
[02:16:50] Finished 'less' after 1.33 s
[02:16:50] Finished 'sass' after 1.15 s

/Users/leonzmq/Documents/zl-webMEAN/node_modules/q/q.js:155
                throw e;
                ^
Packages with unresolved dependencies: meanStarter
[02:16:51] [nodemon] app crashed - waiting for file changes before starting...
[02:16:52] csslint: 3 files lint free
[02:16:52] Finished 'csslint' after 3.37 s
[02:16:58] [webpack:build-dev] Hash: 302fe5a6d20664782e34
Version: webpack 1.13.0
Time: 10007ms
     Asset     Size  Chunks             Chunk Names
    app.js  2.61 MB       0  [emitted]  app
app.js.map  3.04 MB       0  [emitted]  app
chunk    {0} app.js, app.js.map (app) 2.55 MB [rendered]
````
 using `node server.js` then I got this : 
```bash
for real!
forking  0
forking  1
forking  2
forking  3
forking  4
forking  5
forking  6
forking  7

/node_modules/q/q.js:155
                throw e;
                ^
Packages with unresolved dependencies: meanStarter

/node_modules/q/q.js:155
                throw e;
                ^
Packages with unresolved dependencies: meanStarter
Worker 1 died :(
Worker 6 died :(
```

**Comment by martyychang** [comment]
I ran into the same issue, and the two-step init process shown on the front page of http://mean.io appears to a bit misleading. The full requirements are given at http://learn.mean.io/ and can be summarized as follows:
```bash
$ npm install -g mean-cli
$ mean init <myApp>
$ cd <myApp> && npm install bower && npm install
```

Bower is required before `npm install` can complete successfully. If you watch the output if you run `npm install` without Bower, you'll see errors like the following.

```txt
Error: npm install failed
{ [Error: meanio-users@0.1.3 postinstall: `bower install`
spawn ENOENT]
  code: 'ELIFECYCLE',
  errno: 'ENOENT',
  syscall: 'spawn',
  file: 'sh',
  pkgid: 'meanio-users@0.1.3',
  stage: 'postinstall',
  script: 'bower install',
  pkgname: 'meanio-users',
  parent: 'mean' }
```

**Comment by liorkesos** [comment]
did you run npm install?

**Comment by leonzmq520** [comment]
yes, I did it.  
```bash
$ npm install bower && sudo npm install

**Comment by martyychang** [comment]
Hi @leonzmq520 what OS are you running? I don't think you need `sudo` for the `npm install` part.

**Comment by leonzmq520** [comment]
Hi @martyychang,  I'm running  mac os 10.11.4. It will  appear `permission denied` without `sudo`. I did fully install 
`
 $ npm install bower && sudo npm install
 `

But It shows the error from here  `node_module/q/q.js:155 throw e;`

**Comment by martyychang** [comment]
That's strange. In which directory did you run `mean init`? I keep my projects in a custom *~/Workspace* directory on my Mac (OS X El Capitan). What happens if you do this?
```bash
$ cd ~
$ mkdir Workspace && cd Workspace/
$ mean init mean-demo
$ cd mean-demo
$ npm install bower
$ npm install
```

**Comment by leonzmq520** [comment]
@martyychang  the same error .
![2016-04-27 18 29 32](https://cloud.githubusercontent.com/assets/5023103/14859804/177ccaa2-0ca6-11e6-8eb7-b4f3e6ef357f.png)

**Comment by martyychang** [comment]
I'm scratching my head now, @leonzmq520 . Maybe @liorkesos has more insights, as I've exhausted what I know about the CLI.

**Comment by esakia** [comment]
I have the same problem on ubuntu 15.04

**Comment by luvsin27** [comment]
same error ubuntu 16.04
![screenshot from 2016-07-13 13-22-43](https://cloud.githubusercontent.com/assets/20415702/16795867/3fbff94c-48fd-11e6-88ac-ba7538b4e5e0.png)

**Comment by SashaDesigN** [comment]
Yes the same problem on ubuntu 15.04

**Comment by mattsmith13815** [comment]
I was running into the same issue and I spent a little time trying to cobble my way through this, running on Mac OSX 10.11.6 - Note: still not fully running

Running this command, get us passed the bower permission issues:
**sudo npm install bower --noauth && sudo npm install**

**chmod 777** any file that I was getting the following permission error on:
Error: EACCES: permission denied, open '/Users/_{username}_/.config/configstore/bower-github.json' You don't have access to this file.

Examples of some of the files, there may be more: 
chmod 777 /Users/_{username}_/.config/configstore/bower-github.json
chmod 777 /Users/_{username}_/.config/configstore/update-notifier-bower.json
chmod 777 /Users/_{username}-/.config/configstore/update-notifier-bower.json

**Repeat** the above bower and npm command until all permission errors cleared.  After a few files, the server **finally kicked in however from a browser my screen is loading blank.**  The server responses are indicating:

Mean app started on port 3000 (development) cluster.worker.id: 0
[11:07:20] index.html reloaded.
GET /index.html 404 - - 34.661 ms
GET /_getModules 304 - - 0.856 ms
GET /index.html 404 - - 1.724 ms
GET /_getModules 304 - - 0.920 ms
GET /favicon.ico 200 - - 2.095 ms

Happy Hacking!

**Comment by milan8866** [comment]
i have same issue regarding mean , while run the file of mean-master pproject the error ,

 C:\Users\Admin\Desktop\mean-master\mean-master>node server.js

C:\Users\Admin\Desktop\mean-master\mean-master\node_modules\meanio\node_modules\q\q.js:155
                throw e;
                ^

**Comment by SashaDesigN** [comment]
Yes I too had the same issues when install it on Ubuntu 15.04- but then remove all what I install and search on stackoverflow and here on github and I found what a half of my problems was with not correct access rules - I had the same errors, but when set up correct chmod & chown for some folders (can't remember it, sorry) it works for me.

**Comment by igor-lemon** [comment]
I have the same problem with build on Docker.

**Comment by jessemull** [comment]
The only way to fix this issue was to uninstall all npm global packages, uninstall nodejs, reinstall nodejs and then install mean-cli and run mean init.
