### ISSUE TITLE
mean init yourNewAp fails

### ISSUE THREAD

**Issue by asemoon** [linnovate/mean#1545]
> readline.js:925
>             throw err;
>             ^
> TypeError: done is not a function
>     at nextSteps (/usr/local/lib/node_modules/mean-cli/lib/install.js:444:2)
>     at /usr/local/lib/node_modules/mean-cli/lib/install.js:57:7
>     at /usr/local/lib/node_modules/mean-cli/node_modules/async-series/index.js:17:14
>     at PromptUI.completed (/usr/local/lib/node_modules/mean-cli/lib/install.js:361:10)
>     at PromptUI.onCompletion (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
>     at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
>     at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
>     at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
>     at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
>     at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)

OS: OS X 10.11 
Node: v4.4.2
NPM: 2.15.1

**Comment by teogenesmoura** [comment]
same here :(

readline.js:921
            throw err;
            ^

TypeError: done is not a function
    at nextSteps (/usr/local/lib/node_modules/mean-cli/lib/install.js:444:2)
    at /usr/local/lib/node_modules/mean-cli/lib/install.js:57:7
    at /usr/local/lib/node_modules/mean-cli/node_modules/async-series/index.js:17:14
    at PromptUI.completed (/usr/local/lib/node_modules/mean-cli/lib/install.js:361:10)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)

**Comment by liorkesos** [comment]
What operation system?
What version of node?

**Comment by igorg1312** [comment]
Hello,

I Have the same problema.
Il 27 Apr 2016 07:50, "Lior Kesos" <notifications@github.com> ha scritto:

**Comment by Jianglinyuan** [comment]
i have the same problem too.

**Comment by lembadm** [comment]
same problem too.

Ubuntu Linux 16.04
NodeJs v4.2.6
NPM 3.5.2
MEAN 0.12.3

**Comment by teogenesmoura** [comment]
Forgot to mention, but OSX 10.11, Node v 4.1.0, npm 2.14.3, MEAN 0.12.3

**Comment by automech** [comment]
me as well
same node v5 OSX

**Comment by rodgarcia** [comment]
Same problem: Ubuntu 14.04. I tried with with Node 6.0 and Node 5.10.

**Comment by shahfaisal91** [comment]
Same error with me.
Can any one help for this error.

/usr/lib/node_modules/mean-cli/lib/install.js:444
	done();
	^

TypeError: done is not a function
    at nextSteps (/usr/lib/node_modules/mean-cli/lib/install.js:444:2)

**Comment by keremciu** [comment]
same problem :(

**Comment by shahfaisal91** [comment]
Can any one help plz. is any one aware of the solution?

Hello NPM community??????

**Comment by liorkesos** [comment]
I have recreated this finally today.
Will try to address as soon as i can


On Mon, May 2, 2016 at 10:36 PM, shahfaisal91 <notifications@github.com>
wrote:

> Can any one help plz. is any one aware of the solution?
>
> Hello NPM community??????
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1545#issuecomment-216339055>
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by shahfaisal91** [comment]
Oh please let us know how did you do that? Liorkesos.
I am using mean in Ubuntu 14.04:

**Comment by liorkesos** [comment]
The installation is fully functional - the things that are breaking are
related to registration to the mean network and I was sure I allready
removed that part </my-bug>

On Mon, May 2, 2016 at 10:52 PM, shahfaisal91 <notifications@github.com>
wrote:

> Oh please let us know how did you do that? Liorkesos.
> I am using mean in Ubuntu 14.04:
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1545#issuecomment-216343018>
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by shahfaisal91** [comment]
How can I remove the functionality "registration to the mean network"?
