### ISSUE TITLE
Error while running on gulp

### ISSUE THREAD

**Issue by dsrini-open** [linnovate/mean#1548]
When doing gulp I am getting the following exception - 
 Error: ENOENT, no such file or directory '/<proj_name>/node_modules/node-sass/vendor'

I tried updating gulp - npm update -g gulp

npm v - 3.4
node v - 0.10.42
mean: '0.6.1'
gulp: '3.9.1'

OS : Cent OS 7

Ignoring error, and tried to do a $ node server command for which I am getting the other issue reported. 

Any idea on what should I do?

**Comment by liorkesos** [comment]
Did you run a successfullnm install?
You might consider running with a newer version of mean as well..

**Comment by shahfaisal91** [comment]
I think the npm package node-sass is not installed, Try to install node-sass using 
"sudo npm install --save node-sass"
