### ISSUE TITLE
mean.io speed up tips

### ISSUE THREAD

**Issue by esinecan** [linnovate/mean#1553]
Hello, pageSpeed insights berated me badly: https://developers.google.com/speed/pagespeed/insights/?hl=tr&url=http%3A%2F%2Fdokratestest-2hx775l5.cloudapp.net%3A3000%2Fauth%2Flogin

How do I fix these? I run "pm2 server.js" on my server.

**Comment by tranphuoctien** [comment]
Hey, we can use nginx and cloudfare for it.

2016-05-02 3:08 GMT+07:00 Eren Can Sinecan <notifications@github.com>:
