### ISSUE TITLE
Tagging releases appear to have stopped with 0.5.6 (Jul 2015)

### ISSUE THREAD

**Issue by gbevan** [linnovate/mean#1557]
We need to be able to fix app generation at specific tagged releases.  Previously we were able to use:
mean init -b 0.5.5 myApp
to build a scaffolding app based on version 0.5.5, etc,...
but tagging releases seem to have stopped since last July.  We'd like to request that you reinstate this workflow process.

**Comment by timelf123** [comment]
@linnovate/mean-contributors it would be nice to tag 0.5.5 before the merge so people who have not upgraded can pull 0.5.5 changes they were missing

**Comment by igorg1312** [comment]
Helo news reded, seems good. I will reinstate js and pyt seeds. Understud,
Nigthl
Il 03 Mag 2016 22:47, "Graham Lee Bevan" <notifications@github.com> ha
scritto:
