### ISSUE TITLE
MEAN app starts but I get a blank screen in browser

### ISSUE THREAD

**Issue by rubenjimenez** [linnovate/mean#1559]
Hi,

I've installed MEAN and everything seemed to go fairly well. No error found during installation.

But when I did "gulp" and I went to browser to test localhost:3000 I just got a blank page.

Apparently everything is fine. There's no error in terminal log:

```
[12:39:52] [nodemon] starting node --debug server.js
Debugger listening on port 5858
Mean app started on port 3000 (development) cluster.worker.id: 0
[12:39:55] index.html reloaded.
GET / - - - - ms
GET / - - - - ms
GET / - - - - ms
```

The same occurs using "node server":

```
MacBook-Pro-de-Ruben ruben$ node server
for real!
forking  0
forking  1
forking  2
forking  3
Mean app started on port 3000 (undefined) cluster.worker.id: 3
Mean app started on port 3000 (undefined) cluster.worker.id: 4
Mean app started on port 3000 (undefined) cluster.worker.id: 2
Mean app started on port 3000 (undefined) cluster.worker.id: 1
GET / - - - - ms
GET / - - - - ms
GET / - - - - ms
```

In browser's console this is what I get:

```
GET http://localhost:3000/ net::ERR_EMPTY_RESPONSE
```

Any light in the horizon? Any suggestion about what's going on?

**Comment by rubenjimenez** [comment]
Solved.

I think changing the .npm folder permissions made the trick.

```
sudo chown -R  $USER:$GROUP ~/.npm
```

I deleted the project, changed the permissions and made again the mean init afterwards.

**Comment by timelf123** [comment]
Could be helpful to others experiencing the `GET / - - - - ms` bug, thanks

**Comment by rahulmandkriya** [comment]
I am getting same problem https://github.com/linnovate/mean/issues/1625
 and follow @rubenjimenez 
I deleted the project, changed the permissions and made again the mean init afterwards. with sudo chown -R  $USER:$GROUP ~/.npm but issue not solve....

**Comment by vancehu** [comment]
@rahulmandkriya

1. try this first: [https://docs.npmjs.com/getting-started/fixing-npm-permissions]
2. if the problem persists, it's most likely caused by an outdated npm which cannot parse the dependency correctly while installing.
try:
```
npm install -g npm
npm update -g
npm install -g mean-cli
npm install -g bower
mean init yourNewApp
```

I encountered the same issue in a newly deployed Ubuntu 16.04 and solved it by doing these 2 steps
