### ISSUE TITLE
mean init myMeanApp failed

### ISSUE THREAD

**Issue by hem-kant** [linnovate/mean#1562]
HI All,

I am facing issue when executing the mean init myMeanApp command running on windows 7 i have installed all the prerequisites 

C:\Users\hem.kant>mean init myMeanApp
? What would you name your mean app? myMeanApp
On windows platform - Please check permissions independently
All permissions should be run with the local users permissions
Cloning branch: master into destination folder: myMeanApp
git clone  --depth 1  -bmaster https://github.com/linnovate/mean.git "myMeanApp"
Cloning into 'myMeanApp'...

  Added the "remote" upstream origin
'mv' is not recognized as an internal or external command,
operable program or batch file.
'mv' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\hem.kant\AppData\Roaming\npm\node_modules\mean-cli\lib\install.js:52
      if (err) throw err;
               ^
 'mv' is not recognized as an internal or external command,
operable program or batch file.

**Comment by igorg1312** [comment]
Hi Try to add mv to system environment variables, reboot and launch the
command From shell. Yes i agree with you user grant, but consider mostly
case to check super user grant for directory to install (launch as).
Il 09 Mag 2016 09:43, "Hem Kant" <notifications@github.com> ha scritto:

**Comment by hem-kant** [comment]
hi, since i am new with mean based app could you please let me know what value i need to put in **varaible value ** field .

**Comment by hem-kant** [comment]
after updating the mv in system environment variables issue got fixed
