### ISSUE TITLE
MeanStarter.aggregateAsset is not a function?

### ISSUE THREAD

**Issue by kinzdesign** [linnovate/mean#1565]
After a fresh install, I attempted to add assets to the bundle by adding 
  `MeanStarter.aggregateAsset('css', 'foo.css');`
to packages/custom/meanStarter/app.js  after the 
  `MeanStarter.angularDependencies(['mean.system', 'mean.users']);` line. 

When I try to start the application, I get:
`TypeError: MeanStarter.aggregateAsset is not a function`

**Comment by pashist** [comment]
In `packages/custom/meanStarter/public/index.js` you can see example as assets should be included

**Comment by timelf123** [comment]
@kinzdesign 

This should work if you are on a fresh install. All frontend js files are now processed with webpack (rather than aggregation pipeline) and included in app.js bundle

```
'use strict';

import './assets/css/common.css';
import 'moment' // make sure moment is in your package's `package.json`
```

**Comment by kinzdesign** [comment]
Thanks!

**Comment by manojchandrashekar** [comment]
In the previous versions, production mode used to minify/uglify the CSS and JS files - does it still happen with webpack?
