### ISSUE TITLE
Mean init issue

### ISSUE THREAD

**Issue by hem-kant** [linnovate/mean#1568]
Hi

I have installed mena-cli but when creating meanapp using `mean init <myApp>` the command gets terminated automatically after confirming the app name this was working till yesterday , attached is screenshot.
Any suggestion on the same would be highly appreciated 

![mean init issue](https://cloud.githubusercontent.com/assets/13075832/15171616/8f471728-176d-11e6-8d96-4ca37617acb0.PNG)

**Comment by drannos** [comment]
I have encountered the same issue. When running 'mean init <appName>' the wizard starts but never finishes, no directory is created and mean is not cloned. I just get kicked to the command line. 

mean 0.12.9
node 4.4.4 (and 6.1.0 though I later discovered this is not necessarily compatible)
npm 2.15.1
Windows 10 64 bit

I've run init through everything I can think - Windows cmd (both as Administrator and normally) and through git bash (Git for Windows 2.8.2) both normally and as Windows Admin. No change to the outcome.

**Comment by ricktbaker** [comment]
Same issue here.  Until they get this resolved, you can fallback to an older version of mean-cli:

sudo npm install -g mean-cli@0.11.1
