### ISSUE TITLE
adding / creating custom package = Error: [$injector:modulerr]

### ISSUE THREAD

**Issue by JAppsAreUs** [linnovate/mean#1569]
When I attempt to create a custom package or add an existing custom package to "packages/custom" through git clone, I get the following error:

> [$injector:nomod] Module 'mean.test' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Here is my config:
Ubuntu 14.04.3
nodejs -v : v5.11.1
npm -v : 3.8.9
mean-cli : 0.11.1

After "mean-init testapp", my stack is up and running. Landing page is displayed without any problems or errors in console.

After "mean package test", the website displays a blank page and errors in the navigator console:

> [$injector:nomod] Module 'mean.test' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Cloning an existing package from github has the same result.

**Comment by pashist** [comment]
try to update mean-cli

**Comment by JAppsAreUs** [comment]
thanks for the response @pashist but I'm using Mean-cli 0.11.1 because the latest one has a problem and doesn't allow to get past the "Mean init" step. Several issues in your repository mention this as well as comments in Gitter.

**Comment by timelf123** [comment]
@JAppsAreUs this was fixed in the last hour in mean-cli master

**Comment by JAppsAreUs** [comment]
@timelf123 @pashist oh ok! sorry, should have checked again before answering. Thanks, I'll try that now!

**Comment by JAppsAreUs** [comment]
Hi, just to get back to this issue I can create new packages now and the site will continue to work. However, adding my existing package with Mean-Cli 0.12.10 (which works in Mean-Cli 0.11.1) now causes the same angular error 'mean.xxx' is not available!'.

 Are there any incompatibilities between old packages and the new structure? I noticed that the public folders for existing 3rd party packages no longer contain the main js file where the angular  module and config for the package would exist.  For example, if i had created a "test" package, I would have had "test/public/test.js" where i would have a module defined, such as : 

```
angular.module('mean.test', []).config() {
}                                        
```

**Comment by JAppsAreUs** [comment]
So, I've been looking at this problem a bit more and it seems like my package's structure is completely out of date with the new structure. I noticed this by looking around the mean-admin repository and by creating a new package with the latest client. Is there any documentation on the changes that could help to get up to date? 

For example, I'm currently having a problem with the order of my imports in my index.js file. How do I set which of my imports get loaded first? Before, I used the aggregateAsset() function with a weight.

**Comment by timelf123** [comment]
Use webpack and import / require where necessary. Webpack will figure out where things need to be.

See meanStarter package for example

**Comment by JAppsAreUs** [comment]
Thanks @timelf123. I'm trying a few things with the index.js file but still getting some errors about libraries being missing even though they're added before the library requesting those resources. I'll try to figure things out a bit more on this end before getting back to you.

**Comment by timelf123** [comment]
@JAppsAreUs feel free to ping me in the gitter channel to discuss
