### ISSUE TITLE
Using SOAP with Node Js

### ISSUE THREAD

**Issue by ahaqshah** [linnovate/mean#1571]
Hey, hope you guys are doing well. 
 
I'm new to MEAN Stack, and i'm forced to use SOAP with Node js to integration with connect wise software. **The issue i'm facing is that when i parse XML in to JSON by using XML2JS module i got result in JSON like that**.

{"soap:Envelope":
	{"$":
			{"xmlns:soap":"http://schemas.xmlsoap.org/soap/envelope/","xmlns:xsi":"http://www.w3.org/2001/XMLSchema-instance","xmlns:xsd":"http://www.w3.org/2001/XMLSchema"},
	"soap:Body":
		[{"GetAgreementResponse":
 			[{"$":
 				{"xmlns":"http://connectwise.com"},
 				"GetAgreementResult":
 					[{
 						"Id":["19"],
 						"AgreementTypeId":["31"],
 						"AgreementName":["Managed Backup Service Agreement"],
 						"ParentAgreementId":["20"],
 						"CompanyId":["19319"],
 						"ContactId":["128"],
 						"CustomerPO":[""],
 						"LocationId":["11"],
 						"DepartmentId":["2"],
 						"RestrictLocationFlag":["false"],
 						"RestrictDepartmentFlag":["false"],
 						"StartDate":["2014-08-01T00:00:00"],
 						"EndDate":[{"$":{"xsi:nil":"true"}}],
 						"NoEndingDateFlag":["true"],
 						"OpportunityId":["0"],
 						"CancelledFlag":["false"],
 						"DateCancelled":[{"$":{"xsi:nil":"true"}}],
 						"ReasonCancelled":[""],
 						"SlaId":["2"],
 						"SubContractCompanyId":["0"],
 						"SubContractContactId":["0"],
 						"WorkOrder":[""],
 						"InternalNotes":[""],
 						"ApplicationUnits":["Hours"],
 						"ApplicationLimit":["0"],
 						"ApplicationCycle":["CalendarMonth"],
 						"PeriodType":[{"$":{"xsi:nil":"true"}}],
 						"ApplicationUnlimitedFlag":["true"],
 						"OneTimeFlag":["false"],
 						"CoverAgreementTime":["true"],
 						"CoverAgreementProduct":["false"],
 						"CoverAgreementExpense":["false"],
 						"CoverSalesTax":["false"],
 						"CarryOverUnused":["false"],
 						"AllowOverrruns":["false"],
 						"ExpiredDays":["0"],
 						"Limit":["0"],
 						"ExpireWhenZero":["false"],
 						"ChargeToFirm":["false"],
 						"EmployeeCompRate":["Actual"],
 						"EmployeeCompNotExceed":["Billing"],
 						"CompHourlyRate":["0.00"],
 						"CompLimitAmount":["0.00"],
 						"BillCycleId":["2"],
 						"BillOneTimeFlag":["false"],
 						"BillTermsId":[{"$":{"xsi:nil":"true"}}],
 						"InvoicingCycle":["ContractYear"],
 						"BillToCompanyId":[{"$":{"xsi:nil":"true"}}],
 						"BillToAddressId":[{"$":{"xsi:nil":"true"}}],
 						"BillAmount":["0.00"],
 						"Taxable":["false"],
 						"ProrateFirstBill":["0.00"],
 						"BillStartDate":["2014-08-01T00:00:00"],
 						"TaxCodeId":["8"],
 						"RestrictDownPayment":["false"],
 						"InvoiceDescription":[""],
 						"TopComment":["false"],
 						"BottomComment":["false"],
 						"WorkRoleId":[{"$":{"xsi:nil":"true"}}],
 						"WorkTypeId":[{"$":{"xsi:nil":"true"}}],
 						"ProjectTypeId":[{"$":{"xsi:nil":"true"}}],
 						"InvoiceTemplateId":[{"$":{"xsi:nil":"true"}}],
 						"BillTime":["Billable"],
 						"BillExpenses":["Billable"],
 						"BillProducts":["Billable"],
 						"BillableTimeInvoice":["true"],
 						"BillableExpenseInvoice":["false"],
 						"BillableProductInvoice":["false"],
 						"UpdatedBy":["ali            "],
 						"LastUpdate":["2014-08-01T11:03:30.143"]
 					}]
 				
 			}]
 		}]
 	}
}

**1) How could i retrieve  the data (means agreementId information) ?
2) How could i get specific tags information from xml like I just want , 
AgreementTypeId, AgreementName, CompanyId just like that information from it?
3) I have already use xml-stream, xpath and others. Can you please suggest me with code?

I'm stuck in it and i want help to resolve that issue. Thanks in advance.**

**Comment by timelf123** [comment]
This is not a support forum. Try https://stackoverflow.com
