### ISSUE TITLE
Mean Init <MyApp> does not create any MyAppFolder

### ISSUE THREAD

**Issue by kumar88kanishk** [linnovate/mean#1572]
Hi Community,

I followed the steps mentioned in http://learn.mean.io/#mean-stack-installation-install-the-mean-cli and got stuck at <b>mean init Todo </b> after that a question pops up <code>  What would you name your mean app? Todo</code> and nothing happens after that.

Thanks in advance.

**Comment by aseroj** [comment]
Same problem happens with me.
OS : OSX 
Mean version : 0.12.9

**Comment by pedroresende** [comment]
Same problem here
OS: Debian 8
mean-cli@0.12.9

**Comment by RenanRosa** [comment]
Same problem is happening to me.
OS: Windows 10
Mean Version: 0.12.9

**Comment by liorkesos** [comment]
You need to give a name to your app
Stuff changed in 0.6 and the mean starter directory will be renamed to your
new name
Lior

**Comment by espemi01** [comment]
I am having the same issue, and I have tried typing in a name at the prompt; no matter what I do it just silently fails out after the first prompt. Even tried running with sudo.
I (believe I) have all of the prereqs installed and updated.

Here is the term output:
```
[/Users/Michael/mean]
->mean init myApp
? What would you name your mean app? myApp
[/Users/Michael/mean]
->
```

**Comment by igorg1312** [comment]
Hello,

Mean init myapp script, create files, outside? Also Try to create ~./rhc
file with {} inside
Il 13 Mag 2016 18:27, "Michael Espey" <notifications@github.com> ha scritto:

**Comment by espemi01** [comment]
@igorg1312 
I just made ~/.rhc with only {} in it and ran mean init again to no avail. I even searched the whole drive and there was nothing created with "myApp" in the name or contained in a file or directory. I already have a mean app I have been working with for a while now, I just wanted to try something a bit different on a fresh build.

Let me know if there is anything else I can provide.
- Michael

**Comment by kumar88kanishk** [comment]
Hi community,
Did anyone get any potential solution for the issue?

**Comment by kumar88kanishk** [comment]
I got a solution that worked for me, 

Install Express and Express generator by running command
<code> npm install -g express</code>
<code> npm install -g express-generator </code>
<code> npm install -g mean-cli </code>

Hi community, kindly try this if this works for you or not.

**Comment by espemi01** [comment]
Strange, I have had express installed for ages, must have needed a min version, and mine didn't meet the mark. Got it working after updating everything. I didn't know it used the express generator, otherwise I would have tried to update it. Maybe a note should be added to the troubleshooting section of the docs ( http://learn.mean.io/#mean-stack-installation-troubleshooting ) to update some specific dependancies.

Thanks @kumar88kanishk , probably wouldn't have thought to try those.

-Michael
