### ISSUE TITLE
Server starts with no issues but the application does not load

### ISSUE THREAD

**Issue by RenanRosa** [linnovate/mean#1573]
The server starts but no request is answered. Can someone help me?

OS: Windows 10
Mean version: 0.11.1

![screenshot_1](https://cloud.githubusercontent.com/assets/5942669/15257330/3986df0c-191c-11e6-8fa1-5dcf2b36011b.png)

**Comment by DeepY0X** [comment]
same error
OS: OS X El Capitan
Mean version: 0.12.10

**Comment by igorg1312** [comment]
Same error...
Il 14 Mag 2016 17:20, "Ernie Rojas" <notifications@github.com> ha scritto:

**Comment by DeepY0X** [comment]
I tried with mean 0.11.1 version and I have the same error

**Comment by DeepY0X** [comment]
I tried with node version: v5.11.1 and mean version: 0.12.10 and it works

**Comment by deepalifutane** [comment]
Same error tied using following versions
MEAN version : 0.12.10, NodeJS version : v5.11.1

[00:09:49] Finished 'sass' after 14 s
Mean app started on port 3000 (development) cluster.worker.id: 0
GET / - - - - ms
[00:13:50] index.html reloaded.
[00:13:50] csslint: 3 files lint free
[00:13:50] Finished 'csslint' after 4.23 min
GET / - - - - ms
GET / - - - - ms
GET / - - - - ms

**Comment by igorg1312** [comment]
Same error
Il 14 Mag 2016 8:51 PM, "deepalifutane" <notifications@github.com> ha
scritto:

**Comment by kjvenky** [comment]
If its loading a white page. Look for the JS errors in the console. There can be few errors due to failure of dependency injection.

**Comment by muthuishere** [comment]
Same here for me...

**Comment by timelf123** [comment]
Try to clear you `node_modules` folder and `npm install` again

**Comment by deepalifutane** [comment]
Thanks @timelf123. Clearing out `node_modules `folder and running `npm install` helped and it worked!!

**Comment by RenanRosa** [comment]
Thank you @timelf123, its working now :)
