### ISSUE TITLE
How to override core packages in a smart and safe way

### ISSUE THREAD

**Issue by rubenjimenez** [linnovate/mean#1575]
Hi,

In previous MEAN versions, the core packages were accesible and we could modify them without any kind of problem. In the newest version, MEAN core packages are located inside node_modules so they are no longer available for modify them.

I guess you may be able to override them, but excepting views I have not figured out how to extend things like user model and so on.

A solution could be copy/paste the user core package and locate it inside packages/ folder, but I consider this is not the most elegant way to get what I want.

Any suggestion?

Thanks!

**Comment by nhvu1988** [comment]
fork it as your package and modify it, try to keep the remote to original repo so after that can pull any changes from it :)

**Comment by VikramTiwari** [comment]
Ongoing discussion here: https://github.com/linnovate/mean/issues/1549
