### ISSUE TITLE
documentation in the website

### ISSUE THREAD

**Issue by SK-CSE** [linnovate/mean#1576]
@mean.io team --  folder structure of created app is not as per the doc. the doc is old, please update the doc so that it will be easy for new developers to understand it.

Thanks

**Comment by igorg1312** [comment]
Hi folder structure client or server? I Have the same issue in doc, you
know if exist alternative doc?
Il 20 Mag 2016 9:21 AM, "SK-CSE" <notifications@github.com> ha scritto:

**Comment by SK-CSE** [comment]
@igorg1312 i have no idea whether alternative doc exist or not.. i hope they will update the docs as soon as possible

**Comment by gbevan** [comment]
+1
+ add docs on using Circles
+ in 0.6.1 aggregateAssets is replaced with WebPack
