### ISSUE TITLE
Set up an admin user is not working

### ISSUE THREAD

**Issue by RenanRosa** [linnovate/mean#1577]
Hello everyone!

When starting a new mean.io project and choosing to set up an admin user, the application does not requests a user name or email, neither password, like in the older mean.io versions.
By the way, my MongoDB is running with no issues. Can someone help me? Thanks

![error](https://cloud.githubusercontent.com/assets/5942669/15429039/20abb0ee-1e75-11e6-9454-d03967239ea9.png)

**Comment by nidhinprath** [comment]
Yes i think its something to do with new mean push. Anyway after the site is up and running, go and register as a user from Top right bar

And using mean cli type this :-1: 
mean user <your_signin_email> -a admin

**Comment by rivkabenshalom** [comment]
@RenanRosa  fixed.
You can now  install again mean-cli:
- sudo npm uninstall -g mean-cli
- sudo npm install -g mean-cli
- mean init [appName]
