### ISSUE TITLE
Can't run node server.js

### ISSUE THREAD

**Issue by hoangphucvu** [linnovate/mean#1578]
I got this http://prnt.sc/b6qwhe  error when i try to run node server.js
So how can i fix it.Thanks for help.

**Comment by hackerunet** [comment]
Just run
$ node install package_name
where package_name is the missing dependency.
I solved the same this way.

**Comment by rivkabenshalom** [comment]
try again npm install swagger-node-express.
it is work!

**Comment by rivkabenshalom** [comment]
close
