### ISSUE TITLE
After installing with NO errors I only get a blank page after running gulp or node server

### ISSUE THREAD

**Issue by hackerunet** [linnovate/mean#1581]
This is my mean status:
MEAN Status
    -----------

```
MEAN VERSION: 0.6.1

DB connection successful!

MongoDB URI: mongodb://localhost/mean-dev

checking meanio and global mean-cli versions
mean-cli at latest version: 0.12.10
meanio at latest version: 0.9.1
```

After running node server, All iget is 

```
for real!
forking  0
Mean app started on port 3000 (undefined) cluster.worker.id: 1
GET / - - - - ms
GET / - - - - ms
GET /public - - - - ms
GET / - - - - ms
```

So, I fixed the config/env/development.js file to serve the gulp service in 192.168.1.9 address because is a virtual ubuntu 16.0 server .
The same with gulp, it serves the web service but blank page returned. fresh installs doesn't have to show at least a dummy page saying Hello welcome to hell?
thanks

**Comment by igorg1312** [comment]
@hackerunet same issue on 0.5.5, also crash when creating admin user,
without admin user i same  console log and blank page: (have you try with
0.6.1, i will check later)
Mean app started on port 3000 (development) cluster.worker.id: 0
[08:55:35] index.html reloaded.

packages/custom/welcome/public/tests/example.js
  line 2  col 5  Missing "use strict" statement.

  ✖  1 error  ⚠  0 warning

[08:55:35] jshint: 27 files lint free
[08:55:35] Finished 'jshint' after 1.69 s
GET / 200 - - 74.708 ms
GET /bundle/app.js 404 - - 10.311 ms
GET /favicon.ico 200 - - 2.460 ms



2016-05-26 6:14 GMT+02:00 hackerunet <notifications@github.com>:

> This is my mean status:
> MEAN Status
> -----------
>
> MEAN VERSION: 0.6.1
>
> DB connection successful!
>
> MongoDB URI: mongodb://localhost/mean-dev
>
> checking meanio and global mean-cli versions
> mean-cli at latest version: 0.12.10
> meanio at latest version: 0.9.1
>
> After running node server, All iget is
>
> for real!
> forking  0
> Mean app started on port 3000 (undefined) cluster.worker.id: 1
> GET / - - - - ms
> GET / - - - - ms
> GET /public - - - - ms
> GET / - - - - ms
>
> So, I fixed the config/env/development.js file to serve the gulp service
> in 192.168.1.9 address because is a virtual ubuntu 16.0 server .
> The same with gulp, it serves the web service but blank page returned.
> fresh installs doesn't have to show at least a dummy page saying Hello
> welcome to hell?
> thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1581>
>



-- 

*Igor Garofano*

**Comment by hackerunet** [comment]
I'm starting to think that there is no stable implementation of a very single framework done in node.js 
I tested Sails, and at least it works after installation, but when using mongo and roles, it messed up everything, so, Why lot of people is working with node.js if a new developer is not able to at least bring the service up to start coding ASAP? what's the agile part of this frameworks? honnestly, I think quantity of possible developers is foced to get decreased because of the very fact that we cannot start developing immediatly after framework is installed. those kind of things never happen with PHP, Python, C++, Ruby and so on. So, I'm in the moment when I have to choose what to do, going further with this or just change entirely to another technology as python. and Honnestly I think I'm going back to php or moving forward to python.

**Comment by hackerunet** [comment]
This case is very similar as this one, so maybe it's the same
https://github.com/linnovate/mean/issues/1567
