### ISSUE TITLE
npm install gives out  ELIFECYCLE  and bower install error

### ISSUE THREAD

**Issue by erdemtoraman** [linnovate/mean#1582]
npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! meanio-users@0.1.4 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanio-users@0.1.4 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meanio-users package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meanio-users
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meanio-users
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/yyy/mean/npm-debug.log

I got the latest node and npm.

**Comment by timelf123** [comment]
You need to upgrade your mean.io to 0.6.1 by pulling changes from upstream. bower.json does not exist anymore in meanio-users
