### ISSUE TITLE
Server side js code does not exist

### ISSUE THREAD

**Issue by adskiremote** [linnovate/mean#1586]
Hi,

the server js files do not exist only the views folder does. As per the documentation here:

Packages are registered in the app.js Defines package name, version and mean=true in the package.json

All of the Server side code resides in the /server directory.
Server
--- config        # Configuration files - NOT FOUND
--- controllers   # Server side logic goes here - NOT FOUND
--- models        # Database Schema Models - NOT FOUND
--- routes        # Rest api endpoints for routing - NOT FOUND
--- views         # Swig based html rendering  - EXISTS

Is there a git repo to clone for these?

**Comment by timelf123** [comment]
There is no /server directory in root, it is found in `packages/custom/pkgName/server` or `node_modules/meanio-*/server"

**Comment by adskiremote** [comment]
They are not in packages/custom/pkgName/server either.
views exist but nothing else.  I have generated several apps to see if this always happens. 
It does.

**Comment by timelf123** [comment]
Are you scaffolding a new package with mean-cli?

**Comment by adskiremote** [comment]
Yes - I just follow the instructions for creating a new package.

mean init yourNewApp

**Comment by timelf123** [comment]
Sorry, seems the cli has some issues still. Feel free to crosspost this issue in mean-cli.

You can create these folders on your own. Look at the `meanStarter` or any other meanio-* package for an example

**Comment by adskiremote** [comment]
Sorry but can you tell me where to look in meanStarter for these.  In your repository I don't see them either:  https://github.com/linnovate/mean/tree/master/packages/custom/meanStarter/server

**Comment by harishreddy-m** [comment]
Adding a REST route is not working
I added a hello.js file in /packages/custom/appname/server/routes/

This is the content of hello.js file 

```'use strict'
module.exports = function(MeanStarter, app, auth, database) {
  app.get('/hello', function (req,res,next) {
    res.send('Anyone can access this');
  });
};
```


Curl http://localhost:3000/hello is giving html output

How to add a REST endpoint?
