### ISSUE TITLE
Cannot find module 'npm'

### ISSUE THREAD

**Issue by gamevnlc** [linnovate/mean#1595]
Hi guys, I am just new on mean, i have problem when running commands "mean list" , "mean uninstall" ..etc. I got this error but I don't know how to fix. Please help me . Thank you . Sorry for my English.
p/s I already installed node

![image](https://cloud.githubusercontent.com/assets/2215185/16173055/c6313640-35bf-11e6-9d54-ebdf50630483.png)

**Comment by SungjungKim** [comment]
@gamevnlc  Maybe this problem due to your NODE_PATH. You have to install the npm globally. check out this page http://stackoverflow.com/questions/12594541/npm-global-install-cannot-find-module

**Comment by gamevnlc** [comment]
@SungjungKim 
Thank you for your advice. But i think it isn't problem, because I can using npm command line to install global or local package. I don't change the setting NODE_PATH and NODE_MODULES variables, things are still installed in %appdata%\npm by default.

**Comment by timelf123** [comment]
Try `npm install npm@latest-2`

**Comment by suzet** [comment]
same problem here..
npm run globally but did not working while mean status, mean package
any solution please

**Comment by timelf123** [comment]
Try again with npm > 3

**Comment by jacogreyling** [comment]
I'm having the same problems. Should I first install a project and run it from that (e.g. myApp) directory? I can confirm that npm works perfectly fine from the command line.

**Comment by twillard** [comment]
I resolved this locally by defining an environment variable NODE_PATH and setting it to C:\Program Files (x86)\nodejs\node_modules\

**Comment by Nezzit** [comment]
Anyone have a solution for this one?

**Comment by sasha6806** [comment]
The reason is the location of NPM is different from other npm packages. Copy NPM to the directory of other npm packages. That's OK.
Under Windows 10, NPM is in the C:\Program Files\nodejs\
npm, npm.cmd, and node_modules\npm\*
But other npm packages are in the directory C:\Users\USERNAME\AppData\Roaming\npm
So copy npm, npm.cmd, and node_modules\npm\* to this diretory.

**Comment by dev-sflircs** [comment]
I'm having the same problem. Then I try `npm install npm@latest -g` 
It's work.

**Comment by jessemull** [comment]
Installing npm globally could also work. sudo npm install -g npm

**Comment by reaves-tyler** [comment]
`npm install npm@latest -g`

This worked for me, thanks @dev-sflircs

**Comment by Andraw-lin** [comment]
```npm install npm@latest -g```
worked for me too, thanks
