### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by f1lander** [linnovate/mean#1596]
Hi! I'm working on a project with mean.io generator, in the past everything was ok but a few days ago I started to got this error:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:546:26)
```

I tried to remove the task wich raise up the livereload in gulp file but it's still give this error.

I would appreciate any help! 

Thanks,

**Comment by timelf123** [comment]
I am having the same issue, seemingly out of the blue. Haven't found a fix yet
