### ISSUE TITLE
unresolved dependencies

### ISSUE THREAD

**Issue by luvsin27** [linnovate/mean#1609]
#### I'm opening this issue because:
- [x] npm package has unresolved dependencies
#### What's going wrong?

not able to execute gulp because of unresolved dependencies admin,meanStarter
#### How can the CLI team reproduce the problem?

invoking gulp gives me the following error
[16:09:42] Finished 'webpack:build-dev' after 9.83 s
[16:09:42] Starting 'development'...
[16:09:42] Finished 'development' after 3.23 μs
Debugger listening on [::]:5858

/home/luves/test/node_modules/q/q.js:155
                throw e;
                ^
Packages with unresolved dependencies: admin,meanStarter
[16:09:43] [nodemon] app crashed - waiting for file changes before starting...

### supporting information:
- `npm -v` prints:3.10.3
- `node -v` prints:6.3.0
- `npm config get registry` prints:https://registry.npmjs.org/
- Windows, OS X, or Linux?:Linux Ubuntu 16.04

**Comment by timelf123** [comment]
`npm install` 

or try `npm run postinstall`

**Comment by luvsin27** [comment]
Already did that with superuser command and installed bower with --allow-root,still getting the same response.I even tried compilation with the current stable node version (6.2.2) and also with the LTS version.

**Comment by timelf123** [comment]
Did you install with mean-cli or cloning this repo?

**Comment by luvsin27** [comment]
I installed mean cli using npm.

MEAN Status
    -----------
MEAN VERSION: 0.6.1

    DB connection successful!

    MongoDB URI: mongodb://localhost/mean-dev

    checking meanio and global mean-cli versions
    mean-cli at latest version: 0.12.14
    meanio at latest version: 0.9.3

**Comment by nostick** [comment]
i got the same issue :(

**Comment by HenleyKuang** [comment]
Hi, I don't mean to bump an old thread, but I'm having the same issue with gulp. Were you ever able to fix it? If so, please share  Thank you.

**Comment by timelf123** [comment]
This issue is a symptom of your npm build failing to install a required dependency. clearing your node_modules and cache and reinstalling `npm i` should fix it
