### ISSUE TITLE
Cannot install webpack to run gulp

### ISSUE THREAD

**Issue by ntvinhit** [linnovate/mean#1627]
`├─┬ css-loader@0.23.1
│ └─┬ postcss@5.1.1
│   └── supports-color@3.1.2
├─┬ gulp-uglify@2.0.0
│ └─┬ uglify-js@2.7.0
│   ├── async@0.2.10
│   └─┬ yargs@3.10.0
│     ├── camelcase@1.2.1
│     └── window-size@0.1.0
├─┬ jsonwebtoken@7.1.7
│ └─┬ jws@3.1.3
│   └─┬ base64url@1.0.6
│     └─┬ meow@2.0.0
│       └─┬ camelcase-keys@1.0.0
│         └── camelcase@1.2.1
├─┬ karma-coverage@1.1.1
│ └─┬ istanbul@0.4.4
│   └── supports-color@3.1.2
├─┬ meanio@0.9.3
│ ├─┬ express-jwt@3.4.0
│ │ └── jsonwebtoken@5.7.0
│ ├─┬ snyk@1.16.0
│ │ └─┬ snyk-policy@1.5.0
│ │   └── es6-promise@3.2.1
│ └─┬ swig@1.4.2
│   └─┬ uglify-js@2.4.24
│     ├── async@0.2.10
│     └─┬ yargs@3.5.4
│       ├── camelcase@1.2.1
│       └── window-size@0.1.0
├─┬ mocha@3.0.1
│ └── supports-color@3.1.2
├─┬ phantomjs-prebuilt@2.1.10
│ └── es6-promise@3.2.1
├─┬ snyk@1.18.0
│ ├─┬ snyk-config@1.0.1
│ │ └─┬ nconf@0.7.2
│ │   └─┬ yargs@3.15.0
│ │     └── camelcase@1.2.1
│ ├─┬ snyk-policy@1.5.2
│ │ └── es6-promise@3.2.1
│ ├─┬ snyk-resolve-deps@1.7.0
│ │ └─┬ clite@0.3.0
│ │   └── es6-promise@3.2.1
│ └─┬ snyk-try-require@1.1.1
│   └── es6-promise@3.2.1
├── UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta
└─┬ webpack-dev-server@1.14.1
  ├── supports-color@3.1.2
  └── UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "webpack"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/var/www/public/mean/node_modules/.bin/acorn'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "webpack"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path npm-debug.log.415732df4fe12569e0883f175d371421
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.415732df4fe12569e0883f175d371421' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/public/mean/npm-debug.log
`
This is my npm-debug.log file
https://drive.google.com/a/tnv.edu.vn/file/d/0Bws1-aZK3kVvS0VtVzJOY1pqRVE/view?usp=sharing

I'm using Vagrant Scotchbox (Ubuntu 14.04) as dev environment.

Please tell me how should I do to fix this. 
Thank you

**Comment by timelf123** [comment]
Likely it has to do with permissions (or not support symlinks) in your host box. If a Windows machine, try `npm install --no-bin-links`  or `npm rebuild node-sass --no-bin-links` or see the following 
- [ ] [update Vbox](https://www.virtualbox.org/ticket/14563)
- [ ] https://github.com/npm/npm/issues/9901
- [ ] in vagrant guest, symlink the app's node modules dir to a tmp folder of guest `mkdir ~/tmp_node_modules && ln -s ~/tmp_node_modules ./node_modules`, and then run `npm install`

That being said, this is not a support forum for Vagrant so we won't be able to do much for you here. This is more a question for [StackOverflow ](https://stackoverflow.com) our [Gitter chat](https://gitter.im/linnovate/mean).
