### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by 3stacks** [linnovate/mean#1628]
After attempting to run the default gulp task, it has been sequentially failing on missing dependencies.

So far it has failed on:

- cookie-parser
- express-validator
- method-override
- passport

Whose package.json are these supposed to belong to? It was my assumption they were supposed to come through under meanio-users or somewhere in there, however, npm-install doesn't grab those modules.

**Comment by timelf123** [comment]
try deleting the npm-shrinkwrap.json and running `npm i` again

**Comment by timelf123** [comment]
Please reopen if you still are experiencing issues
