### ISSUE TITLE
Mean upload package is missing from github

### ISSUE THREAD

**Issue by sujitkumar01** [linnovate/mean#1629]
Hi All,

I am using mean "upload" module for one of the critical feature in my application and now this module is missing from github, can you please help me to restore this module??

Here is my application detail :
mean cli  --version : 0.9.21
meanio :  0.6.17
overall mean version of 0.4.2

Thanks & Regards,
Sujit kumar

**Comment by liorkesos** [comment]
In latest mean I think you can find it in meanio-upload in npm

**Comment by sujitkumar01** [comment]
The command that run is `mean install upload` and it is now failing with package not found. 
what the correct way to install it is for our version of meanio/cli ??

**Comment by sujitkumar01** [comment]
Can some one help me on this ???
