### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ychen0131** [linnovate/mean#1631]
Hi, I got this error when I was trying to start the application by running 'gulp' in the command window. I have tried troubleshooting methods in the docs but the problem still exits.

Error: ENOENT: no such file or directory, scandir '/Users/DARS/Documents/kkkk/meanApp/node_modules/gulp-sass/node_modules/node-sass/vendor'

Any idea how should I make this work?

**Comment by timelf123** [comment]
`npm install node-sass`
or `npm rebuild node-sass`

**Comment by ychen0131** [comment]
@timelf123 That solved it, thank you so much
