### ISSUE TITLE
mean init MyApp keeps "still cloning" for several days

### ISSUE THREAD

**Issue by lf497003619** [linnovate/mean#1632]
When I try to init MyApp in my Docker container, the process keeps showing "still cloning" for days and no error no break. After checking the server, the network connection is slow indeed but not disconnected, it just does not make sense to keep cloning for days.

**Comment by timelf123** [comment]
Try removing snyk: true from your package.json file

**Comment by lf497003619** [comment]
Seems my package.json file don't have this line.
All the components are up to date. Network connection is also checked, `npm install` and `apt-get install` both works fine and download is smooth.
Still cannot figure out the reason for this problem...

**Comment by rjVapes** [comment]
@lf497003619 If this is still an issue, can you post some output for what you're seeing, some debug info etc.  Also what Dockerfile you're using.

**Comment by wangyuzuo1999** [comment]
@lf497003619 I have seen this issue too.
When the screen appears**? What would you name your mean app? myMeanApp**,
I hit the keyboard on the "yes", it appears this issue.
Try to **mean init myMeanApp** after the operation, what are not input, directly hit the Enter key
