### ISSUE TITLE
Fresh install never responding and no error messages

### ISSUE THREAD

**Issue by ladamiak** [linnovate/mean#1633]
I new on mean.io and I'm trying to run the "yourNewApp", but it's not working.

I did the "mena init yourNewApp", then npm install and bower install, then gulp.
The server starts, but when I request localhost:3000 I never get an answer.

So I tried to run like "node server" and again, the server starts, but my requests never get an answer.

After that I created a new app by cloning the git repository, npm install, bower intall and gulp and, again, my requests to http://localhost:3000 never get an answer.

My versions are:
NODE: v4.4.7
BOWER: 1.7.9
NPM: 2.15.8
MEAN: 0.12.14

We're considering the mean.io as a possible platform for our new App and this is really a show stopper.
I appreciate any help...

**Comment by AlexLRodrigues** [comment]
Same problem

**Comment by liorkesos** [comment]
What version of node/npm are you using?

**Comment by AlexLRodrigues** [comment]
node --version
v4.4.7
npm --version
2.15.8

**Comment by liorkesos** [comment]
Try to upgrade to npm v3 . Remove node_modules and nom install

**Comment by AlexLRodrigues** [comment]
Thanks! Problema solved. I just remove all things and install again using updated npm v3

**Comment by ladamiak** [comment]
In my case it is NODE: v4.4.7 / NPM: 3.10.6.
Still I can't make it work.

Any help would be great, since we're deciding what architecture to use this week.

[npm-debug-log.txt](https://github.com/linnovate/mean/files/430778/npm-debug-log.txt)

**Comment by timelf123** [comment]
```
167691 silly lifecycle mean@0.6.1~prepublish: Args: [ '/d /s /c', 'npm run snyk-protect' ]
167692 silly lifecycle mean@0.6.1~prepublish: Returned: code: 1  signal: null
167693 info lifecycle mean@0.6.1~prepublish: Failed to exec prepublish script
167694 warn optional Skipping failed optional dependency /chokidar/fsevents:
167695 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
167696 verbose stack Error: mean@0.6.1 prepublish: `npm run snyk-protect`
167696 verbose stack Exit status 1
167696 verbose stack     at EventEmitter.<anonymous> (C:\Users\luciano.adamiak\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
167696 verbose stack     at emitTwo (events.js:87:13)
167696 verbose stack     at EventEmitter.emit (events.js:172:7)
167696 verbose stack     at ChildProcess.<anonymous> (C:\Users\luciano.adamiak\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
167696 verbose stack     at emitTwo (events.js:87:13)
167696 verbose stack     at ChildProcess.emit (events.js:172:7)
167696 verbose stack     at maybeClose (internal/child_process.js:827:16)
167696 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
167697 verbose pkgid mean@0.6.1
167698 verbose cwd d:\RSI Transformative\node\meanio\MyApp2
167699 error Windows_NT 6.2.9200
167700 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\luciano.adamiak\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
167701 error node v4.4.7
167702 error npm  v3.10.6
167703 error code ELIFECYCLE
167704 error mean@0.6.1 prepublish: `npm run snyk-protect`
167704 error Exit status 1
```
@liorkesos
