### ISSUE TITLE
mean package request /example/anyone 404

### ISSUE THREAD

**Issue by Narsiss** [linnovate/mean#1643]
After npm install, I create a pakage by 'mean package livetest',
then I sent request as 'http://localhost:3000/api/livetest/example/anyone',
but it returned 404 error: /api/livetest/example/anyone 404 - - 4.708 ms
    MEAN Status
    -----------

```
MEAN VERSION: 0.6.1

DB connection successful!

MongoDB URI: mongodb://localhost/mean-dev

checking meanio and global mean-cli versions
mean-cli at latest version: 0.12.10
meanio at latest version: 0.9.3
```

**Comment by Narsiss** [comment]
http://localhost:3000/gotlive/example/anyone

**Comment by Narsiss** [comment]
http://localhost:3000/livetest/example runs well,
but http://localhost:3000/livetest/example/anyone throw errors like:

<!doctype html> <html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="https://www.facebook.com/2008/fbml" itemscope="itemscope" itemtype="http://schema.org/Product"> <!DOCTYPE html> <head> <base href="/"> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <meta name="viewport" content="width=device-width,initial-scale=1"> <meta name="fragment" content="!"> <title>MEAN - A Modern Stack - Development - MEAN - A Modern Stack - Development</title> <meta http-equiv="Content-type" content="text/html;charset=UTF-8"> <meta name="keywords" content="node.js, express, mongoose, mongodb, angularjs, swig"> <meta name="description" content="MEAN - A Modern Stack: MongoDB, ExpressJS, AngularJS, NodeJS. (BONUS: Passport User Support)."> <meta property="fb:app_id" content="APP_ID"> <meta property="og:title" content="MEAN - A Modern Stack - Development - MEAN - A Modern Stack - Development"> <meta property="og:description" content="MEAN - A Modern Stack: MongoDB, ExpressJS, AngularJS, NodeJS. (BONUS: Passport User Support)."> <meta property="og:type" content="website"> <meta property="og:url" content="APP_URL"> <meta property="og:image" content="APP_LOGO"> <meta property="og:site_name" content="MEAN - A Modern Stack"> <meta property="fb:admins" content="APP_ADMIN"> <link rel="manifest" href="/system/assets/static/manifest.json">  </head> <body data-ng-controller="StarterController" ng-cloak class="ng-cloak" ng-class="state"> <div class="navbar navbar-inverse navbar-fixed-top" data-ng-include="'/meanStarter/views/system/header.html'" data-role="navigation"></div> <div data-ng-include="'/admin/views/index.html'"></div> <section class="content"> <section class="container"> <div id="error-message-box"> <div id="error-stack-trace"> <pre> <code>Not found</code> </pre> </div> </div> </section> </section> <script type="text/javascript" src="/bundle/app.js"></script> <script type="text/javascript" src="//localhost:35729/livereload.js"></script> </body> </html>

**Comment by VikramTiwari** [comment]
@Narsiss This shouldn't have happened. If you have solved it, can you please put some details here so that others can benefit from your knowledge and not get stuck on similar issues. Thanks! 👍

**Comment by timelf123** [comment]
it's returning the full index.html as the error. I've noticed that our error handling could use some love but haven't dove in yet
