### ISSUE TITLE
Readme typo and missing links

### ISSUE THREAD

**Issue by Ednas** [linnovate/mean#1645]
In the readme.md file
Under headings Prerequisite Technologies, Linux, Node.js (line 11):
preffered --> preferred

Under Technologies The MEAN stack,
Missing links to resources for Mongo, Express and Node. Reference to a StackOverflow thread, but no link. 
Suggestions for missing links:
MongoDB site: https://www.mongodb.com/
MongoDB manual: https://docs.mongodb.com/manual/
Express: http://expressjs.com/
Express Guide: http://expressjs.com/en/guide/routing.html
StackOverflow thread on Express: Unknown
Node: https://nodejs.org
StackOverflow thread on Node: Unknown
Node docs: https://nodejs.org/en/docs/

**Comment by VikramTiwari** [comment]
@Ednas Would you like to update readme with remaining links as well?

**Comment by Ednas** [comment]
@VikramTiwari Sure. I'm not sure what the original author had in mind when mentioning StackOverflow. 
I have found two threads that I believe would be helpful. I'll update with these.
Express: http://stackoverflow.com/q/8144214/6115857 
Node:  http://stackoverflow.com/q/2353818/6115857

**Comment by VikramTiwari** [comment]
Fixed! @Ednas if you would find any other issues with documentation, please feel free to reopen the issue. Thanks for your contribution.
