### ISSUE TITLE
material design support for next release

### ISSUE THREAD

**Issue by VikramTiwari** [linnovate/mean#1648]
There have been discussions around making Material Design as primary CSS framework for MEAN stack. I was working on that today and here's a quick checklist of things that should be done before we can properly support that.

- [x] Material replaces Bootstrap as frontend dependency
- [x] Redesign of server templates and public html files for system package
- [x] Redesign of public pages for user packages
- [x] meanio-admin with material package
- [x] meanio-circles with material package

I just finished first two tasks and will be pushing those in `feature_material_design` branch. More updates will come here.

**Comment by VikramTiwari** [comment]
@linnovate/mean-contributors Could someone review this? Would like this to be done by end of this weekend.

**Comment by VikramTiwari** [comment]
Both `meanio-circles` and `meanio-admin` are now material compatible on branch v0.7 in their repositories.

Note:
- MEAN token functionality is not there in those packages since tokens is not a core package as of now.
- Design everywhere could be improved by a lot but currently, the aim is to provide support. We can improve that later.

**Comment by VikramTiwari** [comment]
Well! If there aren't any concerns over this in next few days, I will be merging the associated PR to master and release as a new tag v0.7 @linnovate/mean-contributors any feedback will be helpful.

**Comment by liorkesos** [comment]
I'll check it out.
Sounds great..
Lior

**Comment by VikramTiwari** [comment]
Completed and released at v0.7
