### ISSUE TITLE
What does app.locals.cache = 'memory'; actually do?

### ISSUE THREAD

**Issue by CareerFairPlus** [linnovate/mean#1651]
```
// cache=memory or swig dies in NODE_ENV=production
app.locals.cache = 'memory';
```
I'm trying to understand more about this line of code in the express config file.  I have a few questions:

1. Why is this needed for `NODE_ENV=production`?
2. Does it have any other implications other than ensuring swig works properly?  
3. Are there other options other than `'memory'`?
4. Does this cause large JSON responses to remain in memory for any period of time?

I tried researching this on the expressjs API site, but they don't specifically talk about this cache variable.  Seems to be specific to MEAN.io.

**Comment by timelf123** [comment]
It looks to be a workaround for an old consolidate.js issue https://github.com/tj/consolidate.js/commit/e84860d55b2cb938c9a5525f83feba7f86dfeba7#commitcomment-6427166

That being said I'm not sure of the other implications

**Comment by CareerFairPlus** [comment]
Thanks!  I will enquire on express' GitHub.

**Comment by timelf123** [comment]
Feel free to comment if you have any more information
