### ISSUE TITLE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "snyk-protect"

### ISSUE THREAD

**Issue by iamromeo** [linnovate/mean#1654]
> mean@0.6.1 snyk-protect /var/www/lostkingdomapi
> snyk protect

sh: 1: snyk: not found

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "snyk-protect"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mean@0.6.1 snyk-protect: `snyk protect`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mean@0.6.1 snyk-protect script 'snyk protect'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     snyk protect
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/lostkingdomapi/npm-debug.log

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-optional"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! mean@0.6.1 prepublish: `npm run snyk-protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean@0.6.1 prepublish script 'npm run snyk-protect'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run snyk-protect
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/lostkingdomapi/npm-debug.log

**Comment by adrukh** [comment]
Please run `npm install` locally to get the `snyk` dependency installed.
Validate with `npm run snyk-protect`

**Comment by iamromeo** [comment]
Today I tried again and I got the following error.
I am running this on Ubuntu 14.04 on a Vagrant Machine (TRUSTY) 


-----


npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.5.0/bin/node" "/home/vagrant/.nvm/versions/node/v4.5.0/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! path /vagrant/test/lk/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/test/lk/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/test/lk/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/test/lk/npm-debug.log

**Comment by timelf123** [comment]
Please reopen if you still are experiencing issues, but as @adrukh mentioned, this is due to your missing snyk package
