### ISSUE TITLE
ENOENT Error during installation

### ISSUE THREAD

**Issue by iamromeo** [linnovate/mean#1657]
[npm-debug.log.zip](https://github.com/linnovate/mean/files/455515/npm-debug.log.zip)

System: Ubuntu 14.04 (Vagrant / Trusty) 
node: 4.5 (installed using NVM)
npm: 3.10.6

npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.5.0/bin/node" "/home/vagrant/.nvm/versions/node/v4.5.0/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! path /vagrant/test/lk/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/test/lk/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/test/lk/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/test/lk/npm-debug.log

**Comment by timelf123** [comment]
This is likely an NPM issue not a core mean issue. Does the build fail every time with the same package?

**Comment by rjVapes** [comment]
The structure of your node_modules suggests that it was originally installed with a version lower than 3.0, as 3.0 favors a flat directory structure.  Could you try clearing your npm cache and re-running npm install?
