### ISSUE TITLE
add "one-click-deploy" buttons

### ISSUE THREAD

**Issue by VikramTiwari** [linnovate/mean#1660]
- [ ] [Heroku](https://devcenter.heroku.com/articles/heroku-button)
- [ ] Google Cloud Platform
- [ ] Docker Images

Add more.

**Comment by timelf123** [comment]
I have a working app.json template used to set up review apps for new github PRs (heroku's pipeline feature) and will clean it up and post in a bit

**Comment by VikramTiwari** [comment]
I just added Docker on the list. We should have ready to use Docker images as well, and automatic processes for this as well.

**Comment by timelf123** [comment]
Here is a quick sample app.json for heroku: 
```
{
  "name": "meanio",
  "scripts": {
  },
  "env": {
    "CPU_COUNT": {
      "value": "2"
    },
    "DB_PORT_27017_TCP_ADDR": {
      "value": ""
    },
    "ENFORCE_SSL": {
      "value": ""
    },
    "HEROKU_URL": {
      "value": ""
    },
    "NODE_ENV": {
      "value": "production"
    },
    "NODE_MODULES_CACHE": {
      "value": "false"
    },
    "NPM_CONFIG_PRODUCTION": {
      "value": "false"
    }
  },
  "formation": {
    "web": {
      "quantity": 1
    }
  },
  "addons": [
    "scheduler",
    {
      "plan": "mongolab:sandbox",
      "as": "MONGO"
    }
  ],
  "buildpacks": [
    {
      "url": "heroku/nodejs"
    }
  ]
}

```

**Comment by VikramTiwari** [comment]
Awesome! This looks good. If you wanna raise a PR for this, should go forward. I will be working on it during the weekend, so if things are there already, it will be easier to iterate upon.

**Comment by timelf123** [comment]
I'm not able to contribute a lot of code atm, but the above example should serve as a good jumping off point for heroku
