### ISSUE TITLE
SSL Validation Error For Upload URL

### ISSUE THREAD

**Issue by sujitkumar01** [linnovate/mean#1662]
Hi All,

As below URL : https://github.com/linnovate/mean-upload

Upload module has been moved to new location UR: : https://git.mean.io/orit/upload

But this URL SSL validation certificate has been expired on 2nd Aug 2016. So new location of Upload cant be trusted.

Can Anyone help me to resolve this issue.

Thanks & Regards,
Sujit kumar

**Comment by VikramTiwari** [comment]
Related to this: https://github.com/linnovate/meanio/issues/117#issuecomment-246705899

Even though that SSL cert has expired you can trust the [GitHub package link](https://github.com/linnovate/mean-upload) for your needs.

Closing this. Follow up on the linked issue.

**Comment by sujitkumar01** [comment]
I have a question here : Both Upload repository are different and their commit dates are also different. 
First Repository : https://github.com/linnovate/mean-upload
Second Repository : https://git.mean.io/orit/upload
Which Repository should we prefer ??

**Comment by VikramTiwari** [comment]
My bad! Didn't see the message on [readme](https://github.com/linnovate/mean-upload/blob/master/README.md) earlier. You should use https://git.mean.io/orit/upload.

**Comment by sujitkumar01** [comment]
But for URL : https://git.mean.io/orit/upload , SSL cert has already been expired on 2nd Aug 2016.  How to resolve this issue ??

**Comment by sujitkumar01** [comment]
@VikramTiwari Can you please re-open this issue, i don't think this issue has been resolved ?

**Comment by VikramTiwari** [comment]
@oritpersik If you have local copy, could you please upload it to GitHub and link it here? If not, download the code and init a new repo.

@liorkesos You should be able to pretty easily remove HTTPs from server. We can't clone the repos  with a bad SSL cert.

**Comment by sujitkumar01** [comment]
@VikramTiwari i appreciate if this issue get resolve as soon as possible.

**Comment by timelf123** [comment]
mean-upload in a zip format was posted to gitter.im last week
