### ISSUE TITLE
[Feature] Package upgrade to Angular2.0?

### ISSUE THREAD

**Issue by andrew-h-lee** [linnovate/mean#1664]
I notice the `package.json` has `angular: 1.5.5`.

I was just wondering if the next iteration (or Version of Project) will consider `angular: 2.0.0` now that Google finally confirmed its Final Stabilisation?

Will this Project still continue to use Angular1.x (until LTS stops for Angular1.x) OR start Future versions with Angular2?

**Comment by andrew-h-lee** [comment]
Thanks @VikramTiwari  for the clarification. Looking Forward for the `MEAN 2.0` Project. Will keep an eye on this thread on Updates.

**Comment by liorkesos** [comment]
Aron from my team has been looking in to this were pretty sure it will be
managed in a separate branch and not an organic iteration.
We need both projects to coexist and to be able to evolve independently.
Lior

**Comment by andrew-h-lee** [comment]
@liorkesos , do you mean Two separate Versions of `mean.io`, similar to the Nodejs Project (Two different Versions: LTS Stable Ver => `4.5.0` & Current Stable Ver => `6.5.0`) ?
I'm sure it can be done, just need to inform Users the difference in Versions.
For example, `Version 0.5.x` contains Angular1.x, Express4.x, etc.
Whereas, `Version 1.x.x` contains Angular2.0, Express5.x, Node6.5.0, etc.

**Comment by liorkesos** [comment]
Yes something like that, This will free existing community members to dive in to angular2, es6 on server etc...
I just think that the versions will be 1.x for angular 1 and 2.x for 2

**Comment by timelf123** [comment]
IMHO Angular 2 can live outside of the upgrades to Express >5.x, Node >6.5. The app already runs on Node 6.5 and [the differences between Express 4 and 5 are minimum.](https://expressjs.com/en/guide/migrating-5.html)

Example of some small change to express.
> res.json(obj, status)
> Express 5 no longer supports the signature res.json(obj, status). Instead, set the status and then chain it to the res.json() method like this: res.status(status).json(obj).

**Comment by nicostuhlfauth** [comment]
Any news about when Angular 2 support will be available?

**Comment by deepdil-enfin** [comment]
hey guys,
what is the status of angular 2 to the project? Where can i use mean with angular2

**Comment by JohnnyWalkerDesign** [comment]
Also wondering how this is progressing.

**Comment by Githamza** [comment]
Any news about migration ?

**Comment by timelf123** [comment]
This work is not on the roadmap, and is not being done atm
