### ISSUE TITLE
How to use Circles as middleware for acl?

### ISSUE THREAD

**Issue by mindstorm360** [linnovate/mean#1668]
I've been trying to play with mean.io and circles as a way to do acl (well prob more rbac). I'm fairly new to mean.io and the concept of Circles. It's my understanding that this can be used for authorization (all/deny access to a resource). However, I am lost at how to tie to into my custom packages. I see this in the comments of the circles app.js:

// Y Override queries to check user permisisons

What's the best way to approach this? If there are any examples/documentation, please send me in that direction. The only thing I could find was this https://github.com/linnovate/mean/wiki/Circles

**Comment by timelf123** [comment]
Add permissions array to model of package you want to protect:
```
permissions: {
  type: Array,
  default: ['authenticated']
}
```

server controller
```
// where package is your package name
module.exports = function(package, app, circles, database) {
	var Package = mongoose.model('Package');
	return {
		all: function(req, res) {
				var query;
				if(!req.user || req.acl.user.allowed.indexOf('admin') === -1) {
					query = req.acl.query('Package'); // non admins only see items from their circles
				} else {
					query = Package; // admins see all challenges
				}

				query.find().sort('-created')
				....
				....
		}
	}

```

**Comment by timelf123** [comment]
Closing this as solved, feel free to reopen if you have issues
