### ISSUE TITLE
Remove bower.json in root

### ISSUE THREAD

**Issue by timelf123** [linnovate/mean#1670]
Is there any reason we need to rely on the bower versions of the angular-\* packages instead of npm? My package.json file already has a lot of these:

```
    "angular": "^1.5.8",
    "angular-bootstrap": "^0.12.2",
    "angular-chart.js": "^1.0.0",
    "angular-cookies": "^1.5.2",
    "angular-jwt": "0.0.9",
    "angular-mocks": "^1.5.2",
    "angular-resource": "^1.5.2",
    "angular-route": "^1.5.2",
    "angular-sanitize": "^1.5.2",
    "angular-ui-router": "0.3.1",
```

Thoughts
- loading from npm > loading from bower
- would remove unused web-bootstrap dep
- requires removal of old assets code from meanio?

**Comment by timelf123** [comment]
This is possible. Leaving open until done

**Comment by pashist** [comment]
These bower dependencies not really needed and can be removed. 
Other question is should we remove bower.json, .bowerrc and perhaps even `bower update` from postinstall too?

**Comment by timelf123** [comment]
I did all of those in my fork
