### ISSUE TITLE
 [nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by Jipsian** [linnovate/mean#1671]
I encountered this problem, npm install didn't fix the issue.

[serverpb.txt](https://github.com/linnovate/mean/files/500182/serverpb.txt)

**Comment by timelf123** [comment]
@Jipsian The server log tells you it can't connect to your local mongo.

Your server log also shows that this is not a mean.io scaffolded project so we are not able to support it

**Comment by Jipsian** [comment]
Awsome
