### ISSUE TITLE
Front end assets not updating in development environment

### ISSUE THREAD

**Issue by ADSKLowenthal** [linnovate/mean#1674]
When using the `default` gulp activity that uses Webpack, Nodemon, and Livereload, changes to client side code sometimes are not reflected.  Current suspect is a race condition in Nodemon and Webpack, that Nodemon restarts the server before Webpack has created the new bundle.

**Comment by timelf123** [comment]
One possible solution is nodemon only reloads the app on server side code changes, and livereload handles the frontend webpack bundles changing
