### ISSUE TITLE
Failed at the mean@0.7.0 snyk-protect script 'snyk protect'.

### ISSUE THREAD

**Issue by nileshkamani82** [linnovate/mean#1678]
[npm-debug.zip](https://github.com/linnovate/mean/files/505347/npm-debug.zip)

**Comment by nileshkamani82** [comment]
Windows does not come with the GNU patch utility installed, please get it from http://gnuwin32.sourceforge.net/packages/patch.htm or a similar source.

And add the patch.exe path to PATH variable.

**Comment by timelf123** [comment]
Git for windows has the patch.exe that works. I was unable to get the above link to work
