### ISSUE TITLE
synk protect fails for uglify-js patch

### ISSUE THREAD

**Issue by nileshkamani82** [linnovate/mean#1679]
'npm:uglify-js:20151024':
    - meanio > swig > uglify-js:
        patched: '2016-08-04T11:07:59.126Z'

**Comment by timelf123** [comment]
Try the following:
1. npm cache clear
1. del node_modules -R
1. npm i
1. snyk wizard
1. answer y to the prompt, follow the wizard
1. snyk protect

If that fails, can you post a full stacktrace?

**Comment by nileshkamani82** [comment]
Actually I updated the version of uglify-js in swig manually to match with the version of uglify-js in meanio.
So I will be not able to try the steps. 
I am using Windows 10.

Except that patch, other patches were installed fine.

**Comment by rjVapes** [comment]
Install git tools from here https://git-scm.com/download/win to get the latest version of GNU Patch which is the culprit for this error.

**Comment by nileshkamani82** [comment]
I fixed the issue by removing that line and updating version in package.json manually. So please close this
