### ISSUE TITLE
error when run npm install

### ISSUE THREAD

**Issue by fayeyen** [linnovate/mean#1683]
after I install everything needed in ubuntu
I run 
$ mean init myApp
when I run 
cd myApp && npm install
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please upd
ate to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please upd
ate to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[       ...........] / fetchMetadata: verb cache add spec request@~2.74.0
keep loading...

**Comment by rjVapes** [comment]
Those are all warnings.  Ones we'll look into resolving, but is a seperate issue.  Does the `npm install` complete, or have any `ERR` messages with it?  Also what OS, node, and npm version are you using?

**Comment by ruslanss** [comment]
same here on node v5.9.1 and npm v3.10.8 (windows 10), npm install dies after above-mentioned lines:

```
PS C:\git\myApp> npm install
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update t
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update t
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! cb() never called!
```

and yes, i've tried clearing npm cache. any other ideas would be much appreciated.

**Comment by ruslanss** [comment]
**** solved by updating node.js to v6.8.0 ****

**Comment by rjVapes** [comment]
@ruslanss I actually had the same issue as you today, I'll try updating to 6.8.0.  Granted, it was `standard-engine` that was ultimately throwing that error, which we might be moving away from soon, so not strictly a mean problem, but some combination of that module and node.

@fayeyen Can you verify that this is the issue you had?  Specifically `npm ERR! cb() never called!` ?

**Comment by fayeyen** [comment]
I update to npm 3.9 problem solved
