### ISSUE TITLE
[Priority] issues with production env

### ISSUE THREAD

**Issue by VikramTiwari** [linnovate/mean#1687]
How to reproduce:

Get the project and deps:
- install `mean-cli`
- `mean init newApp`
- `cd newApp`
- `npm install`

Now run it:
- `npm start` or
- `NODE_ENV=production gulp`

Won't result into anything, since there's no `bundle` directory yet
## 

Issue 1:
- Someone is working on branch A on dev environ
- Switched to branch B for deployment
- Code in `bundle` dir is still for branch A
- The deployed code doesn't show results as expected from branch B

Issue 2:
- Building and deploying using docker images is useless if you are trying to build them from CI (no `bundle` dir there)

NOTES:
`bundle` dir along with `app.js` and `app.js.map` gets generated when `gulp` has been run at least once in development mode.

**Comment by timelf123** [comment]
```
  "scripts": {
    "build:production": "cross-env NODE_ENV=production webpack",
    "postinstall": "node tools/scripts/postinstall.js && npm run build:production"
  },
```

This way the bundle is built after npm install finishes

**Comment by VikramTiwari** [comment]
On the same note:
Could we add a new production env webpack config file, with minified js and css tasks? I have seen that issue reported earlier.

**Comment by timelf123** [comment]
There may be a better way but I did it like this:

```
...
if (process.env.NODE_ENV === 'production') {
  webpackConfig.plugins = webpackConfig.plugins.concat([
    // new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js'),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: false,
      mangle: false,
      test: /\.(js|jsx)$/
    }),
    new webpack.optimize.AggressiveMergingPlugin()
  ])
} else if (process.env.NODE_ENV === 'development') {
  webpackConfig.devtool = 'source-map';
}

module.exports = webpackConfig;
```
