### ISSUE TITLE
Front end separation

### ISSUE THREAD

**Issue by esinecan** [linnovate/mean#1689]
Hello, I'd like to separate front end of my Mean.io project completely from the back end, put it in another repository, and then delegate the front end work to my colleague. How do I go about this?

**Comment by chanakaDe** [comment]
This is not a issue actually. If you need to separate the work, it's not needed to separate back end and front end. You can use version control like Git. It's so simple. All you need to do is, 

1. Clone the base repo
2. You can change your back end and commit changes
3. Friend can update front end and commit changes
4. Both of you can merge changes (pull all updates) and run the project.

**Comment by esinecan** [comment]
Oh, thanks for addressing. In the meantime, we've jumped on the microservice hype train, so everything is pretty granular. Though my comment might come across as sarcastic, since we did not have a lot of tangled up legacy code, it worked well for us. Feel free to close this one
