### ISSUE TITLE
Fix abbreviations, compress images

### ISSUE THREAD

**Issue by j9t** [linnovate/mean#1692]
Sorry a bit backwards as I had missed the documentation: I had checked out MEAN to fix some typos in the documentation (“MEAN” vs “mean”, “html” instead of “HTML”), and in the process noticed that images were uncompressed (or not compressed enough), too. Prepared https://github.com/linnovate/mean/compare/master...j9t:master.

Is there a lightweight way to proceed? I saw your contribution guidelines only late and would prefer not to install Node and such to test image updates. Cheers :)

**Comment by timelf123** [comment]
Thanks for the contribution, I made it into a PR here: https://github.com/linnovate/mean/pull/1714
