### ISSUE TITLE
Trying to make it work on codenvy

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1713]
I tried but have some problem finding the good mongo port.

https://codenvy.io/dashboard/#/ide/tyvain/NodeWS

If someone can help me (juste click the link to test) or can give a working codenvy link...;

Thank you.

**Comment by timelf123** [comment]
Please see us in the [gitter chat](https://gitter.im/linnovate/mean) - this is not a support forum. Sounds like you need to set an env variable for `DB_PORT_27017_TCP_ADDR ` according the readme
