### ISSUE TITLE
angular-ui-router 0.3.x throws console errors

### ISSUE THREAD

**Issue by adskjohn** [linnovate/mean#1724]
https://github.com/angular-ui/ui-router/issues/2889  Fixed in 1.0, which is currently in beta.  We need to determine if we want to move to the beta version to silence the errors (which are more like warnings).  We can also just stay at 0.3 until a full release of 1.0 of the ui-router.  This is a mean package.json change so users can easily update their version if they want.

**Comment by timelf123** [comment]
AFAIK the only reason we didn't jump feet first into 1.X was that it was still alpha - and the deprecation of the `$stateChange...` events. https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events

It should be a fairly straightforward migration to 1.X though and would be worth - the routing/component feature is great for >1.5

**Comment by timelf123** [comment]
To squelch the errors for now, we added ` $qProvider.errorOnUnhandledRejections(false);` to our config block until we are ready to upgrade to the transition API instead of `$stateChange`

No this is not recommended, and yes it is a hack.

**Comment by timelf123** [comment]
>0.4.2 fixes this I think?
