### ISSUE TITLE
Cannot import external modules 

### ISSUE THREAD

**Issue by zzjustinzz** [linnovate/mean#1727]
I import angular-nv-d3 to my project in index.js:
import './assets/lib/d3/d3.min.js';
import './assets/lib/nvd3/build/nv.d3.min.js';
import './assets/lib/nvd3/build/nv.d3.min.css';
import './assets/lib/angular-nvd3/dist/angular-nvd3.min.js';

But when i run it notices error in console:
angular-nvd3.min.js:1Uncaught Error: Cannot find module "nvd3" 

and in command prompt notices error: 
Module not found: Error: Cannot resolve module 'd3'
Module not found: Error: Cannot resolve module 'nvd3'

Can you help me??
Thanks

**Comment by timelf123** [comment]
webpack imports look in node_modules and bower_components folders.

For example:
`npm i d3` -> node_modules/d3

import 'd3' or import 'd3/path/to/file'

**Comment by zzjustinzz** [comment]
dont have any d3 folder or nvd3 folder in node_modules and bower_components folders.

i have installed angular-nvd3 in a custom package, and it gets 3 folder d3, nvd3, angular-nvd3 to 'CustomPackageName/assets/lib/...' and i import it in index.js of custom package

Seem like if you want use angular-nvd3, it will uses nvd3 module and nvd3 module must have d3 module. But it cannot import nvd3 and d3 to my project.
