### ISSUE TITLE
Include GNU's Patch in windows installation doc

### ISSUE THREAD

**Issue by waldandrade** [linnovate/mean#1731]
It cause's a error in "run snyk protect

**Comment by adrukh** [comment]
@waldandrade please see https://github.com/Snyk/snyk/issues/48#issuecomment-256260149

We have a plan to address this for Windows users, but no specific timeline yet.

**Comment by waldandrade** [comment]
but with a real smart card, do it works?

**Comment by liorkesos** [comment]
This is a snyk issue.
Closing.
