### ISSUE TITLE
error happen when run $npm install

### ISSUE THREAD

**Issue by lihengzkj** [linnovate/mean#1734]
After run $npm install 
module.js:327
    throw err;
    ^
Error: Cannot find module 'generate-object-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/kejing_usr/kjApp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
warning..............
Binary found at /home/kejing_usr/kjApp/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-46/binding.node
Testing binary
Binary is fine
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kejing_usr/kjApp/npm-debug.log
kejing_usr@mesos-t-env:~/kjApp$ npm install generate-object-property
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "generate-object-property"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular@1.6.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular-material@1.1.1 wants angular@>=1.3 <1.6

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kejing_usr/kjApp/npm-debug.log
kejing_usr@mesos-t-env:~/kjApp$ npm install phantomjs-prebuilt@2.1.14
\
> phantomjs-prebuilt@2.1.14 install /home/kejing_usr/kjApp/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/kejing_usr/kjApp/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1483152163452/phantomjs-2.1.1-linux-x86_64 -> /home/kejing_usr/kjApp/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/kejing_usr/kjApp/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "phantomjs-prebuilt@2.1.14"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular@1.6.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular-material@1.1.1 wants angular@>=1.3 <1.6

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kejing_usr/kjApp/npm-debug.log
kejing_usr@mesos-t-env:~/kjApp$ tmux
├── UNMET PEER DEPENDENCY angular-aria@1.6.1
├─┬ meanio@0.9.3
│ └── lodash@4.17.3
├── meanio-admin@0.1.9  (git://github.com/linnovate/meanio-admin.git#4abc9ac31052346e827bee1c1e5be188ecdcdba5)
├── meanio-circles@0.1.7  (git://github.com/linnovate/meanio-circles.git#ade9ed758646f2b05db39afda3dae4522bfe5ed0)
├── meanio-system@0.1.4  (git://github.com/linnovate/meanio-system.git#cc46fca40ce8df1c5e737bce314622e5500d0b23)
└─┬ meanio-users@0.1.7  (git://github.com/linnovate/meanio-users.git#3143186feb9480b8c2b271820c7a7310ff037666)
  └── angular-jwt@0.1.8

    Dependencies installed for package kjapp1

> mean@0.7.0 prepublish /home/kejing_usr/kjapp1
> npm run snyk-protect

> mean@0.7.0 snyk-protect /home/kejing_usr/kjapp1
> snyk protect

Successfully applied Snyk patches
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular@1.6.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular-material@1.1.1 wants angular@>=1.3 <1.6

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kejing_usr/kjapp1/npm-debug.log

**Comment by lihengzkj** [comment]
for the first error :Error: Cannot find module 'generate-object-property'
i try to install, but still failed: 
kejing_usr@mesos-t-env:~/kjapp1$ sudo npm install generate-object-property
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "generate-object-property"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular@1.6.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular-material@1.1.1 wants angular@>=1.3 <1.6

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kejing_usr/kjapp1/npm-debug.log

**Comment by retorquere** [comment]
I think this is caused by the inclusion of packages like `meanio-admin` by their github url rather than a specific version. This pulls in angular 1.6 which conflicts with angular-material.

**Comment by xjaroo** [comment]
I got the same error which is related with meanio-admin. is there any way to avoid this?

**Comment by kybarg** [comment]
This should fix
`
sudo npm install -g snyk
`

**Comment by indiecore-fm** [comment]
Or just copy your npm from the nodejs module folder to the appdata module folder

**Comment by lihengzkj** [comment]
sorry late for this comment.
I already solve the issue. If you still encounter this issue  , pls try below commands:

$npm update -g npm
$npm update -g bower
$npm cache clean
$bower cache clean
