### ISSUE TITLE
Annoying local development due to webpack aggregation process

### ISSUE THREAD

**Issue by rubenjimenez** [linnovate/mean#1743]
Hi,

Is there any way to disable wabpack in dev?

Every time I make a change in the code and save the file Node automatically restart and webpack creates the app.js, which according to what I see it is necessary to run the project.

The main problem is that it is really annoying because just for a little change in the code It process everything again and again. When I want to see the change on the browser I have to wait. I have disabled jshint and cslint for lighten up the process, but webpack keeps going on.

In previous MEAN versions you could disable the aggregate process from development.js file, therefore the reload process for a change made on the code was almost instant. But now when I set the aggregate var to false it does nothing.

Any idea about this? Thanks people.

**Comment by timelf123** [comment]
Workarounds

1.  run `node server` in one terminal tab, and `webpack --watch` in another
2.  `gulp --wdm`

**Comment by rubenjimenez** [comment]
I think I don't get it.

What is exactly the difference between your workaround and running gulp directly? It seems It remains packaging everything in an app.js file. It even seems to last the same.

**Comment by timelf123** [comment]
Sorry, I was/am on mobile. There is no way to circumvent webpack - it is how the frontend assets are made available to the browser in the current version of mean. 

In my examples the app.js is still built but in `1.` will not cause the server to reboot - you can restart the server by `ctrl-c` and running it again. Sometimes webpack --watch runs faster than the associated gulp task
`2.` - will run webpack in HMR mode http://webpack.github.io/docs/hot-module-replacement-with-webpack.html

**Comment by rubenjimenez** [comment]
Thanks @timelf123 for the explanation.

Restarting node every time I need feels like a little bit more comfortable. And you're right, it is faster. Not much, but enough.

**Comment by timelf123** [comment]
TBH I totally forgot https://github.com/linnovate/mean/pull/1696 is not merged yet. I have pulled those changes locally since October or so and the experience has been much better. Highly recommend testing that PR out @rubenjimenez

**Comment by rubenjimenez** [comment]
Thanks @timelf123, I'll try it out. It sounds good.

**Comment by timelf123** [comment]
Closed with https://github.com/linnovate/mean/commit/f08fc2cab6e433e625a10ffa1a878bbd4716c098
