### ISSUE TITLE
Error: angular-ui-router on install 

### ISSUE THREAD

**Issue by davecyen** [linnovate/mean#1755]
Just installed mean (0.7.0) and I'm getting the following console error messages on install. Looks related to angular-ui-router (0.3.1). The app appears to be working fine however.

<img width="975" alt="screen shot 2017-01-30 at 12 19 37 pm" src="https://cloud.githubusercontent.com/assets/1930455/22440052/dc2965ac-e6e6-11e6-9353-4ac2bea00d4a.png">

**Comment by timelf123** [comment]
upgrading to `0.4.2` should solve

**Comment by davecyen** [comment]
Thanks @timelf123, that worked
