### ISSUE TITLE
Am having problem installing and running nodemon as it keeps crashing

### ISSUE THREAD

**Issue by LunaBawa** [linnovate/mean#1766]
First it skips dependencies and crashes when i try to run nodemon from the terminal then i had to install them one after the other and still it still crashes. 

![image](https://cloud.githubusercontent.com/assets/11213175/22698796/da8e2492-ed55-11e6-8f1e-7721d7fb1e7e.png)

**Comment by timelf123** [comment]
This is not a meanio app
