### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by deepdil-enfin** [linnovate/mean#1780]
Hi Guys,

How can i integrate angular 2 in the mean stack? PLease help me.!

**Comment by rogeriob2br** [comment]
Hi @deepdil-enfin, 
In this repo have this "integration". The express and mongo files live in server folder, and
you can see the [Server](https://github.com/linnovate/mean/tree/master/server) page. 
For Angular 2, and Readme.md live in https://github.com/linnovate/mean. 
Fork This repo and test this Integrations. The Express and mongoose is in a Rest api in server folder...
