### ISSUE TITLE
mean.io "Documentation" link is broken

### ISSUE THREAD

**Issue by johnjspiteri** [linnovate/mean#1785]
The reference to "Documentation" in the main navigation is broken - http://learn.mean.io

**Comment by stormywake** [comment]
is there a fix coming to this?

**Comment by bi-kai** [comment]
I am new here, where can i find the doc of mean.io?

**Comment by timelf123** [comment]
ping @liorkesos

**Comment by liorkesos** [comment]
Please refer to the README.md
Pull requests are welcome (there is some old stuff that needs to be revised.
Lior

**Comment by ZyshanNoor** [comment]
Till when can we expect to get some documentation help. As i need some implementation in mean-sockets and cant find any docs.

**Comment by liorkesos** [comment]
The docs are currently in the README file
Feel free to submit a PR so we can improve them.

**Comment by chanakaDe** [comment]
@johnjspiteri  Documentation is being updated
