### ISSUE TITLE
GET /bundle/app.js 404 - - 4.249 ms

### ISSUE THREAD

**Issue by johnaddme** [linnovate/mean#1790]
When I run 'gulp',then run 'node server' ,the project does not come into being bundle/app.js.

**Comment by timelf123** [comment]
What version of mean are you running?

**Comment by rafagsiqueira** [comment]
I had this same problem. And I had to remove the "bundle/" from the gitignore and allow my automated docker image building process to copy this directory into the final app. The "bundle/" folder is only created if I run gulp with env development.

**Comment by timelf123** [comment]
I think I solved it with this if I understand correctly:
https://github.com/linnovate/mean/issues/1687#issuecomment-255135020

**Comment by rafagsiqueira** [comment]
For me it caused a build failure:

``I  > cross-env NODE_ENV=production webpack 
I  {"insertId":"ac1c0ce1-b554-4fbc-bb66-95c577bf9a0f-21047","resource":{"type":"build","labels":{"project_id":"crawling-158716","build_id":"ac1c0ce1-b554-4fbc-bb66-95c577bf9a0f"}},"timestamp":"2017-05-19T18:58:17.031175792Z","severity":"INFO","logName":"projects/crawling-158716/logs/cloudbuild","receiv… 
I  [91mInvalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema. 
I   - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid: 
I     object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? } 
I  [0m[91m 
I  [0m[91mnpm info lifecycle mean@0.9.1~build:production: Failed to exec build:production script 
I  npm ERR! Linux 4.4.0-78-generic 
I  npm ERR! argv "/usr/local/bin/node" "/usr/src/app/node_modules/.bin/npm" "run" "build:production" 
I  npm ERR! node v7.10.0 
I  npm ERR! npm  v3.10.10 
I  npm ERR! code ELIFECYCLE 
I  npm ERR! mean@0.9.1 build:production: `cross-env NODE_ENV=production webpack` 
I  npm ERR! Exit status 1 
I  npm ERR!  
I  npm ERR! Failed at the mean@0.9.1 build:production script 'cross-env NODE_ENV=production webpack'. ``

**Comment by timelf123** [comment]
this is due to the devdeps setting webpack to latest version. revert to webpack 1 or see the steps taken here https://github.com/linnovate/mean/pull/1786/commits/9a605a5047530dcd595ff8bfb94544f5a9bed4f0 and apply them to your webpack file.

I'll try to roll a PR for webpack 2 next week. Haven't gotten to it yet because my meanio installation is very diverged from upstream atm

**Comment by rafagsiqueira** [comment]
Now it solved. I took the steps that you referred! Thanks!
