### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module firebase due to: Error: [$injector:nomod] Module 'firebase' is not available

### ISSUE THREAD

**Issue by asmaeouali** [linnovate/mean#1792]
Runtime Error
[$injector:modulerr] Failed to instantiate module starter due to: Error: [$injector:modulerr] Failed to instantiate module firebase due to: Error: [$injector:nomod] Module 'firebase' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.5.3/$injector/nomod?p0=firebase at d (http://localhost:8100/build/polyfills.js:3:3991) at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13438:12 at http://localhost:8100/lib/ionic/js/ionic.bundle.js:15404:17 at ensure (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15328:38) at module (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15402:14) at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17894:22 at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13691:20) at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17878:5) at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17895:40 at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13691:20) at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17878:5) at createInjector (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17800:19) at doBootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15080:20) at bootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15101:12) at angularInit (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14986:5) http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=firebase&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'firebase'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.3%2F%24injector%2Fnomod%3Fp0%3Dfirebase%0A%20%20%20%20at%20d%20(http%3A%2F%2Flocalhost%3A8100%2Fbuild%2Fpolyfills.js%3A3%3A3991)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13438%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15404%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15328%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15402%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17894%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13691%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17878%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17895%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13691%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17878%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17800%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15080%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15101%3A12)%0A%20%20%20%20at%20angularInit%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A14986%3A5) at d (http://localhost:8100/build/polyfills.js:3:3991) at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13438:12 at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17917:15 at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13691:20) at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17878:5) at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17895:40 at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13691:20) at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17878:5) at createInjector (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17800:19) at doBootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15080:20) at bootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15101:12) at angularInit (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14986:5) at HTMLDocument.<anonymous> (http://localhost:8100/lib/ionic/js/ionic.bundle.js:44079:5) at j (http://localhost:8100/bootstrap/js/jquery.min.js:2:27309) at Object.fireWith [as resolveWith] (http://localhost:8100/bootstrap/js/jquery.min.js:2:28122) http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=starter&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20firebase%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'firebase'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.3%2F%24injector%2Fnomod%3Fp0%3Dfirebase%0A%20%20%20%20at%20d%20(http%3A%2F%2Flocalhost%3A8100%2Fbuild%2Fpolyfills.js%3A3%3A3991)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13438%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15404%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15328%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15402%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17894%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13691%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17878%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17895%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13691%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17878%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17800%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15080%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15101%3A12)%0A%20%20%20%20at%20angularInit%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A14986%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.3%2F%24injector%2Fmodulerr%3Fp0%3Dfirebase%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'firebase'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.3%252F%2524injector%252Fnomod%253Fp0%253Dfirebase%250A%2520%2520%2520%2520at%2520d%2520(http%253A%252F%252Flocalhost%253A8100%252Fbuild%252Fpolyfills.js%253A3%253A3991)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A13438%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A15404%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A15328%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A15402%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A17894%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A13691%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A17878%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A17895%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A13691%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A17878%253A5)%250A%2520%2520%2520%2520at%2520createInjector%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A17800%253A19)%250A%2520%2520%2520%2520at%2520doBootstrap%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A15080%253A20)%250A%2520%2520%2520%2520at%2520bootstrap%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A15101%253A12)%250A%2520%2520%2520%2520at%2520angularInit%2520(http%253A%252F%252Flocalhost%253A8100%252Flib%252Fionic%252Fjs%252Fionic.bundle.js%253A14986%253A5)%0A%20%20%20%20at%20d%20(http%3A%2F%2Flocalhost%3A8100%2Fbuild%2Fpolyfills.js%3A3%3A3991)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13438%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17917%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13691%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17878%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17895%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13691%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17878%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17800%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15080%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15101%3A12)%0A%20%20%20%20at%20angularInit%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A14986%3A5)%0A%20%20%20%20at%20HTMLDocument.%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A44079%3A5)%0A%20%20%20%20at%20j%20(http%3A%2F%2Flocalhost%3A8100%2Fbootstrap%2Fjs%2Fjquery.min.js%3A2%3A27309)%0A%20%20%20%20at%20Object.fireWith%20%5Bas%20resolveWith%5D%20(http%3A%2F%2Flocalhost%3A8100%2Fbootstrap%2Fjs%2Fjquery.min.js%3A2%3A28122)

**Comment by timelf123** [comment]
This is not a MEAN issue
