### ISSUE TITLE
Where to find API or doc of MEAN?

### ISSUE THREAD

**Issue by bi-kai** [linnovate/mean#1799]
I wanna to use MEAN.js, but where can I find the API or doc about MEAN, do you still maintain it?

**Comment by bi-kai** [comment]
Whether this repo is still maintained?

**Comment by prasadh13** [comment]
This is the MEAN.io project. You can find MEAN.js docs [http://meanjs.org/](here)

**Comment by bi-kai** [comment]
@prasadh13 sorry, not mean.js, I cannot find docs of your MEAN on mean.io.

**Comment by bi-kai** [comment]
@prasadh13 can you gave some advice about this issue?

**Comment by prasadh13** [comment]
@bi-kai all the information required to get started with MEAN.io is in the README file. The link to documentation is right now broken.

**Comment by rogeriob2br** [comment]
Hi, have a read-me file in [Main](https://github.com/linnovate/mean) and [ServerSide](https://github.com/linnovate/mean/tree/master/server)

**Comment by bi-kai** [comment]
Thx.

**Comment by ianchanning** [comment]
It's worrying that the entire documentation for this project is in two readme files.
