### ISSUE TITLE
ERR Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by bnbanakar** [linnovate/mean#1800]
Facing ERR Error: Cannot find module 'debug'. I have tried updating debug dependency. 
Any suggestion or help to fix this issue.

simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      OUT > node ./server/index.js
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     throw err;
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR module.js:442
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     ^
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at Function.Module._load (module.js:388:25)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR Error: Cannot find module 'debug'
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at Function.Module._resolveFilename (module.js:440:15)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at Module.require (module.js:468:17)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at Object.Module._extensions..js (module.js:550:10)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at tryModuleLoad (module.js:417:12)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at Object.<anonymous> (/home/vcap/app/node_modules/finalhandler/index.js:14:13)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at Function.Module._load (module.js:409:3)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at require (internal/module.js:20:19)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at Module.load (module.js:458:32)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR     at Module._compile (module.js:541:32)
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR npm ERR! Linux 4.4.0-64-generic
simple	22-May-2017 21:29:14	2017-05-22T21:29.14-0400 [APP/0]      ERR npm ERR! argv "/home/vcap/app/.heroku/node/bin/node" "/home/vcap/app/.heroku/node/bin/npm" "start"

**Comment by timelf123** [comment]
https://github.com/linnovate/mean/wiki/Deploying-on-Heroku

**Comment by bnbanakar** [comment]
Issue has been fixed. Issue was in package.json, For few of the dependencies caret(^) and tilde(~) were present. Due to that those dependencies are upgrading during install. I have removed them. 
Thank you.

**Comment by rogeriob2br** [comment]
This is Fixed, and can closed.(i don't have this permission..)
