### ISSUE TITLE
Centos 7.2 mean init error

### ISSUE THREAD

**Issue by zygmcc** [linnovate/mean#1802]
while "mean init test",errors  like this :

[root@iZoy1rmijsceffZ mean-master]# mean init test
? What would you name your mean app? test
Installation of mean should not be done as root! bailing out
(node:10703) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RUNNING AS ROOT
Use `mean --help` from command line for all CLI options
Be sure to checkout all the docs on http://mean.io
This may take a little while depending on your connection speed
Still cloning...
Still cloning...
Still cloning...
Still cloning...
Still cloning...
Still cloning...
Still cloning...
Still cloning...
Still cloning...

this means my Internet connecting problem or ... user privilege error?

**Comment by timelf123** [comment]
don't run `mean init` as `root` user, or clone this repo directly to get started
