### ISSUE TITLE
Where did the M.(mongo)and E.(express) end?[Documentation]

### ISSUE THREAD

**Issue by rogeriob2br** [linnovate/mean#1813]
Does this documentation speak only of angular?
Did they forget the name of this Stack?
Is Mean still a FullStack?
M - Mongo
E - Express
A- Angular(js, 2, 4 , ...)
N - Nodejs
I love angular4, but use it on the client side. And the rest?
See, I'm a newbie.
I'm still starting to crawl with this stack. 3 projects in progress...
But learning is harder if you leave the stack and focus only on the Angular. If you need help for the rest, I'll help you, but I need to learn a lot to get to your feet.

**Comment by rogeriob2br** [comment]
Please, i don't understend how Express and Angular 4 can work side by side(Server/Client)

**Comment by rogeriob2br** [comment]
Hi, sorry! You can close this, i found the server docs in server page(https://github.com/linnovate/mean/tree/master/server). 

I'd like to leave a suggestion, to sort out some manners make it clear on the main page of Mean.

**Comment by timelf123** [comment]
Might make sense to show that the server is based on boilerplate here https://github.com/KunalKapadia/express-mongoose-es6-rest-api

**Comment by rogeriob2br** [comment]
Yes, if a newbie like me, read the main documentation in linnovate/mean, will be lost.
I'm reading and studying these docs to try to build a fullstack tutorial based on what's new, but I'm not very experienced.

**Comment by liorkesos** [comment]
Sorry, we're still  ironing out the concept and the docs are not good.
But basically this next evolution will be to allow angular (and react!) to connect to a graphql service and in the background there will be an express based node reslver to fufill the queries
