### ISSUE TITLE
Want a mean.io app with angular 1.4

### ISSUE THREAD

**Issue by akshayseth** [linnovate/mean#1816]
Hello,
I want to make an app with angular 1.4 and gulp and bower.json instead of webpack.Can you please help me in achieving the same.

**Comment by timelf123** [comment]
https://github.com/linnovate/mean/tree/0.5.5

**Comment by akshayseth** [comment]
How can I install this version with command prompt?

**Comment by timelf123** [comment]
git clone git@github.com:linnovate/mean.git
cd mean
git checkout origin/0.5.5

**Comment by akshayseth** [comment]
Got an error while checking out:
error: pathspec 'origin/0.5.5' did not match any file(s) known to git.

**Comment by timelf123** [comment]
git fetch
git checkout 0.5.5

**Comment by akshayseth** [comment]
Again error returned:
error: pathspec '0.5.5' did not match any file(s) known to git.

**Comment by akshayseth** [comment]
Please close the issue only if the issue is really closed.!

**Comment by timelf123** [comment]
https://stackoverflow.com/questions/1783405/how-do-i-check-out-a-remote-git-branch

**Comment by akshayseth** [comment]
Kindly,Open the issue as it is not fixed.Also I have used the commands you commented with no success.
