### ISSUE TITLE
Docker - build failed

### ISSUE THREAD

**Issue by ctomczyk** [linnovate/mean#1827]
To build Docker image I was following: https://github.com/linnovate/mean#build-image and used the command `docker build -t angular-starter .`. However, I've got:

    Sending build context to Docker daemon  1.135MB
    Step 1/8 : FROM nginx:1.13.0-alpine
     ---> f00ab1b3ac6d
    Step 2/8 : RUN apk add --no-cache bash=4.3.46-r5 &&    apk add --no-cache openssl=1.0.2k-r0 &&    apk add --no-cache nodejs
     ---> Using cache
     ---> 6afb54ab0aa4
    Step 3/8 : ADD package.json /tmp/npm_inst/package.json
     ---> Using cache
     ---> 833e0092b6a4
    Step 4/8 : RUN cd /tmp/npm_inst &&    npm install &&    mkdir -p /tmp/app &&    mv /tmp/npm_inst/node_modules /tmp/app/
     ---> Running in 1a7495f1b236
    npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/innograph.git /root/.npm/_git-remotes/git-github-com-linnovate-innograph-git-devel-6f1f86cd: undefined
    npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/linnovate/innograph.git /root/.npm/_git-remotes/git-github-com-linnovate-innograph-git-devel-6f1f86cd: undefined
    npm WARN deprecated apollo-server@0.3.3: apollo-server has been renamed. The package is now called GraphQL Server. Please download the package for your specific server. Install graphql-server-<name> where name is one of the available server integrations: express, hapi, koa, restify, lambda
    npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
    npm ERR! Linux 4.9.41-moby
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! node v6.9.5
    npm ERR! npm  v3.10.10
    npm ERR! code ENOGIT

    npm ERR! not found: git
    npm ERR! 
    npm ERR! Failed using git.
    npm ERR! This is most likely not a problem with npm itself.
    npm ERR! Please check if you have git installed and in your PATH.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/npm_inst/npm-debug.log
    The command '/bin/sh -c cd /tmp/npm_inst &&    npm install &&    mkdir -p /tmp/app &&    mv /tmp/npm_inst/node_modules /tmp/app/' returned a non-zero code: 1

**Environment**:

macOS Sierra 10.12.6 (16G29)
NodeJS 8.4.0
npm 5.3.0

Anyone experiencing similar issue?

**Comment by mzouitni** [comment]
Anybody found a fix to this problem?

**Comment by riteshcn** [comment]
issue resolved, becasue I am experiencing same

**Comment by ctomczyk** [comment]
@riteshcn What's the resolution?

**Comment by ronyrun** [comment]
add the git dependency in the dockerfile

**Comment by joshuansu0897** [comment]
change in DockerFile 
```
RUN apk add --no-cache  &&\
    apk add --no-cache openssl=1.0.2k-r0 &&\
    apk add --no-cache nodejs
```
for this 
```
RUN apk --update --upgrade add --no-cache \
        bash=4.3.46-r5 \
        git \
        libressl \
        libressl-dev \
        nodejs
```

**Comment by ctomczyk** [comment]
Tested reported bug with commit a4e0b1fa89d337c350fac72e626a67b81d8d94d4 and seems everything is now fine. Closing this ticket.
