### ISSUE TITLE
React or Angular4?

### ISSUE THREAD

**Issue by rubenjimenez** [linnovate/mean#1834]
Hi,

We have used previous MEAN.io versions using Angular 1.x for years. Now, we're giving a try to the new version with Angular 4. When we made git clone from the master branch and we started the project we've found it is using React... And doing some research we see that the last commit added React packages.

MEAN.io is migrating to React?

Besides, the first attempt to run the project we're receiving some 500 errors with GraphQL on console when trying to accomplish some basic tasks like adding a post in the default interface.

We've just done npm install & npm start.

Isn't Master branch the stable branch to make git clone and start to use the scaffolding? Is there any other stable branch with Angular 4?

Regards!

**Comment by liorkesos** [comment]
Were on the process of providing much more choice through mean.
This means that you will be able to choose whatever frontend framework you prefer.
It still is not documented well but we going to use bit and innograph to provides prebuilt capabilities + web components.
It's kinda Rocky and unstable right now but stay tuned!

**Comment by rubenjimenez** [comment]
That's wonderful.

But, right now, is there any stable branch with Angular 4 that we can use for production projects?

**Comment by liorkesos** [comment]
yes - i changed the default routes and added some help texts to communicate this better.
