### ISSUE TITLE
Getting errors while installing 

### ISSUE THREAD

**Issue by Ashroyal** [linnovate/mean#1835]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

npm WARN @angular/animations@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/cdk@2.0.0-beta.11 requires a peer of @angular/common@^4.4.3 but none was installed.
npm WARN @angular/common@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/compiler@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/compiler-cli@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/core@4.4.3 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN @angular/forms@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/http@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/material@2.0.0-beta.11 requires a peer of @angular/common@^4.4.3 but none was installed.
npm WARN @angular/platform-browser@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/platform-browser-dynamic@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/platform-server@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN @angular/router@4.3.6 requires a peer of @angular/core@4.3.6 but none was installed.
npm WARN preboot@5.0.0-rc.10 requires a peer of zone.js@^0.8.0 but none was installed.

* **Please tell us about your environment:**
Mac os x Sierra, npm 5.4.2, node 8.5.0

**Comment by Jackychans** [comment]
<img width="751" alt="screen shot 2017-09-26 at 13 30 26" src="https://user-images.githubusercontent.com/6682672/30845720-eb9fad0e-a2be-11e7-966f-964244a9f6e7.png">

I also got another issue in the first time installation (after npm install and npm start). Looks like issue coming from material design.

I tried using nvm to switch between node 8.5 (npm5), 6.11.3 and 7.7.4 but it does not work.
Source code built and run on MacOSX

By the way, if run command line docker build, there was also an issue:

<img width="1110" alt="screen shot 2017-09-26 at 13 32 53" src="https://user-images.githubusercontent.com/6682672/30845786-3b44a530-a2bf-11e7-956e-28014cfac0a4.png">

**Comment by moriz-martiner** [comment]
I solved this problem partly by removing the ^ infront of the version code of the following dependencies: @angular/material, @andgular/cdk

I get the following error/warning (when doing npm install):

`npm WARN angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none is installed. You must install peer dependencies yourself.`

**Comment by liorkesos** [comment]
Nice catch...
Which dependency?
It was unclear
If you can submit a PR I'll review and merge
Lior

**Comment by nhutcorp** [comment]
@liorkesos Here is the fixed PR https://github.com/linnovate/mean/pull/1836

**Comment by Jackychans** [comment]
Hi @liorkesos li
thanks for your update. I'm able to run npm start now.

However, it's still showing error in console log, originated from graphQL.
<img width="824" alt="screen shot 2017-09-27 at 10 53 39" src="https://user-images.githubusercontent.com/6682672/30895171-a14547f0-a372-11e7-96ee-80a9a05ae43d.png">

**Comment by liorkesos** [comment]
Hi guys thanks for the research and the pr - I merged mlthe fix yesterday.
Are you experiencing therapeutics as well?

**Comment by nhutcorp** [comment]
Currently this repo is using @angular/material '2.0.0-beta.10', it's not lasted version yet. My PR is allow to use the last version of MD.
I also use angular-starter to dev a MEAN project, demo here:
http://meancp.sendvn.com/
user: demo
pwd: demo
 More information: https://nhutcorp.com/product/mean-2-fullstack-solution-with-angular-4-and-typescript-59b0f213512c3a2f48d5ad34

**Comment by liorkesos** [comment]
Cool, I'll review and merge
Lior

**Comment by moriz-martiner** [comment]
Has someone found a fix for the graphQL error?

**Comment by Jackychans** [comment]
it seemed nobody :(

**Comment by liorkesos** [comment]
Fixed - it had to do with graphql version clashes between dependencies..

**Comment by phoenix377** [comment]
@liorkesos Same issue is happening again with latest master branch.
