### ISSUE TITLE
Bump NPM minimum version or shrinkwrap

### ISSUE THREAD

**Issue by timmles** [linnovate/mean#1841]
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

Hi,

I tried installing the project and I was getting a ton of dependency issues with angular an its related packages; which didn't make any sense.

I then notices there was a package-lock which isn't supported in the npm v3.
I bumped my npm to the latest (5.4.2) and it installed and started no issues.

However I see on the readme that npm v3 is the prerequisite.
So my suggestion is to:
1) Either swap the package-lock for a shrinkwrap file (which take precedence over the lock file).
1) Or alternatively, change the prerequisites to npm v4.

Thoughts?

**Comment by chanakaDe** [comment]
@liorkesos Any ideas please ?

**Comment by liorkesos** [comment]
@timmles Sounds totally logical 
I guess we were still in the npm2 - to npm3 mindset so we set a minimal prerequisute.
I'll try to add the shrinkwrap and see how my system reacts to it.
