### ISSUE TITLE
native nodejs debug - how to : web-host 0.0.0.0

### ISSUE THREAD

**Issue by ronyrun** [linnovate/mean#1844]
* fix(node-inspector): deprecating node-inspector infavor of native nodejs debug (#1744) ([994369d](https://github.com/meanjs/mean/commit/994369d))

Hello, 

Can you please tell me if it's possible to force the debug on the  --web-host 0.0.0.0 (node-inspector command).

Regards,

**Comment by chanakaDe** [comment]
Hi @ronyrun Can you explain a bit more please. It's not clear what you mean. Sorry.
When you use 0.0.0.0 instead of localhost, you can access in your network. like that when debugging.Is that what you want ?
