### ISSUE TITLE
node-sass version not working with node 9

### ISSUE THREAD

**Issue by idefy** [linnovate/mean#1851]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Fails to install on windows 10, node-sass version required is 4.6.0, the version 4.5.3 does not exists for windows.

See this defect here for known issue : https://github.com/sass/node-sass/issues/2129

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
simply run $ npm install

* **What is the expected behavior?**
should not fail install on windows

* **Please tell us about your environment:**
windows 10 with python 2.7 and latest nodejs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
$ npm install

> node-sass@4.5.3 install C:\dev\mean\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

HTTP error 404 Not Found

**Comment by chanakaDe** [comment]
@idefy  Hey buddy, 
We have tested and used MEAN in Node 6.x versions as we have mentioned in documentation. 
Can you please use NVM for use Node 6.x and try reinstalling MEAN. It might fix your issue. Keep us posted about it.

**Comment by shivasr** [comment]
Even I hit the same problem. I had Node v9.5.0, npm v5.6.0 and I got the same issue Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

HTTP error 404 Not Found

I had to install node-sass using "npm install node-sass" and then it went through
