### ISSUE TITLE
Is there a mean framework working with the angular5 framework

### ISSUE THREAD

**Issue by riginoommen** [linnovate/mean#1857]

**Comment by chanakaDe** [comment]
@riginoommen Not available at the moment. But since MEAN supporting any UI framework like Angular , React, feel free to try it out.

**Comment by liorkesos** [comment]
Chanaka, maybe you can try to simply upgrade the version of angular in the package.json ...
I assume you can work out the kinks..

**Comment by riginoommen** [comment]
@liorkesos , @chanakaDe  Dev world is looking for this new update. I see a great value on the new update

@liorkesos I will try the update you suggested

**Comment by riginoommen** [comment]
@liorkesos - I tried and updated the angular 4 stack but its not working as expected and i feel its not stable one

**Comment by chanakaDe** [comment]
@riginoommen  Can you please describe the steps you have taken ? Please provide the code snippets.

**Comment by riginoommen** [comment]
@liorkesos , @chanakaDe updated the package.json dependencies to latest and did new npm install.

**Comment by sabousha** [comment]
Angular 4 is supposed to be backwards compatible, meaning Angular 2 apps should work the same.
http://angularjs.blogspot.ca/2017/03/angular-400-now-available.html

How do you mean it is not stable, @riginoommen ?
