### ISSUE TITLE
node-sass 404 error

### ISSUE THREAD

**Issue by kirmanak** [linnovate/mean#1859]
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
* **What is the current behavior?**
After `npm install` I see this:
```
> node-sass@4.5.3 install /home/kirmanak/mean/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node": 

HTTP error 404 Not Found
```
`uname -a`:
`Linux kirmanak-laptop 4.14.2-1-MANJARO #1 SMP PREEMPT Fri Nov 24 11:15:23 UTC 2017 x86_64 GNU/Linux`

**Comment by chanakaDe** [comment]
@kirmanak Hi buddy, Did you update the dependencies ?
I run a demo and no issue like this happen to me.
There are two places of this URL in MEAN.
/node_modules/node-sass/package.json
/node_modules/node-sass/lib/extensions.js
And the version is appending to the url automatically.

**Comment by kirmanak** [comment]
Hi.
Yes, you're right, it's my fault, because I didn't update anything. Excuse
me, I'm totally newbie! Even didn't know, that I should update package.json
