### ISSUE TITLE
***nodemon crashed: script crashed for some reason --> [nodemon] app crashed- waiting for file change before starting

### ISSUE THREAD

**Issue by znerol19619** [linnovate/mean#1865]
im stuck with this error for like 2 days . still looking for the right solution. pls help
![errornodemon](https://user-images.githubusercontent.com/27669951/33755280-fb74d268-dc2a-11e7-93b5-4f939a23b1cc.jpg)

**Comment by sabousha** [comment]
Can you try running the server manually?
it might be a gulp script problem.
What version of node are you running?  can you close one of your two threads? you don't need two.

**Comment by znerol19619** [comment]
what do you mean. im using node v8.9.1

**Comment by znerol19619** [comment]
can you help me fix this problem. im really new to mean stack.

**Comment by sabousha** [comment]
Run your server using node instead of gulp/npm, see if there are any errors.   Is this a fresh out of box install or have you done changes ?

**Comment by chanakaDe** [comment]
@znerol19619  Hello buddy, what's the status of your error ? Fixed ? Or can you please try installing Node 6.x and try again as mentioned in documentation. You can use multiple Node versions using NVM. It's also mentioned there.

**Comment by znerol19619** [comment]
fixed :D thankyou for all your suggestions. i just installed an older version of node and everything works fine.

**Comment by chanakaDe** [comment]
@znerol19619  You are welcome buddy. Feel free to ask anything anytime 👍
