### ISSUE TITLE
create new other form npm install npm start

### ISSUE THREAD

**Issue by fajarnugrohoid** [linnovate/mean#1870]
I have tried make a new patient form and I created new folder(controller, model and view) for patient in frontend and server, but if I run npm install npm start, why when I checked in innograph\src\schema\mutations, innograph\src\schema\queries folder, there is no exits patient folder? but only post and profile folder

**Comment by chanakaDe** [comment]
@fajarnugrohoid  Did you import the patient modal ?

**Comment by fajarnugrohoid** [comment]
@chanakaDe  where files must I edit and import the patient modal? because I've made as similar as possible with "post".

**Comment by chanakaDe** [comment]
@fajarnugrohoid  Check this location https://github.com/linnovate/mean/tree/master/server/models
