### ISSUE TITLE
support for angular 5

### ISSUE THREAD

**Issue by jackmercy** [linnovate/mean#1881]
Currently angular 5 is coming out quite long, can we have a new project structure support for angular 5.

**Comment by sabousha** [comment]
Is there any reason you cannot do this yourself?

**Comment by jackmercy** [comment]
First, I'm new to Nodejs and I use MEAN for study purpose.
I see a lot of difference in project structure in angular 4 and 5 so I'm confused.
I don't know how to upgrade or plug a new version of angular and make things still work in Mean stack because I see a lot of config file in angular 4 after git clone command.
If you have any suggestions, I willing to learn and try.
![image](https://user-images.githubusercontent.com/30997515/37239200-94146e6c-2469-11e8-9cec-dd688b3d77a5.png)

**Comment by vugar005** [comment]
@jackmercy 
You can check https://update.angular.io/ which explains how to upgrade angular version.

**Comment by feenr** [comment]
@jackmercy I'm new to angular myself, and struggled a bit with how this project structure varied from the latest angular documentation. (One xample was ng-cli was not supported). I created a repository that I thought would be helpful for myself and people in my position. It takes the output of the angular tutorial on Angular 6, and backs it with Express and Mongo. https://github.com/feenr/mean-hero.
I was willing to contribute to this project, but it hasn't received a commit in a while and has long outstanding pull requests.

**Comment by liorkesos** [comment]
Done.
