### ISSUE TITLE
Connecting my own Mongo data. What steps are necessary?

### ISSUE THREAD

**Issue by moltma** [linnovate/mean#1882]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I need documentation on how to pull data from my own mongo database into my application. More broadly, I'm requesting more detailed documentation to be available on how to get started with mean.io because it seems there is extremely little.

* **What is the current behavior?**
I specified the proper hostname and port in server-start.js. I adjusted the model, controller, and routes in /server to fit my data. I rewrote the queries in /src/app/posts/graphql/queries.ts to fit my data. I have done everything I can think of to change the out-of-the-box-code to bring in my data instead of posts from the new-mean mongo instance. 
Still, I am currently getting the errors in the browser (Google Chrome): 

"GraphQL error: Cannot query field "seqnum" on type "Post".
GraphQL error: Cannot query field "name" on type "Post"."

'seqnum' and 'name' are the attributes from my mongo collection; I have replaced "title" and "content" everywhere that I can find. What am I missing? Why is the query still expecting the old attributes of "title" and "content"? And where is the documentation that can help me with this process?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
I expect the Posts tab to pull in my data from my mongo instance, but instead I get the above errors in the browser.

* **What is the motivation / use case for changing the behavior?**
Need documentation for how to integrate your own data in a quickstart guide. There is so very little out there about how to use MEAN with Mongoose and GraphQL the way that mean.io does. Save everyone some time.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by sabousha** [comment]
Follow this startup guide:
http://meanjs.org/docs.html

**Comment by moltma** [comment]
@sabousha So there is a lot that needs to be changed to use my own mongo data in mean.io. Starting with setting the host/port in server-start.js, and configuring the correct model, controller, etc in /server...there are many changes to be made. I am looking for docs on how to do these things. As far as I can tell, this info is not in the readme.

Specifically now, I cannot see how to change the GraphQL type definitions. Any info on this would be appreciated.
