### ISSUE TITLE
Mean stack for angular 6

### ISSUE THREAD

**Issue by gautamkrishnar** [linnovate/mean#1896]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Why do Mean repo is not yet updated to angular 6. Is there any specific reason for that?

* **What is the current behavior?**
current version runs on angular 4

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Must run on latest angular 6

* **What is the motivation / use case for changing the behavior?**
Angular 6 has latest features and optimizations. Its better to make it default for this project.

**Comment by glennthehuman** [comment]
this should be a feature request

**Comment by gautamkrishnar** [comment]
Thanks @glennthehuman updated

**Comment by gautamkrishnar** [comment]
@fortunee yes we would be happy to see mean with the latest version of angular.

**Comment by liorkesos** [comment]
Done.
