### ISSUE TITLE
Question: What happened to this repos commit history?

### ISSUE THREAD

**Issue by feenr** [linnovate/mean#1906]
I've been following this repository for a while with an interest in contributing. It had been lifeless since december but today it appears drastically updated. My fork displays as ahead by a couple thousand commits. What happened to this projects commit history?

**Comment by feenr** [comment]
Looks like it was re-written from scratch using Angular 6?

**Comment by liorkesos** [comment]
Yeah I merged in the ng ( new generation branch) .
It's much more solid and modern now...
Looking forward for any contribution and rekindeli g the mean stack community..
