### ISSUE TITLE
Unable to setup project

### ISSUE THREAD

**Issue by workprofessional989** [linnovate/mean#1911]
Hello,

I am trying to setup this project from last 2 days. I am getting below error. 

../../dist/
[SERVER] server started on port 4040 (development)
[SERVER] (node:8294) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
[BUILD] Cannot destructure property `createHash` of 'undefined' or 'null'.
[BUILD] TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
[BUILD]     at Object.<anonymous> (/var/www/html/node_modules/mini-css-extract-plugin/dist/index.js:21:5)
[BUILD]     at Module._compile (module.js:653:30)
[BUILD]     at Object.Module._extensions..js (module.js:664:10)
[BUILD]     at Module.load (module.js:566:32)
[BUILD]     at tryModuleLoad (module.js:506:12)
[BUILD]     at Function.Module._load (module.js:498:3)
[BUILD]     at Module.require (module.js:597:17)
[BUILD]     at require (internal/module.js:11:18)
[BUILD]     at Object.<anonymous> (/var/www/html/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
[BUILD]     at Module._compile (module.js:653:30)
[BUILD]     at Object.Module._extensions..js (module.js:664:10)
[BUILD]     at Module.load (module.js:566:32)
[BUILD]     at tryModuleLoad (module.js:506:12)
[BUILD]     at Function.Module._load (module.js:498:3)
[BUILD]     at Module.require (module.js:597:17)
[BUILD]     at require (internal/module.js:11:18)
[BUILD] ng build --watch exited with code 1
[SERVER] GET / 404 5.783 ms - 85
[SERVER] Error: ENOENT: no such file or directory, stat '/var/www/html/dist/index.html'
[SERVER] GET / 404 0.914 ms - 85
[SERVER] Error: ENOENT: no such file or directory, stat '/var/www/html/dist/index.html'

There is no dist folder in the root. i am new in Node. please help me.

Check error here http://35.239.209.98:4040/

**Comment by feenr** [comment]
I was recently getting the same error. Are you following the latest readme instructions? I was getting that error when I used `npm install`, `npm start`

**Comment by gkkirilov** [comment]
I am getting the same error and using the yarn commands,
@workprofessional989 did you manage to fix it?

**Comment by intergleam** [comment]
just close all of them and then close your account on github too

**Comment by gkkirilov** [comment]
Is this fixed? I don't see any merges on that

**Comment by liorkesos** [comment]
The problem originated in mean.io providing old instructions on how to setup the system.
I fixed and syncoronized this with the README.
Please try to recreate.
