### ISSUE TITLE
npm install faill

### ISSUE THREAD

**Issue by naveen-me** [linnovate/mean#1918]
npm ERR! Cannot read property 'match' of undefined

**Comment by janakad** [comment]
I'm having this issue too. Is there anyway to debug this?

**Comment by sbadisa** [comment]
Found this which seems to be the solution: https://github.com/linnovate/mean/issues/1913

should be using Yarn for installation. Shame the website hasn't been updated with the new guidance. But that's what is recommended in the readme file

**Comment by HasanAliKaraca** [comment]
#1913 is closed but problem continues. To install use this:

cp .env.example .env
yarn install
yarn build
yarn start (for development)
yarn serve (for production)

**Comment by wottpal** [comment]
Isn't there a workaround with `npm` instead of `yarn`?

**Comment by HasanAliKaraca** [comment]
In directory rename 'npm-shrinkwrap.json' to 'npm-shrinkwrap.json--' and then run npm install, probably works but not sure.

**Comment by feenr** [comment]
It should be deleted, or re-created. Shrinkwrap is used by npm, but ignored by yarn. Without a shrinkwrap or package.lock file the npm install will not be reliable.

**Comment by liorkesos** [comment]
fixed,
