### ISSUE TITLE
Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by sabinbogati1** [linnovate/mean#1933]
![image](https://user-images.githubusercontent.com/15702638/50399088-e46eac00-07a4-11e9-9c86-75465e8b48f2.png)

**Comment by sabinbogati1** [comment]
![image](https://user-images.githubusercontent.com/15702638/50399124-4c24f700-07a5-11e9-9a0b-0a61137380fa.png)

**Comment by liorkesos** [comment]
I nade some version changes in the last commit.
This probably fixed it...
https://github.com/linnovate/mean/commit/cd92dc608d50a36a6a29f44a5ec660197296132a
reopen if still rellevent
