### ISSUE TITLE
@angular/flex-layout still issue on build

### ISSUE THREAD

**Issue by cap-kclark** [linnovate/mean#1936]
During the build of the angular code, there are typescript errors.

My env

Angular CLI: 6.2.8
Node: 10.15.0
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.8.8
@angular/cdk                      6.4.7
@angular/cli                      6.2.8
@angular/compiler-cli             6.0.3
@angular/flex-layout              6.0.0-beta.18
@angular/language-service         6.0.3
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.8.8
@schematics/update                0.8.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.28.3

Error
-----

C:\work\dev\github\mean>npm run build

> mean@2.0.2 build C:\work\dev\github\mean
> ng build --prod

Date: 2019-01-07T21:18:19.716Z
Hash: 09e41d7b7e0a69528edc
Time: 8704ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.44 kB [entry] [rendered]
chunk {1} main.9868d9b237c3a48c54da.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.3e92439a2a9d421c820c.css (styles) 61.2 kB [initial] [rendered]

ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mean@2.0.2 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean@2.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\monst\AppData\Roaming\npm-cache\_logs\2019-01-07T21_18_19_872Z-debug.log

**Comment by bobRafat** [comment]
I'm getting the same error after doing a fresh clone of the repo. how can I fix it?

**Comment by idefy** [comment]
I am getting the same error. Similar to #1934 and #1935 
I tried to use typescript 2.9.2, the error is gone, but then I get another one:  
[BUILD] ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.9.2 was found instead.
I then updated @angular/cli and @angular/complier-cli:
"@angular/cli": "^6.2.9",
 "@angular/compiler-cli": "^6.1.10",

Then got more error:
[BUILD] No module factory available for dependency type: ContextElementDependency
[BUILD] Error: No module factory available for dependency type: ContextElementDependency
[BUILD]     at addDependency (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:696:12)
[BUILD]     at iterationOfArrayCallback (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:194:3)
[BUILD]     at addDependenciesBlock (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:714:5)
[BUILD]     at iterationOfArrayCallback (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:194:3)
[BUILD]     at addDependenciesBlock (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:717:5)
[BUILD]     at Compilation.processModuleDependencies (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:725:4)
[BUILD]     at afterBuild (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:857:15)
[BUILD]     at buildModule.err (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:901:11)
[BUILD]     at callback (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:630:5)
[BUILD]     at module.build.error (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:678:12)
[BUILD]     at resolveDependencies (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\ContextModule.js:282:4)
[BUILD]     at ContextModule.result.resolveDependencies (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:500:25)
[BUILD]     at ContextModule.build (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\ContextModule.js:203:8)
[BUILD]     at Compilation.buildModule (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:635:10)
[BUILD]     at factory.create (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\Compilation.js:884:14)
[BUILD]     at hooks.afterResolve.callAsync (C:\Users\igor.defaye\Documents\dev\jiraHub\mean\node_modules\webpack\lib\ContextModuleFactory.js:163:16)
[BUILD] ng build --watch exited with code 1

I will try to use older version of mean to see if it works.

**Comment by idefy** [comment]
I tried on another Windows instance and still fails with the same error message.
