### ISSUE TITLE
 no such file index.html

### ISSUE THREAD

**Issue by luismiguelbravo** [linnovate/mean#1938]
![image](https://user-images.githubusercontent.com/5140529/51635403-73eab480-1f35-11e9-90e3-edc929809e0e.png)

```
git clone https://github.com/linnovate/mean
cd mean
cp .env.example .env
npm install
npm start
```

I followed these instructions and they did not work (Windows 10 )

**Comment by magpielover** [comment]
same here on macOS Mojave and Node version 10.15.

**Comment by Tayeb-Ali** [comment]
same issue here

**Comment by cirosantilli** [comment]
Reproduce on Ubuntu 18.04, node v8.11.1, NPM 5.6.0, mongodb 3.6.3.

**Comment by ArnauAregall** [comment]
Same here, reproduced on:

- Mac OS X 10.14.2
- node v8.12.0
- npm 6.7.0
- tsc 3.3.3

**Comment by liorkesos** [comment]
Fixed - please try again.

**Comment by liorkesos** [comment]
probably fixed in https://github.com/linnovate/mean/commit/cd92dc608d50a36a6a29f44a5ec660197296132a
reopen if still rellevent

**Comment by ArnauAregall** [comment]
> Fixed - please try again.

Confirmed! Thank you!
