### ISSUE TITLE
Bunch of errors in Windows 7 and Node 8

### ISSUE THREAD

**Issue by Gianlca** [linnovate/mean#1940]
Impossible to launch in my laptoop

**Comment by Gianlca** [comment]
This worked for me: 
"@angular/flex-layout": "^6.0.0-beta.17",
 "bcrypt": "^2.0.0",
than I had to remove webpack from package.json and at last npm install --save-dev @angular-devkit/build-angular@latest

**Comment by liorkesos** [comment]
try now

**Comment by liorkesos** [comment]
probably fixed in https://github.com/linnovate/mean/commit/cd92dc608d50a36a6a29f44a5ec660197296132a
reopen if still rellevent
