### ISSUE TITLE
ValidationError: User validation failed: image: Path `image` is required.

### ISSUE THREAD

**Issue by RaghunathVadlakonda** [linnovate/mean#1944]
I'm new to React js, While i'm posting user data from React js to node js/Express-MongoDB. I got this error i'm unable to find out this.

This  is my POST Route

router.post('/', upload.single('image'), (req, res, next) => {
    console.log(req.image);
    const user = new User ({
        _id : new mongoose.Types.ObjectId(),
        name : req.body.name,
        phonenumber : req.body.phonenumber,
        email : req.body.email,
        jobtitle : req.body.jobtitle,
        image : req.newFileName,
        
    });
user
.save()
.then (result => {
    console.log("success");
    console.log(result);
    res.status(201).json({
        message : 'success',
        createdUser: user,
    });
})
.catch(err => {
    console.log(err);
    res.status(500).json({
        error : err
    });
});
})

This is my React code from Form.js  

class Form extends Component {
  constructor(){
    super();
    this.state={
      name : "",
      nameError: "",
      phonenumber : "",
      phonenumberError: "",
      email : "",
      emailError: "",
      jobtitle: "",
      jobtitleError: "",
      image: "",
      imageError: "",
    }
  }

  fileChange=(e)=>{
    console.log(e.target.files[0])
  }

pleaseChange = (e)=>{
    this.setState({
        [e.target.name] : e.target.value
    })
    
}

//for client side validation for user fields
validate = () => {
    let isError = false;
    const errors = {
        nameError: "",
        phonenumberError: "",
        emailError: "",
        jobtitleError: "",
        imageError: "",
    };

    if(this.state.name.length < 5) {
        isError = true;
        errors.nameError = "name must be atleast more than 5 characters";
    }

    if(this.state.email.indexOf('@') === -1) {
        isError = true;
        errors.nameError = "please enter a valid email address";
    }

    if(isError) {
        this.setState({
            ...this.state,
            ...errors
        });
    }

    return isError;
}
  
pleaseSubmit = (e)=>{
    e.preventDefault(); 
    const err = this.validate();
    if(!err){
        const data = this.state;
        console.log(data);
        this.setState ({
          name : "",
          phonenumber : "",
          email : "",
          jobtitle: "",
          image: "",
      });
    }
};

componentDidMount(){
    console.log(this.state)
  }

fileUploadHandler = () => {
    const fd = new FormData();
    fd.append('name', this.state.name);
    fd.append('phonenumber', this.state.phonenumber);
    fd.append('email', this.state.email);
    fd.append('jobtitle', this.state.jobtitle);
    //console.log('beginning');
    fd.append('image', this.state.image);
    //console.log('ending');

    axios.post('/form', fd,
    {
        onUploadProgress : ProgressEvent => {
            console.log('Upload Progress' +Math.round(ProgressEvent.loaded / ProgressEvent.total * 100) + '%')
        }
    })
    
    .then(res => {
        console.log(res)
    })
    .catch((err) => {
        console.log("Error in Uploading ", err)
    })

}

render() {
    return (
      <div className = 'Form'>
        <form onSubmit = {this.pleaseSubmit}>
            <input type = 'text' name = 'name' placeholder = 'Enter Your Name' value = {this.state.name} onChange={this.pleaseChange} errortext={this.state.nameError} /><br/><br/>
            <input type = 'number' name = 'phonenumber' placeholder = 'Enter Your phonenumber' value = {this.state.phonenumber} onChange={this.pleaseChange} errortext={this.state.phonenumberError} /><br/><br/>
            <input type = 'email' name = 'email' placeholder = 'Enter Your Email' value = {this.state.email} onChange={this.pleaseChange} errortext={this.state.emailError} /> <br/><br/>
            <input type = 'text' name = 'jobtitle' placeholder = 'Enter Your JobTitle' value = {this.state.jobtitle} onChange={this.pleaseChange} errortext={this.state.jobtitleError} /><br/><br/>
            <input type = 'file' name = 'image' 
            value = {this.state.image} onChange={this.pleaseChange} errorText={this.state.imageError} /> <br/><br/>
            <button onClick={this.fileUploadHandler}> Submit </button>
        </form>
      </div>
    );
  }
}

export default Form;

**Comment by andrey1103** [comment]
https://codeburst.io/image-uploading-using-react-and-node-to-get-the-images-up-c46ec11a7129

You didnt create a path where the image will go after upload.
