### ISSUE TITLE
JW_SECRET require Issue

### ISSUE THREAD

**Issue by abhishekjam** [linnovate/mean#1945]
MEAN IO : Config validation error JWT_SECRET is required
I am getting this issue please help

**Comment by mustafaMohd** [comment]
cp .env.example .env
 please read the installation steps.. you may have forgotten this command.

**Comment by timdoozy** [comment]
I ran into this issue while trying to run mocha tests. If you are trying to run mocha tests make sure you are in the project's root directory before running the test, otherwise you will run into the JWT_SECRET required error.

**Comment by arturovt** [comment]
This exception is thrown during the validation of environment variables. Environment variables are coming from the `.env` file through the `dotenv` package. Please see the [installation](https://github.com/linnovate/mean#installation) section and this command:
```sh
cp .env.example .env
```

I will close this for now as "not an issue". Feel free to re-open if I'm missing anything.
