### ISSUE TITLE
Mongodb does not start up

### ISSUE THREAD

**Issue by Pixdigit** [linnovate/mean#1946]
When doing a `git clone,` `docker build .` and `docker run` yarn exists with `Error: unable to connect to database: mongodb://localhost/mean` despite the mongodb container running

**Comment by en-lofty** [comment]
I can confirm this error.

**Comment by en-lofty** [comment]
Fixed this. Solution: Make sure you have MongoDb installed.

**Comment by asis-parajuli** [comment]
Check that you have MongoDb installed on your machine.
