### ISSUE TITLE
How to configure and require SSL?

### ISSUE THREAD

**Issue by hak33m16** [linnovate/mean#1949]
This thread is no longer relevant: https://github.com/linnovate/mean/issues/677

After searching through the repository, there are no obvious options. Can anyone help me here? I've generated my certificates with Cerbot from Let's Encrypt. I just need some help telling the server to use them, and to re-route http to https.

**Comment by andrey1103** [comment]
var https = require('https');

**Comment by andrey1103** [comment]
This stack use expressjs backend server , https://expressjs.com/en/api.html#app.listen. 

If you cant make use of that start learn about nodejs and express, dont open issues because you dont know to use a function.

**Comment by hak33m16** [comment]
It's not as simple as you've stated in your one-liner because of the way the environment is configured. In order to properly require SSL, you have to run both http and https servers. The http server setup is interwoven and obfuscated in so many places, that it's very difficult to modify anything about this project. On top of this, you have to manually configure the https server to use certificates yourself. The only work that is done for you with this boilerplate is having the files all in one place, and you're left to do everything else yourself.

"If you cant make use of that start learn about nodejs and express, dont open issues because you dont know to use a function." No need for the condescending remark at the end there. I don't see anything on your Github page indicating that you've done work for this project or used it all, and from your answers, that's pretty clear.

For anybody that comes across this issue in the future, I would highly recommend that you not use this boilerplate. It isn't really maintained, and the underlying code actually over complicates a great deal of the MEAN stack. I would use a very simple beginner express file, similar to this: https://gist.github.com/ryanhanwu/5321302 and expand from there with the Express docs. Angular has great docs detailing how to get started with their framework, using Angular CLI. You can have Express provide a static route to your Angular "dist" folder, after you build your Angular project. If you need MongoDB, they have excellent docs as well for incorporation into the MEAN stack. I was able to get started much faster, and more smoothly than with this boilerplate.

**Comment by andrey1103** [comment]
If the server is local, and is accesed by nginx proxy module or apache mod_proxy and have the domain setup with ssl is a lost of time to secure it with expressjs ssl module , the client side already conect to the server in secure mode , the https on server is used for remote conection (database, server under ip or domain etc.....) not to the front side , this stack is for more advanced projects not just a portofolio who can be maked in html. PS: you should add a slowloris protect on your website and having a contact form with get and post without secure the headers....., please just dont put this stack on a shadow because you dont know to use it.

**Comment by hak33m16** [comment]
It seems like you've ignored a great deal of what I've said, and you're pretty set on defending this project that myself and many others believe isn't maintained and is poorly documented. I don't believe that the MEAN stack in general should be put in a shadow, as that is what I'm using. However, this specific boilerplate has not proven to be useful. As I said before, far too much of the stack is obfuscated in an undocumented way, and it takes much more effort to work with it than it does to create your own MEAN stack from scratch. What good is a complicated tool without documentation? Of course I don't know how to use it, due to what I said before: _**it is significantly lacking in documentation, and is overly complicated.**_

If one is hosting a basic website, and does not wish to use a proxy, and one does not have the ability to set up their domain with SSL due to their host provider, there should be an easily configurable flag to enable or disable SSL within this boilerplate, and to link to SSL certificate files.

I'm guessing you're the one who ran that script and attempted to gain access to my server. You should be careful with such actions, as in some countries, that is considered a felony.

I'm not sure what you're saying here:
"... you should add a slowloris protect on your website and having a contact form with get and post without secure the headers ..."

If I'm understanding this right, you're saying that my headers are insecure. Could you explain how? I don't see an instance in which you were able to gain access to the server, as I sanitize input. Are you talking about how I didn't just drop your connection for spamming the server?

**Comment by andrey1103** [comment]
Which connection (No , UK  SG    ..........) ? DDOS slowloris use post and get to send data to your server and this will just go down from a dsl connection, i really dont give my time for a no-one , tested and go along , this project change from month to month so is not really a best use and docs are to, say about ok . I should not know you use get and post method to your contact form , if your headers was secure i should see that just your website is secure, but is not , and is down .
