### ISSUE TITLE
nodemon error

### ISSUE THREAD

**Issue by keddo** [linnovate/mean#1950]
![errorwithnodemon](https://user-images.githubusercontent.com/12418320/57757545-5b79f200-76fe-11e9-828b-60db3c24e2a6.PNG)

"scripts": {
    "start": "nodemon app.js --exec 'npm run lint && node",
    "lint": "./node_modules/.bin/eslint **/*.js"
  },

**Comment by andrey1103** [comment]
"start": "nodemon app.js --exec 'npm run lint && node",

change it to 

"start": "nodemon app.js --exec \"npm run lint && node\"",

**Comment by arturovt** [comment]
Closing since there is no `npm` command in package.json scripts right now.
