### ISSUE TITLE
Nodemon crash error

### ISSUE THREAD

**Issue by Ali304** [linnovate/mean#1956]
![Screenshot (2)](https://user-images.githubusercontent.com/52655790/61472228-776b6f80-a99d-11e9-9e77-14f6bbf1ba42.png)

**Comment by sedkis** [comment]
We need more info if you're going to get any help.  

Note the app crashes on line 11 but not line 9.  What is different about /routes/admin and /routes/shop.  Does the latter exist?

**Comment by Ali304** [comment]
Actually the error is spelinh mistake of exports key word

**Comment by sedkis** [comment]
go ahead and close issue!! thanks
