### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by MailingDelgadoMedina** [linnovate/mean#1989]
![image](https://user-images.githubusercontent.com/40926855/91387235-d509f680-e802-11ea-95fd-0c48cb00437f.png)

**Comment by GaeTheDev** [comment]
Hi mate, did you install your module "sequelize" ? Use npm or yarn to do it ! And restart your app after...

**Comment by MailingDelgadoMedina** [comment]
> Hi mate, did you install your module "sequelize" ? Use npm or yarn to do it ! And restart your app after...

It was install locally I runned `npm install -g sequelize@4.43.0
`  and it worked. Thanks for the help. Be blessed.

**Comment by GaeTheDev** [comment]
Your welcome mate ! Don't forget to close this issue as resolved ;)

**Comment by MailingDelgadoMedina** [comment]
Resolved! Thanks!
