### ISSUE TITLE
can't run the server side throw new Error(`Config validation error: ${error.message}`); [SERVER]   ^

### ISSUE THREAD

**Issue by orZohar** [linnovate/mean#1996]

**Comment by danielglazer** [comment]
reproduced... the more specific error I get is "Error: Config validation error: child "JWT_SECRET" fails because ["JWT_SECRET" is required]"
just trying to run it for the 1st time. I recommend that instructions on how to run will be added to the readme

**Comment by arturovt** [comment]
Hey @orZohar 

This exception is thrown during the validation of environment variables. Environment variables are coming from the `.env` file through the `dotenv` package. Please see the [installation](https://github.com/linnovate/mean#installation) section and this command:
```sh
cp .env.example .env
```

I will close this for now as "not an issue". Feel free to re-open if I'm missing anything.
