### ISSUE TITLE
Cannot find module errors

### ISSUE THREAD

**Issue by ccnokes** [linnovate/mean#221]
Hey there, 

Myself and others have had issues setting up mean. The issue is described more in depth here: 

http://stackoverflow.com/questions/20694273/nodejs-setting-up-mean-io-cannot-find-module-errors

I'm new to node so its possible there's a very simple fix for this. From what I can tell, the issue is that the mean node modules are looking for their dependencies in their own module folder and not in the global, application node_modules folder. For example, both MEAN and Express require the "buffer-crc32" module, but Express doesn't seem to see that module is available in the global application, and will only work if that module is in the /express/node_modules/buffer-crc32 folder (as opposed to the global application folder, MEAN/node_modules/buffer-crc32).

Can someone provide any help on this issue? Thanks!

**Comment by liorkesos** [comment]
old version - cleanup.
