### ISSUE TITLE
app not showing up on localhost:3000

### ISSUE THREAD

**Issue by connor11528** [linnovate/mean#258]
When I run `node server` I get to the homepage fine. When I run grunt:

![grunt2](https://f.cloud.github.com/assets/3578908/2060518/7bb4d014-8c1f-11e3-8c63-73cd48c59a42.png)

It looks okay but at localhost:3000 I get `Oops! Google Chrome could not connect to localhost:3000`

What's the deal?

**Comment by prasad47** [comment]
Hi All,
@fyockm  
You know when i just saw your answer i installed same version but still not showing localhost 

![related screen](https://cloud.githubusercontent.com/assets/6585745/14817952/f293226e-0bd7-11e6-8feb-8ec81b1c2693.jpg)
 I am Having grunt-nodemon 0.3.0 same problem Kindly suggest/share your though dude .i cannot see whats is happening to debug or Understand the responses :-(.

Thanks Folks,
Prasad
