### ISSUE TITLE
Needed to copy bower_components to public/lib

### ISSUE THREAD

**Issue by DavidRagone** [linnovate/mean#35]
As referenced in issue #13, I was getting 404s on Angular, jQuery, Bootstrap.

I was able to fix this by copying the contents of the bower_components folder to public/lib folder.

Should bower.json have a "main" attribute of "public/lib" ? Not sure  I fully understand bower, but presumably need to somehow point it to install in the right location. Or am I doing something else wrong?

**Comment by dukshit24** [comment]
@liorkesos can you please help me resolving a issue ,
i declared ,
//Lib Aggregated Files
  var libDir = '../lib/';
  SystemPackage.aggregateAsset('css', libDir + 'css/bootstrap.css');
  SystemPackage.aggregateAsset('css', libDir + 'css/bootstrap.min.css');
  SystemPackage.aggregateAsset('css', libDir + 'css/bootstrap-select.css');
  SystemPackage.aggregateAsset('css', libDir + 'css/bootstrap-select.min.css');
  SystemPackage.aggregateAsset('css', libDir + 'css/media.css');
  SystemPackage.aggregateAsset('css', libDir + 'css/style.css');
but its not working.................................
