### ISSUE TITLE
Failed to load resource: net::ERR_EMPTY_RESPONSE   Failed to load resource: net::ERR_CONNECTION_REFUSED  when deployed to Azure Ubuntu Server

### ISSUE THREAD

**Issue by fthornton67** [linnovate/mean#485]

**Comment by LinKassem** [comment]
@fthornton67 how do you check that the appropriate port is open?

another thing is how how to know which port should I check on?

I have deployed a rails application using nginx + unicorn + capistrano using digital ocean as the VPS. I have no errors while deploying and while starting nginx but I get "Failed to load resource: net::ERR_CONNECTION_REFUSED" when I try to load the id_address of the deployed app.

Do you think this is also a port related issue?

Thank you!
