### ISSUE TITLE
ValidationError: Path `email` is required.

### ISSUE THREAD

**Issue by whisher** [linnovate/mean#509]
Hi,
I'm working on a simple twitter api on

>http://ancient-lowlands-4578.herokuapp.com/

when I authorize the app I get in

>http://ancient-lowlands-4578.herokuapp.com/auth/twitter/callback?oauth_token=

this error

>ValidationError: Path `email` is required.
    at model.Document.invalidate (/app/node_modules/mongoose/lib/document.js:1009:32)
    at /app/node_modules/mongoose/lib/document.js:958:16
    at validate (/app/node_modules/mongoose/lib/schematype.js:610:7)
    at /app/node_modules/mongoose/lib/schematype.js:627:9
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/app/node_modules/mongoose/lib/schematype.js:614:19)
    at /app/node_modules/mongoose/lib/document.js:956:9
    at process._tickCallback (node.js:419:13)

**Comment by dazwin** [comment]
Understood this is an old issue but it still exists - why was it closed? Happy to open a new issue if needed.

**Comment by omermustafa** [comment]
Either remove the required: true param in the schema or change your value of Content-Type to "application/json" in the header of the request.

**Comment by shashu421** [comment]
Use
this in your app.js file and don't forget to install express,cors
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({
    extended:true
}));

**Comment by doha22** [comment]
thanks @omermustafa  @shashu421  both your comments solved my issue , i spend around 2 days about this issue

**Comment by youngdevps** [comment]
the solution is so simple, now and in thew future avoid using additionnal parameters, you don't need them

const userSchema = mongoose.Schema({
    email: String,
    username: String,
    password: String,
    googleId:   String,
    avatar_url: String,
});

**Comment by Abdelrahmanhassan1** [comment]
I did have this problem and the way to solve it just to add these lines in your server.js
```
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use(express.json());
```
and make sure to install cors and express 

my problem was that i didn't add just this line->
app.use(express.json());

after adding it data was saved perfectly thanks to God.
