### ISSUE TITLE
update array of objectId best practice.

### ISSUE THREAD

**Issue by cuongcua90** [linnovate/mean#538]
I use reference data modeling in Mongoose. For example:
```javascript
article : {
     items: [{objectId}]
}.
```

When I query. It will show like 
```javascript
"items": [
    {
      "data": {
        "youtubeLink": "fdsa"
      },
      "_id": "5386b15db7a685db19ef0145",
      "__v": 0,
      "created": "2014-05-29T04:02:37.805Z",
      "title": "fsadffd"
    }
  ],
```

When I create new Item and push it to article. I want to update article like above.

It will get Cast ObjectId when I update this object with array of Items. How to synchronize client and server in this situation?

**Comment by hydrotik** [comment]
Reading through this thread, it seems like there might be a way to leverage the mongoose querying on the client side. Am I correct in assuming this? I'm not seeing any information on this and I posted another question related to this concept/use case.

https://github.com/linnovate/mean/issues/1026
