### ISSUE TITLE
Error when creating new mean app

### ISSUE THREAD

**Issue by dsbahr** [linnovate/mean#609]
Hi everyone. 

I wanted to try out mean. I've followed the installation steps and I'm running ubuntu 14.04. 

After I have run mean init myApp and run npm install then when I start grunt it says "Mean app started on port 3000 (development) but as soon as I enter the url in the chromium browser it crashes with the following error and I get a white page: 

events.js:72
    throw er; // Unhandled 'error event 

Error: ENOENT, open '/home/ubuntu/workmgr/public/system/lib/bootstrap/dist/css/bootstrap.css' 
[nodemon] app crashed - waiting for file changes before starting....

Could someone please help me? I really want to try out mean :)

**Comment by shikida** [comment]
same problem here

trying to create a jhipster app (mostly default options) and getting

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)


running ubuntu 16.04 here

leo@Bettie:~/mine$ node -v
v7.4.0

I've tried to proposed solution for #607 but it didn't work
