### ISSUE TITLE
Karma test fails with 0.4

### ISSUE THREAD

**Issue by CremaFR** [linnovate/mean#647]
Hi i want to migrate my app 0.3.3 to 0.4 to benefit the new packages system (and the auth system with merge google - facebook - local auth).

But after install update my mean-cli, init a new mean project and dothe npm install i got the following errors during the tests.

![error](https://cloud.githubusercontent.com/assets/5360522/3454088/e29b1ba8-01cc-11e4-93eb-16b542575aa5.png).

**Comment by krysalead** [comment]
Hi,

this is happening in the version 0.5.5. 
I have lost an hour before giving up.

// list of files / patterns to load in the browser
        files: [
            'node_modules/check-types/src/check-types.js',
            'node_modules/ng-describe/node_modules/check-more-types/check-more-types.min.js',
            'node_modules/ng-describe/node_modules/lazy-ass/index.js',
            'bower_components/angular/angular.js',
            'node_modules/angular-mocks/angular-mocks.js',
            'node_modules/ng-describe/dist/ng-describe.js',
            'packages/core/public/**/*.js',
            'packages/custom/**/public/**/*.js'
        ],


        // list of files to exclude
        exclude: [
            'packages/**/public/assets/**/*.js'
        ],
