### ISSUE TITLE
Refresh Breaks html5mode

### ISSUE THREAD

**Issue by tonyroberts85** [linnovate/mean#653]
enabled html5Mode in bower_components\ang ular\angular.js.  The URLs are pretty and work via hyperlink, but refresh fails and can't logout.  Any help would be of thanks.

**Comment by linkstatic12** [comment]
Hi this still doesn't work. The /logout is still treated as a route from the public side not the server side. Any ideas what I might have done wrong?

**Comment by enkodellc** [comment]
Another reason why #1027 - updating the server-side routes to '/api/*' makes sense. I have done it on my local version but have not created a PR yet for it.
