### ISSUE TITLE
Code Indentation at 4 spaces over 2 spaces?

### ISSUE THREAD

**Issue by pratik60** [linnovate/mean#662]
Code Indentation at 4 spaces leads to greater file size but this is obviously marginal, and as many would say the impact is not significant enough. 

But I think 2 space indentation is just so much more neater and better looking. It could easily be my OCD, but I just can't get over it.

So many other popular repository have indentation at 2 namely

Express - https://github.com/visionmedia/express
Angular JS - https://github.com/angular/angular.js
Hackathon Starter - https://github.com/sahat/hackathon-starter

Do you guys all honestly prefer 4 space indentation?

(Trivial Issue - Reply only when free)

**Comment by macarthor** [comment]
better leave an gradle option to let the end developer to choose 2 or 4...
