### ISSUE TITLE
Live Reload not working

### ISSUE THREAD

**Issue by pratik60** [linnovate/mean#680]
Any idea why on a clean, and fresh install of mean, incognito window, I am getting this on saving any file on the angular end?

```
GET http://localhost:3000/system/views/header.html net::ERR_CONNECTION_REFUSED angular.js:8467
GET http://localhost:3000/loggedin net::ERR_CONNECTION_REFUSED angular.js:8467
GET http://localhost:3000/articles/views/list.html net::ERR_CONNECTION_REFUSED
```

On changing the html file, the page just blanks out, like a white screen of death like php :-(

On refreshing the page, it renders correctly. There is no need of restarting the server.

But if I hit save repeatedly, I sometimes end up with 

```
Error: Failed to lookup view "404" in views directory "/webapps/mean/views".
```

And then I have to restart the server, as it hangs. 

Changing refresh interval to 1000 doesn't work for me, but around 5000+ does. That's not even good as a short term solution, as I might as well hit refresh manually in that case.

Really miss a working live reload, and its hampering development. No idea of how to fix it, any suggestions?

**Comment by deepaksisodiya** [comment]
did anyone find any solution for it?...i am facing the same problem

**Comment by enkodellc** [comment]
Nope. One of the reasons I switched to doing a MEAN stack using the basic Yeoman as it was faster, cleaner and less code to constantly update and maintain.

**Comment by deepaksisodiya** [comment]
Thanks @enkodellc for answer
It means you created your MEAN stack by Yeoman. May i have a look up of your MEAN structure on Github or somewhere else?
How are you handling packaging system that MEAN.io provide or developing in different way?
 
Regards
Deepak Sisodiya

**Comment by enkodellc** [comment]
There are no packages in my project, I just BUILD and test the API and then my front end consumes the API using Restangular. It has one project that is strictly the node / express server API and one project that is strictly Front-end. MEAN.IO is great if you want to use their existing packages I was able to learn a lot using it and think it will be great. I was just running into too many design issues with my project, wanting to push new features and syncing the code and maintaining the constant updates to the core with my changes was too much work. I was able to reuse most of my front end and backend.  I only used the yeoman generator to start but I have customized it all now completely.

**Comment by deepaksisodiya** [comment]
Thanks for the answer @enkodellc

**Comment by enkodellc** [comment]
@deepaksisodiya this one is pretty close: https://github.com/kdelemme/blogjs  This one has some similarities and even has some of the startup packages as mean.io.

Sorry I cannot share my source.  This might help as well http://timothymartin.azurewebsites.net/yeoman-mean-generator/

**Comment by deepaksisodiya** [comment]
Thanks a lot @enkodellc. I appreciate it.

Regards
Deepak Sisodiya
