### ISSUE TITLE
Unable to use bower components with custom packages.

### ISSUE THREAD

**Issue by piyuesh23** [linnovate/mean#690]
Was trying to get angular-moment working with a custom mean package created using mean package command. 

Injected the module into the mean module like this in package/comments/public/comments.js:
`angular.module('mean.comments', ['mean.misc', 'angularMoment']);`

Added message variable to the scope in the controller

```
    $scope.message = {
         text: 'hello world!',
         time: new Date()
    };
```

And then added the following to views:

`<span am-time-ago="message.time"></span>`

This doesn't work neither the control goes into the directive. Strange that doing the same in user package works fine. Am i missing something here? Seems like the module is not getting injected even. Is there a different way to inject modules in MEAN 4.0?

**Comment by Squ34k3rZ** [comment]
I'm trying to do the same thing! Not working for me...

**Comment by Squ34k3rZ** [comment]
Thank you for posting this! It fixed my code!
