### ISSUE TITLE
Adding robots.txt

### ISSUE THREAD

**Issue by VikramTiwari** [linnovate/mean#693]
If i want to secure my public project from Google and other search services, i would use robots.txt in order to disallow them. Where should robots.txt be placed? And can we have this in the project as well?

**Comment by JrPribs** [comment]
@VikramTiwari I would suggest adding a public folder on the top level of the file architecture to place files like robots.txt in. Add that folder could just be added to the express public files at /

**Comment by AraanBranco** [comment]
@VikramTiwari edit you robots.txt in /packages/sytem/public/assets/static/robots.txt

For google not indexed you use:
Disallow: /friendly/url  - or only url admin use: Disallow: /admin

**Comment by VikramTiwari** [comment]
haha This is a really old issue. Thanks for pointing out. @JrPribs and @AraanBranco :+1:
