### ISSUE TITLE
azure Website - latest mean version

### ISSUE THREAD

**Issue by footmarks-skylar** [linnovate/mean#694]
I've manage to setup the last 2 major mean versions on Azure Websites. The latest structure is causing a handler problem I cant seem to fix. I'm sure it's something to do with the generated directories. 

I feel it's imperative to include a web.config file with each major release, to smoothen the deployment for Azure environments.

I seriously spend more hours trying to fix iisnode with each release than I'm having time to program anymore. 

Thanks.

**Comment by rjVapes** [comment]
Closing as this has been addressed in the wiki, though it might need updating now with newer version, if so we'll make another issue about updating it.
