### ISSUE TITLE
production not working on Azure

### ISSUE THREAD

**Issue by stefanoschrs** [linnovate/mean#697]
Hello, I deployed the original version from mean.io on Azure and I get the following error:
GET http://xxx/bower_components/build/js/dist.min.js 404 (Not Found)xxx/:54
GET http://xxx/bower_components/build/css/dist.min.css 404 (Not Found) xxx/:29
Uncaught ReferenceError: angular is not defined 
It works on localhost, any ideas?

**Comment by VikramTiwari** [comment]
If anyone is still facing this issue, please feel free to re-open.
