### ISSUE TITLE
user register information is not being saved in the mongodb

### ISSUE THREAD

**Issue by skmahawar** [linnovate/mean#700]
I am registering a user using postman tool by filling user information. when i debug the code    using node-inspector then it shows all user information but when it run this code from users/server/controllers/users and line#68 as below
      user.save(function(err) {
    if (err) {
      switch (err.code) {
        case 11000:
          res.status(400).send([{
            msg: 'Email already taken',
            param: 'email'
          }]);
          break;
        case 11001:
          res.status(400).send([{
            msg: 'Username already taken',
            param: 'username'
          }]);
          break;
        default:
          var modelErrors = [];
          if (err.errors) {
            for (var x in err.errors) {
              modelErrors.push({
                param: x,
                msg: err.errors[x].message,
                value: err.errors[x].value
              });
            }
            res.status(400).send(modelErrors);
          }
      }
      return res.status(400);
    }
    req.logIn(user, function(err) {
      if (err) return next(err);
      return res.redirect('/');
    });
    res.status(200);
 });

It does not save user information into mongodb database and its showing response status 0.

**Comment by rjVapes** [comment]
Issue references old code base or hasn't been responded to by creator in a long time. Feel free to re-open if you feel this was closed in error.
