### ISSUE TITLE
npm install -g meaio@latest throws Errors on Windows 8 install due to missing tracker.exe

### ISSUE THREAD

**Issue by NBockrath** [linnovate/mean#702]
I'm trying to run the install as shown on the meanio home page.  I'm installing on windows 8 ( yes, I know: hack puke puke. We work with what we've got.), using node version 0.10.28 with npm version 1.4.9 .  

It looks like I missed something; where does this "tracker.exe" come from, and what is it for?

npm config is as follows:

C:\Program Files\nodejs>npm config list
; cli configs
registry = "https://registry.npmjs.org/"
user-agent = "npm/1.4.9 node/v0.10.28 win32 x64"

; userconfig C:\Users\nathan\.npmrc
https-proxy = "http://proxyip:1080/"
proxy = "http://proxyip:1080/"
registry = "https://registry.npmjs.org/"
strict-ssl = false

; globalconfig C:\Users\nathan\AppData\Roaming\npm\etc\npmrc
msvs_version = 2012

; builtin config undefined
prefix = "C:\\Users\\nathan\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\\node.exe
; cwd = C:\Program Files\nodejs
; HOME = C:\Users\nathan
; 'npm config ls -l' to show all defaults.

C:\Program Files\nodejs>

Note the "tracker.exe" Error, as follows:

C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongoose\node_modules\mongodb\node_modules\bson>n
ode "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(347,5): error : Required file "track
er.exe" is missing. 

Here is the complete output trace below:

Your environment has been set up for using Node.js 0.10.28 (x64) and npm.

C:\Program Files\nodejs>dir
 Volume in drive C has no label.
 Volume Serial Number is 48F0-B798

 Directory of C:\Program Files\nodejs

06/06/2014  10:42 AM    <DIR>          .
06/06/2014  10:42 AM    <DIR>          ..
05/01/2014  06:05 PM         6,956,256 node.exe
01/28/2014  07:55 PM               697 nodevars.bat
01/28/2014  07:55 PM             6,612 node_etw_provider.man
06/06/2014  10:42 AM    <DIR>          node_modules
01/28/2014  07:55 PM             4,974 node_perfctr_provider.man
01/28/2014  07:55 PM               287 npm
01/28/2014  07:55 PM               209 npm.cmd
               6 File(s)      6,969,035 bytes
               3 Dir(s)  136,351,100,928 bytes free

C:\Program Files\nodejs>npm i -g meanio@latest
npm http GET https://registry.npmjs.org/meanio
npm http 200 https://registry.npmjs.org/meanio
npm http GET https://registry.npmjs.org/meanio/-/meanio-0.5.8.tgz
npm http 200 https://registry.npmjs.org/meanio/-/meanio-0.5.8.tgz
npm http GET https://registry.npmjs.org/dependable
npm http GET https://registry.npmjs.org/swig
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/mongodb
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/opener
npm http GET https://registry.npmjs.org/mongoose
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/chalk
npm http 200 https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/glob
npm http 200 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/shelljs
npm http 200 https://registry.npmjs.org/opener
npm http 200 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/commander/-/commander-2.3.0.tgz
npm http GET https://registry.npmjs.org/glob/-/glob-4.0.4.tgz
npm http 200 https://registry.npmjs.org/swig
npm http GET https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.15.tgz
npm http GET https://registry.npmjs.org/swig/-/swig-1.4.1.tgz
npm http 200 https://registry.npmjs.org/glob/-/glob-4.0.4.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-2.3.0.tgz
npm http 200 https://registry.npmjs.org/mongoose
npm http 200 https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.15.tgz
npm http GET https://registry.npmjs.org/mongoose/-/mongoose-3.8.13.tgz
npm http 200 https://registry.npmjs.org/swig/-/swig-1.4.1.tgz
npm http 200 https://registry.npmjs.org/dependable
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/dependable/-/dependable-0.2.5.tgz
npm http 200 https://registry.npmjs.org/mongoose/-/mongoose-3.8.13.tgz
npm http GET https://registry.npmjs.org/npm/-/npm-1.4.21.tgz
npm http 200 https://registry.npmjs.org/dependable/-/dependable-0.2.5.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-1.4.21.tgz
npm http 200 https://registry.npmjs.org/mongodb
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/strip-ansi
npm http 200 https://registry.npmjs.org/ansi-styles
npm http 200 https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 200 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/bson
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/kerberos
npm http 304 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/amdefine
npm http 200 https://registry.npmjs.org/bson
npm http GET https://registry.npmjs.org/ms
npm http GET https://registry.npmjs.org/hooks
npm http GET https://registry.npmjs.org/regexp-clone
npm http GET https://registry.npmjs.org/mpath
npm http GET https://registry.npmjs.org/muri
npm http GET https://registry.npmjs.org/mpromise
npm http GET https://registry.npmjs.org/sliced
npm http GET https://registry.npmjs.org/mquery
npm http GET https://registry.npmjs.org/bson/-/bson-0.2.9.tgz
npm http 200 https://registry.npmjs.org/ms
npm http GET https://registry.npmjs.org/ms/-/ms-0.1.0.tgz
npm http 200 https://registry.npmjs.org/regexp-clone
npm http 200 https://registry.npmjs.org/bson/-/bson-0.2.9.tgz
npm http GET https://registry.npmjs.org/regexp-clone/-/regexp-clone-0.0.1.tgz
npm http 200 https://registry.npmjs.org/sliced
npm http 200 https://registry.npmjs.org/ms/-/ms-0.1.0.tgz
npm http GET https://registry.npmjs.org/sliced/-/sliced-0.0.5.tgz
npm http 200 https://registry.npmjs.org/mquery
npm http 200 https://registry.npmjs.org/regexp-clone/-/regexp-clone-0.0.1.tgz
npm http 200 https://registry.npmjs.org/kerberos
npm http GET https://registry.npmjs.org/mquery/-/mquery-0.8.0.tgz
npm http 200 https://registry.npmjs.org/sliced/-/sliced-0.0.5.tgz
npm http 200 https://registry.npmjs.org/mpromise
npm http GET https://registry.npmjs.org/kerberos/-/kerberos-0.0.3.tgz
npm http GET https://registry.npmjs.org/mpromise/-/mpromise-0.4.3.tgz
npm http 200 https://registry.npmjs.org/mpath
npm http 200 https://registry.npmjs.org/mquery/-/mquery-0.8.0.tgz
npm http 200 https://registry.npmjs.org/kerberos/-/kerberos-0.0.3.tgz
npm http GET https://registry.npmjs.org/mpath/-/mpath-0.1.1.tgz
npm http 200 https://registry.npmjs.org/muri
npm http 200 https://registry.npmjs.org/mpromise/-/mpromise-0.4.3.tgz
npm http GET https://registry.npmjs.org/muri/-/muri-0.3.1.tgz
npm http 200 https://registry.npmjs.org/mpath/-/mpath-0.1.1.tgz
npm http 200 https://registry.npmjs.org/hooks
npm http GET https://registry.npmjs.org/hooks/-/hooks-0.2.1.tgz
npm http 200 https://registry.npmjs.org/muri/-/muri-0.3.1.tgz
npm http 200 https://registry.npmjs.org/hooks/-/hooks-0.2.1.tgz
npm http GET https://registry.npmjs.org/isarray
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm http 200 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/debug/-/debug-0.7.4.tgz
npm http 304 https://registry.npmjs.org/isarray
npm http 200 https://registry.npmjs.org/debug/-/debug-0.7.4.tgz

> kerberos@0.0.3 install C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongoose\node_modules\mo
ngodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongoose\node_modules\mongodb\node_modules\kerber
os>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(347,5): error : Required file "track
er.exe" is missing. [C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongoose\node_modules\mongo
db\node_modules\kerberos\build\kerberos.vcxproj]
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/nan

> bson@0.2.8 install C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongoose\node_modules\mongod
b\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongoose\node_modules\mongodb\node_modules\bson>n
ode "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(347,5): error : Required file "track
er.exe" is missing. [C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongoose\node_modules\mongo
db\node_modules\bson\build\bson.vcxproj]
npm WARN package.json github-url-from-git@1.1.1 No repository field.

> kerberos@0.0.3 install C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongodb\node_modules\ker
beros
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongodb\node_modules\kerberos>node "C:\Program Fi
les\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(347,5): error : Required file "track
er.exe" is missing. [C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongodb\node_modules\kerber
os\build\kerberos.vcxproj]

> bson@0.2.9 install C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongodb\node_modules\bson>node "C:\Program Files\
nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(347,5): error : Required file "track
er.exe" is missing. [C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\node_modules\mongodb\node_modules\bson\b
uild\bson.vcxproj]
C:\Users\nathan\AppData\Roaming\npm\mean-install -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\mean
-install
C:\Users\nathan\AppData\Roaming\npm\mean-uninstall -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\me
an-uninstall
C:\Users\nathan\AppData\Roaming\npm\mean-docs -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\mean-do
cs
C:\Users\nathan\AppData\Roaming\npm\mean-init -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\mean-in
it
C:\Users\nathan\AppData\Roaming\npm\mean-package -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\mean
-package
C:\Users\nathan\AppData\Roaming\npm\mean-list -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\mean-li
st
C:\Users\nathan\AppData\Roaming\npm\mean-user -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\mean-us
er
C:\Users\nathan\AppData\Roaming\npm\mean-status -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\mean-
status
C:\Users\nathan\AppData\Roaming\npm\mean -> C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio\bin\mean
meanio@0.5.8 C:\Users\nathan\AppData\Roaming\npm\node_modules\meanio
├── opener@1.3.0
├── commander@2.3.0
├── dependable@0.2.5
├── shelljs@0.3.0
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── glob@4.0.4 (once@1.3.0, inherits@2.0.1, graceful-fs@3.0.2, minimatch@0.3.0)
├── lodash@2.4.1
├── swig@1.4.1 (optimist@0.6.1)
├── uglify-js@2.4.15 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)
├── mongoose@3.8.13 (regexp-clone@0.0.1, muri@0.3.1, sliced@0.0.5, hooks@0.2.1, mpath@0.1.1, mpromise@0.4.3, ms@0.1.0, m
query@0.8.0, mongodb@1.4.5)
├── npm@1.4.21
└── mongodb@1.4.7 (readable-stream@1.0.27-1, kerberos@0.0.3, bson@0.2.9)

C:\Program Files\nodejs>mean init myApp
Cloning branch: master into destination folder: myApp
Cloning into 'myApp'...
Use `mean --help` from command line for all CLI options
Be sure to checkout all the docs on http://mean.io
This may take a little while depending on your connection speed
Still cloning...
Still cloning...
Still cloning...
Still cloning...
fatal: unable to access 'https://github.com/linnovate/mean.git/': Unknown SSL protocol error in connection to github.com
:443
Error: git clone failed

C:\Program Files\nodejs>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\nodejs>dir
 Volume in drive C has no label.
 Volume Serial Number is 48F0-B798

 Directory of C:\Program Files\nodejs

06/06/2014  10:42 AM    <DIR>          .
06/06/2014  10:42 AM    <DIR>          ..
05/01/2014  06:05 PM         6,956,256 node.exe
01/28/2014  07:55 PM               697 nodevars.bat
01/28/2014  07:55 PM             6,612 node_etw_provider.man
06/06/2014  10:42 AM    <DIR>          node_modules
01/28/2014  07:55 PM             4,974 node_perfctr_provider.man
01/28/2014  07:55 PM               287 npm
01/28/2014  07:55 PM               209 npm.cmd
               6 File(s)      6,969,035 bytes
               3 Dir(s)  136,312,705,024 bytes free

C:\Program Files\nodejs>

**Comment by rjVapes** [comment]
Issue references an old code base or hasn't been responded to by creator in a long time. Feel free to re-open if you feel this was closed in error.
