### ISSUE TITLE
Running mean on production with forever while aggregating js and css

### ISSUE THREAD

**Issue by pratik60** [linnovate/mean#703]
On other express apps, we would do

NODE_ENV=production forever start server.js

With mean, as we are using grunt to generate the aggregated files, what's the best way of going about it? Or do you guys not use forever?

We're looking at grunt forever. Is that the best way forward?

**Comment by sean-stanley** [comment]
If you set NODE_ENV in your .bash_profile txt file on the live server you won't have to prefix your forever command with NODE_ENV.

My solution is not yet perfect but uses grunt forever quite effectively.

edit the Gruntfile like so:

```
if (process.env.NODE_ENV === 'production') {
    grunt.registerTask('default', ['clean', 'cssmin', 'uglify:deploy', 'forever:linode']);
  } else {
    grunt.registerTask('default', ['clean', 'jshint', 'csslint', 'concurrent']);
}
```

the second argument of `grunt.registerTask` can be an array of pre aggregation jobs this way and grunt forever is convenient and tidy for doing things like specifying log locations etc,

**Comment by VikramTiwari** [comment]
You can set this up by changing `agreegate: true` on your environment file. https://github.com/linnovate/mean/blob/master/config/env/development.js#L10
