### ISSUE TITLE
Work around for access dependency

### ISSUE THREAD

**Issue by elauqsap** [linnovate/mean#704]
From what I have gathered from my searching is that system and access are the core packages that cannot be removed. However if I want to create a site without and user access is there anyway to get around this dependency? I am new to the MEAN stack and I am still trying to figure out the app structure but the bottled packages is an awesome idea!

**Comment by VikramTiwari** [comment]
@elauqsap Now you can do this by allowing anonymous used on the site. There are more details on the same coming up in the wiki soon.
