### ISSUE TITLE
'mean package --nocomments $name'

### ISSUE THREAD

**Issue by matchdav** [linnovate/mean#706]
Hey guys,

I really like the convenience of a CLI generator, but I hate having to delete all the comments in a package so I can insert my own jsdoc.  Currently running jsdoc on a package generates a bunch of globals, which is a bit of a pain to work around.

```mean package --nocomments UsefulThing```

would really really make me happy.

**Comment by VikramTiwari** [comment]
@matchdav Can you confirm this still exists as an issue. If so, please reopen.
