### ISSUE TITLE
app.config ??

### ISSUE THREAD

**Issue by wikett** [linnovate/mean#726]
Hi there,
I would like to put a http loader for my requests. I dont know if it's the best approch, buy I'm trying with this: angular-http-loader (https://github.com/wongatech/angular-http-loader).

I need to put some code in app.config like this:
```
<script>
   var app = angular
        .module('demo', ['ng.httpLoader'])

        .config([
          'httpMethodInterceptorProvider',
          function (httpMethodInterceptorProvider) {
            httpMethodInterceptorProvider.whitelistDomain('validate.jsontest.com');
            httpMethodInterceptorProvider.whitelistDomain('github.com');
          }
        ])
...
```

Using mean.io, where I must put the code for the app.config???

Thanks in advance.

**Comment by VikramTiwari** [comment]
@wikett Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
