### ISSUE TITLE
node postinstall sh: node: command not found

### ISSUE THREAD

**Issue by applefreak** [linnovate/mean#731]
I decided to check out MEAN, but failed to install it, the most suspicious line I caught was this

> mean-health@0.1.5 postinstall /usr/local/lib/node_modules/meanio/node_modules/mean-health
> node postinstall
> sh: node: command not found

After that, it was followed by bunch of errors. I've been struggling for a day now, any help would be appreciated!

**Comment by Wangct23** [comment]
I fixed my problem by following these:
1. export PATH=/usr/local/bin:$PATH has to be in .bash_profile
2. http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo
     a.  sudo chown -R $(whoami) ~/.npm
     b.  sudo chown -R $USER /usr/local/lib/node_modules

-------------
Thanks for @applefreak @pratik60

**Comment by applefreak** [comment]
@Wangct23 This question was asked by me LONG time ago, when I didn't understand Node.js fully. It is now suggested to installl Node.js using a version manager like [NVM](https://github.com/creationix/nvm), which handles all the $PATH and versioning stuff for you.
