### ISSUE TITLE
Default Setup with Oauth2 Bearer token

### ISSUE THREAD

**Issue by danicomas** [linnovate/mean#732]
Why @mean_io not use oauth2 bearer token by default? Is not it better to have the same auth on web and mobile?

Eg: http://localhost:3000/token and on headers add "bearer THISTOKEN"

**Comment by VikramTiwari** [comment]
@danicomas Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
