### ISSUE TITLE
Unit test and manual bootstrap

### ISSUE THREAD

**Issue by whisher** [linnovate/mean#743]
Hi, sorry to bother you but being quite new at unit test
I've not enough acknowledge to judge to myself.
What to think about this

>By including your manual bootstrap in the files that karma imports, your app is un-necessarily being bootstrapped within the karma test environment.

http://stackoverflow.com/questions/25363969/karma-angularjs-how-to-test-run-block-with-an-asynchronous-service

in the reply.

Btw did you find any issues to test with ui-router ?

**Comment by VikramTiwari** [comment]
Old issue and not relative anymore. If more questions please ask in gitter chat room (https://gitter.im/linnovate/mean).
