### ISSUE TITLE
Access to the http instance from a MEAN Package

### ISSUE THREAD

**Issue by karambar** [linnovate/mean#744]
Hi,

I am doing a web application and for this project I decided to create a package managing WebRTC and socket.io.
I already did this package by creating a new http instance especially for socket.io but this solution is not efficient.
Indeed, I want only one instance of http because I deploy this application on a PAAS and they have only one port opened for my application.
My issue is that I don't understand how to get the http instance established in the server.js file,  from a MEAN package .

Does anybody have an idea to resolve this issue ?

PS: my web application uses the release 0.3.0

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
