### ISSUE TITLE
Where can I config HTTPS?

### ISSUE THREAD

**Issue by eduardomagaldi** [linnovate/mean#745]
I wanna serve my app only in https, where do I put my certificates and set https only?

This doesn't work, does it?

https://github.com/zlokomatic/mean/blob/fd8a1de672503ce5e32bfa35aea7ff4fb3f7d8a7/config/env/all.js

Thanks.

**Comment by VikramTiwari** [comment]
This is now available as instructions in readme and is easily configurable.

**Comment by hak33m16** [comment]
@VikramTiwari This is no longer the case. Can anyone point me in the right direction on how I could configure HTTPS on the mean.io stack?
