### ISSUE TITLE
Heavy caching in Ubuntu on production

### ISSUE THREAD

**Issue by Prateek479** [linnovate/mean#748]
We're on the latest version of mean 0.5.17. Some of my co-worker are working on ubuntu 14.04 machine , and everything seems to be working fine on their machine. 

But we noticed a very unusual behaviour of mean sometimes  that it load the cache copy of files (html,js). Even though files are clearly changed, its not loading the changed file . 

Just today, it happened on the production too which is on ubuntu 12.04. We deployed a few code fixes, but they don't seem to be registering with mean. Had to restart mean on a different port, and then back on the same port to get it working. The aggregated js file continued to be of the old package, and was not updating according to the new code.

We tried cleaning cache by running 

bower cache clean 
npm cache clean 

nothing works out . I am not very sure of what is initiating the issue but this is very disturbing

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
