### ISSUE TITLE
running tests via strider causing issues with the mean package see log below

### ISSUE THREAD

**Issue by yourdeveloper** [linnovate/mean#757]
> mean@0.4.0 postinstall /home/ec2-user/.strider/data/weknodeit-server_goal-53fb21cfb68d761a05000022
> node node_modules/bower/bin/bower install

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/ec2-user/.strider/data/weknodeit-server_goal-53fb21cfb68d761a05000022/node_modules/bower/bin/bower'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! mean@0.4.0 postinstall: `node node_modules/bower/bin/bower install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the mean@0.4.0 postinstall script.
npm ERR! This is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/bower/bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.48-55.140.amzn1.x86_64
npm ERR! command "node" "/home/ec2-user/site/strider/node_modules/strider-node/node_modules/.bin/npm" "install" "--color=always"
npm ERR! cwd /home/ec2-user/.strider/data/weknodeit-server_goal-53fb21cfb68d761a05000022
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.3.26
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ec2-user/.strider/data/weknodeit-server_goal-53fb21cfb68d761a05000022/npm-debug.log
npm ERR! not ok code 0

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
