### ISSUE TITLE
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by davecyen** [linnovate/mean#759]
I tried running npm install in my new project directory but ran into this error.

npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-concurrent@0.5.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-clean@0.5.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-csslint@0.2.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-cssmin@0.9.0 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-contrib-jshint@0.10.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-uglify@0.4.0 wants grunt@^0.4.0
npm ERR! peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-nodemon@0.2.1 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-karma@0.8.2 wants grunt@0.4.x

**Comment by Maninderb87** [comment]
hi Zeikko,
            Ur work around helped me get rid of this error. 
Thank you

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
