### ISSUE TITLE
How to test with Supertest?

### ISSUE THREAD

**Issue by MichaelJCole** [linnovate/mean#769]
Hi, I got stuck trying to write some tests.

I wanted to use Supertest to test the end-points of the REST API.  Supertest is a http test helper.

The pattern for tests is below, but I wasn't able to get the 'app' from MEAN.IO.  What's the best way?  

```
var app = express();

app.get('/user', function(req, res){
  res.send(200, { name: 'tobi' });
});

request(app)
  .get('/user')
  .expect('Content-Type', /json/)
  .expect('Content-Length', '20')
  .expect(200)
  .end(function(err, res){
    if (err) throw err;
  });
```

You can see the project and tests here (it's a public repo):
https://bitbucket.org/MichaelCole/counting-calories/src/5bd945f7d9f19021c2ac83957f1fe4b7e76c29bb/packages/dashboard/server/tests/dashboard.js?at=master

I spent alot of time setting up a delay so the tests would start after the server was done loading.  I was getting a ECONNECTIONREFUSED error.

This project is done, but if you have any suggestions on how to improve the tests I'm interested.

**Comment by ADSKLowenthal** [comment]
@rjVapes This is probably handled by the server startup fix. https://github.com/linnovate/mean/pull/1340
