### ISSUE TITLE
Suggestion: Edit account page

### ISSUE THREAD

**Issue by skyserpent** [linnovate/mean#770]
There should be an edit account page for the boilerplate to make it a better boilerplate. Sort of like how Hackathon-Starter has it.

**Comment by scrock1987** [comment]
@liorkesos  I can provide with the PR for Edit user profile If you'd like.

**Comment by pratik60** [comment]
@scrock1987 / @brownman  - Feel free to complete/extend/overwrite this in altogetherness....

https://github.com/pratik60/mean-user-package

**Comment by liorkesos** [comment]
Sauarbh,
That would be awesome.
Lior

On Wed, Jan 28, 2015 at 1:09 PM, Saurabh Chawla <notifications@github.com>
wrote:

> @liorkesos <https://github.com/liorkesos> I can provide with the PR for
> Edit user profile If you'd like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/770#issuecomment-71816979>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by VikramTiwari** [comment]
PR needed. @pratik60 @scrock1987

**Comment by VikramTiwari** [comment]
I think this is a good feature. If anyone wants to work on this, I would be happy to merge.

**Comment by timelf123** [comment]
Before we had forked the user package, we created a userprofile package to store this info in our project. In hindsight, this is much better stored on the user model itself so we dont have to call `populate('userprofile')`
