### ISSUE TITLE
How to include a new module

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#771]
Hi,

I face diffculties to inclued a new module, this one:
https://github.com/m-e-conroy/angular-dialog-service

In init.js I add: 'dialogs.main'

but I get an "Uncaught object " error. I tried to add 'public/system/lib/angular-dialog-service/dialogs.js' in assets.json but it doesn't work.

What do I miss?

**Comment by VikramTiwari** [comment]
Fixed. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
