### ISSUE TITLE
Fresh mean install not rendering HTML in browser but HTML rendered properly via curl

### ISSUE THREAD

**Issue by lukehollis** [linnovate/mean#774]
On fresh mean install, after running grunt, visting localhost:3000 in a browser renders an admixture of garbled unicode specials and js;  but curling localhost:3000 yields correct html.  What possible causes might there be?

mean 0.5.19, ubuntu 14.04, node 0.11.5-pre or 0.10.31, mongo 2.4.11
browsers: chrome, firefox

examples of browser rendering mean app - http://pastebin.com/faPpqxmf
example of curl - http://pastebin.com/dS2bypML

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
