### ISSUE TITLE
etag problem for fresh mean project

### ISSUE THREAD

**Issue by hbzhang** [linnovate/mean#775]
Encounter the following error today. After install meanio, try to fresh init a project with 

mean init projectname

I then run grunt, then it shows the following error when try to access localhost:3000. I have tried many times on my two computers, all have same error. Node:0.11.3 NPM:1.4.9

Any thoughts? Thanks.

error:

node_modules/etag/index.js:55
    throw new TypeError('argument entity must be string or Buffer')
          ^
TypeError: argument entity must be string or Buffer

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
