### ISSUE TITLE
Extending User Schema from models of another package

### ISSUE THREAD

**Issue by bring2dip** [linnovate/mean#780]
I am able to extend the user schema while registering a package in app.js but i am having problem while extending it from models.js of my package.

**Comment by pbharatprdxn** [comment]
Please help a newbie like me in understanding this, how do I use the 'usermodel' variable which has the value database.connection.model('User'); as mentioned in this http://stackoverflow.com/questions/25781499/extending-the-users-package-of-mean-io in my js file in models directory?

I tried module.exports but it didn't yield the desired outcome. Please help.

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. @pbharatprdxn If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
