### ISSUE TITLE
Trying to add custom fields to user, but it won't save

### ISSUE THREAD

**Issue by TylerL-uxai** [linnovate/mean#785]
UPDATE: I think I fixed it by updating to the latest MEAN.

http://stackoverflow.com/questions/25835870/adding-additional-fields-to-the-user-model-in-the-mean-io-stack

Thanks for your help, guys!

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
