### ISSUE TITLE
All routes are randomly not available when restarting..

### ISSUE THREAD

**Issue by velniukas** [linnovate/mean#797]
Or are accessible via POSTMAN, but not via e.g. Jasmine-node / Frisby tests.

I have upgraded, restarted and get intermittent fixes, however this occurs very regularly. With no errors on the command line, or via lint.

I would appreciate any idea's on how to attack debugging this?

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
