### ISSUE TITLE
Themes broken. Works on localhost:3000, not on Heroku. Mean-Admin breaks it.

### ISSUE THREAD

**Issue by TylerL-uxai** [linnovate/mean#798]
Update: Replicated error result after fresh mean init, deploy to heroku using mongo lab. Everything worked on heroku until I did mean install mean-admin. For some reason on heroku it's not finding the Request module.

/app/packages/contrib/mean-admin/server/controllers/themes.js
 Error: Cannot find module 'request'

I see 'request' in the packages.json. It works on my local machine. But when I deploy to heroku, for some reason, it doesn't work and the app crashes.

Will be working on some UX improvements later, if I find the time. Thanks for your help, guys!

![screen shot 2014-09-18 at 11 50 49 pm](https://cloud.githubusercontent.com/assets/4743518/4330868/a7a4047c-3fb8-11e4-8e41-b2eab22b6d0e.png)

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
