### ISSUE TITLE
Multiple Single Page Apps in one large app..

### ISSUE THREAD

**Issue by SridharSubramaniam** [linnovate/mean#802]
Hi Guys,

I am trying to port Mean.io from old version(non-package) based to current package based version. I got a large application that has multiple single page apps(or modules).. Each page bootstraps a top levek angular module. 

In old world, all the views were in one folder and was easy to reuse the layout, header, footer etc.. With the new package structure, I see we can render html directly from package, but couldn't figure out how to extend the templates from system package etc..

Anyone tried this before ?

**Comment by VikramTiwari** [comment]
@SridharSubramaniam Did you attempt to do this? I couldn't understand what is your ask properly. If you could update this issue with some more details, I would be happy to look into it.
