### ISSUE TITLE
XSS in name field

### ISSUE THREAD

**Issue by eoftedal** [linnovate/mean#803]
When registering an account, the name field is subject to Cross Site Scripting. This is due to the JSON being written in an inline script-tag as a part of the HTML body on the index page.

````
<script type="text/javascript">
    window.user = {"name":"boring_guy","_id":"542105e757f4feb52ba79e39","username":"boring_guy","roles":["authenticated"]};
...
````

This JSON is not escaped for the JavaScript-within-HTML-context, which means you can end the script tag and open a new one. By creating an account with name (not username) of `</script><script>alert(1)//` you can execute the alert, and the page rendering is broken. You can even get the renderinge working again with a username of 

````
</script><script>alert(1);eval(String.fromCharCode(119,105,110,100,111,119,46,117,115,101,114,32,61,32,123,34,110,97,109,101,34,58,34,104,97,99,107,101,100,34,44,34,95,105,100,34,58,34,53,52,49,100,97,49,50,99,48,97,99,101,52,51,55,51,55,49,48,48,56,97,102,57,34,44,34,117,115,101,114,110,97,109,101,34,58,34,104,97,99,107,101,100,34,44,34,114,111,108,101,115,34,58,91,34,97,117,116,104,101,110,116,105,99,97,116,101,100,34,93,125))//
````

I would suggest you didn't add the username there at all. By using inline script-tags, it becomes hard to use the [Content Security Policy](http://www.html5rocks.com/en/tutorials/security/content-security-policy/) in a proper way. It would be better to cleany separate code from templates, and rather load the modules in a seperate JS-file, and the username through a JSON service.

**Comment by enkodellc** [comment]
@eoftedal  have you looked into helmet? 
https://github.com/helmetjs/helmet

**Comment by liorkesos** [comment]
This was addressed in - 
https://github.com/AlmogBaku/mean/commit/1d1d81bb70cbcda0ba7704f3f3a8523303ca4725
