### ISSUE TITLE
Lack of access control in JSON services

### ISSUE THREAD

**Issue by eoftedal** [linnovate/mean#804]
While the articles cannot be edited by other than the author in the UI, there is no server side restriction to do so. By manipulating the UI or invoking the JSON services directly, any user can edit any article.

Also fields that are perceived to be read only, are not. As an example it is not possible to change the creation date of an article through the UI, but you can change it by manipulating the UI or by directly invoking the JSON services by adding the `created`-field when editing a post. This is similar to http://www.zdnet.com/blog/security/how-github-handled-getting-hacked/10473

**Comment by gsbernstein** [comment]
All you have to do is add "/edit" after the article URL and you can edit anything.  Not sure why the auth check is broken.

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
