### ISSUE TITLE
Use zxvbn for password validation

### ISSUE THREAD

**Issue by eoftedal** [linnovate/mean#805]
Currently the password policy allows any password between 8-20 characters long. For instance "AAAAAAAA" og "password" are valid passwords.

It would be better to use something like Dropbox' zxcvbn to validate passwords.

Also the 20 character max length is weird. Why so low? After hashing the passwords are all the same length, so why not allow a user to have a longer password if he/she wants to. I would rather have it set to 256 or something if there is a worry that pbkdf2 will eat too much resources for longer passwords.

**Comment by VikramTiwari** [comment]
I like the idea of using zxcvbn. Will look into it.

Related post: https://ryanwinchester.ca/posts/stop-forcing-your-arbitrary-password-rules-on-me

**Comment by timelf123** [comment]
Love this idea. One thing to consider is that we will want to conditionally load this and not bundle it -- minified and gzipped, zxcvbn is still several hundred kilobytes. 

see https://github.com/dropbox/zxcvbn#perf
