### ISSUE TITLE
Linkedin login

### ISSUE THREAD

**Issue by elvisvoer** [linnovate/mean#813]
Hi eveyone,

I am new to MEAN.io and I am not sure this sould be flagged as an issus but here we are.

I am trying to use Linkedin login with MEAN.io. The first login works as expected but if I clear the cookies and try to login again I get the following error:

"ValidationError: E-mail address is already in-use" which comes from the users model. 

Is this a bug or I need to make extra configurations so that if the provider is Linkedin there is no check for validateUniqueEmail?

Thanks,
Elvis

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
