### ISSUE TITLE
Bug at mean startup on Azure Websites

### ISSUE THREAD

**Issue by SebastienTraxair** [linnovate/mean#814]
I have put a website in production on Azure Websites. I followed the procedure of the official [Microsoft Node.js doc](http://azure.microsoft.com/fr-fr/documentation/articles/web-sites-nodejs-develop-deploy-mac/). It did not work right away, so I followed the advice from #697 where you have to run grunt locally and version dist.min.js.

Then I tried 2 web.config files, one is the default one from the Azure procedure, the second one I found on your Wiki at the [hosting page](https://github.com/linnovate/mean/wiki/Hosting-MEAN). You can find them on my [gist](https://gist.github.com/OlivierTraxair/0e41173af28d0d108f9b):
* the file named "default_azure_nodejs" was giving me two errors when accessing the web site. The first error is the file named "iisnode_error"; the second error happens at the first refresh (it reads "Cannot GET /"), and when I refresh another time the website is functional. Under the hood, the logfile tells me that during the first error message there is a "Mean app started" message.
* the file named "mean_wiki" yields the same errors, but instead of "Cannot GET /" it shows "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

I figure there is something wrong somewhere in the wiki's instructions or in configuration...

**Comment by VikramTiwari** [comment]
I guess this is fixed. If not so, please reopen.
