### ISSUE TITLE
Integrate https://github.com/sahat/satellizer for Token-based AngularJS Authentication

### ISSUE THREAD

**Issue by spiddy** [linnovate/mean#816]
Hi,

Satellizer is getting lot of traction, and seems to be the best tool for integrating social logins.

I''d love to see mean.io integrate into their boilerplate to use directly satellizer for the task. It would probably reduce the core code and complexity on mean.io project.

**Comment by countrdd** [comment]
+1

**Comment by lirantal** [comment]
that will be coming up on MEAN.io 0.5

**Comment by liorkesos** [comment]
Releasef and merges to master of latests mean.io...

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
