### ISSUE TITLE
Bootstrap folding navbar

### ISSUE THREAD

**Issue by hayatnoor** [linnovate/mean#818]
In a traditional bootstrap navbar, the menu will adapt to the browser width and provide the hamburger menu icon for smaller windows. The menu will also expand and collapse when clicked on. It would be nice to see this integrated in mean.io by default rather than changing the template file and sourcing the bootstrap.js file.

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
