### ISSUE TITLE
webpage not available at localhost:3000

### ISSUE THREAD

**Issue by tianzhu** [linnovate/mean#830]
I initiated a new app using 'mean init' and then did 'npm install' and 'grunt'. Output seems to be OK:

Running "clean:0" (clean) task
Running "jshint:all" (jshint) task
>> 47 files lint free.
Running "csslint:src" (csslint) task
>> 5 files lint free.
Running "concurrent:tasks" (concurrent) task
Running "watch" task
Waiting...
Running "nodemon:dev" (nodemon) task
[nodemon] v1.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
Mean app started on port 3000 (development)

But when I launched it in browser (http://localhost:3000), it complaint 'The webpage is not available'.

Did I do anything wrong? Or I missed some steps? Thank you

Following are the versions I'm using:

node: 0.10.32
npm: 1.4.28
meanio: 0.5.40

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
