### ISSUE TITLE
Make /register API friendly. Return 200 on register ok. Let Angular do the redirect.

### ISSUE THREAD

**Issue by MichaelJCole** [linnovate/mean#834]
Hey, coming back to this after some time. BTW, the new theme looks killer!

I've been working on an off-line angular app. I'd like to use MEAN.IO as the backend.

While playing with the /register route, I found it wan't returning JSON on success. I updated it to my needs, and tested it from the web. It seems to work and all the tests pass.

I think returning the response, or res.status(200) won't actually send the response. I think we need to call .send().

There's an opportunity to call .send(user) instead, but it includes some internal data which may not be appropriate.

Anyways, hope this helps! Thanks!

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
