### ISSUE TITLE
$scope.global.user.email undefined

### ISSUE THREAD

**Issue by TylerL-uxai** [linnovate/mean#841]
I'm trying to update the logged in user.

```
$scope.findOne = function() {
  Users.get({
    userId: $scope.global.user._id
   }, function(person) {
        console.log(person); // console says: GET http://localhost:3000/admin/users/54244aa1be4b850800504261 404 (Not Found) 
   });
};
```
Why isn't Users.get finding someone at admin/users/_id?

Also, unclear how global.user.objects are working.
```
console.log($scope.global.user); // gives us...
```
{
name: "Bugs Bunny", 
_id: "54160d83b3368608354c95e7", 
username: "Bugs", 
roles: "authenticated"
}

But where is the email? specifically $scope.global.user.email?

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
