### ISSUE TITLE
Failed Install Windows

### ISSUE THREAD

**Issue by joevolcano** [linnovate/mean#848]
Windows 8.1 64bit
Installed latest Node x64  http://nodejs.org/
Installed mongodb

node v0.10.32
npm  v1.4.28

Ran instructions @http://mean.io/#!/docs
"npm install -g meanio@latest"
seem to put the node_modules in my roaming profile...
Ran
"mean init myApp "
"'mean' is not recognized as an internal or external command,
operable program or batch file."

Ran instructions on home page @ http://mean.io/#!/
"npm install -g mean-cli "
fail requires npm 2.1.x 

tried to update npm 
"npm install npm -g"
returns
"npm@2.1.5"

I cant seem to update npm to the version that mean-cli wants
and I cannot seem to run any of the mean cli commands. I think its because of where npm and the nodejs installer are putting the packages and node_modules and where I run the commands from in the command line window (that has admin privaleges)

I also tried copying the node_modules from the npm root to the "C:\Program Files\nodejs\node_modules\npm\node_modules" and that did not work

I also tried running these commands from within these directories...and that did not work

can someone please help?

**Comment by juanxintel** [comment]
I can not install Windows Mean

Run the main init <my-app> I have the following error:

Can not find the path

When I run the install npm

Bower fails, do not install dependencies me

Help!
