### ISSUE TITLE
config/env port configuration is wrong in startup project

### ISSUE THREAD

**Issue by AnotherCodeArtist** [linnovate/mean#849]
While the sever.js script is checking for config.http.port, the various config script still contain port. This should, however, be changed to something like http: {port: 3001} (in the case of test.js).
Otherwise the standard port 3000 is used.

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
