### ISSUE TITLE
need to use grunt --force to start server

### ISSUE THREAD

**Issue by earthican** [linnovate/mean#850]
I have to use `grunt --force` (on a fresh install) to start the server and run my mean app:

```
$ grunt
Running "clean:0" (clean) task

Running "jshint:all" (jshint) task

   packages/system/app.js
     10 |var System = new Module('system');
             ^ Redefinition of 'System'.

>> 1 error in 47 files
Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.
```

I know the README says I should use `grunt -f` to force grunt, but is there a reason why I would have to instead of just using `grunt`?

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
