### ISSUE TITLE
Failed to load resource http://localhost:35729/livereload.js

### ISSUE THREAD

**Issue by thanhthang20** [linnovate/mean#86]
Please help!

I have reinstalled livereload.js with "npm install livereload" command but it not work

![image](https://f.cloud.github.com/assets/5382700/1184891/980371c4-2263-11e3-9730-16b9aa48da34.png)

**Comment by obliviga** [comment]
I have the same problem, and always started with gulp.

**Comment by leolux** [comment]
I have the same problem, and always started with grunt.
