### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by elvisvoer** [linnovate/mean#863]
Hi,

I have created a custom package which has some dependencies that I manually added to the bower.json. I was expecting that if I run bower install in the root folder the dependencies to be installed in bower_components. Is this an error or I missundertood the way this works?

Thanks,
Elvis

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
