### ISSUE TITLE
Multi-tenant app where each client has a separate db

### ISSUE THREAD

**Issue by pratik60** [linnovate/mean#867]
We are setting up client sites with each having a subdomain, and we would like the connection to be maintained at a separate db level. 

Any idea on how this might be possible in mean?

**Comment by anoopsinghbayes** [comment]
I see this in the release notes here[http://mean.io/#!/release-notes] and here[https://github.com/linnovate/mean/wiki/Database-core-module] but no example in the documentation to follow

**Comment by anoopsinghbayes** [comment]
any updates on this

**Comment by anoopsinghbayes** [comment]
any updates on this
