### ISSUE TITLE
title in head (<title>) appears twice

### ISSUE THREAD

**Issue by zohar** [linnovate/mean#872]
/packages/system/server/views/includes/head.html has 
```html
<title>{{appName}} - {{title}}</title>
``` 
but appName and title are always identical.

![mean - fullstack js - development - mean - fullstack js - development](https://cloud.githubusercontent.com/assets/109613/4952069/51883fa8-666f-11e4-9480-e0d8f04e4608.jpg)

**Comment by rick4470** [comment]
So is this part of node? or is part of mean.io?

**Comment by VikramTiwari** [comment]
Similar issue with answer: https://github.com/linnovate/mean/issues/1423
