### ISSUE TITLE
Documentation not clear about DI on packages

### ISSUE THREAD

**Issue by redirect11** [linnovate/mean#877]
Hi all, i think the section in main documentation on the main site (http://learn.mean.io/#mean-io-packages-dependency-injection) could be more clear. I can't understand that this call

``` javascript
 MyPackage.someExampleFunction('some paramater');
```

it's a function call on the Token package. 

Please provide a more clear doc about DI and how to access other package functions.

Thanks

**Comment by VikramTiwari** [comment]
@linnovate/mean-contributors We need a major rehaul of documentation. Anyone up for it?

**Comment by timelf123** [comment]
Where can I commit changes to learn.mean.io?
