### ISSUE TITLE
Can someone explain where is the global factory coming from? 

### ISSUE THREAD

**Issue by supritashankar** [linnovate/mean#880]
I cannot follow how is "Global" injected here
https://github.com/linnovate/mean/blob/master/packages/articles/public/controllers/articles.js#L3

Also if you notice, as soon as we login and we hit the /articles page, "Global is empty" - undefined.
Once refreshed, it gets updated. 

Isn't this wrong? thanks!

Edit: It is the same as this https://github.com/linnovate/mean/issues/454
Can I understand where is global coming from to understand how to fix it?
@enkodellc @fyockm

**Comment by VikramTiwari** [comment]
Please ask questions in gitter chatroom (https://gitter.im/linnovate/mean)
