### ISSUE TITLE
command: npm install

### ISSUE THREAD

**Issue by brownman** [linnovate/mean#887]
global packages:
- should clone remote repo's only if not already installed on the machine.

git clone:
- should use: --depth=1 for shallow-cloning

**Comment by VikramTiwari** [comment]
I would like to know how other popular packages do this? As I remember this was a problem with NPM cloning dependency trees for each dependency in the project. I think they have resolved this with current versions and are improving over it.

Also global copies of dependencies make sense only if you are working on once single package. Maybe this would be helpful for deployments. But even in those cases, most people tend to deploy multiple different types of apps on the same server and this will cause major breaking deps issues.

My vote is against it. Would love to hear thoughts from others @linnovate/mean-contributors
