### ISSUE TITLE
IDEA:  + 'getting started' tutorial

### ISSUE THREAD

**Issue by brownman** [linnovate/mean#895]
the tutorial can be based on:
https://github.com/vkarpov15/mean-stack-todo

and have its final product here:
http://todomvc.com/

it can be documented as a node.js lesson here:
http://nodeschool.io

**Comment by VikramTiwari** [comment]
Awesome idea! Though as much I would like to build a MEAN stack tutorial, there are some amazing ones out there already. And as much as I know, they tend to get old pretty quick in NodeJS world. We are barely able to upkeep our documentation.

Regardless, this is an awesome suggestion. Anyone who would like to start working this? I can help with reviewing content.
