### ISSUE TITLE
Error: ENOENT, open '.../bower_components/bootstrap/dist/css/bootstrap.css'

### ISSUE THREAD

**Issue by ryandesign** [linnovate/mean#899]
After starting my first ever "empty" meanio project and accessing http://localhost:3000 in a browser, it exits with this message:

```
debugger listening on port 5858
Mean app started on port 3000 (development)
GET / 200 51.172 ms - -

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '/path/to/myproject/bower_components/bootstrap/dist/css/bootstrap.css'
[nodemon] app crashed - waiting for file changes before starting...
```

The directory /path/to/myproject/bower_components does not exist. What was supposed to have populated it?

The first time bower is mentioned on http://learn.mean.io/ is when it says I can update bower by running `npm update -g bower`. I can't update what was never installed. Was I supposed to `npm install -g bower` at some point? Was I supposed to run some `bower` command at some point?

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
