### ISSUE TITLE
Rewriting default view erratic behaviour. 

### ISSUE THREAD

**Issue by MilosStanic** [linnovate/mean#903]
As I discussed today with @rmisiak on Facebook, the overriding feature for default view behaves completely erratic for me. 
Sometimes it works, sometimes it doesn't. Even if I don't change anything.
 
Sometimes it simply doesn't work with no error message, it just displays default mean.io page, instead of my overridden view. 

Sometimes it complains that it cant load module theme, which I thought I fixed by injecting 'mean.system' into the theme and users packages. And then the whole app crashes. 

I then refresh a few times, or restart, and it works again. Or it doesn't.
 
I added a line console.log('overriding view') in line 15 of the /packages/system/public/routes/system.js.
So, when it works, the console always displays this message. When it doesn't work, the message doesn't get displayed, and a default view is loaded instead of the overridden view. 

I'm guessing this is some sort of problem with asynchronous calls, or promises, or somethng. 
I just can't find what it is.

**Comment by VikramTiwari** [comment]
Fixed.
