### ISSUE TITLE
Can we clean up the articles controller and add a findOne to the users controller?

### ISSUE THREAD

**Issue by TylerL-uxai** [linnovate/mean#908]
The articles server controller has exports.show that's just a simple res.json(req.article);

Can't we put   res.json(req.article); in the exec of exports.article and make the whole thing simpler?

I also don't know what the  app.param('articleId', articles.article); is in the article routes. Can we modify the user routes to include an exports.findUser to get just one user and add the needed route? Even if getting one user isn't used on the front end, this would help clarify things for our developers who need this functionality.

**Comment by ADSKLowenthal** [comment]
@rjVapes Reviewing some old issues, this one can probably be closed.

For articles it's not always the case that finding an article by id would mean you want to send the data back. It may also need to be updated after it's been found.  That's what `app.param('articleId', articles.article)` is for, getting the article. But it doesn't decide what to do with it.

The single user may be useful, but hasn't been necessary to the User module. It could be added in a separate module that depends on User. If it's still something that's being request, probably best to open a separate ticket just for it.
