### ISSUE TITLE
Mongoose password with special character

### ISSUE THREAD

**Issue by Prateek479** [linnovate/mean#913]
Hi 

I am using MongoLab for my mongoDB  , i had set the db variable in development.js as

module.exports = {
  db: 'mongodb://user:pass@ds051720.mongolab.com:51720/testdb',

My password consists of special character (%,@,^) and numbers. I know in case of normal mongoose.connect we can pass parameter as 

mongoose.connect(host, db, port, {user: 'username', pass: 'p@ssword'}, callback);

How can we pass this in mean.io ? My console throws the error as -
Error: failed to connect to []|9:27017]
**Could not connect to MongoDB. Please ensure mongod is running and restart MEAN app.**

**Comment by VikramTiwari** [comment]
Not an issue.

**Comment by fullflash** [comment]
mongoose.connect("mongodb://username:p%40ssword@localhost/dbname", {uri_decode_auth: true}, function(err, db) { });

**Comment by aeroxy** [comment]
%40 doesn't work in my case.

**Comment by davidshare** [comment]
This does not work for me when I am using environment variables from my .env file.
