### ISSUE TITLE
ui-router resolve not working as expected in mean.io

### ISSUE THREAD

**Issue by dmora** [linnovate/mean#915]
We have been noticing that the UI-router resolve functionality is not working as expected, see the following code based on the users package as a example:

```javascript

var checkLoggedOut = function($q, $timeout, $http, $location) {
      // Initialize a new promise
      var deferred = $q.defer();

      // Make an AJAX call to check if the user is logged in
      $http.get('/loggedin').success(function(user) {
        // Authenticated
        if (user !== '0') {
          $timeout(deferred.reject);
          $location.url('/login');
        }

        // Not Authenticated
        else $timeout(deferred.resolve);
      });

      return deferred.promise;
    };

.state('auth.login', {
        url: '/login',
        templateUrl: 'users/views/login.html',
        controller: 'accountCtrl',
        resolve: {
          loggedin: checkLoggedOut
        }
      })
```
loggedin is never injected to the controller, we have noticed that:

1.) if you have the resolve to return a promise, the controller is never instantiated.
2.) if you return a function on the resolve, you need to specific the controller function directly in the state for it to actually work (instead of specifying the controller name)

The only way it works right now is doing something similar to this:

https://gist.github.com/anonymous/920a22f8af9c9038160e

Notice that we have tried the examples shown in the ui-router documentation as well.

**Comment by VikramTiwari** [comment]
@dmora If this is still an issue, please re-open.
