### ISSUE TITLE
IDEA: free the package out !

### ISSUE THREAD

**Issue by brownman** [linnovate/mean#925]
A mean package should be testable 

how?  
- packages should be independant of the mean stack.

why?
the concept of mean still remains: 
- mongo/express/node/mongodb

what we want?
- just run grunt - and start the testing

**Comment by VikramTiwari** [comment]
haha Run gulp now. 👍 

Significant steps have been taken over multiple iterations and I think we are at the point where this is very much true.

Reopen if you have suggestions regarding how we can do this better.
