### ISSUE TITLE
Bower components aren't automatically added to assets

### ISSUE THREAD

**Issue by TylerL-uxai** [linnovate/mean#928]
You can add javascript and it's automatically added to the aggregate.js (I think), but if you add something to the bower.json or do a bower install, you have to find config/assets.json and add the javascript. Is there any way we can automatically add once installed?

**Comment by williscool** [comment]
This could be mentioned in the docs.

Along with the needing your angular app to require `mean.system` :/

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
