### ISSUE TITLE
Live reload not working.  Change index.html and get Module 'mean-factory-interceptor' is not available! 

### ISSUE THREAD

**Issue by MichaelJCole** [linnovate/mean#929]
Hi, livereload is coming back with a WSOD.  I'm getting this error in the console:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:modulerr] Failed to instantiate module mean.system due to:
Error: [$injector:modulerr] Failed to instantiate module mean-factory-interceptor due to:
Error: [$injector:nomod] Module 'mean-factory-interceptor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```
The file `/packages/system/public/services/interceptor.js` is not in the sources after reload.

How to reproduce:
  - Clone MEAN.IO
  - Change repo/packages/system/public/views/index.html
  - Save change
  - livereload comes back with WSOD

It fails 90% of the time for me

Workaround:
  - Kill and restart server
  - Reload in browser

Suggestions?

Thanks!

**Comment by xiaoyang2022** [comment]
issue is having!

**Comment by lvarayut** [comment]
Any progress on this issue?

**Comment by baskint** [comment]
having the same issue here. going to try another system later. looks like intermittent and seems to be happening cloned repositories more than creating a new 'mean init <appname>' instances. any other ideas?

**Comment by VikramTiwari** [comment]
This is fixed in latest builds. If anyone is still getting this an an issue, please reopen.
