### ISSUE TITLE
Trying to delete username from the model

### ISSUE THREAD

**Issue by TylerL-uxai** [linnovate/mean#931]
I'm not understanding this code:

```

        user.save(function (err) {
            if (err) {
                switch (err.code) {
                case 11000:
                case 11001:
                    res.status(400).send([{
                        msg: 'Username already taken',
                        param: 'username'
          }]);
                    break;
                default:
                    var modelErrors = [];

                    if (err.errors) {

                        for (var x in err.errors) {
                            modelErrors.push({
                                param: x,
                                msg: err.errors[x].message,
                                value: err.errors[x].value
                            });
                        }

                        res.status(400).send(modelErrors);
                    }
                }

                return res.status(400);
            }
```

Where do I find the code that defines 1100 and 1101 error codes? Is it in another javascript file? I just want to remove username from the model, but it's not letting me.

UX note: I think it's great you guys added the functionality for a username here, but UX consultants recommend username be the same as the person's email. So when they log in, they just have to remember their email instead of their username. You could simplify your form by not requiring a username, even though I know you spent a lot of time and effort putting it there in the first place. Just a tip :)

I actually like that there's extra examples in there to play around with. I just wish it was more apparent what's happening. There's some extra code happening here that's not in the users/server/controller or users/server/model

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
