### ISSUE TITLE
Assetmanager in Mean.io not working in production mode

### ISSUE THREAD

**Issue by wikett** [linnovate/mean#933]
Hello,

My problem is when I grunt in production mode, always I have this problem

```
GET http://localhost:3000/bower_components/build/css/dist.min.css 404 (Not Found) 
```

My assets.json is:
```
{
  "core": {
    "css": {
      "bower_components/build/css/dist.min.css": []
    },
    "js": {
      "bower_components/build/js/dist.min.js": [

        "bower_components/angular/angular.js",
        "bower_components/angular-mocks/angular-mocks.js",
        "bower_components/angular-cookies/angular-cookies.js",
        "bower_components/angular-resource/angular-resource.js",
        "bower_components/angular-ui-router/release/angular-ui-router.js",
        "bower_components/angular-bootstrap/ui-bootstrap.js",
        "bower_components/angular-bootstrap/ui-bootstrap-tpls.js"
      ]
    }
  }
}
```
I have my website uploaded in heroku: http://damp-wave-1192.herokuapp.com/

Any idea? It's very frustating :(

**Comment by sandyrayblr** [comment]
I am facing a similar problem though it applies to both cssmin and uglify. I have install load-grunt-tasks. When I run grunt default I get the error Task "cssmin"  not found. This happened after I installed grunt-contrib-clean to get rid to "clear" Task not found. I do have a css file as well added to assets.json. Here is how it looks . Also I am running the openshift edition and version details are 
mean@0.4.0 /home/.......
└── meanio@0.5.17 

Contents of my assets.json file
{
  "core": {
    "css": {
      "bower_components/build/css/dist.min.css": [
        "bower_components/angular-material/angular-material.css"
      ]
    },
    "js": {
      "bower_components/build/js/dist.min.js": [
        "bower_components/jquery/dist/jquery.min.js",
        "bower_components/angular/angular.js",
        "bower_components/angular-mocks/angular-mocks.js",
        "bower_components/angular-cookies/angular-cookies.js",
        "bower_components/angular-resource/angular-resource.js",
        "bower_components/angular-ui-router/release/angular-ui-router.js",
        "bower_components/angular-aria/angular-aria.js",
        "bower_components/angular-animate/angular-animate.js",
        "bower_components/angular-material/angular-material.js"
      ]
    }
  }
}

**Comment by gowthaman-i2i** [comment]
same issue for me also

**Comment by VikramTiwari** [comment]
Is this still an issue for anyone? Please reopen if so.

**Comment by saeed68gm** [comment]
I still see injection issue on after I deploy on heroku.
Is there a way to get around this? What's the best way to debug the issue?
Here is the output of mean status:

    MEAN VERSION: 0.5.5

    DB connection successful!

    checking meanio and global mean-cli versions
    mean-cli at latest version: 0.11.1
    meanio at latest version: 0.8.84

**Comment by ADSKLowenthal** [comment]
@saeed68gm Best to open another issue, or find a related issue that's still open. This one is centered around GRUNT which MEAN 0.5.5 does not use.  It uses Gulp and if there is perhaps and issue with that, it's best to address it as a new issue.
