### ISSUE TITLE
Sometimes works sometimes doesn't work

### ISSUE THREAD

**Issue by wikett** [linnovate/mean#936]
I have my website here: https://damp-wave-1192.herokuapp.com/
I right now doesn't work. 

I don't understand the problem, because in two three hours works perfectly, but it's not professional...(in localhost always works)

Anyone has experience with this type of error? (Is deployed in heroku)

```
GET https://damp-wave-1192.herokuapp.com/bower_components/build/css/dist.min.css 404 (Not Found) damp-wave-1192.herokuapp.com/:20
Uncaught object dist.min.js:3
```

Thanks in advance.

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
