### ISSUE TITLE
Aggregation system - too much magic

### ISSUE THREAD

**Issue by MichaelJCole** [linnovate/mean#941]
Hi, this is a meta bug for the aggregation system.

It's caused me a bunch of headaches.  It's a really cool idea, but it's got some bugs and needs some documentation.  I'd love to see something like this - it's just killing my productivity.

If it was better documented, I'd write some PR's for it.

See also:

#940

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
