### ISSUE TITLE
Theme (specifically navbar) color modification

### ISSUE THREAD

**Issue by chrislarsenqlik** [linnovate/mean#944]
I posted this on your FB page but am not confident it will get seen nor answered.. so trying here as well. Please tell me the right place to ask stupid questions.

Are there are articles out there talking about how to change theme colors? I have changed the navbar by setting about 5 different style attributes in bootstrap.css, have also done it in common.css, and head.html, some with varying degrees of success, but no matter what i do I cannot change the color of the top right account drop-down (when opened). I'm thinking there has got to be a straight forward way that i'm not seeing, and can't find anything on the internet about it. Thanks in advance.

**Comment by VikramTiwari** [comment]
Fixed.
