### ISSUE TITLE
[RFC] Structure Refactoring

### ISSUE THREAD

**Issue by AlmogBaku** [linnovate/mean#951]
As discussed on gitter..
I suggest to embrace the way symfony/symfony-standard#584 managed their files and structure.

### Units
We have 3 units:

1. **components** - which are strong part of the project - such as express, mongo, authentication, angular, access, system
1. **bundles** - *(a.k.a. mean-packages)* which are good way to implement the components- such as users, admin, articles
1. **distribution***(/vanilla)* - a configuration that combined them all

The main distro- `mean.io`, will include a starter version of the project. The distro is a set of `mean.json` the pre-configured.

### Filesystem structure

```php
├─ vendor/
│   ├─ mean [vendor]
│   │   ├─ access/
│   │   └─ system/
│   ├─ AlmogBaku/
│   │   └─ mean-compass/
│   │      ├─ package.json [npm]
│   │      └─ meanGruntfile.jsom [grunt injection]
│   ├─ linnovate
│   │   ├─ articles/ [bundle]
│   │   └─ users/
│   ├─ node_modules [npms]
│   └─ bower_components [bowers]
├─ src/
│   └─ ACME [vendor]
│        ├─ pages [bundle]
│        └─ books
│           ├─ server/
│           ├─ public/
│           ├─ mean.json
│           ├─ package.json
│           └─ bower.json
├─ config/
│   ├─ Gruntfile.js
│   ├─ bower.json [bower broker]
│   └─ env/
│        ├─ prod.js
│        └─ all.js
├─ package.json
└─ mean.json
```

### Dependencies:
Dependencies will loaded by 4 main components:

1. **mean.json** - manage the mean bundles dependencies map
1. **bower broker** - manage the whole project bowers into `vendor/bower_components`
1. **npm** - will loaded per bundle
1. **Injectable grunt/gulp** - allow injection into the grunt/gulp process (**Grunt implemented on master!** as _mean-grunt_)

### Aggregation
Mean.io will aggregrate its dependencies by 3 mechnisms

1. **npm**
1.  **grunt/gulp**
    1. bower - will load automatically all the components on the `vendor/bower_components`
        1. mean.json can set rules for the grunt/gulp (for instance locations of the files if not set on the bower config properly)
    1. css/compass/less - will aggregate automatically
    1. views- aggregate views into js (performance)
1. **system** - will load the whole project and bundles

### Mean-cli

1. `mean start $env` - instead of `bower` (looks much stylish, will run the grunt from the config)
1. `mean install $bundle`
1. `mean uninstall $bundle`

### Noteable bundles(a.k.a. packages)
1. **mean-admin** - a start point for creating "backoffice" interface. (should be generic as possible, and not as dependency of bootstrap)
1. **starter** - a bundle which contains a starting point: homepage, default design, bootstrap
1. ~~theme~~ - theme will be removed
1. **mean-compass** - inject compass tasks to grunt/gulp (**implemented with grunt**)
1. **articles** - as a example basic package.

### Noteable assets to consider
1. **restangular** as part of the core #562

**Comment by VikramTiwari** [comment]
Awesome work on this thread. There's been amazing work towards this and most of the packages are modular now. We can always do better, though.

I will be closing this since it's fully lived its usage. Let's open a new issue for further discussions.
