### ISSUE TITLE
npm INSTALL WARN optional dep failed, continuing fsevents@0.3.1

### ISSUE THREAD

**Issue by tqangxl** [linnovate/mean#960]
run  npm install

> bson@0.2.15 install E:\web1\mean-master\node_modules\mongoose\node_modules\mon
godb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

E:\web1\mean-master\node_modules\mongoose\node_modules\mongodb\node_modules\bson
>node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild
<B>npm WARN optional dep failed, continuing fsevents@0.3.1<B>
-

> phantomjs@1.9.12 install E:\web1\mean-master\node_modules\karma-phantomjs-laun
cher\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\JAMEST~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
.zip
Receiving...
  [===================---------------------] 46% 0.0s  [===================-----
  [====================--------------------] 50% 0.0s  [====================----
  [=====================-------------------] 52% 0.0s

**Comment by 823844596** [comment]
DId you solve the question?  can you give me some help to solve it? thanks ~
