### ISSUE TITLE
Documentation on Angular Directive library added to created package.

### ISSUE THREAD

**Issue by hydrotik** [linnovate/mean#964]
I've created a package in the custom folder and I would like to add an Angular dependency for syntax highlighting. https://github.com/pc035860/angular-highlightjs

It's not completely obvious how to do so and I think this is a basic need for getting started with the stack. assets.json and maybe MyPackage.aggregateAsset and MyPackage.angularDependencies(['hljs']) seem to be needed. I'm also guessing it needs to be added to bower.json but is that in the root? or would it go in the package folder? If that's the case do you just do a bower install in the package folder?

Also if there is a good place to find this type of information, I would love to know:) Cheers!

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
