### ISSUE TITLE
suggestion: +annotated source

### ISSUE THREAD

**Issue by brownman** [linnovate/mean#969]
just like:
- http://www.explainjs.com/

**Comment by VikramTiwari** [comment]
@brownman you keep coming up with all the awesome ideas. I think this would be awesome idea. I know of some projects which have annotated source and use scripts to generate the final docs. 

Example: http://googlecloudplatform.github.io/google-cloud-node/#/

I will try to give it a go.

**Comment by timelf123** [comment]
JSdoc for now / ESdoc for mean 2.x with ES6 support
