### ISSUE TITLE
mean update fails

### ISSUE THREAD

**Issue by randwa1k** [linnovate/mean#970]
I stopped working on my project for a few months and I am having trouble updating to the latest version.  Currently I'm at 

    $ mean status

    MEAN Status
    -----------

    MEAN VERSION: 0.4.0

    DB connection successful!

    MongoDB URI: mongodb://localhost/mean-dev

    checking meanio and global mean-cli versions
    meanio at latest version: 0.5.16
    mean-cli at latest version: 0.5.39

I would like to update meanio, but it failed:

     npm update -g meanio

    > meanio@0.6.16 preinstall /home/arrow/local/lib/node_modules/meanio
    > node ./scripts/preinstall

    Please install 'mean-cli' globally instead of 'meanio' as:

      $ npm install -g mean-cli

    npm ERR! meanio@0.6.16 preinstall: `node ./scripts/preinstall`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the meanio@0.6.16 preinstall script.
    npm ERR! This is most likely a problem with the meanio package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ./scripts/preinstall
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls meanio
    npm ERR! There is likely additional logging output above.

    npm ERR! System Linux 2.6.35.4-rscloud
    npm ERR! command "node" "/home/arrow/local/bin/npm" "update" "-g" "meanio"
    npm ERR! cwd /home/arrow/app201408app
    npm ERR! node -v v0.10.30
    npm ERR! npm -v 1.4.23
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/arrow/app201408app/npm-debug.log
    npm ERR! not ok code 0

This is my /home/arrow/app201408app/npm-debug.log

    0 info it worked if it ends with ok
    1 verbose cli [ 'node', '/home/arrow/local/bin/npm', 'update', '-g', 'meanio' ]
    2 info using npm@1.4.23
    3 info using node@v0.10.30
    4 verbose request where is /meanio
    5 verbose request registry https://registry.npmjs.org/
    6 verbose request id be12ac3ffea43138
    7 verbose url raw /meanio
    8 verbose url resolving [ 'https://registry.npmjs.org/', './meanio' ]
    9 verbose url resolved https://registry.npmjs.org/meanio
    10 verbose request where is https://registry.npmjs.org/meanio
    11 info trying registry request attempt 1 at 06:04:12
    12 verbose etag "7GBHDMOGKVSCJRHLL2VZP6TMU"
    13 http GET https://registry.npmjs.org/meanio
    14 http 304 https://registry.npmjs.org/meanio
    15 silly registry.get cb [ 304,
    15 silly registry.get   { date: 'Wed, 17 Dec 2014 05:42:03 GMT',
    15 silly registry.get     server: 'Apache',
    15 silly registry.get     via: '1.1 varnish',
    15 silly registry.get     'last-modified': 'Wed, 17 Dec 2014 05:42:03 GMT',
    15 silly registry.get     'cache-control': 'max-age=60',
    15 silly registry.get     etag: '"7GBHDMOGKVSCJRHLL2VZP6TMU"',
    15 silly registry.get     age: '0',
    15 silly registry.get     'x-served-by': 'cache-jfk1030-JFK',
    15 silly registry.get     'x-cache': 'HIT',
    15 silly registry.get     'x-cache-hits': '1',
    15 silly registry.get     'x-timer': 'S1418794923.721902,VS0,VE44',
    15 silly registry.get     vary: 'Accept',
    15 silly registry.get     'content-length': '0',
    15 silly registry.get     'keep-alive': 'timeout=10, max=50',
    15 silly registry.get     connection: 'Keep-Alive' } ]
    16 verbose etag https://registry.npmjs.org/meanio from cache
    17 info outdated updating [ [ '/home/arrow/local/lib',
    17 info outdated     'meanio',
    17 info outdated     '0.5.39',
    17 info outdated     '0.6.16',
    17 info outdated     '0.6.16',
    17 info outdated     'latest' ] ]
    18 verbose install where,what [ '/home/arrow/local/lib', [ 'meanio@0.6.16' ] ]
    19 verbose cache add [ 'meanio@0.6.16', null ]
    20 verbose cache add name=undefined spec="meanio@0.6.16" args=["meanio@0.6.16",null]
    21 verbose parsed url { protocol: null,
    21 verbose parsed url   slashes: null,
    21 verbose parsed url   auth: null,
    21 verbose parsed url   host: null,
    21 verbose parsed url   port: null,
    21 verbose parsed url   hostname: null,
    21 verbose parsed url   hash: null,
    21 verbose parsed url   search: null,
    21 verbose parsed url   query: null,
    21 verbose parsed url   pathname: 'meanio@0.6.16',
    21 verbose parsed url   path: 'meanio@0.6.16',
    21 verbose parsed url   href: 'meanio@0.6.16' }
    22 verbose cache add name="meanio" spec="0.6.16" args=["meanio","0.6.16"]
    23 verbose parsed url { protocol: null,
    23 verbose parsed url   slashes: null,
    23 verbose parsed url   auth: null,
    23 verbose parsed url   host: null,
    23 verbose parsed url   port: null,
    23 verbose parsed url   hostname: null,
    23 verbose parsed url   hash: null,
    23 verbose parsed url   search: null,
    23 verbose parsed url   query: null,
    23 verbose parsed url   pathname: '0.6.16',
    23 verbose parsed url   path: '0.6.16',
    23 verbose parsed url   href: '0.6.16' }
    24 verbose addNamed [ 'meanio', '0.6.16' ]
    25 verbose addNamed [ '0.6.16', '0.6.16' ]
    26 silly lockFile 4ea91ea2-meanio-0-6-16 meanio@0.6.16
    27 verbose lock meanio@0.6.16 /home/arrow/.npm/4ea91ea2-meanio-0-6-16.lock
    28 verbose registry.get https://registry.npmjs.org/meanio not expired, no request
    29 silly lockFile 95977678-mjs-org-meanio-meanio-0-6-16-tgz https://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz
    30 verbose lock https://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz /home/arrow/.npm/95977678-mjs-org-meanio-meanio-0-6-16-tgz.lock
    31 verbose addRemoteTarball [ 'https://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz',
    31 verbose addRemoteTarball   '1147bed261cf5257ba15adec6e6a7f41115ac85a' ]
    32 info retry fetch attempt 1 at 06:04:13
    33 verbose fetch to= /tmp/npm-1452-0U_xop70/registry.npmjs.org/meanio/-/meanio-0.6.16.tgz
    34 http GET https://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz
    35 http 200 https://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz
    36 silly lockFile 95977678-mjs-org-meanio-meanio-0-6-16-tgz https://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz
    37 silly lockFile 95977678-mjs-org-meanio-meanio-0-6-16-tgz https://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz
    38 silly lockFile 4ea91ea2-meanio-0-6-16 meanio@0.6.16
    39 silly lockFile 4ea91ea2-meanio-0-6-16 meanio@0.6.16
    40 silly resolved [ { name: 'meanio',
    40 silly resolved     version: '0.6.16',
    40 silly resolved     description: 'Extracted functionality for MEAN.io',
    40 silly resolved     author: { name: 'linnovate' },
    40 silly resolved     contributors: [ [Object], [Object], [Object] ],
    40 silly resolved     license: 'MIT',
    40 silly resolved     main: 'index',
    40 silly resolved     scripts: { preinstall: 'node ./scripts/preinstall' },
    40 silly resolved     repository: { type: 'git', url: 'https://github.com/linnovate/meanio.git' },
    40 silly resolved     keywords: [ 'mean', 'meanio', 'mean.io', 'mean-cli' ],
    40 silly resolved     engines: { node: '0.10.x', npm: '1.4.x' },
    40 silly resolved     dependencies:
    40 silly resolved      { dependable: '^0.2.5',
    40 silly resolved        glob: '^4.0.3',
    40 silly resolved        lodash: '^2.4.1',
    40 silly resolved        'mean-cli': '^0.9.6',
    40 silly resolved        'mean-health': '~0.1.3',
    40 silly resolved        q: '^1.0.1',
    40 silly resolved        request: '^2.47.0',
    40 silly resolved        swig: '^1.3.2',
    40 silly resolved        'uglify-js': '^2.4.14' },
    40 silly resolved     devDependencies:
    40 silly resolved      { grunt: '^0.4.4',
    40 silly resolved        'grunt-contrib-jshint': '^0.10.0',
    40 silly resolved        'grunt-mocha-test': '^0.10.0',
    40 silly resolved        mocha: '^1.18.2',
    40 silly resolved        should: '^3.2.0' },
    40 silly resolved     gitHead: '1b48669a135aaa7061d49b53eb422b31a4ca1a32',
    40 silly resolved     bugs: { url: 'https://github.com/linnovate/meanio/issues' },
    40 silly resolved     homepage: 'https://github.com/linnovate/meanio',
    40 silly resolved     _id: 'meanio@0.6.16',
    40 silly resolved     _shasum: '1147bed261cf5257ba15adec6e6a7f41115ac85a',
    40 silly resolved     _from: 'meanio@0.6.16',
    40 silly resolved     _npmVersion: '2.1.8',
    40 silly resolved     _nodeVersion: '0.10.33',
    40 silly resolved     _npmUser: { name: 'fyockm', email: 'fyockm@gmail.com' },
    40 silly resolved     maintainers: [ [Object], [Object], [Object] ],
    40 silly resolved     dist:
    40 silly resolved      { shasum: '1147bed261cf5257ba15adec6e6a7f41115ac85a',
    40 silly resolved        tarball: 'http://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz' },
    40 silly resolved     directories: {},
    40 silly resolved     _resolved: 'https://registry.npmjs.org/meanio/-/meanio-0.6.16.tgz' } ]
    41 info install meanio@0.6.16 into /home/arrow/local/lib
    42 info installOne meanio@0.6.16
    43 verbose lib/node_modules/meanio unbuild
    44 info preuninstall meanio@0.5.39
    45 info uninstall meanio@0.5.39
    46 verbose true,/home/arrow/local/lib/node_modules,/home/arrow/local/lib/node_modules unbuild meanio@0.5.39
    47 verbose /home/arrow/local/bin,[object Object] binRoot
    48 info postuninstall meanio@0.5.39
    49 verbose tar unpack /home/arrow/.npm/meanio/0.6.16/package.tgz
    50 silly lockFile 5a499175-ow-local-lib-node-modules-meanio tar:///home/arrow/local/lib/node_modules/meanio
    51 verbose lock tar:///home/arrow/local/lib/node_modules/meanio /home/arrow/.npm/5a499175-ow-local-lib-node-modules-meanio.lock
    52 silly lockFile 7eb472b0-ow-npm-meanio-0-6-16-package-tgz tar:///home/arrow/.npm/meanio/0.6.16/package.tgz
    53 verbose lock tar:///home/arrow/.npm/meanio/0.6.16/package.tgz /home/arrow/.npm/7eb472b0-ow-npm-meanio-0-6-16-package-tgz.lock
    54 silly gunzTarPerm modes [ '755', '644' ]
    55 silly gunzTarPerm extractEntry package.json
    56 silly gunzTarPerm extractEntry .npmignore
    57 silly gunzTarPerm extractEntry README.md
    58 silly gunzTarPerm extractEntry LICENSE
    59 silly gunzTarPerm extractEntry Gruntfile.js
    60 silly gunzTarPerm extractEntry index.js
    61 silly gunzTarPerm extractEntry .jshintrc
    62 silly gunzTarPerm extractEntry lib/aggregation.js
    63 silly gunzTarPerm extractEntry lib/bootstrap.js
    64 silly gunzTarPerm extractEntry lib/config.js
    65 silly gunzTarPerm extractEntry lib/db.js
    66 silly gunzTarPerm extractEntry lib/mean.js
    67 silly gunzTarPerm extractEntry lib/menu.js
    68 silly gunzTarPerm extractEntry lib/module.js
    69 silly gunzTarPerm extractEntry lib/platform.js
    70 silly gunzTarPerm extractEntry lib/util.js
    71 silly gunzTarPerm extractEntry modules/package.js
    72 silly gunzTarPerm extractEntry CONTRIBUTING.md
    73 silly gunzTarPerm extractEntry scripts/preinstall.js
    74 silly gunzTarPerm extractEntry test/lib/mean_test.js
    75 silly lockFile 5a499175-ow-local-lib-node-modules-meanio tar:///home/arrow/local/lib/node_modules/meanio
    76 silly lockFile 5a499175-ow-local-lib-node-modules-meanio tar:///home/arrow/local/lib/node_modules/meanio
    77 silly lockFile 7eb472b0-ow-npm-meanio-0-6-16-package-tgz tar:///home/arrow/.npm/meanio/0.6.16/package.tgz
    78 silly lockFile 7eb472b0-ow-npm-meanio-0-6-16-package-tgz tar:///home/arrow/.npm/meanio/0.6.16/package.tgz
    79 info preinstall meanio@0.6.16
    80 verbose unsafe-perm in lifecycle true
    81 info meanio@0.6.16 Failed to exec preinstall script
    82 verbose lib/node_modules/meanio unbuild
    83 info preuninstall meanio@0.6.16
    84 info uninstall meanio@0.6.16
    85 verbose true,/home/arrow/local/lib/node_modules,/home/arrow/local/lib/node_modules unbuild meanio@0.6.16
    86 info postuninstall meanio@0.6.16
    87 error meanio@0.6.16 preinstall: `node ./scripts/preinstall`
    87 error Exit status 1
    88 error Failed at the meanio@0.6.16 preinstall script.
    88 error This is most likely a problem with the meanio package,
    88 error not with npm itself.
    88 error Tell the author that this fails on your system:
    88 error     node ./scripts/preinstall
    88 error You can get their info via:
    88 error     npm owner ls meanio
    88 error There is likely additional logging output above.
    89 error System Linux 2.6.35.4-rscloud
    90 error command "node" "/home/arrow/local/bin/npm" "update" "-g" "meanio"
    91 error cwd /home/arrow/app201408app
    92 error node -v v0.10.30
    93 error npm -v 1.4.23
    94 error code ELIFECYCLE
    95 verbose exit [ 1, true ]

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
