### ISSUE TITLE
mean init behind corporate proxy

### ISSUE THREAD

**Issue by gotson** [linnovate/mean#974]
Hi,

i have a problem when running **mean init**, i get the following error:
`fatal: unable to access 'https://github.com/linnovate/mean.git/': Could not resolve host: github.com
Error: git clone failed: Cloning into 'rats'...
fatal: unable to access 'https://github.com/linnovate/mean.git/': Could not resolve host: github.com`

I have proper proxy configuration for git, bower, and npm.

I am not sure what command exactly does **mean init** runs, how could i set the proxy configuration for it to work ?

thanks

**Comment by infinitesupermagic** [comment]
same issue
