### ISSUE TITLE
Validation Error: Can't update a user

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#977]
Hi,

I add some fields to the user object. I also added a custom method to the server / controllers / users.js:

```
/**
 * Update an user
 */
exports.update = function(req, res) {
	  logger.info('Updating user: ' + req);
    var user = req.user;

    user = _.extend(user, req.body);

    user.save(function(err) {
        if (err) {
            logger.error(err);
            return res.status('users/signup').send({
                errors: err.errors,
                user: user
            });
        } else {
            res.jsonp(user);
        }
    });
};

```

When I update I get a ValidationError : Email adress is already in use.

How can I make this work without removing the Validation constraint from user object ??

Thank you.

**Comment by VikramTiwari** [comment]
@Tyvain If this is still an issue for you, please reopen.
