### ISSUE TITLE
ZeroClipboard error while loading the app in the browser

### ISSUE THREAD

**Issue by priyankshukla** [linnovate/mean#983]
After performing npm install and bower install, grunt works successfully and the server starts listening at 3000. However, when I load the URL (http://localhost:3000) in the browser, nothing loads. In the Javascript console I see this:

Filename: /modules/aggregated.js
ReferenceError: ZeroClipboard is not defined
ZeroClipboard.config(angular.extend(config,ngClip.config || {}));

On the other hand, I have another copy of this folder on my machine in which npm install was run few weeks ago. That copy works fine. There are no differences of the custom code that I wrote across these two folders.

I need to be able to start working towards a production release; unfortunately, the recent npm install caused all this to come to a halt.

**Comment by coolsebz** [comment]
i have somewhat of a similar issue and upon a closer inspection, i've seen that the asset.json files that are under dist.min.js are not anywhere to be found on the final html served to the browser

This means that for me, in the header i only have my css files and in the footer i have the custom js files that i wrote. Really weird

**Comment by VikramTiwari** [comment]
Fixed.
