### ISSUE TITLE
submenu: RangeError: Maximum call stack size exceeded。

### ISSUE THREAD

**Issue by sunyuyangg555** [linnovate/mean#984]
I have used MEAN VERSION: 0.4.2
meanio version: 0.6.16。
mean-cli version: 0.9.6。
but I can not add submenu . when I add submenus ,for example 
Test.menus.add([{
title: 'test example page',
roles: ['authenticated'],
name: 'test'
}]);
,the error is : RangeError: Maximum call stack size exceeded。 could anyone help me?

**Comment by VikramTiwari** [comment]
If this is still a bug, please reopen.
