### ISSUE TITLE
mongoose: err loading bson

### ISSUE THREAD

**Issue by brownman** [linnovate/mean#986]
problem:
---
Running "mochaTest:src" (mochaTest) task
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

solution:
----
http://stackoverflow.com/questions/21656420/failed-to-load-c-bson-extension

**Comment by vkarpov15** [comment]
@brownman perhaps try `rm -rf` on your `node_modules` directory and do a clean npm install? The times I've seen this pop up is usually because you're running with a different version of node than the one you used to build js-bson.

**Comment by VikramTiwari** [comment]
Fixed.
