### ISSUE TITLE
add way to force www

### ISSUE THREAD

**Issue by AlmogBaku** [linnovate/mean#990]

**Comment by AlmogBaku** [comment]
this can't be done by third party because the dependency order

**Comment by VikramTiwari** [comment]
Can you provide more details on this @AlmogBaku

**Comment by VikramTiwari** [comment]
I did a bit of digging yet unable to understand why would you want to do that. Even if you wanted to do so, you can always do it by using your proxy server (nginx/apache) in production environment.

Please reopen if you think this is still relevant.
