### ISSUE TITLE
Mean-admin: stuck at 'Git clone'

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#992]
Hi,

I try to install mean + 2 additional packages: comments and mean-admin.

Everything is ok until I launch the command :

```
C:\BitNami\meanstack-2.4.9-0\projects\mean>mean install mean-admin
```

I am stuck with this (waited like 1 hours...):

```
Installing module: mean-admin:
git clone --branch master https://git.mean.io/linnovate/mean-admin.git node_modules/mean-admin
```

Any idea?

**Comment by duanemck** [comment]
I'm having this issue as well, any advice?
