### ISSUE TITLE
Can't delete username

### ISSUE THREAD

**Issue by TylerL-uxai** [linnovate/mean#994]
How do I delete username from the model? I've been debugging this for over a month.

**Comment by liorkesos** [comment]
Do you mean user removal support?
Lior

**Comment by Squ34k3rZ** [comment]
When I delete username from the meanUser.js model, I get 400 errors (bad request). I commented out the req.assert from the express-validator node module

**Comment by Squ34k3rZ** [comment]
I can delete other objects from the user model but not username for some reason...

**Comment by lirantal** [comment]
I think this happens because the username probably has a constraint in the model, such as being unique, or required, and this is causing mongodb to not remove the record.

**Comment by Squ34k3rZ** [comment]
So create a new database?

**Comment by Squ34k3rZ** [comment]
Creating a new database fixed it!

**Comment by VikramTiwari** [comment]
Fixed.
