### ISSUE TITLE
mean-upload: Error: ENOENT, rename

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#995]
Hi,

First, I post here, it seems to be not very reactive there: https://git.mean.io/orit/upload/issues
(is this project dead?)

Anyway, I am on windows and I get this error when I upload a file:

```
C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\packages\contrib\upload\server\controllers\meanUpload.js:17
                throw err;
                      ^
Error: ENOENT, rename 'C:\Users\Tyvain\AppData\Local\Temp\7932-1yhpof5.png'
[nodemon] app crashed - waiting for file changes before starting...
```

Any idea?
Did you manage to upload images with this? Or do you know a better solution?

Tx.

**Comment by Tyvain** [comment]
I create the repository /files/ at the root of my project (where the photos are uploaded) -> solved it.

(Maybe it should be in the documentation...)

**Comment by RegardtHerbst** [comment]
Having the same issue. Where exactly did you make the folder?

my code in index.html 

<mean-upload file-dest="'/UploadedFiles/'"
		upload-callback="uploadFinished(files)"
		upload-file-callback="uploadFileCallback(files)">
</mean-upload>
