### ISSUE TITLE
grunt/gulp: aggregation(uglify) depends on the config value

### ISSUE THREAD

**Issue by AlmogBaku** [linnovate/mean#998]
we need to open a getaway to the `menio` module to access `meanio.util.getConfig` and not the regular `meanio.config` which required serving before.

see also: #997 #996 #989

**Comment by AlmogBaku** [comment]
***Gruntfile.js***
```js
  grunt.hook.push('clean', -9999);
  grunt.hook.push('concurrent', 9999);
  if (process.env.NODE_ENV === 'production') {
    grunt.hook.push('cssmin', 100);
    grunt.hook.push('uglify', 200);
  } else {
    grunt.hook.push('jshint', -200);
    grunt.hook.push('csslint', 100);
  }
```
The grunt decide whether to run the "uglify" by the `NODE_ENV`.. but if you wish to enable aggregation if MUST run "uglify" first(the uglify responsible for aggregating all the system files[assets.json]).

In general- I think the better solution is to take this out from the grunt, and to aggregate them with the aggregation mechanism only OR with the grunt only.

cc: @andrija-hers

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
