### ISSUE TITLE
Add a splash screen / loader

### ISSUE THREAD

**Issue by whisher** [linnovate/mean#999]
Hi everybody,
it could be nice put a splash screen / loader
to the mean stack like:
https://gist.github.com/whisher/71b53ece0fd74271e920

Bye

**Comment by VikramTiwari** [comment]
haha I like the bye. 👍 

I will try to add a splash screen. Sound like a good idea, esp considering that we have a lot of dependencies which take time to load on slower connections.

**Comment by timelf123** [comment]
Related, we should support multiple webpack bundles (app.js and vendor.js for example) until HTTP2 is a thing
